Repository JMRI/JMRI, pull requests merged in 2018-07, with the labels that each got.

#5514 Add missing properties
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/jmrix/loconet/ds64/Ds64TabbedPanel.java
Labels: Add to Next Release

#5512 Apply LE panel name change to Track Drawing Options
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTrackDrawingOptionsDialog.java
Labels: Add to Next Release

#5525 Modify CPE Palette to handle sorted lists
  java/src/jmri/jmrit/display/palette/MultiSensorItemPanel.java
  java/src/jmri/jmrit/display/palette/SignalMastItemPanel.java
  java/src/jmri/jmrit/display/palette/TableItemPanel.java
Labels: Add to Next Release

#5542 Operations enhancements
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/automation/Automation.java
  java/src/jmri/jmrit/operations/automation/AutomationItem.java
  java/src/jmri/jmrit/operations/automation/Xml.java
  java/src/jmri/jmrit/operations/automation/actions/GotoAction.java
  java/src/jmri/jmrit/operations/automation/actions/GotoFailureAction.java
  java/src/jmri/jmrit/operations/automation/actions/GotoSuccessAction.java
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsAction.java
  java/src/jmri/jmrit/operations/setup/AutoSave.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/test/jmri/jmrit/operations/OperationsSwingTestCase.java
  java/test/jmri/jmrit/operations/OperationsTestCase.java
  java/test/jmri/jmrit/operations/router/OperationsCarRouterTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainEditFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainManagerTest.java
  java/test/jmri/jmrit/operations/trains/tools/PrintTrainsActionTest.java
  java/test/jmri/util/JUnitOperationsUtil.java
Labels: Enhancement

#5554 Improve operations engine export
  java/src/jmri/jmrit/operations/rollingstock/engines/ExportEngines.java
  java/src/jmri/jmrit/operations/rollingstock/engines/ImportEngines.java
Labels: Enhancement

#5565 Improve engine import
  java/src/jmri/jmrit/operations/rollingstock/ImportRollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/cars/ImportCars.java
  java/src/jmri/jmrit/operations/rollingstock/engines/ImportEngines.java
Labels: Enhancement

#5567 Fix NCE edit consist
  java/src/jmri/jmrix/nce/consist/NceConsistBundle.properties
  java/src/jmri/jmrix/nce/consist/NceConsistBundle_da.properties
  java/src/jmri/jmrix/nce/consist/NceConsistBundle_fr.properties
  java/src/jmri/jmrix/nce/consist/NceConsistBundle_it.properties
  java/src/jmri/jmrix/nce/consist/NceConsistEditPanel.java
  java/src/jmri/jmrix/nce/consist/NceConsistRoster.java
Labels: Bug

#5570 web panel, also skip dark state for clickmode 3 (#3664)
  web/js/panel.js
Labels: Bug

#5572 Code clean up
  java/src/jmri/jmrit/throttle/AddressPanel.java
  java/src/jmri/jmrix/nce/consist/Bundle.java
  java/src/jmri/jmrix/nce/consist/NceConsistBackup.java
  java/src/jmri/jmrix/nce/consist/NceConsistBundle.properties
  java/src/jmri/jmrix/nce/consist/NceConsistBundle_da.properties
  java/src/jmri/jmrix/nce/consist/NceConsistBundle_fr.properties
  java/src/jmri/jmrix/nce/consist/NceConsistEditPanel.java
  java/src/jmri/jmrix/nce/consist/NceConsistRestore.java
  java/src/jmri/jmrix/nce/consist/NceConsistRoster.java
  java/src/jmri/jmrix/nce/consist/NceConsistRosterEntry.java
  java/src/jmri/jmrix/nce/consist/PrintNceConsistRosterAction.java
  java/src/jmri/jmrix/nce/ncemon/NceMonBinary.java
Labels: Cleanup

#5573 Add auto refresh to show NCE cabs
  java/src/jmri/jmrix/nce/NceTurnoutMonitor.java
  java/src/jmri/jmrix/nce/cab/NceShowCabBundle.properties
  java/src/jmri/jmrix/nce/cab/NceShowCabPanel.java
Labels: Enhancement

#5574 Fix NCE monitor responses
  java/src/jmri/jmrix/nce/consist/NceConsistBundle.properties
  java/src/jmri/jmrix/nce/macro/NceMacroGenPanel.java
  java/src/jmri/jmrix/nce/ncemon/NceMonBinary.java
  java/src/jmri/jmrix/nce/ncemon/NceMonBinaryBundle.properties
  java/src/jmri/jmrix/nce/packetgen/NcePacketGenPanel.java
Labels: Bug

#5552 CBUS EventTablePane
  java/src/jmri/jmrix/can/Bundle_nl.properties
  java/src/jmri/jmrix/can/cbus/swing/eventtable/CbusEventTablePane.java
  java/test/jmri/jmrix/can/cbus/swing/eventtable/CbusEventTablePaneTest.java
  java/test/jmri/util/swing/JmriPanelTest.java
Labels: Add to Next Release

#5589 Improve train built warning message
  java/src/jmri/jmrit/operations/routes/JmritOperationsRoutesBundle.properties
  java/src/jmri/jmrit/operations/routes/RoutesTableModel.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainEditFrame.java
Labels: Enhancement
