Repository JMRI/JMRI, pull requests merged in 2018-12, with the labels that each got.

#6250 Update to location of new jmri-developers list
  help/en/html/doc/Technical/TechRoadMap.shtml
  help/en/html/doc/Technical/index.shtml
  help/fr/html/doc/Technical/index.shtml
  scripts/HOWTO-distribution.md
Labels: dev/test/publish infrastructure

#6255 Fix problem with Kernel move from alternate track
  java/src/jmri/jmrit/operations/locations/tools/TrackDestinationEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/locations/OperationsPoolTest.java
  java/test/jmri/jmrit/operations/rollingstock/OperationsRollingStockTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/KernelTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
Labels: Bug

#6271 Update Loconet initialization (for 4.13.6)
  java/src/apps/Apps.java
  java/src/jmri/jmrix/loconet/LnDeferProgrammer.java
  java/src/jmri/jmrix/loconet/LnOpsModeProgrammer.java
  java/src/jmri/jmrix/loconet/LnProgrammerManager.java
  java/src/jmri/jmrix/loconet/LocoNetSystemConnectionMemo.java
  java/src/jmri/jmrix/loconet/locormi/LnMessageClientPollThread.java
  java/src/jmri/jmrix/loconet/uhlenbrock/UhlenbrockProgrammerManager.java
  java/src/jmri/profile/Profile.java
  java/test/jmri/jmrix/loconet/LnDeferProgrammerTest.java
  java/test/jmri/jmrix/loconet/PackageTest.java
  java/test/jmri/managers/ManagerDefaultSelectorTest.java
Labels: Add to Next Release

#6297 Update engine table when HP changes
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/engines/Engine.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineModels.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableModel.java
Labels: Bug

#6361 Improve CI test running time
  help/en/html/doc/Technical/Threads.shtml
  java/src/jmri/implementation/AbstractMultiMeter.java
  java/src/jmri/jmrit/logix/OBlockManager.java
  java/src/jmri/jmrit/ussctc/CodeLine.java
  java/src/jmri/jmrit/ussctc/SignalHeadSection.java
  java/src/jmri/jmrix/dccpp/network/DCCppEthernetAdapter.java
  java/src/jmri/jmrix/lenz/XNetThrottle.java
  java/src/jmri/jmrix/lenz/liusbethernet/LIUSBEthernetAdapter.java
  java/src/jmri/jmrix/lenz/liusbserver/LIUSBServerAdapter.java
  java/src/jmri/jmrix/loconet/LnTurnout.java
  java/src/jmri/jmrix/loconet/LocoNetSystemConnectionMemo.java
  java/src/jmri/jmrix/loconet/SlotManager.java
  java/src/jmri/jmrix/marklin/MarklinTurnout.java
  java/src/jmri/jmrix/openlcb/OlcbConfigurationManager.java
  java/src/jmri/jmrix/openlcb/OlcbSensor.java
  java/src/jmri/managers/AbstractSensorManager.java
  java/src/jmri/script/ScriptOutput.java
  java/src/jmri/swing/JmriJTablePersistenceManager.java
  java/src/jmri/util/TimerUtil.java
  java/test/jmri/jmrit/automat/SigletTest.java
  java/test/jmri/jmrit/blockboss/BlockBossLogicTest.java
  java/test/jmri/jmrit/display/switchboardEditor/SwitchboardEditorTest.java
  java/test/jmri/jmrix/cmri/serial/SerialAddressTest.java
  java/test/jmri/jmrix/cmri/serial/SerialAddressTwoSystemTest.java
  java/test/jmri/jmrix/cmri/serial/SerialLightManagerTest.java
  java/test/jmri/jmrix/cmri/serial/SerialLightTest.java
  java/test/jmri/jmrix/cmri/serial/SerialNodeListTest.java
  java/test/jmri/jmrix/cmri/serial/SerialNodeTest.java
  java/test/jmri/jmrix/cmri/serial/SerialSensorManagerTest.java
  java/test/jmri/jmrix/cmri/serial/SerialSensorTest.java
  java/test/jmri/jmrix/cmri/serial/SerialTurnoutManagerTest.java
  java/test/jmri/jmrix/cmri/serial/SerialTurnoutTest.java
  java/test/jmri/jmrix/cmri/swing/CMRIComponentFactoryTest.java
  java/test/jmri/util/PackageTest.java
  java/test/jmri/util/PipeListenerTest.java
  java/test/jmri/util/TimerUtilTest.java
  scripts/HOWTO-distribution.md
Labels: Cleanup, dev/test/publish infrastructure
