Repository JMRI/JMRI, pull requests merged in 2018-09, with the labels that each got.

#5785 fix LocoNet Monitor decode of transponding messages from BXP88 and BXPA1
  java/src/jmri/jmrix/loconet/locomon/Llnmon.java
  java/src/jmri/jmrix/loconet/locomon/Llnmon.properties
  java/test/jmri/jmrix/loconet/locomon/LlnmonTest.java
Labels: Bug

#5808 Javadoc cleanup
  java/src/apps/gui3/package.html
  java/src/jmri/NamedBean.java
  java/src/jmri/configurexml/package.html
  java/src/jmri/jmris/package.html
  java/src/jmri/jmrit/catalog/package.html
  java/src/jmri/jmrit/tracker/package.html
  java/src/jmri/jmrix/can/adapters/package.html
  java/src/jmri/jmrix/grapevine/package.html
  java/src/jmri/jmrix/loconet/locoio/LocoIOModeList.java
  java/src/jmri/jmrix/loconet/spjfile/package.html
  java/src/jmri/jmrix/rfid/protocol/em18/package.html
  java/src/jmri/jmrix/rps/swing/debugger/package.html
  java/src/jmri/jmrix/rps/swing/polling/package.html
  java/src/jmri/util/jdom/package.html
  java/src/jmri/util/swing/mdi/package.html
Labels: Cleanup

#5813 Small improvements
  .spotbugs-check.xml
  java/src/jmri/jmrit/beantable/MemoryTableAction.java
  java/src/jmri/jmrit/picker/PickListModel.java
  java/src/jmri/jmrit/roster/PrintRosterEntry.java
  java/src/jmri/jmrix/AbstractMonPane.java
  java/src/jmri/jmrix/grapevine/package.html
  java/src/jmri/jmrix/roco/z21/Z21LocoNetTunnel.java
  java/src/jmri/jmrix/roco/z21/Z21XPressNetTunnel.java
  java/src/jmri/jmrix/sprog/SprogTrafficController.java
Labels: Bug, Cleanup

#5831 Update ex_set_turnouts.shtml
  help/en/html/tools/scripting/ex_set_turnouts.shtml
Labels: Contribution

#5844 Interpret LocoNet routes configuration messages
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Enhancement

#5848 F2 is not always the horn.
  java/src/jmri/jmrit/throttle/FunctionPanel.java
  java/src/jmri/jmrix/AbstractThrottle.java
  java/src/jmri/jmrix/dccpp/DCCppThrottle.java
  java/src/jmri/jmrix/lenz/XNetThrottle.java
  java/src/jmri/jmrix/loconet/LocoNetThrottle.java
  java/test/jmri/jmrix/loconet/Ib1ThrottleTest.java
  java/test/jmri/jmrix/loconet/Ib2ThrottleTest.java
  java/test/jmri/jmrix/loconet/LocoNetThrottleTest.java
Labels: Bug

#5856 Show wait value when printing out schedules
  help/en/html/doc/Technical/Eclipse.shtml
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsAction.java
Labels: Enhancement

#5873 FIx HTML tidy errors, CI status page
  help/en/html/doc/Technical/CI-status.shtml
  help/en/html/doc/Technical/jacoco_sort_report.php
  scripts/tidy-check.sh
Labels: dev/test/publish infrastructure

#5895 add implementsIdle to LnCommandStation
  java/src/jmri/jmrix/loconet/LnCommandStationType.java
  java/test/jmri/jmrix/loconet/LnCommandStationTypeTest.java
Labels: Enhancement
