Repository JMRI/JMRI, pull requests merged in 2018-02, with the labels that each got.

#4876 Create MTH_PS3_Full.xml
  xml/decoders/MTH_PS3_Full.xml
Labels: Contribution, Enhancement

#4865 Activate Train fixs
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
Labels: Enhancement

#4874 Switchboard update
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/NamedBeanBundle_da.properties
  java/src/jmri/NamedBeanBundle_de.properties
  java/src/jmri/NamedBeanBundle_es.properties
  java/src/jmri/NamedBeanBundle_fr.properties
  java/src/jmri/NamedBeanBundle_it.properties
  java/src/jmri/NamedBeanBundle_ja_JP.properties
  java/src/jmri/NamedBeanBundle_nl.properties
  java/src/jmri/jmrit/beantable/TurnoutTableAction.java
  java/src/jmri/jmrit/display/DisplayBundle.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_da.properties
  java/src/jmri/jmrit/display/DisplayBundle_de.properties
  java/src/jmri/jmrit/display/DisplayBundle_nl.properties
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_fr.properties
  java/src/jmri/jmrit/display/switchboardEditor/BeanSwitch.java
  java/src/jmri/jmrit/display/switchboardEditor/SwitchboardEditor.java
  java/src/jmri/jmrit/display/switchboardEditor/configurexml/BeanSwitchXml.java
  java/src/jmri/jmrit/display/switchboardEditor/configurexml/SwitchboardEditorXml.java
  java/src/jmri/jmrix/loconet/LocoNetBundle.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_cs.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_da.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_de.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_es.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_fr.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_it.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_ja_JP.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_nl.properties
  java/src/jmri/jmrix/loconet/cmdstnconfig/CmdStnConfigPane.java
  java/src/jmri/web/servlet/panel/SwitchboardServlet.java
Labels: Bug, Enhancement

#4767 Hide Table Columns Persistently
  .gitignore
  build.xml
  java/src/jmri/BlockManager.java
  java/src/jmri/Manager.java
  java/src/jmri/UserPreferencesManager.java
  java/src/jmri/jmrit/beantable/AbstractTableAction.java
  java/src/jmri/jmrit/beantable/AudioTablePanel.java
  java/src/jmri/jmrit/beantable/BeanTableDataModel.java
  java/src/jmri/jmrit/beantable/BeanTableFrame.java
  java/src/jmri/jmrit/beantable/RowComboBoxPanel.java
  java/src/jmri/jmrit/beantable/SensorTableAction.java
  java/src/jmri/jmrit/beantable/SignalHeadTableAction.java
  java/src/jmri/jmrit/beantable/SignalMastLogicTableAction.java
  java/src/jmri/jmrit/beantable/SignalMastTableAction.java
  java/src/jmri/jmrit/beantable/TurnoutTableAction.java
  java/src/jmri/jmrit/beantable/oblock/TableFrames.java
  java/src/jmri/jmrit/beantable/sensor/SensorTableDataModel.java
  java/src/jmri/jmrit/beantable/signalmast/SignalMastTableDataModel.java
  java/src/jmri/jmrit/picker/PickListModel.java
  java/src/jmri/jmrit/roster/swing/RosterTableModel.java
  java/src/jmri/jmrit/signalling/SignallingPanel.java
  java/src/jmri/jmrit/signalling/SignallingSourcePanel.java
  java/src/jmri/jmrix/openlcb/OlcbSensorManager.java
  java/src/jmri/jmrix/openlcb/OlcbTurnoutManager.java
  java/src/jmri/managers/AbstractManager.java
  java/src/jmri/managers/AbstractProxyManager.java
  java/src/jmri/managers/JmriUserPreferencesManager.java
  java/src/jmri/managers/configurexml/DefaultUserMessagePreferencesXml.java
  java/src/jmri/swing/JTablePersistenceManager.java
  java/src/jmri/swing/JmriJTablePersistenceManager.java
  java/src/jmri/swing/RowSorterUtil.java
  java/src/jmri/util/swing/XTableColumnModel.java
  java/test/jmri/swing/JmriJTablePersistenceManagerTest-user-interface.xml
  java/test/jmri/swing/JmriJTablePersistenceManagerTest.java
  java/test/jmri/util/swing/XTableColumnModelTest.java
Labels: Bug

#4881 Address delays in launching on Windows with lots of fonts
  java/src/apps/systemconsole/SystemConsolePreferencesManager.java
  java/src/jmri/util/swing/FontComboUtil.java
Labels: Bug

#4889 VSDecoder: remove file BUGS.txt
  java/src/jmri/jmrit/vsdecoder/BUGS.txt
Labels: Cleanup

#4893 Fix Drag and Drop of Files
  java/src/jmri/util/iharder/dnd/FileDrop.java
Labels: Bug

#4894 Restore throttle user increment when add throttle user
  java/src/jmri/jmrix/AbstractThrottleManager.java
  java/test/jmri/jmrix/loconet/LnThrottleManagerTest.java
Labels: Bug

#4896 refactor WiThrottle Servers
  java/src/jmri/jmrit/withrottle/DeviceManager.java
  java/src/jmri/jmrit/withrottle/FacelessServer.java
  java/src/jmri/jmrit/withrottle/UserInterface.java
  java/src/jmri/jmrit/withrottle/WiThrottleCreationAction.java
  java/test/jmri/jmrit/withrottle/UserInterfaceTest.java
Labels: Cleanup, Enhancement

#4904 Update Dispatcher Stopping Flag at Appropriate Time
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
Labels: Bug

#4908 SoundTraxx Tsunami 2 Diesel update SW version 1.2
  xml/decoders/SoundTraxx_Tsu2_Diesel.xml
  xml/decoders/SoundTraxx_Tsu2_Electric.xml
  xml/decoders/SoundTraxx_Tsu2_Steam.xml
  xml/decoders/soundtraxx/ECOPaneFnMap.xml
  xml/decoders/soundtraxx/TSU2CV.xml
  xml/decoders/soundtraxx/TSUPaneReverb.xml
Labels: Enhancement

#4916 Address Javadoc and other warnings.
  java/src/jmri/InstanceManager.java
  java/src/jmri/Manager.java
  java/src/jmri/RailComManager.java
  java/src/jmri/jmrit/catalog/configurexml/DefaultCatalogTreeManagerXml.java
  java/src/jmri/jmrix/AbstractNetworkConnectionConfig.java
  java/src/jmri/jmrix/AbstractSimulatorConnectionConfig.java
  java/src/jmri/jmrix/AbstractStreamConnectionConfig.java
  java/src/jmri/jmrix/acela/serialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/bachrus/serialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/can/adapters/ConnectionConfig.java
  java/src/jmri/jmrix/can/adapters/gridconnect/can2usbino/serialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/can/adapters/gridconnect/canrs/serialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/can/adapters/gridconnect/canusb/serialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/can/adapters/gridconnect/lccbuffer/serialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/can/adapters/gridconnect/net/ConnectionConfig.java
  java/src/jmri/jmrix/can/adapters/gridconnect/net/MergConnectionConfig.java
  java/src/jmri/jmrix/can/adapters/lawicell/canusb/serialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/can/adapters/loopback/ConnectionConfig.java
  java/src/jmri/jmrix/srcp/networkdriver/ConnectionConfig.java
  java/src/jmri/jmrix/tams/serialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/tams/simulator/ConnectionConfig.java
  java/src/jmri/jmrix/tmcc/SerialAddress.java
  java/src/jmri/jmrix/tmcc/SerialThrottleManager.java
  java/src/jmri/jmrix/tmcc/SerialTurnout.java
  java/src/jmri/jmrix/tmcc/simulator/ConnectionConfig.java
  java/src/jmri/util/swing/DrawSquares.java
  java/src/jmri/util/swing/JComboBoxUtil.java
  java/test/jmri/ManagerTest.java
Labels: Cleanup

#4917 Prevent potential NPE in Cucumber/Selenium tests
  java/acceptancetest/step_definitions/jmri/web/WebServerAcceptanceSteps.java
  java/acceptancetest/step_definitions/jmri/web/WebServerScaffold.java
  nbproject/project.xml
Labels: Cleanup, dev/test/publish infrastructure

#4912 Add Fast Clock to WiThrottle Protocol
  java/src/jmri/jmrit/withrottle/DeviceServer.java
  java/src/jmri/jmrit/withrottle/FastClockController.java
  java/src/jmri/jmrit/withrottle/WiThrottleBundle.properties
  java/src/jmri/jmrit/withrottle/WiThrottleManager.java
  java/src/jmri/jmrit/withrottle/WiThrottlePreferences.java
  java/src/jmri/jmrit/withrottle/WiThrottlePrefsPanel.java
  java/test/jmri/jmrit/withrottle/FastClockControllerTest.java
  java/test/jmri/jmrit/withrottle/PackageTest.java
Labels: Enhancement

#4915 Add, improve tests for JSON services
  java/src/jmri/server/json/JSON.java
  java/src/jmri/server/json/JsonClientHandler.java
  java/src/jmri/server/json/JsonException.java
  java/src/jmri/server/json/JsonWebSocket.java
  java/src/jmri/server/json/operations/JsonOperationsSocketService.java
  java/src/jmri/server/json/schema.json
  java/src/jmri/server/json/util/JsonUtilHttpService.java
  java/src/jmri/web/servlet/json/JsonServlet.java
  java/src/jmri/web/servlet/operations/HtmlConductor.java
  java/src/jmri/web/servlet/operations/HtmlManifest.java
  java/src/jmri/web/servlet/operations/HtmlTrainCommon.java
  java/src/jmri/web/servlet/operations/OperationsServlet.java
  java/test/jmri/server/json/JSONTest.java
  java/test/jmri/server/json/JsonClientHandlerTest.java
  java/test/jmri/server/json/JsonExceptionTest.java
  java/test/jmri/server/json/JsonHttpServiceTest.java
  java/test/jmri/server/json/JsonMockConnection.java
  java/test/jmri/server/json/JsonTestHttpService.java
  java/test/jmri/server/json/PackageTest.java
  java/test/jmri/server/json/util/JsonUtilHttpServiceTest.java
  java/test/jmri/server/json/util/JsonUtilSocketServiceTest.java
Labels: Cleanup

#4924 VSDecoder: throttle button for Engine start-stop
  java/src/jmri/jmrit/vsdecoder/EngineSoundEvent.java
Labels: Enhancement

#4921 Tam Valley Depot QuadLN_S decoder update
  xml/decoders/TamValleyDepot_QuadLn_S_11.xml
  xml/decoders/TamValleyDepot_QuadLn_S_11.xsl
  xml/decoders/tvd/DetRange.xml
Labels: Enhancement

#4883 Remove deprecated methods
  help/fr/html/doc/Technical/Jython.shtml
  help/fr/html/tools/scripting/FAQ.shtml
  java/src/jmri/InstanceManager.java
  java/src/jmri/jmrix/loconet/LocoNetSystemConnectionMemo.java
  java/src/jmri/jmrix/loconet/pr3/PR3SystemConnectionMemo.java
  java/src/jmri/jmrix/mrc/MrcSystemConnectionMemo.java
  java/src/jmri/jmrix/nce/NceSystemConnectionMemo.java
  jython/AlarmClock.py
  jython/AutoDispatcher2.py
  jython/ConsistExample.py
  jython/ReporterFontControl.py
  jython/javaone/setup.py
Labels: Cleanup

#4909 Updates to SPROG bootloader
  help/en/html/hardware/sprog/SPROG.shtml
  java/src/jmri/jmrix/sprog/SPROGCSMenu.java
  java/src/jmri/jmrix/sprog/SPROGMenu.java
  java/src/jmri/jmrix/sprog/SprogBundle.properties
  java/src/jmri/jmrix/sprog/SprogBundle_nl.properties
  java/src/jmri/jmrix/sprog/SprogMessage.java
  java/src/jmri/jmrix/sprog/SprogReply.java
  java/src/jmri/jmrix/sprog/update/SprogIIUpdateFrame.java
  java/src/jmri/jmrix/sprog/update/SprogType.java
  java/src/jmri/jmrix/sprog/update/SprogUpdateFrame.java
Labels: Bug

#4933 Fix bugs in tables introduced in 4.11.3
  java/src/jmri/jmrit/beantable/sensor/SensorTableDataModel.java
  java/src/jmri/swing/JmriJTablePersistenceManager.java
Labels: Bug

#4945 Ecos direction change
  java/src/jmri/jmrix/ecos/EcosDccThrottle.java
Labels: Bug

#4964 Typo-fix - missed a rather important angle bracket in JMRI/JMRI#4945
  java/src/jmri/jmrix/ecos/EcosDccThrottle.java
Labels: Bug

#4965 Reply parser was not honouring replies with multiple items
  java/src/jmri/jmrix/ecos/EcosDccThrottle.java
Labels: Bug

#4969 Fix Copy Route where "Random" value was not copied
  java/src/jmri/jmrit/operations/routes/RouteManager.java
Labels: Bug
