Repository JMRI/JMRI, pull requests merged in 2018-04, with the labels that each got.

#5181 Improve memory use during tests
  java/test/jmri/jmrit/display/AnalogClock2DisplayTest.java
  java/test/jmri/jmrit/display/CoordinateEditTest.java
  java/test/jmri/jmrit/display/DisplayFrameTest.java
  java/test/jmri/jmrit/display/IconAdderTest.java
  java/test/jmri/jmrit/display/IconEditorWindowTest.java
  java/test/jmri/jmrit/display/LinkingLabelTest.java
  java/test/jmri/jmrit/display/MemoryIconCoordinateEditTest.java
  java/test/jmri/jmrit/display/MemoryIconTest.java
  java/test/jmri/jmrit/display/MemorySpinnerIconTest.java
  java/test/jmri/jmrit/display/PositionableLabelTest.java
  java/test/jmri/jmrit/display/PositionableTestBase.java
  java/test/jmri/jmrit/display/ReporterIconTest.java
  java/test/jmri/jmrit/display/RpsPositionIconTest.java
  java/test/jmri/jmrit/display/SensorTextEditTest.java
  java/test/jmri/jmrit/display/SignalMastIconTest.java
  java/test/jmri/jmrit/display/SlipIconAdderTest.java
  java/test/jmri/jmrit/display/controlPanelEditor/CircuitBuilderTest.java
  java/test/jmri/jmrit/display/controlPanelEditor/ControlPanelEditorActionTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorToolsTest.java
  java/test/jmri/jmrit/display/layoutEditor/PositionablePointTest.java
  java/test/jmri/jmrit/display/palette/DetectionPanelTest.java
  java/test/jmri/jmrit/display/switchboardEditor/SwitchboardEditorTest.java
Labels: dev/test/publish infrastructure

#5252 Minor improvement to operations GUI
  java/src/jmri/jmrit/operations/routes/SetTrainIconRouteFrame.java
Labels: Enhancement

#5255 Minor improvement to operations build report
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
Labels: Enhancement

#5269 Warn user if there's an error when saving a schedule
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/SpurEditFrame.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/schedules/ScheduleEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/PrintCarRosterAction.java
Labels: Enhancement

#5282 Fix random schedule failures out of staging
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/Track.java
Labels: Bug
