Repository JMRI/JMRI, pull requests merged in 2019-07, with the labels that each got.

#7159 jmrit.display Spotbugs
  java/src/jmri/SignalMast.java
  java/src/jmri/implementation/AbstractSignalMast.java
  java/src/jmri/implementation/DccSignalMast.java
  java/src/jmri/implementation/MatrixSignalMast.java
  java/src/jmri/implementation/SignalHeadSignalMast.java
  java/src/jmri/implementation/TurnoutSignalMast.java
  java/src/jmri/implementation/VirtualSignalMast.java
  java/src/jmri/jmrit/audio/AbstractAudioFactory.java
  java/src/jmri/jmrit/audio/AbstractAudioSource.java
  java/src/jmri/jmrit/audio/AudioFactory.java
  java/src/jmri/jmrit/conditional/ConditionalListEdit.java
  java/src/jmri/jmrit/conditional/ConditionalTreeEdit.java
  java/src/jmri/jmrit/dispatcher/AutoTrainAction.java
  java/src/jmri/jmrit/display/SensorIcon.java
  java/src/jmri/jmrit/display/SlipTurnoutIcon.java
  java/src/jmri/jmrit/display/TurnoutIcon.java
  java/src/jmri/jmrit/entryexit/PointDetails.java
  java/src/jmri/jmrit/entryexit/configurexml/EntryExitPairsXml.java
  java/src/jmri/jmrit/progsupport/ProgOpsModePane.java
  java/src/jmri/jmrit/roster/swing/RosterMenu.java
  java/src/jmri/jmrit/roster/swing/speedprofile/SpeedProfilePanel.java
  java/src/jmri/jmrit/withrottle/RouteController.java
  java/src/jmri/jmrix/acela/AcelaAddress.java
  java/src/jmri/jmrix/acela/AcelaNode.java
  java/src/jmri/jmrix/cmri/serial/cmrinetmetrics/CMRInetMetricsCollector.java
  java/src/jmri/jmrix/cmri/serial/diagnostic/DiagnosticFrame.java
  java/src/jmri/jmrix/cmri/serial/serialmon/SerialMonFrame.java
  java/src/jmri/jmrix/dcc4pc/Dcc4PcReporter.java
  java/src/jmri/jmrix/direct/MakePacket.java
  java/src/jmri/jmrix/lenz/xnetsimulator/XNetSimulatorAdapter.java
  java/src/jmri/jmrix/loconet/LNCPSignalMast.java
  java/src/jmri/jmrix/marklin/MarklinPowerManager.java
  java/src/jmri/jmrix/nce/consist/NceConsistRosterMenu.java
  java/src/jmri/jmrix/openlcb/OlcbSignalMast.java
  java/src/jmri/jmrix/openlcb/swing/OlcbSignalMastAddPane.java
Labels: Cleanup

#7204 Test both DTD and Schema forms of roster file
  java/test/jmri/jmrit/display/BlockContentsIconTest.java
  java/test/jmri/jmrit/display/MemoryIconTest.java
  java/test/jmri/jmrit/display/layoutEditor/BlockContentsIconTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutBlockTest.java
  java/test/jmri/jmrit/roster/ACL1012-DTD.xml
  java/test/jmri/jmrit/roster/ACL1012-Schema.xml
  java/test/jmri/jmrit/roster/PrintRosterEntryTest.java
  java/test/jmri/jmrit/roster/RosterEntryTest.java
  xml/DTD/locomotive-config.dtd
Labels: dev/test/publish infrastructure

#7060 Load IdTag data at construction time
  java/src/jmri/jmrit/beantable/IdTagTableAction.java
  java/src/jmri/managers/DefaultIdTagManager.java
  java/src/jmri/managers/ProxyIdTagManager.java
Labels: Bug
