Repository JMRI/JMRI, pull requests merged in 2019-06, with the labels that each got.

#7044 Prevent NPE for EB and EC context menu
  java/src/jmri/jmrit/display/layoutEditor/PositionablePoint.java
Labels: Add to Next Test Release

#7051 Change Digitrax SFX Series 6 CV 11 default to 6
  xml/decoders/Digitrax_0SFX_Series6.xml
Labels: Add to Next Test Release

#7053 Correct issue #7050
  java/src/jmri/jmrit/display/layoutEditor/LayoutBlock.java
  java/src/jmri/jmrit/display/layoutEditor/MemoryIcon.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutBlockTest.java
  java/test/jmri/jmrit/display/layoutEditor/MemoryIconTest.java
Labels: Add to Next Test Release, Bug

#7054 Fix issue "Cannot Drag in CPE"
  java/src/jmri/jmrit/display/controlPanelEditor/CircuitBuilder.java
Labels: Add to Next Test Release

#7065 Update LokSound 5 language
  xml/decoders/esu/v5readMePane.xml
Labels: Add to Next Test Release

#7075 fix: web manifest had null from some car attributes
  java/src/jmri/jmrit/operations/rollingstock/Xml.java
  java/src/jmri/web/servlet/operations/HtmlManifest.java
Labels: Add to Next Test Release

#7078 MERG CBUS Revert Defs Update
  java/src/jmri/jmrix/can/cbus/node/CbusNodeConstants.java
Labels: Add to Next Test Release

#7077 Correct Hornby Elite programming sequence
  java/src/jmri/jmrix/lenz/hornbyelite/EliteXNetProgrammer.java
  java/test/jmri/jmrix/lenz/hornbyelite/EliteXNetProgrammerTest.java
Labels: Add to Next Test Release

#7087 TCS ditch light fix first part
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/tcs/2_CV35-54_Fn.xml
  xml/decoders/tcs/Choice_BlinkingditchAB.xml
Labels: Add to Next Test Release

#7061 Fix minor spelling
  java/src/jmri/Reportable.java
Labels: After Next Production Release

#7057 Have LocoNet reporters extend the CollectingReporter interface.
  java/src/jmri/jmrix/loconet/LnReporter.java
  java/test/jmri/jmrix/loconet/LnReporterTest.java
  jython/CollectingReporterExample.py
Labels: Enhancement

#7088 Start Travis subjobs in order of runtime
  .travis.yml
  pom.xml
  release.properties
Labels: dev/test/publish infrastructure

#7084 Remove hyphen location name in conductor
  java/src/jmri/jmrit/operations/trains/TrainConductorPanel.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/Xml.java
  java/src/jmri/jmrit/operations/trains/tools/ShowCarsInTrainFrame.java
  xml/DTD/operations-trains.dtd
Labels: Enhancement

#7073 SpotBugs in IntelliJ
  .idea/JMRI.iml
  help/en/html/doc/Technical/IntelliJ.shtml
  help/en/html/doc/Technical/images/IntelliJ/IjBuildtaskProgressbar.png
  help/en/html/doc/Technical/images/IntelliJ/IjCoverageResultPane.png
  help/en/html/doc/Technical/images/IntelliJ/IjDebug1Button.png
  help/en/html/doc/Technical/images/IntelliJ/IjDebug3ConfigPane.png
  help/en/html/doc/Technical/images/IntelliJ/IjDebug3ConfigPaneJar.png
  help/en/html/doc/Technical/images/IntelliJ/IjDebug6DebugInterface.png
  help/en/html/doc/Technical/images/IntelliJ/IjDebug7StepInto.png
  help/en/html/doc/Technical/images/IntelliJ/IjDebugConfigJunit1.png
  help/en/html/doc/Technical/images/IntelliJ/IjDebugConfigJunit2.png
  help/en/html/doc/Technical/images/IntelliJ/IjEditProperties.png
  help/en/html/doc/Technical/images/IntelliJ/IjPrefsEditorProperties.png
  help/en/html/doc/Technical/images/IntelliJ/IjProjectCompilepathsSet.png
  help/en/html/doc/Technical/images/IntelliJ/IjProjectJmriSetting1ModulesPaths.png
  help/en/html/doc/Technical/images/IntelliJ/IjProjectSettingsSourcesStep1_class.png
  help/en/html/doc/Technical/images/IntelliJ/IjProjectSettingsSourcesStep2_tests.png
  help/en/html/doc/Technical/images/IntelliJ/IjResourceJump.png
Labels: dev/test/publish infrastructure

#7100 Show car color and load attribute lengths
  java/src/jmri/jmrit/operations/rollingstock/RollingStockAttribute.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarColors.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLoads.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarRoads.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarTypes.java
  java/src/jmri/jmrit/operations/trains/TrainConductorPanel.java
Labels: Enhancement

#7113 Disable invalid minVal/maxVal checking in splitVal.
  java/src/jmri/jmrit/symbolicprog/SplitVariableValue.java
Labels: Bug

#7112 Fix ESU LokPilot regression created in V4.15.6.
  xml/decoders/ESU_LokPilot_StandardV1_0.xml
  xml/decoders/ESU_Misc_LightingInterior.xml
Labels: Bug

#7119 Implementation SpotBugs
  java/src/jmri/NamedBean.java
  java/src/jmri/Section.java
  java/src/jmri/implementation/AbstractIdTag.java
  java/src/jmri/implementation/AbstractNamedBean.java
  java/src/jmri/implementation/AbstractTurnout.java
  java/src/jmri/implementation/DccSignalMast.java
  java/src/jmri/implementation/DefaultIdTag.java
  java/src/jmri/implementation/DefaultLogix.java
  java/src/jmri/implementation/MatrixSignalMast.java
  java/src/jmri/implementation/SignalHeadSignalMast.java
  java/src/jmri/implementation/TurnoutSignalMast.java
  java/src/jmri/implementation/VirtualSignalMast.java
  java/src/jmri/implementation/configurexml/DoubleTurnoutSignalHeadXml.java
  java/src/jmri/implementation/configurexml/LsDecSignalHeadXml.java
  java/src/jmri/implementation/configurexml/MergSD2SignalHeadXml.java
  java/src/jmri/implementation/configurexml/SE8cSignalHeadXml.java
  java/src/jmri/jmrix/openlcb/OlcbSignalMast.java
  java/test/jmri/jmrit/beantable/signalmast/VirtualSignalMastAddPaneTest.java
  java/test/jmri/jmrix/openlcb/swing/OlcbSignalMastAddPaneTest.java
Labels: Cleanup

#7134 Beantable spotbugs
  java/src/jmri/TurnoutOperation.java
  java/src/jmri/TurnoutOperationManager.java
  java/src/jmri/jmrit/beantable/LRouteTableAction.java
  java/src/jmri/jmrit/beantable/MemoryTableAction.java
  java/src/jmri/jmrit/beantable/SectionTableAction.java
  java/src/jmri/jmrit/beantable/SignalGroupSubTableAction.java
  java/src/jmri/jmrit/beantable/SignalHeadTableAction.java
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/beantable/TurnoutTableAction.java
  java/src/jmri/jmrit/beantable/beanedit/TurnoutEditAction.java
  java/src/jmri/jmrit/beantable/oblock/DnDJTable.java
  java/src/jmri/jmrit/beantable/oblock/TableFrames.java
  java/src/jmri/jmrit/beantable/signalmast/AddSignalMastPanel.java
  java/src/jmri/jmrit/beantable/signalmast/MatrixSignalMastAddPane.java
  java/src/jmri/jmrit/beantable/signalmast/SignalHeadSignalMastAddPane.java
  java/src/jmri/jmrit/beantable/signalmast/TurnoutSignalMastAddPane.java
  java/src/jmri/jmrit/beantable/signalmast/VirtualSignalMastAddPane.java
  java/src/jmri/jmrit/beantable/usermessagepreferences/UserMessagePreferencesPane.java
  java/src/jmri/jmrix/openlcb/swing/OlcbSignalMastAddPane.java
  java/test/jmri/implementation/MatrixSignalMastTest.java
  java/test/jmri/jmrit/beantable/signalmast/AbstractSignalMastAddPaneTestBase.java
  java/test/jmri/jmrit/beantable/signalmast/DccSignalMastAddPaneTest.java
  java/test/jmri/jmrit/beantable/signalmast/MatrixSignalMastAddPaneTest.java
  java/test/jmri/jmrit/beantable/signalmast/SignalHeadSignalMastAddPaneTest.java
  java/test/jmri/jmrit/beantable/signalmast/TurnoutSignalMastAddPaneTest.java
  java/test/jmri/jmrit/beantable/signalmast/VirtualSignalMastAddPaneTest.java
  java/test/jmri/jmrix/openlcb/swing/OlcbSignalMastAddPaneTest.java
Labels: Cleanup
