Repository JMRI/JMRI, pull requests merged in 2019-01, with the labels that each got.

#6395 Add simple time-based JUnitUtil.waitfor
  java/test/jmri/util/JUnitUtil.java
Labels: dev/test/publish infrastructure

#6430 Add the concept of a "collecting" reporter
  java/src/jmri/CollectingReporter.java
  java/src/jmri/implementation/AbstractRailComReporter.java
  java/src/jmri/implementation/AbstractReporter.java
  java/src/jmri/jmrix/internal/InternalReporterManager.java
  java/src/jmri/jmrix/internal/TrackReporter.java
  java/src/jmri/jmrix/roco/z21/Z21CanReporter.java
  java/test/jmri/jmrix/internal/TrackReporterTest.java
  java/test/jmri/jmrix/roco/z21/Z21CanReporterTest.java
Labels: Enhancement

#6429 Flag Unread Field cases in SpotBugs
  .spotbugs-check.xml
Labels: dev/test/publish infrastructure

#6441 Add a check for long tests
  help/en/html/doc/Technical/JUnit.shtml
  help/en/html/doc/Technical/StartUpScripts.shtml
  java/test/jmri/util/JUnitUtil.java
Labels: dev/test/publish infrastructure

#6440 Move release note
  help/en/html/doc/Technical/gitadmin.shtml
  help/en/html/doc/Technical/gitdeveloper.shtml
  help/en/releasenotes/README.md
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/jmri4.15-master.shtml
  scripts/HOWTO-distribution.md
Labels: Add to Next Release, dev/test/publish infrastructure

#6451 Fix schema for RGB SignalHeads
  help/en/releasenotes/current-draft-note.shtml
  java/test/jmri/implementation/configurexml/load/RYG-RGB-test.xml
  xml/schema/types/signalheads-2-9-6.xsd
Labels: Bug

#6454 HTML scan should skip releasenotes/
  build.xml
  scripts/tidy-check.sh
  scripts/tidy-scan.sh
Labels: dev/test/publish infrastructure

#6468 New serial I/O scripts (contributed in Issue 6385)
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/serialinput/Sensor_Channel_To_JMRI/JMRISensorScanMega.ino
  jython/serialinput/Sensor_Channel_To_JMRI/JMRISensorScanUNO.ino
  jython/serialinput/Sensor_Channel_To_JMRI/SensorSerialClose.py
  jython/serialinput/Sensor_Channel_To_JMRI/Sensor_Channels_Readme.md
  jython/serialinput/Sensor_Channel_To_JMRI/Sensor_Scan.py
  jython/serialinput/Turnout_Channel_from_JMRI/JMRITurnoutScanMega.ino
  jython/serialinput/Turnout_Channel_from_JMRI/JMRITurnoutScanUno.ino
  jython/serialinput/Turnout_Channel_from_JMRI/TurnoutDataTransfer.py
  jython/serialinput/Turnout_Channel_from_JMRI/Turnout_Channels_Readme.md
  jython/serialinput/Turnout_Channel_from_JMRI/Turnout_Table_Build.py
Labels: Contribution

#6474 Windows Installer looks for java11 windows registry
  help/en/releasenotes/current-draft-note.shtml
  scripts/WinInstallFiles/InstallJMRI.nsi
  scripts/WinInstallFiles/LaunchJMRI.nsi
Labels: Enhancement, Future Java

#6476 Improve release note documentation
  help/en/html/doc/Technical/gitdeveloper.shtml
  help/en/releasenotes/README.md
Labels: dev/test/publish infrastructure

#6485 Updated LaunchJMRI version number
  scripts/WinInstallFiles/LaunchJMRI.nsi
Labels: Future Java

#6486 Add a few extra debug messages and compile LaunchJMRI.exe
  scripts/WinInstallFiles/LaunchJMRI.exe
  scripts/WinInstallFiles/LaunchJMRI.nsi
Labels: Future Java

#6504 Run on jdk11
  help/en/html/doc/Technical/StartUpScripts.shtml
  scripts/WinInstallFiles/LaunchJMRI.exe
  scripts/WinInstallFiles/LaunchJMRI.nsi
Labels: Future Java

#6505 NCE Serial Cab Addresses start at 1.
  java/src/jmri/jmrix/nce/cab/NceShowCabPanel.java
Labels: Bug, Cleanup
