Repository JMRI/JMRI, pull requests merged in 2019-08, with the labels that each got.

#7258 fix LocoNet turnout retry
  java/src/jmri/jmrix/loconet/LnTurnoutManager.java
  java/test/jmri/jmrix/loconet/LnTurnoutManagerTest.java
Labels: Bug

#7268 Add timeout to ImportRosterEngineActionTest to prevent CI time limit exceeded
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/ImportRosterEngineActionTest.java
Labels: dev/test/publish infrastructure

#7270 Add the ability to update CV19 from the Consisting tool.
  help/en/html/tools/consisttool/ConsistTool.shtml
  help/en/html/tools/consisttool/images/ConsistControl-Preferences.png
  help/en/html/tools/consisttool/images/ConsistTool-ScanForConsists.png
  java/src/apps/AppsStructureBundle.properties
  java/src/jmri/implementation/DccConsist.java
  java/src/jmri/jmrit/consisttool/ConsistPreferencesManager.java
  java/src/jmri/jmrit/consisttool/ConsistTool.properties
  java/src/jmri/jmrit/consisttool/ConsistToolPrefsPanel.java
  java/src/jmri/jmrit/withrottle/WiFiConsist.java
  java/src/jmri/jmrix/easydcc/EasyDccConsist.java
  java/src/jmri/jmrix/lenz/XNetConsist.java
  java/src/jmri/jmrix/loconet/LocoNetConsist.java
  java/src/jmri/jmrix/nce/NceConsist.java
  java/test/jmri/implementation/AbstractConsistTestBase.java
  java/test/jmri/implementation/DccConsistTest.java
  java/test/jmri/implementation/NmraConsistTest.java
  java/test/jmri/jmrit/consisttool/ConsistFileTest.java
  java/test/jmri/jmrit/consisttool/ConsistToolFrameTest.java
  java/test/jmri/jmrit/consisttool/ConsistToolPrefsPanelTest.java
  java/test/jmri/jmrit/consisttool/PackageTest.java
  java/test/jmri/jmrit/withrottle/WiFiConsistTest.java
  java/test/jmri/jmrix/easydcc/EasyDccConsistTest.java
  java/test/jmri/jmrix/lenz/XNetConsistTest.java
  java/test/jmri/jmrix/loconet/LocoNetConsistTest.java
  java/test/jmri/jmrix/nce/NceConsistTest.java
  java/test/jmri/util/RosterTestUtil.java
Labels: Enhancement

#7277 Remove invalid portable name from ProfileFileStructure.shtml
  help/en/html/doc/Technical/ProfileFileStructure.shtml
Labels: Bug

#7267 Time out and retry RosterFrameTest
  java/test/jmri/jmrit/roster/swing/RosterFrameTest.java
Labels: dev/test/publish infrastructure

#7284 Restrict IdentifyDecoder PAGEMODE fallback initiation to test1 (CV8).
  java/src/jmri/jmrit/AbstractIdentify.java
  java/test/jmri/jmrit/decoderdefn/IdentifyDecoderTest.java
Labels: Enhancement

#7303 Allow user to display the Dcc address of the train's loco
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/Train.java
Labels: Enhancement

#7309 Improve printing operations locomotive roster
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterAction.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterAction.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterActionTest.java
Labels: Enhancement

#7321 fix NPEs associated with LnSensorManager, fix test-time NPEs
  java/src/jmri/jmrix/loconet/LnPacketizer.java
  java/src/jmri/jmrix/loconet/LnSensorManager.java
Labels: Add to Next Test Release, Bug

#7343 improve use of LnConstants, getOpCode()
  java/src/jmri/jmrix/loconet/AbstractAlmImplementation.java
  java/src/jmri/jmrix/loconet/AbstractBoardProgPanel.java
  java/src/jmri/jmrix/loconet/CsOpSwAccess.java
  java/src/jmri/jmrix/loconet/LnOpsModeProgrammer.java
  java/src/jmri/jmrix/loconet/LnPacketizerStrict.java
  java/src/jmri/jmrix/loconet/LocoNetMessage.java
  java/src/jmri/jmrix/loconet/SlotManager.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/DuplexGroupScanPanel.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/LnDplxGrpInfoImpl.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/LnIPLImplementation.java
  java/src/jmri/jmrix/loconet/lnsvf2/LnSv2MessageContents.java
  java/src/jmri/jmrix/loconet/locoid/LocoIdPanel.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/pr2/LnPr2PowerManager.java
Labels: Cleanup

#7346 Update FindBugsCheck
  java/src/apps/FindBugsCheck.java
Labels: Developer, dev/test/publish infrastructure

#7349 LocoNetThrottleTest coverage improvements
  java/test/jmri/jmrix/loconet/LocoNetThrottleTest.java
Labels: Enhancement

#7350 update LocoNet dispose methods
  java/src/jmri/jmrix/loconet/CsOpSwAccess.java
  java/src/jmri/jmrix/loconet/LnReporter.java
  java/src/jmri/jmrix/loconet/LocoNetConsist.java
  java/src/jmri/jmrix/loconet/SE8cSignalHead.java
Labels: Cleanup

#7371 fix possible NPE in LnTurnout, improve maintainability
  java/src/jmri/jmrix/loconet/LnTurnout.java
Labels: Bug, Cleanup

#7376 Improve LnTurnout Coverage
  java/test/jmri/jmrix/loconet/LnTurnoutTest.java
Labels: Enhancement
