Repository JMRI/JMRI, pull requests merged in 2019-12, with the labels that each got.

#7685 Scan french help 7629
  help/en/html/doc/Technical/CI-status.shtml
  help/fr/html/doc/Technical/TurnoutFeedback.shtml
  pom.xml
Labels: Cleanup, dev/test/publish infrastructure

#7698 SwitchPilot Bounce Effects, Read Sheets Warning.
  xml/decoders/ESU_SwitchPilot.xml
  xml/decoders/esu/switchPilotFnOutCVs.xml
  xml/decoders/esu/switchPilotFnOutPane.xml
Labels: Enhancement

#7702 More fine tuning for the export timetable
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/tools/ExportTimetable.java
Labels: Enhancement

#7710 Fix for RR-CirKits definitions.
  java/src/jmri/jmrit/symbolicprog/SplitVariableValue.java
Labels: Add to Next Test Release, Bug

#7719 Fix NPE. Fix alternate track redirect.
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
Labels: Bug

#7712 Minor doc updates
  help/en/html/doc/Technical/JVMCapabilities.shtml
  help/en/html/doc/Technical/index.shtml
  help/en/html/tools/signaling/SignalMasts.shtml
  help/fr/html/doc/Technical/index.shtml
Labels: Cleanup, Developer

#7684 Java11 updates
  java/src/jmri/jmrit/Sound.java
  java/src/jmri/jmrit/beantable/oblock/TableFrames.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/FunctionButton.java
  java/src/jmri/jmrix/AbstractMRTrafficController.java
  java/src/jmri/jmrix/ecos/EcosTrafficController.java
  java/src/jmri/util/BusyGlassPane.java
  java/src/jmri/util/MenuScroller.java
Labels: After Next Production Release

#7709 Windows Installer remove JMRI Demo Shortcut
  scripts/WinInstallFiles/InstallJMRI.nsi
Labels: After Next Production Release

#7677 Run integration tests separately
  build.xml
  java/src/apps/SystemConsoleAction.java
  java/test/apps/PackageTest.java
  java/test/apps/RunCucumberIT.java
  java/test/jmri/PackageTest.java
  java/test/jmri/RunCucumberIT.java
  pom.xml
  project.properties
  scripts/travis.sh
Labels: After Next Production Release, dev/test/publish infrastructure

#7733 Fix car load replace attributes
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/tools/AlternateTrackFrame.java
  java/src/jmri/jmrit/operations/locations/tools/IgnoreUsedTrackFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarLoadEditFrame.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarLoadEditFrameTest.java
Labels: Add to Next Test Release, Bug

#7657 LayoutEditor-reorg
  java/src/jmri/jmrit/display/layoutEditor/LayoutBlock.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/Bundle.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/EnterGridSizesDialog.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/EnterReporterDialog.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutTrackDrawingOptionsDialog.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutTrackEditors.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/MoveSelectionDialog.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/ScaleTrackDiagramDialog.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutSlip.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTrackDrawingOptions.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTurnout.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTurntable.java
  java/src/jmri/jmrit/display/layoutEditor/LevelXing.java
  java/src/jmri/jmrit/display/layoutEditor/TrackSegment.java
  java/src/jmri/jmrit/display/layoutEditor/configurexml/LayoutTrackDrawingOptionsXml.java
  java/src/jmri/jmrit/entryexit/EntryExitPairs.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/BundleTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/EnterGridSizesDialogTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/EnterReporterDialogTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutTrackDrawingOptionsDialogTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutTrackEditorsTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/MoveSelectionDialogTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/PackageTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/ScaleTrackDiagramDialogTest.java
  java/test/jmri/jmrit/display/layoutEditor/PackageTest.java
Labels: After Next Production Release

#7736 TCS WOW
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/tcs/CV1_CV99_wow.xml
Labels: Add to Next Test Release

#7734 LayoutEditor-Add-ability-to-rotate-entire-layout
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutSlip.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTrack.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTurnout.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTurntable.java
  java/src/jmri/jmrit/display/layoutEditor/LevelXing.java
  java/src/jmri/jmrit/display/layoutEditor/PositionablePoint.java
  java/src/jmri/jmrit/display/layoutEditor/TrackSegment.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorTest.java
Labels: After Next Production Release

#7735 update jacoco version to 0.8.5; reduce number of excluded classes
  build.xml
  java/src/jmri/jmris/simpleserver/parser/package-info.java
  java/src/jmri/jmris/srcp/parser/package-info.java
  java/src/jmri/jmrix/srcp/parser/package-info.java
  java/test/jmri/jmrit/operations/rollingstock/cars/XmlTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/XmlTest.java
  lib/org.jacoco.ant-0.8.2-nodeps.jar
  lib/org.jacoco.ant-0.8.5-nodeps.jar
  pom.xml
Labels: After Next Production Release, dev/test/publish infrastructure

#7747 Mark testStopButton as intermittent
  java/test/jmri/jmrit/throttle/ThrottleFrameTest.java
Labels: After Next Production Release, dev/test/publish infrastructure

#7750 remove a few more classes from the excluded coverage list.
  appveyor.yml
  build.xml
  java/src/jmri/jmrit/operations/automation/Xml.java
  java/src/jmri/jmrit/operations/locations/Xml.java
  java/src/jmri/jmrit/operations/locations/schedules/Xml.java
  java/src/jmri/jmrit/operations/rollingstock/Xml.java
  java/src/jmri/jmrit/operations/rollingstock/cars/Xml.java
  java/src/jmri/jmrit/operations/rollingstock/engines/Xml.java
  java/src/jmri/jmrit/operations/routes/Xml.java
  java/src/jmri/jmrit/operations/setup/Xml.java
  java/src/jmri/jmrit/operations/trains/Xml.java
  java/src/jmri/jmrit/operations/trains/configurexml/Xml.java
  java/src/jmri/jmrit/operations/trains/excel/Xml.java
  java/src/jmri/jmrit/operations/trains/schedules/Xml.java
  java/test/jmri/jmrit/operations/automation/PackageTest.java
  java/test/jmri/jmrit/operations/automation/XmlTest.java
  java/test/jmri/jmrit/operations/locations/schedules/PackageTest.java
  java/test/jmri/jmrit/operations/locations/schedules/XmlTest.java
  java/test/jmri/jmrit/operations/rollingstock/PackageTest.java
  java/test/jmri/jmrit/operations/rollingstock/XmlTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/PackageTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/XmlTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/PackageTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/XmlTest.java
  java/test/jmri/jmrit/operations/routes/PackageTest.java
  java/test/jmri/jmrit/operations/routes/XmlTest.java
  java/test/jmri/jmrit/operations/setup/PackageTest.java
  java/test/jmri/jmrit/operations/setup/XmlTest.java
  java/test/jmri/jmrit/operations/trains/configurexml/PackageTest.java
  java/test/jmri/jmrit/operations/trains/configurexml/XmlTest.java
  java/test/jmri/jmrit/operations/trains/excel/PackageTest.java
  java/test/jmri/jmrit/operations/trains/excel/XmlTest.java
  java/test/jmri/jmrit/operations/trains/schedules/PackageTest.java
  java/test/jmri/jmrit/operations/trains/schedules/XmlTest.java
  pom.xml
Labels: dev/test/publish infrastructure

#7749 Fix DTD files
  xml/DTD/operations-config.dtd
  xml/DTD/operations-routes.dtd
Labels: Bug

#7754 Nonnull and others
  .idea/codeStyles/Project.xml
  help/en/html/tools/throttle/ThrottlesPreferencesPane.shtml
  java/src/jmri/CatalogTreeManager.java
  java/src/jmri/LightManager.java
  java/src/jmri/Manager.java
  java/src/jmri/NamedBeanHandleManager.java
  java/src/jmri/ProxyManager.java
  java/src/jmri/ReporterManager.java
  java/src/jmri/SectionManager.java
  java/src/jmri/SignalMastManager.java
  java/src/jmri/TransitManager.java
  java/src/jmri/TurnoutManager.java
  java/src/jmri/jmrit/audio/DefaultAudioManager.java
  java/src/jmri/jmrit/beantable/AbstractTableAction.java
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/ReporterTableAction.java
  java/src/jmri/jmrit/beantable/SensorTableAction.java
  java/src/jmri/jmrit/beantable/TurnoutTableAction.java
  java/src/jmri/jmrit/blockboss/BlockBossLogic.java
  java/src/jmri/jmrit/catalog/DefaultCatalogTreeManager.java
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/panelEditor/PanelEditor.java
  java/src/jmri/jmrit/entryexit/EntryExitPairs.java
  java/src/jmri/jmrit/logix/OBlock.java
  java/src/jmri/jmrit/logix/OBlockManager.java
  java/src/jmri/jmrit/logix/OPath.java
  java/src/jmri/jmrit/logix/PortalManager.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantManager.java
  java/src/jmri/jmrit/logix/configurexml/OBlockManagerXml.java
  java/src/jmri/jmrix/can/cbus/CbusReporterManager.java
  java/src/jmri/jmrix/internal/InternalReporterManager.java
  java/src/jmri/jmrix/internal/InternalTurnoutManager.java
  java/src/jmri/jmrix/powerline/SerialTurnoutManager.java
  java/src/jmri/jmrix/roco/z21/Z21ReporterManager.java
  java/src/jmri/managers/AbstractLightManager.java
  java/src/jmri/managers/AbstractMemoryManager.java
  java/src/jmri/managers/AbstractProxyManager.java
  java/src/jmri/managers/AbstractReporterManager.java
  java/src/jmri/managers/AbstractSensorManager.java
  java/src/jmri/managers/AbstractSignalHeadManager.java
  java/src/jmri/managers/AbstractTurnoutManager.java
  java/src/jmri/managers/DefaultLogixManager.java
  java/src/jmri/managers/DefaultMemoryManager.java
  java/src/jmri/managers/DefaultRouteManager.java
  java/src/jmri/managers/DefaultSignalMastManager.java
  java/src/jmri/managers/ProxyIdTagManager.java
  java/src/jmri/managers/ProxyLightManager.java
  java/src/jmri/managers/ProxyReporterManager.java
  java/src/jmri/managers/ProxySensorManager.java
  java/src/jmri/managers/ProxyTurnoutManager.java
  java/test/jmri/jmrit/blockboss/BlockBossLogicTest.java
  java/test/jmri/jmrit/logix/PortalTest.java
  java/test/jmri/managers/TurnoutManagerScaffold.java
  java/test/jmri/util/managers/InternalLightManagerThrowExceptionScaffold.java
  java/test/jmri/util/managers/MemoryManagerThrowExceptionScaffold.java
  java/test/jmri/util/managers/RouteManagerThrowExceptionScaffold.java
  java/test/jmri/util/managers/SignalHeadManagerThrowExceptionScaffold.java
  java/test/jmri/util/managers/TurnoutManagerThrowExceptionScaffold.java
Labels: Cleanup

#7762 Remove deprecated code
  java/src/jmri/implementation/DccSignalHead.java
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTrack.java
  java/src/jmri/jmrit/signalling/SignallingPanel.java
  java/src/jmri/jmrix/loconet/LnOpsModeProgrammer.java
  java/src/jmri/jmrix/loconet/LnPacketizer.java
  java/src/jmri/jmrix/loconet/LnProgrammerManager.java
  java/src/jmri/jmrix/loconet/LnTrafficRouter.java
  java/src/jmri/jmrix/openlcb/OlcbThrottle.java
  java/src/jmri/jmrix/openlcb/OlcbThrottleManager.java
  java/src/jmri/jmrix/qsi/QsiTrafficController.java
  java/src/jmri/managers/JmriUserPreferencesManager.java
  java/src/jmri/managers/configurexml/DefaultSignalGroupManagerXml.java
  java/src/jmri/server/json/throttle/JsonThrottleManager.java
  java/src/jmri/util/BareBonesBrowserLaunch.java
  java/test/jmri/ArchitectureTest.java
  java/test/jmri/jmrix/loconet/LnProgrammerManagerTest.java
  java/test/jmri/managers/JmriUserPreferencesManagerTest.java
  java/test/jmri/server/json/throttle/JsonThrottleManagerTest.java
  java/test/jmri/util/BareBonesBrowserLaunchTest.java
  java/test/jmri/util/PackageTest.java
Labels: Cleanup, dev/test/publish infrastructure

#7764 Validate names.xml file using an XML Schema
  java/test/jmri/jmrit/decoderdefn/SchemaTest.java
  xml/DTD/names-config.dtd
  xml/names.xml
  xml/schema/names-4.19.1.xsd
Labels: dev/test/publish infrastructure

#7792 fix issues in B&O semaphore
  xml/signals/B&O-Semaphore/appearance-bumper.xml
Labels: Bug, Cleanup, Enhancement

#7791 fix NW-1981 issue against strict appearancetable.xsd
  xml/signals/NW-1981/appearance-CPL-1-arm-permissive.xml
Labels: Bug, Cleanup, Enhancement

#7793 define missing 'Not Lit' aspect in WM-1980
  xml/signals/WM-1980/appearance-USS-R2-1-arm-low-marker-permissive.xml
  xml/signals/WM-1980/appearance-USS-R2-1-arm-permissive.xml
Labels: Bug, Cleanup, Enhancement

#7790 fix SOU-1981 issues against strict appearancetable.xsd
  xml/signals/SOU-1981/appearance-CL-2-arm-highspace-absolute.xml
  xml/signals/SOU-1981/appearance-CL-2-arm-permissive.xml
  xml/signals/SOU-1981/appearance-CL-3-arm-absolute.xml
Labels: Bug, Cleanup, Enhancement

#7797 Second try - fix for SOU-1981
  xml/signals/SOU-1981/appearance-CL-2-arm-highspace-absolute.xml
Labels: Bug
