Repository JMRI/JMRI, pull requests merged in 2019-02, with the labels that each got.

#6516 Initial version total rewritten
  xml/decoders/Fleischmann_Function.xml
Labels: Enhancement

#6539 Request by operations user inspectordave to change the order of the text
  java/src/jmri/jmrit/operations/routes/SetTrainIconPositionFrame.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/ImportEnginesTest.java
  java/test/jmri/jmrit/operations/routes/SetTrainIconPositionFrameTest.java
Labels: Enhancement

#6541 Minor improvement to build reports
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
Labels: Enhancement

#6557 Fix typo
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
Labels: Bug

#6564 remove 'extra' LocoNet menu for standalone programmer mode
  java/src/jmri/jmrix/loconet/pr2/LnPr2Packetizer.java
  java/src/jmri/jmrix/loconet/pr3/PR3Adapter.java
Labels: Bug

#6580 Code and infrastructure updates - turn on deprecation checks
  build.xml
  java/ecj.warning.options
  java/ecj.warning.options-ci
  java/ecj.warning.options-test
  java/ecj.warning.options-test-ci
  java/src/jmri/AudioException.java
  java/src/jmri/implementation/DefaultRailCom.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/sample/swing/SampleConfigPane.java
  java/src/jmri/jmrit/vsdecoder/DieselPane.java
  java/src/jmri/jmrit/vsdecoder/EnginePane.java
  java/src/jmri/jmrit/vsdecoder/LoadVSDFileAction.java
  java/src/jmri/jmrit/vsdecoder/StoreXmlVSDecoderAction.java
  java/src/jmri/jmrit/vsdecoder/VSDManagerEvent.java
  java/src/jmri/jmrit/vsdecoder/VSDOptionPanel.java
  java/src/jmri/jmrit/vsdecoder/VSDSoundsPanel.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderCreationAction.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderEvent.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderFrame.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderPane.java
  java/src/jmri/jmrit/vsdecoder/swing/DieselPane.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDControl.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDManagerFrame.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDPreferencesAction.java
  java/src/jmri/jmrix/configurexml/AbstractConnectionConfigXml.java
  java/src/jmri/jmrix/loconet/AbstractBoardProgPanel.java
  java/src/jmri/jmrix/roco/z21/Z21Reply.java
  java/src/jmri/server/json/JsonException.java
  java/src/jmri/server/json/JsonHttpService.java
  java/test/jmri/configurexml/TestBean1.java
Labels: dev/test/publish infrastructure

#6590 Allow user to modify name, description, or comment after train is built.
  java/src/jmri/jmrit/operations/trains/TrainEditFrame.java
Labels: Enhancement

#6591 Czech translation - fix mistypes
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/jmris/srcp/JmriSRCPServerBundle_cs.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/conditional/ConditionalBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelBundle_cs.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_cs.properties
  java/src/jmri/jmrit/display/palette/PaletteBundle_cs.properties
  java/src/jmri/jmrit/signalling/SignallingBundle_cs.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_cs.properties
  java/src/jmri/jmrit/withrottle/WiThrottleBundle_cs.properties
  java/src/jmri/jmrix/JmrixBundle_cs.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_cs.properties
  java/src/jmri/profile/Bundle_cs.properties
  web/servlet/operations/Operations_cs.html
  web/servlet/panel/Panel_cs.html
  web/servlet/roster/Roster_cs.html
  xml/decoders/Public_Domain_dccdoma_ARD_SCOM_MX.xml
Labels: Enhancement

#6607 Eliminate data files left behind by TimeTable tests.
  java/src/jmri/jmrit/timetable/configurexml/TimeTableXml.java
  java/test/jmri/jmrit/timetable/StopTest.java
  java/test/jmri/jmrit/timetable/TimeTableCsvExportTest.java
  java/test/jmri/jmrit/timetable/TimeTableCsvImportTest.java
  java/test/jmri/jmrit/timetable/TimeTableDataManagerTest.java
  java/test/jmri/jmrit/timetable/TimeTableImportTest.java
  java/test/jmri/jmrit/timetable/TrainTest.java
  java/test/jmri/jmrit/timetable/TrainTypeTest.java
  java/test/jmri/jmrit/timetable/configurexml/TimeTableXmlTest.java
  java/test/jmri/jmrit/timetable/swing/TimeTableActionTest.java
  java/test/jmri/jmrit/timetable/swing/TimeTableFrameTest.java
  java/test/jmri/jmrit/timetable/swing/TimeTableGraphTest.java
Labels: Cleanup
