Repository JMRI/JMRI, pull requests merged in 2019-11, with the labels that each got.

#7587 Allow user to not use the car drops format
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_de.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/schedules/SchedulesByLoadFrame.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockAttribute.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarRoads.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarTypes.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarLoadEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarLoadsAction.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarLoadsActionTest.java
Labels: Enhancement

#7592 Minor Manifest formating when last location has no work
  java/src/jmri/jmrit/operations/trains/TrainManifest.java
Labels: Enhancement

#7593 Allow user to display load name as a single character
  java/src/jmri/jmrit/operations/rollingstock/RollingStockAttribute.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLengths.java
Labels: Enhancement

#7601 Manifest can now show car weight and load type
  java/src/jmri/jmrit/operations/JmritOperationsBundle.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_ca.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_da.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_de.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_fr.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_it.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_nl.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_nl.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLengths.java
  java/src/jmri/jmrit/operations/setup/EditManifestHeaderTextPanel.java
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/jmrit/operations/trains/TrainManifestHeaderText.java
  java/src/jmri/jmrit/operations/trains/Xml.java
Labels: Enhancement

#7606 Formatting, Javadoc lint, FindBugs, Checkstyle.
  java/src/jmri/jmrit/symbolicprog/AbstractValue.java
  java/src/jmri/jmrit/symbolicprog/VariableValue.java
  java/test/jmri/jmrit/symbolicprog/AbstractVariableValueTestBase.java
  java/test/jmri/jmrit/symbolicprog/DecVariableValueTest.java
Labels: Cleanup

#7635 Improve help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Enhancement

#7494 Close Windows during tests
  java/src/jmri/jmrit/beantable/BlockTableAction.java
  java/src/jmri/jmrit/consisttool/ConsistToolPrefsPanel.java
  java/src/jmri/jmrit/timetable/swing/TimeTableStartup.java
  java/test/apps/gui3/FirstTimeStartUpWizardTest.java
  java/test/apps/gui3/mdi/MDITest.java
  java/test/jmri/implementation/DefaultConditionalTest.java
  java/test/jmri/jmrit/catalog/DirectorySearcherTest.java
  java/test/jmri/jmrit/catalog/PreviewDialogTest.java
  java/test/jmri/jmrit/consisttool/ConsistToolFrameTest.java
  java/test/jmri/jmrit/ctc/editor/CtcEditorActionTest.java
  java/test/jmri/jmrit/ctc/editor/gui/FrmMainFormTest.java
  java/test/jmri/jmrit/dispatcher/LoadAtStartUpTest.java
  java/test/jmri/jmrit/display/PanelEditorTest.java
  java/test/jmri/jmrit/display/SensorIconWindowTest.java
  java/test/jmri/jmrit/display/SignalSystemTest.java
  java/test/jmri/jmrit/display/TurnoutIconWindowTest.java
  java/test/jmri/jmrit/display/layoutEditor/MemoryIconTest.java
  java/test/jmri/jmrit/display/layoutEditor/PositionablePointTest.java
  java/test/jmri/jmrit/jython/SampleScriptTest.java
  java/test/jmri/jmrit/logix/NXFrameTest.java
  java/test/jmri/jmrit/operations/OperationsTestCase.java
  java/test/jmri/jmrit/progsupport/ProgDeferredServiceModePaneTest.java
  java/test/jmri/jmrit/roster/swing/speedprofile/SpeedProfileTableTest.java
  java/test/jmri/jmrit/throttle/BackgroundPanelTest.java
  java/test/jmri/jmrit/throttle/ControlPanelPropertyEditorTest.java
  java/test/jmri/jmrit/throttle/ControlPanelTest.java
  java/test/jmri/jmrit/throttle/FunctionButtonPropertyEditorTest.java
  java/test/jmri/jmrit/throttle/FunctionPanelTest.java
  java/test/jmri/jmrit/throttle/ThrottleFramePropertyEditorTest.java
  java/test/jmri/jmrit/throttle/ThrottleFrameTest.java
  java/test/jmri/jmrit/throttle/ThrottleOperator.java
  java/test/jmri/jmrit/timetable/configurexml/TimeTableXmlTest.java
  java/test/jmri/jmrit/timetable/swing/TimeTableActionTest.java
  java/test/jmri/jmrit/timetable/swing/TimeTableFrameTest.java
  java/test/jmri/jmrit/vsdecoder/swing/VSDConfigDialogTest.java
  java/test/jmri/jmrit/vsdecoder/swing/VSDOptionsDialogTest.java
  java/test/jmri/jmrix/dccpp/DCCppMessageTest.java
  java/test/jmri/jmrix/dccpp/DCCppMultiMeterTest.java
  java/test/jmri/jmrix/dccpp/DCCppOpsModeProgrammerTest.java
  java/test/jmri/jmrix/dccpp/DCCppPacketizerTest.java
  java/test/jmri/jmrix/dccpp/DCCppStreamConnectionConfigTest.java
  java/test/jmri/jmrix/dccpp/DCCppStreamPortControllerTest.java
  java/test/jmri/jmrix/dccpp/DCCppThrottleManagerTest.java
  java/test/jmri/jmrix/dccpp/DCCppTurnoutManagerTest.java
  java/test/jmri/jmrix/dccpp/network/configurexml/ConnectionConfigXmlTest.java
  java/test/jmri/jmrix/dccpp/simulator/ConnectionConfigTest.java
  java/test/jmri/jmrix/dccpp/simulator/configurexml/ConnectionConfigXmlTest.java
  java/test/jmri/jmrix/dccpp/swing/packetgen/PacketGenFrameTest.java
  java/test/jmri/jmrix/grapevine/SerialTurnoutTest.java
  java/test/jmri/jmrix/loconet/hexfile/HexFileFrameTest.java
  java/test/jmri/jmrix/loconet/hexfile/configurexml/ConnectionConfigXmlTest.java
  java/test/jmri/server/json/util/JsonUtilSocketServiceTest.java
  java/test/jmri/util/JmriJFrameTestBase.java
  java/test/jmri/util/Log4JErrorIsErrorTest.java
  java/test/jmri/util/swing/JmriColorChooserTest.java
Labels: Cleanup, Developer, dev/test/publish infrastructure

#7651 Add Locale to context
  java/src/jmri/jmrit/mailreport/ReportContext.java
Labels: Enhancement

#7665 include signal systems not previously documented
  help/en/html/tools/signaling/AspectSignaling.shtml
  xml/signals/DanishSimplified/index.shtml
Labels: Enhancement

#7674 Avoid crash in certain scenarios when logging
  java/src/jmri/util/JTextPaneAppender.java
Labels: Bug

#7675 Improve formatting.
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/tools/ExportTimetable.java
Labels: Enhancement

#7676 Create new schedule for every OperationsPro import
  java/src/jmri/jmrit/operations/trains/tools/ExportTimetable.java
Labels: Enhancement

#7678 Update help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Enhancement

#7679 Fix for deprecated instance method
  jython/USBThrottleAsJynstrument.py
Labels: Bug

#7680 MERG CBUS - Display OPC by default in CBUS Console
  java/src/jmri/jmrix/can/cbus/swing/console/CbusConsolePane.java
Labels: Enhancement
