Repository JMRI/JMRI, pull requests merged in 2019-05, with the labels that each got.

#6920 Allow consist to be built by single locos when departing staging
  java/src/jmri/jmrit/operations/trains/TrainEditBuildOptionsFrame.java
Labels: Enhancement

#6923 Fix consist blocking order bug
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_nl.properties
  java/src/jmri/jmrit/operations/rollingstock/RollingStockEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineEditFrame.java
  jython/operations/OperationsSelectBuildAndTerminateTrain.py
Labels: Bug

#6882 Added code to set turnout circle color based on turnout state
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutSlip.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTurnout.java
  java/src/jmri/jmrit/display/layoutEditor/configurexml/LayoutEditorXml.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorTest.java
  java/test/jmri/jmrit/display/layoutEditor/loadref/LayoutEditorTest.xml
  xml/schema/types/layouteditor.xsd
Labels: Enhancement

#6860 Convert the panel editors to use machine dependent locations
  java/src/apps/AppsConfigBundle.properties
  java/src/apps/GuiLafConfigPane.java
  java/src/apps/gui/GuiLafPreferencesManager.java
  java/src/jmri/jmrit/display/controlPanelEditor/configurexml/ControlPanelEditorXml.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/configurexml/LayoutEditorXml.java
  java/src/jmri/jmrit/display/panelEditor/configurexml/PanelEditorXml.java
  java/src/jmri/jmrit/display/switchboardEditor/configurexml/SwitchboardEditorXml.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorTest.java
  java/test/jmri/jmrit/display/layoutEditor/PackageTest.java
  java/test/jmri/jmrit/display/layoutEditor/load/LayoutEditorTest.xml
  java/test/jmri/jmrit/display/layoutEditor/loadref/LayoutEditorTest.xml
  xml/schema/types/layouteditor.xsd
  xml/schema/types/paneleditor.xsd
  xml/schema/types/switchboardeditor.xsd
Labels: Enhancement

#6929 Fix synchronization lock
  java/src/jmri/InstanceManager.java
Labels: Bug

#6914 MERG CBUS Reporter Autocreation
  help/en/html/hardware/can/cbus/Names.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/can/cbus/CbusReporter.java
  java/src/jmri/jmrix/can/cbus/CbusReporterManager.java
  java/test/jmri/jmrix/can/cbus/CbusReporterManagerTest.java
  java/test/jmri/jmrix/can/cbus/CbusReporterTest.java
Labels: Enhancement

#6942 add jarchive library which is a dependency for webdrivermanager
  .classpath
  build.xml
  lib/README.md
  lib/jarchivelib-1.0.0.jar
  nbproject/project.xml
Labels: dev/test/publish infrastructure

#6967 Running on GUI thread can cause complete lockup of JMRI, revert change
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/configurexml/TrainIconXml.java
Labels: Bug

#6971 Don't pass the train object to the GUI thread
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/configurexml/TrainIconXml.java
Labels: Cleanup

#6999 Minor GUI improvements, disable Tools menu for new items
  java/src/jmri/jmrit/operations/locations/InterchangeEditFrame.java
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/SpurEditFrame.java
  java/src/jmri/jmrit/operations/locations/StagingEditFrame.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/YardEditFrame.java
  java/src/jmri/jmrit/operations/locations/tools/ShowCarsByLocationAction.java
  java/src/jmri/jmrit/operations/routes/RouteCopyAction.java
  java/src/jmri/jmrit/operations/routes/RouteCopyFrame.java
  java/src/jmri/jmrit/operations/routes/RouteEditFrame.java
  java/src/jmri/jmrit/operations/routes/SetTrainIconRouteAction.java
  java/src/jmri/jmrit/operations/routes/SetTrainIconRouteFrame.java
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/trains/TrainEditBuildOptionsFrame.java
  java/src/jmri/jmrit/operations/trains/TrainEditFrame.java
  java/test/jmri/jmrit/operations/routes/RouteCopyFrameTest.java
  java/test/jmri/jmrit/operations/routes/SetTrainIconRouteFrameTest.java
Labels: Enhancement

#7005 Order seems to matter to profile startup tests
  java/test/apps/PackageTest.java
Labels: dev/test/publish infrastructure

#6989 Digitrax help reorg and clarification, incl. bushby
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/images/LnTurnoutBushbySettings.png
  help/en/html/hardware/loconet/images/LnTurnoutFeedbackAutomationSettings.png
Labels: Cleanup

#7007 Code style
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: Developer

#7030 MatrixMast comment
  java/src/jmri/implementation/MatrixSignalMast.java
  java/src/jmri/jmrit/beantable/SignalMastTableAction.java
  java/src/jmri/jmrit/beantable/signalmast/MatrixSignalMastAddPane.java
  java/src/jmri/jmrit/beantable/signalmast/SignalMastAddPane.java
  java/src/jmri/util/swing/BeanSelectCreatePanel.java
Labels: Bug
