Repository JMRI/JMRI, pull requests merged in 2020-08, with the labels that each got.

#8882 updates for JMRI Web Access page
  help/en/html/web/index.shtml
Labels: Documentation

#8839 Fix Weblink in CBUS Support
  help/en/html/hardware/can/cbus/index.shtml
Labels: Documentation

#8866 Updates, fixes for ESU decoder definitions.
  xml/decoders/ESU_LokPilot5.xml
  xml/decoders/ESU_LokPilotV4.0.xml
  xml/decoders/ESU_LokPilot_StandardV1_0.xml
  xml/decoders/ESU_LokSound5.xml
  xml/decoders/ESU_LokSoundV4_0.xml
  xml/decoders/ESU_LokSound_Select.xml
  xml/decoders/esu/lpStdV1AltLightEnum.xml
  xml/decoders/esu/lpStdV1FnMapCVs.xml
  xml/decoders/esu/susiMapCVs.xml
  xml/decoders/esu/susiMapPane.xml
  xml/decoders/esu/v4fnOutPane.xml
  xml/decoders/esu/v4lightEnum.xml
  xml/decoders/esu/v4soundPane.xml
  xml/decoders/esu/v4standardCVs.xml
  xml/decoders/esu/v5fnEnum.xml
  xml/decoders/esu/v5fnOutCVs.xml
  xml/decoders/esu/v5standardCVs.xml
Labels: Add to Next Test Release, Cleanup

#8887 Correct footer on XSLT-generated pages
  xml/XSLT/CVsummary.xsl
  xml/XSLT/DecoderID.xsl
  xml/XSLT/DecoderMfgIndex.xsl
  xml/XSLT/DecoderModelIndex.xsl
  xml/XSLT/DecoderModelList.xsl
  xml/XSLT/LogixToCode.xsl
  xml/XSLT/SelectionGuide.xsl
  xml/XSLT/appearancetable.xsl
  xml/XSLT/aspecttable.xsl
  xml/XSLT/consistRoster.xsl
  xml/XSLT/decoder-with-form.xsl
  xml/XSLT/decoder.xsl
  xml/XSLT/idtags.xsl
  xml/XSLT/locomotive.xsl
  xml/XSLT/mfgID.xsl
  xml/XSLT/panelfile-2-9-6.xsl
  xml/XSLT/panelfile-4-19-2.xsl
  xml/XSLT/panelfile.xsl
  xml/XSLT/roster.xsl
  xml/XSLT/roster2array.xsl
  xml/XSLT/roster2text.xsl
  xml/XSLT/rpsfile.xsl
  xml/XSLT/speedometer.xsl
  xml/XSLT/throttle.xsl
  xml/XSLT/vsdecoder-config.xsl
Labels: dev/test/publish infrastructure

#8841 Create JMRI general FAQ.shtml
  help/en/html/FAQ.shtml
Labels: Documentation

#8874 Digirails_Stationary.xml: fix mask for CV47
  xml/decoders/Digirails_Stationary.xml
Labels: Bug

#8855 Update Testing documentation for JUnit 5
  help/en/html/doc/Technical/JUnit.shtml
Labels: Developer, Documentation

#8896 Mark a LocoNet test as intermittent
  java/test/jmri/jmrix/loconet/LocoNetThrottledTransmitterTest.java
Labels: dev/test/publish infrastructure

#8905 Update general JMRI FAQ
  help/en/html/FAQ.shtml
Labels: Documentation

#8911 fix typos
  xml/signals/B&O-1980/index.shtml
Labels: Add to Next Test Release, Cleanup

#8907 Update some help docs with broken sidebar links and related...
  help/en/html/doc/Technical/Help.shtml
  help/en/html/doc/Technical/Sidebar.shtml
  help/en/html/doc/Technical/UpdatingDocs.shtml
  help/en/html/doc/Technical/WebSite.shtml
  help/en/html/tools/Sidebar.shtml
  help/en/html/tools/signaling/Sidebar.shtml
Labels: Documentation

#8917 Update JmriHelp_enIndex.xml and JmriTOC_enIndex.xml
  help/en/JmriHelp_enIndex.xml
  help/en/JmriHelp_enTOC.xml
Labels: Documentation

#8915 Add backwards search to DecoderPro and restore status bar layout
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
  java/src/jmri/util/swing/SearchBar.java
Labels: Bug

#8921 Minor doc update (routine parts of #8832)
  help/en/html/doc/Technical/RP.shtml
  help/en/html/doc/Technical/TechRoadMap.shtml
  help/en/html/doc/Technical/TechRoadMapOlder.shtml
  help/en/html/doc/Technical/gitadmin.shtml
Labels: Documentation, dev/test/publish infrastructure

#8925 Adjust CI test thresholds
  .codeclimate.yml
  codecov.yml
Labels: dev/test/publish infrastructure

#8934 Update release notes.
  help/en/releasenotes/current-draft-note.shtml
Labels: Add to Next Test Release

#8932 Defining Decoders that use Functions above F28.
  java/src/jmri/jmrit/roster/RosterEntry.java
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
  java/test/jmri/jmrit/decoderdefn/DecoderFileTest.java
  java/test/jmri/jmrit/roster/RosterEntryTest.java
  java/test/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrameTest.java
  xml/decoders/ESU_LokPilot5.xml
  xml/decoders/ESU_LokSound5.xml
  xml/decoders/ESU_LokSoundV3_5.xml
  xml/schema/decoder-4-15-2.xsd
  xml/schema/locomotive-config.xsd
Labels: Add to Next Test Release, Enhancement

#8933 Function Group Packets up to F68.
  java/src/jmri/NmraPacket.java
  java/test/jmri/NmraPacketTest.java
Labels: Add to Next Test Release, Enhancement

#8944 Allow disabling of 'Reset to Defaults' button for some decoders.
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
  xml/decoders/ESU_LokPilot5.xml
  xml/decoders/ESU_LokPilotV4.0.xml
  xml/decoders/ESU_LokSound5.xml
  xml/decoders/ESU_LokSoundV3_5.xml
  xml/decoders/ESU_LokSoundV4_0.xml
  xml/decoders/ESU_LokSound_Select.xml
  xml/decoders/ESU_LokSound_Select_Steam.xml
  xml/schema/decoder-4-15-2.xsd
Labels: Enhancement

#8959 Help small fix
  help/en/html/tools/signaling/index.shtml
  xml/signals/RG-1965/index.shtml
Labels: Documentation

#8962 Remake decoderIndex - recent ESU and SoundTraxx changes.
  xml/decoderIndex.xml
Labels: Add to Next Test Release

#8973 restore missing SPROG command station in OpsMode
  java/src/jmri/jmrix/sprog/SprogSystemConnectionMemo.java
  java/test/jmri/jmrix/sprog/SprogSystemConnectionMemoTest.java
Labels: Bug

#8979 Output Interval help
  help/en/html/hardware/XBee/index.shtml
  help/en/html/hardware/XPressNet/index.shtml
  help/en/html/hardware/arduino/index.shtml
  help/en/html/hardware/can/cbus/Details.shtml
  help/en/html/hardware/cmri/CMRI.shtml
  help/en/html/hardware/digirails/index.shtml
  help/en/html/hardware/easydcc/EasyDCC.shtml
  help/en/html/hardware/grapevine/index.shtml
  help/en/html/hardware/loconet/DCS52.shtml
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/images/LoconetAdditionalSettings.png
  help/en/html/hardware/mqtt/index.shtml
  help/en/manual/DecoderPro3/Start_Preferences.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Start_Preferences.shtml
  help/en/package/apps/TabbedPreferences.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#8972 Fix broken MQTT Sensor invert option
  java/src/jmri/jmrix/mqtt/MqttLight.java
  java/src/jmri/jmrix/mqtt/MqttSensor.java
  java/src/jmri/jmrix/mqtt/MqttTurnout.java
Labels: Bug
