Repository JMRI/JMRI, pull requests merged in 2020-01, with the labels that each got.

#7836 Final merge of development to master
  .travis.yml
  build.xml
  help/en/html/doc/Technical/Names.shtml
  help/en/html/doc/Technical/Swing.shtml
  help/en/package/jmri/jmrit/beantable/RouteAddEdit.shtml
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/jmri/jmrit/throttle/FunctionButton.java
  java/src/jmri/managers/DefaultRouteManager.java
  java/src/jmri/managers/ManagersBundle.properties
  java/src/jmri/managers/configurexml/Bundle.java
  java/src/jmri/managers/configurexml/DefaultRouteManagerXml.java
  java/src/jmri/swing/NamedBeanComboBox.java
  java/test/jmri/configurexml/LoadAndCheckTest.java
  java/test/jmri/configurexml/LoadAndStoreTestBase.java
  java/test/jmri/configurexml/loadref/LoadFileTest-4.7.4.xml
  java/test/jmri/configurexml/loadref/LoadFileTest.xml
  java/test/jmri/configurexml/loadref/LoadFileTest277-4.7.4.xml
  java/test/jmri/configurexml/loadref/LoadFileTest277.xml
  java/test/jmri/configurexml/loadref/LoadFileTest295-4.7.4.xml
  java/test/jmri/configurexml/loadref/LoadFileTest295.xml
  java/test/jmri/configurexml/loadref/PanelFileSchemaTest.xml
  java/test/jmri/configurexml/loadref/PanelFileSchemaTest295.xml
  java/test/jmri/configurexml/loadref/PanelFileSchemaTest382-4.7.4.xml
  java/test/jmri/configurexml/loadref/PanelFileSchemaTest382.xml
  java/test/jmri/implementation/configurexml/loadref/RouteTestExamples.xml
  java/test/jmri/jmrit/beantable/RouteTableActionTest.java
  java/test/jmri/jmrit/entryexit/load/EntryExitTest.xml
  java/test/jmri/managers/DefaultRouteManagerTest.java
  java/test/jmri/managers/configurexml/BundleTest.java
  java/test/jmri/managers/configurexml/PackageTest.java
  java/test/jmri/server/json/route/JsonRouteHttpServiceTest.java
  java/test/jmri/server/json/route/JsonRouteSocketServiceTest.java
  java/test/jmri/swing/NamedBeanComboBoxTest.java
  pom.xml
Labels: Cleanup

#7853 Signal system fixes for more comprehensive schema
  xml/signals/AAR-1946/appearance-PL-2-high.xml
  xml/signals/AAR-1946/appearance-SL-2-high-abs.xml
  xml/signals/AAR-1946/appearance-SL-2-high-pbs.xml
  xml/signals/B&O-1957/appearance-PL-2-high.xml
  xml/signals/B&O-1957/appearance-SL-2-high-abs.xml
  xml/signals/B&O-1957/appearance-SL-2-high-pbs.xml
  xml/signals/B&O-1980/appearance-CPL-High-permissive.xml
  xml/signals/B&O-Semaphore/appearance-bumper.xml
  xml/signals/BNSF-1996/appearance-SE-2D.xml
  xml/signals/BNSF-1996/appearance-SL-3A.xml
  xml/signals/BNSF-1996/appearance-SL-3L3.xml
  xml/signals/CNJ-1974/appearance-SL-2-abs.xml
  xml/signals/CNJ-1974/appearance-SL-2-pbs.xml
  xml/signals/CNJ-1974/appearance-SL-3-pbs.xml
  xml/signals/CROR-2008/appearance-CROR-1-Hi.xml
  xml/signals/CROR-2008/appearance-CROR-1A-Hi.xml
  xml/signals/CROR-2008/appearance-CROR-1R-Hi.xml
  xml/signals/CROR-2008/appearance-CROR-2O-Hi.xml
  xml/signals/CROR-2008/appearance-CROR-2OL-Hi.xml
  xml/signals/CROR-2008/appearance-CROR-2SD-Hi.xml
  xml/signals/CROR-2008/appearance-CROR-2SL-Hi.xml
  xml/signals/CROR-2008/appearance-CROR-3L-Hi.xml
  xml/signals/CSX-1998/appearance-CLS-3-3-2-hi.xml
  xml/signals/CSX-1998/appearance-CLS-3-3-2A-hi.xml
  xml/signals/CSX-2014-Chessie/appearance-CO-1-3-1-hi.xml
  xml/signals/CSX-2014-Chessie/appearance-CO-1-3-2-hi.xml
  xml/signals/CSX-2014-Chessie/appearance-CO-1-3-3-hi.xml
  xml/signals/CSX-2014-Chessie/appearance-CO-3-2-2-hi.xml
  xml/signals/CSX-2014-Chessie/appearance-CO-3-3-1-hi.xml
  xml/signals/CSX-2014-Chessie/appearance-CO-3-3-lo.xml
  xml/signals/CSX-2014-Chessie/appearance-CO-3-hi.xml
  xml/signals/CSX-2014-Chessie/appearance-CO-3p-lo.xml
  xml/signals/DanishSimplified/aspects.xml
  xml/signals/NS-2008/appearance-171.xml
  xml/signals/NS-2008/appearance-CLS-3-3-hi.xml
  xml/signals/NW-1981/appearance-CPL-2-arm-permissive.xml
  xml/signals/NYC-1956/appearance-SL-2-high-abs.xml
  xml/signals/PRR-1956/appearance-PL-2-low.xml
  xml/signals/SLSF-1973/appearance-SL-3-b.xml
  xml/signals/SLSF-1973/appearance-SL-3-c.xml
  xml/signals/SLSF-1973/appearance-SL-3-d.xml
  xml/signals/SLSF-1973/appearance-SL-3.xml
  xml/signals/SPTCO-1969/appearance-SL-1-A.xml
Labels: Cleanup

#7865 RG 1965 Signal xml
  xml/signals/RG-1965/appearance-SL-2-low-abs.xml
  xml/signals/RG-1965/aspects.xml
Labels: Bug

#7731 Add Codecov coverage reporting
  .travis.yml
  codecov.yml
Labels: dev/test/publish infrastructure

#7891 fix compilation error
  java/src/jmri/web/servlet/panel/LayoutPanelServlet.java
Labels: Bug

#7879 Improve signal mast repeater help
  help/en/html/tools/signaling/SignalMasts.shtml
  help/en/html/tools/signaling/index.shtml
  help/en/package/jmri/jmrit/beantable/SignalMastRepeater.shtml
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterBidirectionalButton.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterCreation.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterCreation0.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterCreationBlocks.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterCreationMasts.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterCreationSelectDestination.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterCreationTurnouts.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterFinalSignalMastLogic.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterIconPlaced.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterMaster-to-SlaveButton.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterRoute1.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterRoute1SMLogic.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterRoute2.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterRoute2SMLogic.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterRoute3.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterRoute3Functioning.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterRoute3NoSMLogic.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterSlave-to-MasterButton.png
  help/en/package/jmri/jmrit/beantable/images/SignalMastRepeaterTurnoutSettings.png
Labels: Enhancement

#7915 Remove javadoc compile warning wrt joal. Fix broken javadoc-uml target
  build.xml
  lib/jackson-databind-2.9.8-package-list
  lib/openlcb-0.7.23-package-list
Labels: Bug

#7946 fix: Support browsers on iOS 9.3.6.
  web/js/jquery.jmri.js
  web/js/panel.js
Labels: Bug

#7945 Matrixmast reset prev aspect setting
  java/src/jmri/implementation/MatrixSignalMast.java
  java/src/jmri/implementation/configurexml/MatrixSignalMastXml.java
  java/test/jmri/implementation/MatrixSignalMastTest.java
  xml/schema/types/signalmasts-2-9-6.xsd
Labels: Bug

#7988 Fix issue with CbusOpcData.xml not being found in packaged version
  java/src/jmri/jmrix/can/cbus/CbusOpCodes.java
  xml/cbus/CbusOpcData.xml
Labels: Bug

#8001 Increase explicit timeout for tests
  build.xml
Labels: dev/test/publish infrastructure

#8000 configure infrastructure for junit 5
  build.xml
  lib/junit-jupiter-engine-5.5.2.jar
  lib/junit-platform-commons-1.5.2.jar
  lib/junit-platform-engine-1.5.2.jar
  lib/junit-platform-launcher-1.2.0.jar
  lib/junit-vintage-engine-5.5.2.jar
  lib/opentest4j-1.2.0.jar
  pom.xml
Labels: Developer, dependencies, dev/test/publish infrastructure

#8014 Use more succinct Jenkins URL
  help/en/html/doc/Technical/ContinuousIntegration.shtml
  help/en/html/doc/Technical/gitdeveloper.shtml
Labels: dev/test/publish infrastructure

#8030 Fix bug. Reset trains that were building during file save
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/TrainManagerXml.java
Labels: Bug

#8034 Use new Jenkins URLs
  README.md
Labels: dev/test/publish infrastructure

#8039 Fix JavaDoc compile error on JDK13
  java/src/jmri/jmrix/can/cbus/package.html
  java/src/jmri/jmrix/can/package.html
  java/src/jmri/util/JmriJFrame.java
Labels: Future Java
