Repository JMRI/JMRI, pull requests merged in 2020-11, with the labels that each got.

#9127 Add tool tips to train table buttons
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/.settings/JMRI Tests.launch
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/setup/Control.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/trains/TrainsTableFrame.java
  java/src/jmri/jmrit/operations/trains/TrainsTableModel.java
Labels: Add to Next Test Release

#9136 Allow user to save a RFID that hasn't been registered
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
Labels: Add to Next Test Release

#9146 Improve test coverage
  java/src/jmri/jmrit/operations/rollingstock/RollingStockSetFrame.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarsSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineSetFrameTest.java
Labels: Add to Next Test Release

#9148 Update rfid/index.shtml
  help/en/html/hardware/rfid/index.shtml
Labels: Documentation

#9153 Some minor improvements and cleanup, no functional changes
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/schedules/ExportSchedules.java
  java/src/jmri/jmrit/operations/locations/tools/ExportLocations.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/ExportEngines.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Add to Next Test Release

#9150 Update Names.shtml to highlight allowable system prefixes
  help/en/html/doc/Technical/Names.shtml
Labels: Documentation

#9157 Fix NPE new-format splitVal with default value.
  java/src/jmri/jmrit/symbolicprog/SplitVariableValue.java
  java/src/jmri/jmrit/symbolicprog/VariableTableModel.java
  java/src/jmri/jmrit/symbolicprog/VariableValue.java
  java/test/jmri/jmrit/symbolicprog/VariableTableModelTest.java
Labels: Add to Next Test Release, Bug

#9160 Refactor SwitchPilot to use new splitVal syntax.
  xml/decoders/ESU_SwitchPilot.xml
Labels: Add to Next Test Release, Cleanup, Enhancement

#9166 Fix cast bug. Improve build report messages.
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle.properties
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle_da.properties
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle_fr.properties
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle_it.properties
  java/src/jmri/jmrit/operations/router/Router.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineEditFrameTest.java
  java/test/jmri/jmrit/operations/router/OperationsCarRouterTest.java
Labels: Add to Next Test Release

#9163 Updated mqtt/index.shtml and related to bring up to current
  help/en/html/hardware/mqtt/images/MQTT_Preferences rel4-21-2.png
  help/en/html/hardware/mqtt/images/MQTT_Preferences.png
  help/en/html/hardware/mqtt/images/mqtt-logo.png
  help/en/html/hardware/mqtt/index.shtml
  jython/MQTT/ReceiveMqttMessage.py
  jython/MQTT/SendMqttMessage.py
  jython/MQTT/SetMqttOptions.py
  jython/MQTT/SetMqttParser.py
  jython/MQTT/SetMqttPrefix.py
  jython/test/SetMqttParserTest.py
  jython/test/SetMqttPrefixTest.py
Labels: Documentation

#9181 Fix DS64 configuration tool ability to perform factory reset
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/LocoNetBundle.properties
  java/src/jmri/jmrix/loconet/ds64/Ds64TabbedPanel.java
Labels: Bug

#9187 Add ZIMO model 177 Firmware 37 as per #9183.
  xml/decoders/Zimo_Unified_software_v37_MX617.xml
  xml/decoders/zimo/CV100-CV152version30.xml
  xml/decoders/zimo/CV158version32.xml
  xml/decoders/zimo/CV835.xml
  xml/decoders/zimo/CVSwissMapping_v36.xml
  xml/decoders/zimo/CVs_version37.xml
Labels: Add to Next Test Release, Bug
