Repository JMRI/JMRI, pull requests merged in 2020-07, with the labels that each got.

#8764 Minor updates to some help pages
  help/en/html/apps/DecoderPro/FAQ.shtml
  help/en/html/apps/PanelPro/FAQ.shtml
  help/en/html/apps/StoringYourWork.shtml
  help/en/html/doc/Technical/Help.shtml
  help/en/html/doc/Technical/Sidebar.shtml
Labels: Documentation

#8774 Add some PR automation
  .github/mergeable.yml
  help/en/releasenotes/current-draft-note.shtml
Labels: dev/test/publish infrastructure

#8788 Improve code underlying ./runtest
  java/test/jmri/util/junit/TestClassMainMethod.java
Labels: dev/test/publish infrastructure

#8802 Fix 'ant remakedecoderindex' target.
  build.xml
Labels: Bug

#8807 Bugfix: Store correct value of enumVal in roster entry.
  java/src/jmri/jmrit/symbolicprog/EnumVariableValue.java
  java/test/jmri/jmrit/symbolicprog/EnumVariableValueTest.java
Labels: Bug

#8806 remove reference to apps in OlcbprotocolOptionsFrame
  java/src/jmri/jmrix/can/CanSystemConnectionMemo.java
  java/src/jmri/jmrix/openlcb/swing/protocoloptions/ProtocolOptionsFrame.java
Labels: Cleanup

#8810 Remove reference from RosterFrame to apps
  java/src/apps/gui3/dp3/DecoderPro3Window.java
  java/src/jmri/jmrit/roster/swing/RosterFrame.java
Labels: Cleanup

#8830 Documentation updates
  help/en/Acknowledgements.shtml
  help/en/html/apps/PanelPro/GettingStarted.shtml
  help/en/package/jmri/jmrit/withrottle/Protocol.shtml
  help/en/releasenotes/current-draft-warnings.shtml
Labels: Documentation
