Repository JMRI/JMRI, pull requests merged in 2020-04, with the labels that each got.

#8297 Fix incorrect link in SOU-1961 index.shtml
  xml/signals/SOU-1981/index.shtml
Labels: Bug

#8303 Update Lights documentation
  help/en/html/tools/Lights.shtml
  help/en/package/jmri/jmrit/beantable/LightAddEdit.shtml
  help/en/package/jmri/jmrit/beantable/LightTable.shtml
  help/en/package/jmri/jmrit/simplelightctrl/SimpleLightCtrl.shtml
Labels: Documentation

#8304 Update two files to use appropriate sidebars
  help/en/html/doc/Technical/webupdate/UpdatingDocs.shtml
  help/en/html/tools/signaling/interlock/Sidebar.shtml
  help/en/html/tools/signaling/interlock/index.shtml
Labels: Documentation

#8293 VSDecoder: remove old GUI
  help/en/package/jmri/jmrit/vsdecoder/VSDecoderFrame.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/DebugMenu.java
  java/src/jmri/jmrit/vsdecoder/DieselPane.java
  java/src/jmri/jmrit/vsdecoder/LoadXmlVSDecoderAction.java
  java/src/jmri/jmrit/vsdecoder/NotchSound.java
  java/src/jmri/jmrit/vsdecoder/StoreXmlVSDecoderAction.java
  java/src/jmri/jmrit/vsdecoder/VSDConfigPanel.java
  java/src/jmri/jmrit/vsdecoder/VSDOptionPanel.java
  java/src/jmri/jmrit/vsdecoder/VSDSoundsPanel.java
  java/src/jmri/jmrit/vsdecoder/VSDecoder.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderBundle.properties
  java/src/jmri/jmrit/vsdecoder/VSDecoderCreationAction.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderEvent.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderFrame.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderListener.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderPane.java
  java/src/jmri/jmrit/vsdecoder/swing/ManageLocationsAction.java
  java/test/jmri/jmrit/vsdecoder/DieselPaneTest.java
  java/test/jmri/jmrit/vsdecoder/LoadXmlVSDecoderActionTest.java
  java/test/jmri/jmrit/vsdecoder/NotchSoundTest.java
  java/test/jmri/jmrit/vsdecoder/StoreXmlVSDecoderActionTest.java
  java/test/jmri/jmrit/vsdecoder/VSDConfigPanelTest.java
  java/test/jmri/jmrit/vsdecoder/VSDOptionPanelTest.java
  java/test/jmri/jmrit/vsdecoder/VSDSoundsPanelTest.java
  java/test/jmri/jmrit/vsdecoder/VSDecoderEventTest.java
  java/test/jmri/jmrit/vsdecoder/VSDecoderFrameTest.java
  java/test/jmri/jmrit/vsdecoder/VSDecoderPaneTest.java
  java/test/jmri/jmrit/vsdecoder/VSDecoderTest.java
  java/test/jmri/jmrit/vsdecoder/swing/ManageLocationsActionTest.java
Labels: Cleanup

#8288 test: run CI tests in alphabetical order
  .travis.yml
Labels: dev/test/publish infrastructure

#8312 Change “JMRI Web Site” to “JMRI Help” in SidebarTail.shtml
  help/en/parts/SidebarTail.shtml
Labels: Documentation

#8305 Update doc/Technical/Help.shtml and Sidebar.shtml
  help/en/html/doc/Technical/Help.shtml
  help/en/html/doc/Technical/Sidebar.shtml
Labels: Developer

#8296 chore: Add AssertJ Swing dependency
  build.xml
  lib/assertj-swing-3.9.2.jar
  lib/assertj-swing-junit-3.9.2.jar
  pom.xml
Labels: dependencies

#8294 fix: do not start logging console if headless
  java/src/jmri/util/Log4JUtil.java
Labels: Bug, dev/test/publish infrastructure

#8283 Linting
  java/src/jmri/InstanceManager.java
  java/src/jmri/implementation/AbstractSensor.java
  java/src/jmri/jmris/AbstractSensorServer.java
  java/src/jmri/jmris/AbstractSignalHeadServer.java
  java/src/jmri/jmris/AbstractSignalMastServer.java
  java/src/jmri/jmris/AbstractThrottleServer.java
  java/src/jmri/jmris/AbstractTimeServer.java
  java/src/jmri/jmris/AbstractTurnoutServer.java
  java/src/jmri/jmris/JmriServer.java
  java/src/jmri/jmris/JmriServerFrame.java
  java/src/jmri/jmris/simpleserver/SimpleLightServer.java
  java/src/jmri/jmris/simpleserver/SimpleOperationsServer.java
  java/src/jmri/jmris/simpleserver/SimplePowerServer.java
  java/src/jmri/jmris/simpleserver/SimpleReporterServer.java
  java/src/jmri/jmris/simpleserver/SimpleSensorServer.java
  java/src/jmri/jmris/simpleserver/SimpleServer.java
  java/src/jmri/jmris/simpleserver/SimpleServerAction.java
  java/src/jmri/jmris/simpleserver/SimpleServerFrame.java
  java/src/jmri/jmris/simpleserver/SimpleServerManager.java
  java/src/jmri/jmris/simpleserver/SimpleServerPreferencesPanel.java
  java/src/jmri/jmris/simpleserver/SimpleSignalHeadServer.java
  java/src/jmri/jmris/simpleserver/SimpleTurnoutServer.java
  java/src/jmri/jmris/simpleserver/parser/SimpleVisitor.java
  java/src/jmri/jmris/srcp/JmriSRCPPowerServer.java
  java/src/jmri/jmris/srcp/JmriSRCPProgrammerServer.java
  java/src/jmri/jmris/srcp/JmriSRCPSensorServer.java
  java/src/jmri/jmris/srcp/JmriSRCPServer.java
  java/src/jmri/jmris/srcp/JmriSRCPServerBundle.properties
  java/src/jmri/jmris/srcp/JmriSRCPServerFrame.java
  java/src/jmri/jmris/srcp/JmriSRCPServerManager.java
  java/src/jmri/jmris/srcp/JmriSRCPServiceHandler.java
  java/src/jmri/jmris/srcp/JmriSRCPThrottleServer.java
  java/src/jmri/jmris/srcp/JmriSRCPTimeServer.java
  java/src/jmri/jmris/srcp/JmriSRCPTurnoutServer.java
  java/src/jmri/jmris/srcp/TimeStampedOutput.java
  java/src/jmri/jmris/srcp/parser/SRCPVisitor.java
  java/src/jmri/jmrit/ToolsMenu.java
  java/src/jmri/jmrit/beantable/ListedTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockEditFrame.java
  java/test/jmri/jmris/AbstractSensorServerTestBase.java
  java/test/jmri/jmris/simpleserver/SimpleSensorServerTest.java
  java/test/jmri/jmris/simpleserver/SimpleServerActionTest.java
  java/test/jmri/jmris/simpleserver/SimpleServerFrameTest.java
  java/test/jmri/jmris/simpleserver/SimpleServerManagerTest.java
  java/test/jmri/jmris/simpleserver/SimpleServerMenuTest.java
  java/test/jmri/jmris/srcp/JmriSRCPPowerServerTest.java
  java/test/jmri/jmris/srcp/JmriSRCPProgrammerServerTest.java
  java/test/jmri/jmris/srcp/JmriSRCPSensorServerTest.java
  java/test/jmri/jmris/srcp/JmriSRCPThrottleServerTest.java
  java/test/jmri/jmris/srcp/JmriSRCPTimeServerTest.java
  java/test/jmri/jmris/srcp/JmriSRCPTurnoutServerTest.java
  java/test/jmri/jmris/srcp/TimeStampedOutputTest.java
  java/test/jmri/util/JUnitUtil.java
Labels: Cleanup

#8313 add assertJ jars to lib/README
  lib/README.md
Labels: Documentation, dev/test/publish infrastructure

#8319 Add debug for NoClassDefFoundError of NCE classes
  java/src/jmri/jmrix/AbstractMRMessage.java
  java/src/jmri/jmrix/nce/NceConsist.java
  java/src/jmri/jmrix/nce/NceMessage.java
  java/src/jmri/jmrix/nce/NceReply.java
  java/src/jmri/jmrix/nce/ncemon/NceMonBinary.java
  java/test/jmri/jmrix/nce/NceMessageTest.java
Labels: Bug, Cleanup, dev/test/publish infrastructure

#8315 doc: Redirect French directory access to French content
  help/fr/.htaccess
Labels: Documentation

#8320 Documentation updates
  help/en/html/doc/Technical/JVMCapabilities.shtml
  xml/decoders/bli/P2FunctionChoiceSteam.xml
  xml/decoders/bli/P3FunctionChoiceDiesel.xml
  xml/decoders/bli/P3FunctionChoiceSteam.xml
  xml/decoders/bli/enumLightDirection.xml
  xml/decoders/bli/enumLightFunction.xml
  xml/decoders/mth/FunctionChoice.xml
Labels: Documentation

#8321 Remake decoderIndex.
  xml/decoderIndex.xml
Labels: Cleanup

#8316 VSDecoder: correct some tests
  java/test/jmri/jmrit/vsdecoder/BoolTriggerTest.java
  java/test/jmri/jmrit/vsdecoder/ButtonTriggerTest.java
  java/test/jmri/jmrit/vsdecoder/FloatTriggerTest.java
  java/test/jmri/jmrit/vsdecoder/IntTriggerTest.java
  java/test/jmri/jmrit/vsdecoder/NotchTriggerTest.java
  java/test/jmri/jmrit/vsdecoder/swing/VSDControlTest.java
Labels: dev/test/publish infrastructure

#8308 feat: Allow a Turnout to follow another Turnout's state
  java/src/jmri/Turnout.java
  java/src/jmri/implementation/AbstractTurnout.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTurnout.java
  java/src/jmri/jmrix/internal/InternalTurnoutManager.java
  java/test/jmri/implementation/AbstractTurnoutTestBase.java
  java/test/jmri/jmrix/internal/InternalTurnoutManagerTest.java
Labels: Bug, Enhancement

#8325 fix minor typos in signaling help
  help/en/html/tools/signaling/SignalGroups.shtml
  help/en/html/tools/signaling/SignalMastLogic.shtml
Labels: Cleanup

#8330 Add ant target single-test-coveragereport-head
  build.xml
Labels: dev/test/publish infrastructure

#8338 fix: Update serial ports docs for macOS and Linux
  help/en/html/doc/Technical/StartUpScripts.shtml
  jmri.conf
  scripts/AppScriptTemplate
Labels: Documentation

#8337 Add script to check lib and control file commit dates
  help/en/releasenotes/current-draft-note.shtml
  lib/README.md
  scripts/check_lib_dates
Labels: dev/test/publish infrastructure

#8352 ESU improvements.
  xml/decoders/ESU_LokPilot5.xml
  xml/decoders/esu/v5ConsistCVs.xml
  xml/decoders/esu/v5fnOutCVs.xml
  xml/decoders/esu/v5standardCVs.xml
Labels: Enhancement

#8353 Update decoderIndex.
  xml/decoderIndex.xml
Labels: Cleanup

#8361 Update draft release note.
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#8356 Update arduino/index.shtml
  help/en/html/hardware/arduino/index.shtml
Labels: Documentation

#8363 Fix Javdoc bugs
  java/src/jmri/jmrix/AbstractThrottle.java
  java/src/jmri/jmrix/can/cbus/swing/eventtable/CbusEventTable.java
Labels: Documentation

#8341 fix: test frameworks should not log results to GUI
  java/src/apps/SystemConsole.java
  java/test/jmri/util/JUnitUtil.java
Labels: dev/test/publish infrastructure

#8376 chore: Make NetBeans use Line Feeds (LF) as line endings
  nb-configuration.xml
Labels: dev/test/publish infrastructure

#8222 Page on example use of XSL to generate decoder xml contents.
  help/en/html/apps/DecoderPro/CreateDecoderAdvanced.shtml
  help/en/html/apps/DecoderPro/TransformDecoder.shtml
  help/en/html/apps/DecoderPro/resources/decoder-template.xml
  help/en/html/apps/DecoderPro/resources/scom.xsl
Labels: Documentation

#8381 For *MonPaneTest classes, run pane and frame operations on GUI thread.
  java/src/jmri/jmrix/AbstractMonPane.java
  java/test/jmri/jmrix/AbstractMonPaneScaffold.java
  java/test/jmri/jmrix/AbstractMonPaneTestBase.java
  java/test/jmri/jmrix/dcc4pc/swing/monitor/Dcc4PcMonPaneTest.java
  java/test/jmri/jmrix/dccpp/swing/mon/DCCppMonPaneTest.java
  java/test/jmri/jmrix/ecos/swing/monitor/EcosMonPaneTest.java
  java/test/jmri/jmrix/lenz/swing/mon/XNetMonPaneTest.java
  java/test/jmri/jmrix/loconet/locomon/LocoMonPaneTest.java
  java/test/jmri/jmrix/marklin/swing/monitor/MarklinMonPaneTest.java
  java/test/jmri/jmrix/mrc/swing/monitor/MrcMonPanelTest.java
  java/test/jmri/jmrix/nce/ncemon/NceMonPanelTest.java
  java/test/jmri/jmrix/powerline/swing/serialmon/SerialMonPaneTest.java
  java/test/jmri/jmrix/rfid/swing/serialmon/SerialMonPaneTest.java
  java/test/jmri/jmrix/roco/z21/swing/mon/Z21MonPaneTest.java
  java/test/jmri/jmrix/tams/swing/monitor/TamsMonPaneTest.java
  java/test/jmri/jmrix/xpa/swing/xpamon/XpaMonPaneTest.java
Labels: dev/test/publish infrastructure

#8399 Split a testcase in two
  java/test/jmri/jmrix/loconet/SlotManagerTest.java
Labels: Enhancement

#8420 Create new hardware/indexnew.shtml and associated sidebar
  help/en/html/hardware/SidebarNew.shtml
  help/en/html/hardware/indexnew.shtml
  help/en/parts/SidebarSupportedHardwareNew.shtml
Labels: Documentation

#8424 Add checks for logging issues to spotbugs
  .spotbugs-check.xml
  .spotbugs.xml
  pom.xml
Labels: dev/test/publish infrastructure

#8457 add default-cli configuration for jacoco:merge
  pom.xml
Labels: dev/test/publish infrastructure
