Repository JMRI/JMRI, pull requests merged in 2020-05, with the labels that each got.

#8475 Minor test updates
  java/src/jmri/jmrit/display/layoutEditor/TODO_migration.md
  java/src/jmri/util/ThreadingUtil.java
  java/test/jmri/util/JUnitSwingUtil.java
Labels: dev/test/publish infrastructure

#8493 fix: Track Editors in one place
  .travis.yml
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/apps/Apps.java
  java/src/apps/AppsLaunchFrame.java
  java/src/jmri/implementation/DefaultSignalMastLogic.java
  java/src/jmri/jmrit/beantable/Maintenance.java
  java/src/jmri/jmrit/beantable/SectionTableAction.java
  java/src/jmri/jmrit/dispatcher/OptionsFile.java
  java/src/jmri/jmrit/dispatcher/OptionsMenu.java
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/EditorManager.java
  java/src/jmri/jmrit/display/PanelMenu.java
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelEditorAction.java
  java/src/jmri/jmrit/display/controlPanelEditor/configurexml/ControlPanelEditorXml.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutBlockConnectivityTools.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutBlockManager.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorAction.java
  java/src/jmri/jmrit/display/layoutEditor/PositionablePoint.java
  java/src/jmri/jmrit/display/layoutEditor/configurexml/LayoutEditorXml.java
  java/src/jmri/jmrit/display/layoutEditor/configurexml/PositionablePointXml.java
  java/src/jmri/jmrit/display/panelEditor/PanelEditor.java
  java/src/jmri/jmrit/display/panelEditor/PanelEditorAction.java
  java/src/jmri/jmrit/display/panelEditor/configurexml/PanelEditorXml.java
  java/src/jmri/jmrit/display/switchboardEditor/SwitchboardEditorAction.java
  java/src/jmri/jmrit/display/switchboardEditor/configurexml/SwitchboardEditorXml.java
  java/src/jmri/jmrit/entryexit/AddEntryExitPairPanel.java
  java/src/jmri/jmrit/entryexit/EntryExitPairs.java
  java/src/jmri/jmrit/entryexit/PointDetails.java
  java/src/jmri/jmrit/operations/routes/tools/SetTrainIconPositionFrame.java
  java/src/jmri/jmrit/operations/routes/tools/SetTrainIconRouteFrame.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/signalling/SignallingSourcePanel.java
  java/src/jmri/jmrit/whereused/WhereUsedCollectors.java
  java/src/jmri/server/json/util/JsonUtilHttpService.java
  java/src/jmri/web/servlet/panel/AbstractPanelServlet.java
  java/test/jmri/implementation/DefaultCabSignalIT.java
  java/test/jmri/jmrit/display/LinkingLabelTest.java
  java/test/jmri/jmrit/display/PanelMenuTest.java
  java/test/jmri/jmrit/entryexit/EntryExitTestTools.java
  java/test/jmri/jmrit/operations/trains/TrainIconAnimationTest.java
  java/test/jmri/jmrix/can/cbus/CbusCabSignalIT.java
  java/test/jmri/jmrix/loconet/LnCabSignalIT.java
  java/test/jmri/jmrix/rps/RpsPositionIconTest.java
  java/test/jmri/server/json/util/JsonUtilSocketServiceTest.java
  java/test/jmri/util/JUnitUtil.java
  jython/BlockLister.py
  jython/ControlPanel.py
  jython/DisableLayoutEditorSensorIcon.py
  jython/ManageBlocks.py
Labels: Add to Next Test Release, Bug, Cleanup

#8498 fix: Do not attempt to show visible/hidden state in panel menu
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/EditorActionFactory.java
  java/src/jmri/jmrit/display/EditorManager.java
  java/src/jmri/jmrit/display/PanelMenu.java
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelEditorActionFactory.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorActionFactory.java
  java/src/jmri/jmrit/display/panelEditor/PanelEditorActionFactory.java
  java/src/jmri/jmrit/display/switchboardEditor/SwitchboardEditorActionFactory.java
Labels: Bug

#8506 Hornby TTS Loco updates from Brian Jackson.
  xml/decoders/HornbyTTS.xml
Labels: Add to Next Test Release, Cleanup, Enhancement

#8504 Test improvements
  .spotbugs-check.xml
  .spotbugs.xml
  build.xml
  java/test/jmri/jmrit/display/controlPanelEditor/EditCircuitPathsTest.java
Labels: dev/test/publish infrastructure

#8523 Remove max of 28 for soundlabel and functionlabel numbers.
  xml/schema/locomotive-config.xsd
Labels: Bug

#8541 use Mock memo to prevent loading BlockManager
  java/test/jmri/jmrix/loconet/CsOpSwAccessTest.java
Labels: dev/test/publish infrastructure

#8539 Update hardware/indexnew.shtml for review
  help/en/html/hardware/indexnew.shtml
  help/en/parts/SidebarSupportedHardware.shtml
  help/en/parts/SidebarSupportedHardwareNew.shtml
Labels: Documentation

#8563 chore: skip intermittently failing tests on GitHub Windows CI Tests action
  .github/workflows/windows-test.yml
Labels: dev/test/publish infrastructure

#8571 Fix problem building UML javadoc
  build.xml
Labels: Contribution, dev/test/publish infrastructure

#8573 test: free up a Travis CI slot
  .travis.yml
Labels: dev/test/publish infrastructure

#8566 Update to CI page
  help/en/html/doc/Technical/ContinuousIntegration.shtml
  help/en/html/doc/Technical/images/ActionSettings.png
Labels: Developer, dev/test/publish infrastructure

#8574 Raise memory on logalltest target for Jenkins
  build.xml
Labels: dev/test/publish infrastructure

#8578 Catch and finally on same line in NetBeans
  nb-configuration.xml
Labels: Bug, Developer

#8585 Prevent NumberFormatException in SplitVariableValue & subclasses.
  java/src/jmri/jmrit/symbolicprog/SplitTextVariableValue.java
  java/src/jmri/jmrit/symbolicprog/SplitVariableValue.java
  java/test/jmri/jmrit/symbolicprog/SplitHexVariableValueTest.java
  java/test/jmri/jmrit/symbolicprog/SplitTextVariableValueTest.java
  java/test/jmri/jmrit/symbolicprog/SplitVariableValueTest.java
Labels: Add to Next Test Release, Bug, Enhancement

#8593 fix: Delay loading ECoS roster until JMRI Roster is initialized
  java/src/jmri/jmrix/ecos/EcosLocoAddressManager.java
Labels: Bug

#8596 fix cast exception during panel load
  java/src/jmri/jmrit/display/EditorManager.java
Labels: Bug

#8599 Minor sidebar changes
  help/en/html/tools/scripting/SidebarToolLocalPart.shtml
  help/en/parts/SidebarTail.shtml
Labels: Documentation

#8597 Create SaveWhatHowWhereWhen.shtml
  help/en/html/apps/SaveWhatHowWhereWhen.shtml
Labels: Documentation

#8607 Add Sensor Settings ESU Generation 5.
  xml/decoders/esu/v4fnSetPane.xml
  xml/decoders/esu/v4soundCVs.xml
  xml/decoders/esu/v4standardCVs.xml
  xml/decoders/esu/v5standardCVs.xml
Labels: Add to Next Test Release, Enhancement

#8609 Load proper LE Editor types
  java/src/jmri/jmrit/display/layoutEditor/LayoutDoubleSlip.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutDoubleXOver.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutLHTurnoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutRHTurnoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutTurnoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutWyeEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutXOverEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutLHTurnout.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutLHXOver.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutRHTurnout.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutRHXOver.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutSingleSlip.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutSlip.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTurnout.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutWye.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutXOver.java
Labels: Bug

#8602 Add info to TOC and Index headers
  help/en/indexheader
  help/en/tocheader
Labels: Documentation

#8612 Promote new hardware/index.shtml page to production
  help/en/html/doc/Technical/Help.shtml
  help/en/html/doc/Technical/Sidebar.shtml
  help/en/html/hardware/index.shtml
  help/en/html/hardware/indexnew.shtml
Labels: Documentation
