Repository JMRI/JMRI, pull requests merged in 2020-10, with the labels that each got.

#9054 Improve LnPacketizer.status()
  java/src/jmri/jmrix/loconet/LnPacketizer.java
  java/src/jmri/jmrix/loconet/LnTrafficController.java
  java/src/jmri/jmrix/loconet/LocoNetInterface.java
Labels: Bug

#9053 Further deprecate getSystemNameList getNamedBeanList
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/implementation/DefaultConditional.java
  java/src/jmri/jmrit/beantable/BeanTableDataModel.java
  java/src/jmri/jmrit/beantable/LRouteTableAction.java
  java/src/jmri/jmrit/beantable/Maintenance.java
  java/src/jmri/jmrit/beantable/SignalGroupSubTableAction.java
  java/src/jmri/jmrit/display/layoutEditor/BlockValueFile.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutBlock.java
  java/src/jmri/jmrit/display/layoutEditor/configurexml/LayoutBlockManagerXml.java
  java/src/jmri/jmrit/entryexit/EntryExitPairs.java
  java/src/jmri/jmrit/picker/PickListModel.java
  java/src/jmri/jmrit/sensorgroup/BeanTableModel.java
  java/src/jmri/jmrit/sensorgroup/SensorGroupFrame.java
  java/src/jmri/jmrit/withrottle/AbstractController.java
  java/src/jmri/jmrit/withrottle/ControllerFilterFrame.java
  java/src/jmri/jmrix/acela/AcelaSensorManager.java
  java/src/jmri/jmrix/cmri/serial/SerialSensorManager.java
  java/src/jmri/jmrix/ecos/EcosLocoAddressManager.java
  java/src/jmri/jmrix/grapevine/SerialSensorManager.java
  java/src/jmri/jmrix/maple/SerialSensorManager.java
  java/src/jmri/jmrix/oaktree/SerialSensorManager.java
  java/src/jmri/jmrix/powerline/cm11/SpecificSensorManager.java
  java/src/jmri/jmrix/powerline/insteon2412s/SpecificSensorManager.java
  java/src/jmri/jmrix/powerline/simulator/SpecificSensorManager.java
  java/src/jmri/jmrix/secsi/SerialSensorManager.java
  java/src/jmri/managers/AbstractManager.java
  java/src/jmri/managers/AbstractProxyManager.java
  java/src/jmri/managers/DefaultConditionalManager.java
  java/test/jmri/jmrit/beantable/LRouteTableActionTest.java
  java/test/jmri/jmrix/internal/InternalSensorManagerTest.java
  java/test/jmri/jmrix/loconet/LnTurnoutManagerTest.java
  java/test/jmri/managers/AbstractSensorMgrTestBase.java
  java/test/jmri/managers/DefaultSignalSystemManagerTest.java
  java/test/jmri/managers/ProxySensorManagerTest.java
  java/test/jmri/managers/TurnoutManagerScaffold.java
  java/test/jmri/util/JUnitAppender.java
  jython/RobotThrottle3.py
Labels: Cleanup

#9050 Improvements to Meters feature
  help/en/html/hardware/loconet/DigitraxMeters.shtml
  help/en/html/hardware/loconet/images/CurrentMeter.png
  help/en/html/hardware/loconet/images/TrackVoltageMeter.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/swing/meter/MeterFrame.java
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/LnMeterInitTask.java
  java/src/jmri/jmrix/loconet/LnPredefinedMeters.java
  java/src/jmri/jmrix/loconet/LocoNetSystemConnectionMemo.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/LnIPLImplementation.java
  java/test/jmri/jmrix/loconet/LnPredefinedMetersTest.java
  java/test/jmri/jmrix/loconet/duplexgroup/swing/LnIPLImplementationTest.java
Labels: Enhancement

#9067 Fix csv manifest bug, unique railroad name
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/TrainCsvManifest.java
Labels: Add to Next Test Release

#9066 Terminology update
  help/en/package/jmri/jmrit/display/PanelTarget.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/DisplayBundle.properties
Labels: Documentation

#9065 Additions to JMRI-files-in-git note
  help/en/html/setup/git.shtml
Labels: Documentation

#9064 LocoNet interrogate process improvements, javadocs
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/LnSensorManager.java
  java/test/jmri/jmrix/loconet/LnSensorManagerTest.java
Labels: Enhancement

#9071 Catch panel exception when placing train icon on panel
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/CommonConductorYardmasterPanel.java
  java/src/jmri/jmrit/operations/automation/actions/IsTrainEnRouteAction.java
  java/src/jmri/jmrit/operations/automation/actions/WaitTrainAction.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/Engine.java
  java/src/jmri/jmrit/operations/trains/JsonManifest.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainConductorPanel.java
  java/src/jmri/jmrit/operations/trains/TrainCsvCommon.java
  java/src/jmri/jmrit/operations/trains/TrainEditBuildOptionsFrame.java
  java/src/jmri/jmrit/operations/trains/TrainIcon.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/TrainManifest.java
  java/src/jmri/jmrit/operations/trains/TrainsTableModel.java
  java/src/jmri/jmrit/operations/trains/tools/ShowCarsInTrainFrame.java
  java/src/jmri/jmrit/vsdecoder/VSDecoder.java
  java/src/jmri/server/json/operations/JsonUtil.java
  java/src/jmri/web/servlet/operations/HtmlConductor.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainCsvSwitchListsTest.java
  java/test/jmri/jmrit/operations/trains/TrainSwitchListsTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
  java/test/jmri/jmrit/operations/trains/XmlTest.java
  java/test/jmri/server/json/operations/JsonOperationsSocketServiceTest.java
Labels: Add to Next Test Release

#9077 Fix SprogThrottle 28 step mode EStop
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/sprog/SprogThrottle.java
Labels: Add to Next Test Release, Bug

#9076 Allow users to sort, change column width and position in edit location window
  java/src/jmri/jmrit/operations/OperationsFrame.java
  java/src/jmri/jmrit/operations/OperationsPanel.java
  java/src/jmri/jmrit/operations/locations/InterchangeTableModel.java
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/SpurTableModel.java
  java/src/jmri/jmrit/operations/locations/StagingTableModel.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/YardTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockSetFrame.java
  java/test/jmri/jmrit/operations/locations/StagingEditFrameTest.java
Labels: Add to Next Test Release

#9085 Athearn Caboose decoder
  xml/decoders/NCE_Caboose.xml
  xml/decoders/nce/CabooseEnumLightEffect.xml
Labels: Contribution

#9087 Improve help, some code cleanup
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/setup/OptionPanel.java
Labels: Add to Next Test Release

#9090 Fix LE canvas hop
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/DisplayBundle.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_da.properties
  java/src/jmri/jmrit/display/DisplayBundle_de.properties
  java/src/jmri/jmrit/display/DisplayBundle_nl.properties
  java/src/jmri/jmrit/display/switchboardEditor/BeanSwitch.java
  java/src/jmri/jmrit/display/switchboardEditor/SwitchboardEditor.java
  web/css/panel.css
  web/js/panel.js
Labels: Add to Next Test Release, Bug

#9105 Fix broken link in scripting/Examples.shtml
  help/en/html/tools/scripting/Examples.shtml
Labels: Documentation

#9109 SwitchPilot workaround for splitVal/enumVal interaction.
  xml/decoders/ESU_SwitchPilot.xml
Labels: Add to Next Test Release, Bug

#9113 Fix bug, IDtag was not saved for rolling stock between sessions.
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockEditFrame.java
  java/test/jmri/jmrit/operations/rollingstock/OperationsRollingStockTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarManagerTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineManagerTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/ImportEnginesTest.java
  java/test/jmri/server/json/operations/JsonOperationsHttpServiceTest.java
Labels: Add to Next Test Release

#9124 Promote TCP/UDP port to main config settings
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/rfid/networkdriver/ConnectionConfig.java
Labels: Enhancement
