Repository JMRI/JMRI, pull requests merged in 2020-09, with the labels that each got.

#8986 Minor code cleanup
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/jmrit/operations/trains/TrainCsvManifest.java
  java/src/jmri/jmrit/operations/trains/TrainManifest.java
Labels: Add to Next Test Release

#8988 Fix loading RFID bug
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
Labels: Add to Next Test Release

#8987 Add help for LocoNet 'MultiMeter' functionality
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/DigitraxMeters.shtml
  help/en/html/hardware/loconet/images/CurrentMeter.png
  help/en/html/hardware/loconet/images/TrackVoltageMeter.png
Labels: Add to Next Test Release, Documentation

#8989 Update Sensor and Turnout Table Help
  help/en/html/tools/Sensors.shtml
  help/en/package/jmri/jmrit/beantable/SensorTable.shtml
  help/en/package/jmri/jmrit/beantable/TurnoutTable.shtml
  help/en/package/jmri/jmrit/beantable/images/SensorTableColumnList.jpg
  help/en/package/jmri/jmrit/beantable/images/TurnoutTableColumnList.jpg
Labels: Documentation

#8994 Small corrections/additions to arduino/index.shtml
  help/en/html/hardware/arduino/index.shtml
Labels: Documentation

#9006 Fix Conductor "set" passenger car bug
  java/src/jmri/jmrit/operations/CommonConductorYardmasterPanel.java
Labels: Add to Next Test Release

#9004 Remove the loco from DCCppThrottleManagers internal list of throttles on last release
  java/src/jmri/jmrix/dccpp/DCCppThrottleManager.java
  java/test/jmri/jmrix/dccpp/DCCppThrottleManagerTest.java
Labels: Bug

#9002 Create new Warrants Help Intro and associated changes
  help/en/JmriHelp_enIndex.xml
  help/en/JmriHelp_enTOC.xml
  help/en/html/FAQ.shtml
  help/en/html/tools/WarrantsIntro.shtml
  help/en/package/jmri/jmrit/logix/Warrant.shtml
  help/en/parts/SidebarLayoutAutomation.shtml
Labels: Documentation

#9012 Add info to Sensors/SensorTable Help
  help/en/html/hardware/XBee/SidebarHardwareLocalPart.shtml
  help/en/html/tools/Sensors.shtml
  help/en/package/jmri/jmrit/beantable/SensorTable.shtml
Labels: Documentation

#9022 Honour shutdown and reboot return codes
  help/en/releasenotes/current-draft-note.shtml
  scripts/WinInstallFiles/LaunchJMRI.exe
  scripts/WinInstallFiles/LaunchJMRI.nsi
Labels: Enhancement

#9021 Fix baud rate not being set
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/acela/serialdriver/SerialDriverAdapter.java
Labels: Bug

#9027 Add reporter names to operations location and track tables
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/LocationManager.java
  java/src/jmri/jmrit/operations/locations/LocationsTableModel.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
Labels: Add to Next Test Release

#9026 New images for use by LCD meter
  resources/icons/misc/LCD/kampb.gif
  resources/icons/misc/LCD/kvoltb.gif
  resources/icons/misc/LCD/mampb.gif
  resources/icons/misc/LCD/mvoltb.gif
  resources/icons/misc/LCD/uampb.gif
  resources/icons/misc/LCD/uvoltb.gif
Labels: Enhancement

#9032 Shutdown return code
  scripts/WinInstallFiles/LaunchJMRI.exe
Labels: Bug

#9035 Fix link to JavaDoc classes in Sidebar
  help/en/html/doc/Technical/Sidebar.shtml
Labels: Bug, Documentation

#9037 Code cleanup. Remove deprecated methods.
  java/src/jmri/jmrit/operations/OperationsXml.java
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/LocationsTableModel.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/schedules/ExportSchedules.java
  java/src/jmri/jmrit/operations/locations/tools/ExportLocations.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockManager.java
  java/src/jmri/jmrit/operations/rollingstock/cars/Car.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/ExportCars.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/ExportEngines.java
  java/src/jmri/jmrit/operations/routes/tools/ExportRoutes.java
  java/src/jmri/jmrit/operations/trains/tools/ExportTimetable.java
  java/src/jmri/jmrit/operations/trains/tools/ExportTrains.java
Labels: Cleanup

#9038 Two new ESU models, one name correction.
  xml/decoders/ESU_LokPilot5.xml
  xml/decoders/ESU_LokSound5.xml
  xml/decoders/esu/v5standardCVs.xml
Labels: Add to Next Test Release

#9042 Remake decoderIndex due to recent ESU, SoundTraxx and HDL changes.
  xml/decoderIndex.xml
Labels: Cleanup

#9048 Increase the width of roster entry comment fields
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/roster/RosterEntryPane.java
Labels: Add to Next Test Release
