Repository JMRI/JMRI, pull requests merged in 2020-02, with the labels that each got.

#8063 Remove VI remnants
  .gitignore
  help/fr/package/jmri/jmrit/.DebugMenu.shtml.swo
  help/fr/package/jmri/jmrit/display/.LayoutEditor.shtml.swm
  help/fr/package/jmri/jmrit/display/.LayoutEditor.shtml.swn
  help/fr/package/jmri/jmrit/display/.LayoutEditor.shtml.swo
  help/fr/package/jmri/jmrix/loconet/soundloader/.EditorFrame.shtml.swo
Labels: Cleanup

#8058 Bump jetty.version from 9.4.7.v20170914 to 9.4.26.v20200117
  .factorypath
  build.xml
  java/src/jmri/web/server/WebServer.java
  java/src/jmri/web/servlet/directory/DirectoryResource.java
  java/src/jmri/web/servlet/directory/DirectoryService.java
  java/src/jmri/web/servlet/roster/MultipartRequestHandler.java
  lib/jetty-client-9.4.26.v20200117.jar
  lib/jetty-client-9.4.7.v20170914.jar
  lib/jetty-http-9.4.26.v20200117.jar
  lib/jetty-http-9.4.7.v20170914.jar
  lib/jetty-io-9.4.26.v20200117.jar
  lib/jetty-io-9.4.7.v20170914.jar
  lib/jetty-security-9.4.26.v20200117.jar
  lib/jetty-security-9.4.7.v20170914.jar
  lib/jetty-server-9.4.26.v20200117.jar
  lib/jetty-server-9.4.7.v20170914.jar
  lib/jetty-servlet-9.4.26.v20200117.jar
  lib/jetty-servlet-9.4.7.v20170914.jar
  lib/jetty-util-9.4.26.v20200117.jar
  lib/jetty-util-9.4.7.v20170914.jar
  lib/jetty-xml-9.4.26.v20200117.jar
  lib/jetty-xml-9.4.7.v20170914.jar
  lib/websocket-api-9.4.26.v20200117.jar
  lib/websocket-api-9.4.7.v20170914.jar
  lib/websocket-client-9.4.26.v20200117.jar
  lib/websocket-client-9.4.7.v20170914.jar
  lib/websocket-common-9.4.26.v20200117.jar
  lib/websocket-common-9.4.7.v20170914.jar
  lib/websocket-server-9.4.26.v20200117.jar
  lib/websocket-server-9.4.7.v20170914.jar
  lib/websocket-servlet-9.4.26.v20200117.jar
  lib/websocket-servlet-9.4.7.v20170914.jar
  nbproject/project.xml
  pom.xml
Labels: dependencies

#8074 disable the default maven compile on appveyor
  pom.xml
Labels: dev/test/publish infrastructure

#8080 Fix local with staging track
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainEditFrame.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Add to Next Test Release

#8059 Add ability to print names of run tests
  help/en/html/doc/Technical/JUnit.shtml
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelEditor.java
  java/src/jmri/jmrix/sprog/update/SprogIIUpdateFrame.java
  java/test/jmri/jmrit/display/controlPanelEditor/CircuitBuilderTest.java
  java/test/jmri/jmrit/display/controlPanelEditor/ControlPanelEditorTest.java
  java/test/jmri/jmrit/display/controlPanelEditor/ConvertDialogTest.java
  java/test/jmri/jmrit/display/controlPanelEditor/PortalIconTest.java
  java/test/jmri/jmrix/sprog/console/SprogConsoleFrameTest.java
  java/test/jmri/jmrix/sprog/sprogmon/SprogMonFrameTest.java
  java/test/jmri/jmrix/sprog/sprogslotmon/SprogSlotMonFrameTest.java
  java/test/jmri/jmrix/sprog/update/SprogIIUpdateFrameTest.java
  java/test/jmri/jmrix/sprog/update/SprogVersionFrameTest.java
  java/test/jmri/util/junit/PrintingTestListener.java
  java/test/jmri/util/junit/TestClassMainMethod.java
Labels: dev/test/publish infrastructure

#8096 Some minor cleanup, no functional changes
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/OperationsTests.java
Labels: Add to Next Test Release

#8102 chore: exclude JHelpDev generated content from newline at EOF checking
  checkstyle.xml
Labels: Developer

#8106 Some JUnit5 updates
  build.xml
  java/test/apps/tests/AllTest.java
  java/test/jmri/HeadLessTest.java
  java/test/jmri/jmrix/can/adapters/gridconnect/sproggen5/PackageTest.java
  java/test/jmri/jmrix/can/adapters/gridconnect/sproggen5/serialdriver/PackageTest.java
  java/test/jmri/jmrix/can/adapters/gridconnect/sproggen5/serialdriver/configurexml/PackageTest.java
  java/test/jmri/jmrix/can/cbus/swing/bootloader/PackageTest.java
  java/test/jmri/jmrix/ieee802154/xbee/XBeeIOStreamTest.java
  java/test/jmri/util/junit/TestClassMainMethod.java
  pom.xml
Labels: dev/test/publish infrastructure

#8107 Fix not showing available cars in conductor window
  java/src/jmri/jmrit/operations/CommonConductorYardmasterPanel.java
Labels: Bug

#8154 chore: Update Travis CI configuration
  .travis.yml
Labels: dev/test/publish infrastructure

#8152 Enable upload of test results to appveyor
  appveyor.yml
Labels: dev/test/publish infrastructure

#8171 test: Update Mockito to allow testing on JDK11
  build.xml
  lib/README.md
  lib/byte-buddy-1.10.5.jar
  lib/byte-buddy-1.7.10.jar
  lib/byte-buddy-agent-1.10.5.jar
  lib/mockito-core-2.13.0.jar
  lib/mockito-core-3.3.0.jar
  nbproject/project.xml
  pom.xml
Labels: dev/test/publish infrastructure

#8184 Don't send unwanted error-correction byte to DCC++ command station
  java/src/jmri/jmrix/dccpp/DCCppCommandStation.java
  java/src/jmri/jmrix/dccpp/DCCppMessage.java
  java/test/jmri/jmrix/dccpp/DCCppCommandStationTest.java
Labels: Bug, Cleanup

#8182 Digitrax Help changes
  help/en/html/hardware/loconet/DCS240.shtml
  help/en/html/hardware/loconet/DCS52.shtml
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/EnhancedSlots.shtml
  help/en/html/hardware/loconet/Sidebar.shtml
  help/en/html/hardware/loconet/images/DCS240LocoNetInterfaceViaAdapter.png
  help/en/html/hardware/loconet/images/DCS52LocoNetInterfaceViaAdapter.png
Labels: Cleanup
