Repository JMRI/JMRI, pull requests merged in 2021-11, with the labels that each got.

#10231 Update JOAL to 2.4.0-rc-20210111
  lib/README.md
  lib/gluegen-rt.jar
  lib/joal.jar
  lib/linux/aarch64/libgluegen_rt.so
  lib/linux/aarch64/libjoal.so
  lib/linux/aarch64/libopenal.so
  lib/linux/armv6l/libgluegen-rt.so
  lib/linux/armv6l/libgluegen_rt.so
  lib/linux/armv6l/libjoal.so
  lib/linux/armv6l/libopenal.so
  lib/linux/armv7l/libgluegen-rt.so
  lib/linux/armv7l/libgluegen_rt.so
  lib/linux/armv7l/libjoal.so
  lib/linux/armv7l/libopenal.so
  lib/linux/i386/libgluegen-rt.so
  lib/linux/i386/libgluegen_rt.so
  lib/linux/i386/libjoal.so
  lib/linux/i386/libopenal.so
  lib/linux/x86_64/libgluegen-rt.so
  lib/linux/x86_64/libgluegen_rt.so
  lib/linux/x86_64/libjoal.so
  lib/linux/x86_64/libopenal.so
  lib/macosx/libgluegen-rt.jnilib
  lib/macosx/libgluegen_rt.dylib
  lib/macosx/libjoal.dylib
  lib/macosx/libjoal.jnilib
  lib/macosx/libopenal.1.15.1.dylib
  lib/macosx/libopenal.1.dylib
  lib/macosx/libopenal.dylib
  lib/windows/x64/gluegen-rt.dll
  lib/windows/x64/gluegen_rt.dll
  lib/windows/x64/joal.dll
  lib/windows/x64/soft_oal.dll
  lib/windows/x86/gluegen-rt.dll
  lib/windows/x86/gluegen_rt.dll
  lib/windows/x86/joal.dll
  lib/windows/x86/soft_oal.dll
Labels: Add to Next Test Release, dependencies, New PR

#10243 Allow car to be dropped off late to spur with a schedule
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/routes/Route.java
Labels: Add to Next Test Release

#10230 Update JmriHelp template
  help/en/local/stub_template.html
  help/fr/local/stub_template.html
  java/test/jmri/util/BuildHelpFilesTest.java
Labels: Documentation

#10245 Changes for Apple Silicon
  build.xml
  help/en/releasenotes/current-draft-note.shtml
  lib/README.md
  lib/libusb4java-1.3.0-darwin-aarch64.jar
  scripts/MacOSXapps/TemplateApp.app/Contents/InfoTemplate.plist
  scripts/diskimage-sign.sh
Labels: Add to Next Test Release

#10250 Update CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
Labels: Needs L10N, New PR

#10264 Use a dynamic stub file instead of 1000s of static stub files.
  help/en/html/doc/Technical/Help.shtml
  help/en/html/doc/Technical/Sidebar.shtml
  help/en/local/stub_template.html
  help/en/releasenotes/current-draft-note.shtml
  help/fr/local/stub_template.html
  java/src/jmri/util/HelpUtil.java
  java/src/jmri/util/UtilBundle.properties
  java/test/jmri/util/BuildHelpFilesTest.java
Labels: Documentation, Needs L10N

#10268 Try to make operation test more robust.
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeEditFrameTest.java
  java/test/jmri/util/swing/JemmyUtil.java
Labels: Add to Next Test Release

#10253 Add LogixNG functions
  java/src/jmri/jmrit/logixng/SymbolTable.java
  java/src/jmri/jmrit/logixng/actions/ActionListenOnBeans.java
  java/src/jmri/jmrit/logixng/actions/NamedBeanType.java
  java/src/jmri/jmrit/logixng/implementation/DefaultSymbolTable.java
  java/src/jmri/jmrit/logixng/util/parser/Constant.java
  java/src/jmri/jmrit/logixng/util/parser/Function.java
  java/src/jmri/jmrit/logixng/util/parser/FunctionFactory.java
  java/src/jmri/jmrit/logixng/util/parser/FunctionManager.java
  java/src/jmri/jmrit/logixng/util/parser/LocalVariableExpressionVariable.java
  java/src/jmri/jmrit/logixng/util/parser/LogixNGParserBundle.properties
  java/src/jmri/jmrit/logixng/util/parser/Tokenizer.java
  java/src/jmri/jmrit/logixng/util/parser/functions/ClockFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/ConvertFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/LayoutFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/MathFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/NamedBeanFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/StringFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/swing/FunctionsHelpDialog.java
  java/src/jmri/jmrit/logixng/util/parser/swing/ParserSwingBundle.properties
  java/test/jmri/jmrit/logixng/util/parser/ExpressionNodeIdentifierTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/LayoutFunctionsTest.java
  xml/schema/logixng/common-types-4.23.1.xsd
Labels: Needs L10N

#10270 clear ShutDownManager to avoid test hanging on exit
  java/test/jmri/jmrit/display/palette/IndicatorTOIconDialogTest.java
Labels: New PR

#10267 (Proposed draft) Update tech pages for Java 11
  help/en/html/doc/Technical/JVMCapabilities.shtml
  help/en/html/doc/Technical/TechRoadMap.shtml
Labels: Future Java, Documentation, Java 11

#10273 Test maintenance
  java/test/jmri/jmrit/beantable/MaintenanceTest.java
  java/test/jmri/jmrit/vsdecoder/DieselSoundTest.java
  java/test/jmri/jmrit/vsdecoder/Steam1SoundTest.java
  java/test/jmri/jmrit/vsdecoder/SteamSoundTest.java
  java/test/jmri/jmrit/vsdecoder/VSDecoderTest.java
  java/test/jmri/jmrit/vsdecoder/swing/VSDConfigDialogTest.java
  java/test/jmri/jmrit/vsdecoder/swing/VSDecoderPreferencesPaneTest.java
  java/test/jmri/util/prefs/JmriPreferencesProviderTest.java
  scripts/run_tests_separately
Labels: dev/test/publish infrastructure

#10276 Clean up test threads left running
  java/src/jmri/implementation/AbstractTurnout.java
  java/src/jmri/implementation/DefaultRoute.java
  java/src/jmri/implementation/MatrixSignalMast.java
  java/src/jmri/jmrit/logix/Engineer.java
  java/test/jmri/implementation/MatrixSignalMastTest.java
  java/test/jmri/jmrit/entryexit/AddEntryExitPairPanelTest.java
  java/test/jmri/jmrit/entryexit/DestinationPointsTest.java
  java/test/jmri/jmrit/entryexit/EntryExitPairsTest.java
  java/test/jmri/jmrit/entryexit/PointDetailsTest.java
  java/test/jmri/jmrit/entryexit/SourceTest.java
  java/test/jmri/jmrit/logix/LearnWarrantTest.java
  java/test/jmri/jmrit/logix/LinkedWarrantTest.java
  java/test/jmri/jmrit/logix/NXFrameTest.java
  java/test/jmri/jmrit/logix/PortalManagerTest.java
  java/test/jmri/util/HelpUtilTest.java
  java/test/jmri/util/JUnitUtil.java
  java/test/jmri/util/PlaceWindowTest.java
Labels: dev/test/publish infrastructure

#10282 Remove dead code warnings
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
Labels: Add to Next Test Release

#10283 More test threadicide
  java/src/jmri/jmrix/loconet/LocoNetThrottledTransmitter.java
  java/test/jmri/jmrit/beantable/IdTagTableDataModelTest.java
  java/test/jmri/jmrit/display/EditorFrameOperator.java
  java/test/jmri/jmrit/display/SensorIconWindowTest.java
  java/test/jmri/jmrit/display/SignalSystemTest.java
  java/test/jmri/jmrit/display/TurnoutIconWindowTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutTrackEditorTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorToolsTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorWindowTest.java
  java/test/jmri/jmrit/display/palette/ColorDialogTest.java
  java/test/jmri/jmrit/display/switchboardEditor/SwitchboardEditorTest.java
  java/test/jmri/jmrix/loconet/LnCabSignalIT.java
  java/test/jmri/jmrix/loconet/LnClockControlTest.java
  java/test/jmri/jmrix/loconet/LnSystemConnectionMemoTestBase.java
  java/test/jmri/jmrix/loconet/LocoNetSystemConnectionMemoTest.java
  java/test/jmri/jmrix/loconet/configurexml/LoadAndStoreTest.java
  java/test/jmri/jmrix/loconet/duplexgroup/swing/LnIPLImplementationTest.java
  java/test/jmri/jmrix/loconet/hexfile/HexFileFrameTest.java
  java/test/jmri/jmrix/loconet/hexfile/HexFileSystemConnectionMemoTest.java
  java/test/jmri/jmrix/loconet/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrix/loconet/pr3/PR3SystemConnectionMemoTest.java
  java/test/jmri/jmrix/loconet/pr4/PR4SystemConnectionMemoTest.java
  java/test/jmri/jmrix/loconet/sdfeditor/EditorFrameTest.java
  java/test/jmri/jmrix/loconet/sdfeditor/EditorPaneTest.java
  java/test/jmri/jmrix/loconet/uhlenbrock/UhlenbrockSystemConnectionMemoTest.java
  java/test/jmri/jmrix/loconet/usb_dcs240/UsbDcs240SystemConnectionMemoTest.java
  java/test/jmri/jmrix/loconet/usb_dcs52/UsbDcs52SystemConnectionMemoTest.java
  java/test/jmri/util/JUnitUtil.java
Labels: dev/test/publish infrastructure

#10262 Modify ramp calculations
  help/en/package/apps/TabbedPreferences.shtml
  help/en/package/jmri/jmrit/logix/WarrantTable.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/oblock/OBlockTableModel.java
  java/src/jmri/jmrit/beantable/oblock/SignalTableModel.java
  java/src/jmri/jmrit/beantable/oblock/TableFrames.java
  java/src/jmri/jmrit/display/IndicatorTrackIcon.java
  java/src/jmri/jmrit/display/IndicatorTrackPaths.java
  java/src/jmri/jmrit/display/IndicatorTurnoutIcon.java
  java/src/jmri/jmrit/display/PositionableLabel.java
  java/src/jmri/jmrit/display/controlPanelEditor/shape/configurexml/LocoLabelXml.java
  java/src/jmri/jmrit/logix/BlockSpeedInfo.java
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/LearnSpeedPanel.java
  java/src/jmri/jmrit/logix/LearnThrottleFrame.java
  java/src/jmri/jmrit/logix/MergePrompt.java
  java/src/jmri/jmrit/logix/NXFrame.java
  java/src/jmri/jmrit/logix/OBlock.java
  java/src/jmri/jmrit/logix/RampData.java
  java/src/jmri/jmrit/logix/SCWarrant.java
  java/src/jmri/jmrit/logix/SpeedProfilePanel.java
  java/src/jmri/jmrit/logix/SpeedUtil.java
  java/src/jmri/jmrit/logix/ThrottleSetting.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantFrame.java
  java/src/jmri/jmrit/logix/WarrantManager.java
  java/src/jmri/jmrit/logix/WarrantPreferences.java
  java/src/jmri/jmrit/logix/WarrantPreferencesPanel.java
  java/src/jmri/jmrit/logix/WarrantRoute.java
  java/src/jmri/jmrit/logix/WarrantShutdownTask.java
  java/src/jmri/jmrit/logix/WarrantTableAction.java
  java/src/jmri/jmrit/logix/WarrantTableFrame.java
  java/src/jmri/jmrit/logix/WarrantTableModel.java
  java/src/jmri/jmrit/logix/configurexml/WarrantManagerXml.java
  java/src/jmri/jmrit/roster/RosterSpeedProfile.java
  java/test/jmri/jmrit/dispatcher/AutoTrainsMultiBlockStopTest.java
  java/test/jmri/jmrit/logix/BlockSpeedInfoTest.java
  java/test/jmri/jmrit/logix/LearnWarrantTest.java
  java/test/jmri/jmrit/logix/LinkedWarrantTest.java
  java/test/jmri/jmrit/logix/NXFrameTest.java
  java/test/jmri/jmrit/logix/OBlockTest.java
  java/test/jmri/jmrit/logix/RampDataTest.java
  java/test/jmri/jmrit/logix/SCWarrantTest.java
  java/test/jmri/jmrit/logix/SpeedUtilTest.java
  java/test/jmri/jmrit/logix/valid/ShortBlocksTest.xml
Labels: Documentation, Needs L10N

#10290 VSDecoder test thread removal
  java/src/jmri/jmrit/vsdecoder/Diesel3Sound.java
  java/src/jmri/jmrit/vsdecoder/Steam1Sound.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderManagerThread.java
  java/test/jmri/jmrit/vsdecoder/Diesel3SoundTest.java
  java/test/jmri/jmrit/vsdecoder/DieselSoundTest.java
  java/test/jmri/jmrit/vsdecoder/EngineSoundTest.java
  java/test/jmri/jmrit/vsdecoder/Steam1SoundTest.java
  java/test/jmri/jmrit/vsdecoder/SteamSoundTest.java
  java/test/jmri/jmrit/vsdecoder/VSDecoderManagerThreadTest.java
  java/test/jmri/jmrit/vsdecoder/VSDecoderTest.java
  java/test/jmri/jmrit/vsdecoder/swing/VSDConfigDialogTest.java
  java/test/jmri/jmrit/vsdecoder/swing/VSDManagerFrameTest.java
  java/test/jmri/jmrit/vsdecoder/swing/VSDecoderPreferencesPaneTest.java
  java/test/jmri/util/JUnitUtil.java
Labels: dev/test/publish infrastructure

#10298 Commit due to Windows CR-LR errors
  xml/decoders/soundtraxx/ECOenumChoiceDieselAirHornBachmann1.xml
  xml/decoders/soundtraxx/ECOenumDieselBellBachmann1.xml
Labels: New PR

#10291 MQTT reconnects if disconnected
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/mqtt/MqttAdapter.java
Labels: New PR

#10265 Remove limit for sections per transit
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle.properties
  java/src/jmri/jmrit/beantable/TransitTableAction.java
Labels: Needs L10N

#10295 Change LogixNG TreeEditor dialogs to non-modal
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
  java/src/jmri/jmrit/logixng/util/parser/swing/FunctionsHelpDialog.java
Labels: Needs L10N

#10296 Fix NX cancel and LE Edit block permissive
  help/en/package/jmri/jmrit/display/LayoutEditor.shtml
  java/src/jmri/jmrit/display/layoutEditor/LayoutBlock.java
  java/src/jmri/jmrit/entryexit/DestinationPoints.java
Labels: Documentation

#10303 Disable test
  java/test/jmri/jmrit/logix/LinkedWarrantTest.java
Labels: New PR

#10300 Add `ant checklineends` to GitHub workflows
  .github/workflows/run-separate.yml
  .github/workflows/static-analysis.yml
  build.xml
  help/en/html/doc/Technical/Eclipse.shtml
  java/test/jmri/util/FileLineEndingsCheck.java
  pom.xml
  scripts/mvn-check
  scripts/travis.sh
Labels: dev/test/publish infrastructure, New PR

#10306 Killing test threads
  java/src/jmri/jmrit/logix/Engineer.java
  java/test/jmri/jmrit/ctc/CtcManagerVetoTest.java
  java/test/jmri/jmrit/ctc/CtcRunWithSignalHeadsTest.java
  java/test/jmri/jmrit/ctc/editor/CtcEditorSignalHeadsTest.java
  java/test/jmri/jmrit/display/EditorFrameOperator.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorTest.java
  java/test/jmri/jmrit/jython/SampleScriptTest.java
  java/test/jmri/jmrit/whereused/WhereUsedCollectorsTest.java
  java/test/jmri/jmrit/whereused/WhereUsedFrameTest.java
  java/test/jmri/server/json/route/JsonRouteHttpServiceTest.java
  java/test/jmri/server/json/route/JsonRouteSocketServiceTest.java
  java/test/jmri/util/JUnitUtil.java
Labels: Java 11

#10313 LinkedWarrentTest threading
  java/test/jmri/jmrit/logix/LinkedWarrantTest.java
Labels: New PR

#10309 Throttles default
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/FunctionPanel.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
  java/src/jmri/jmrit/throttle/ThrottleFrame.java
  java/src/jmri/jmrit/throttle/ThrottleWindow.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferences.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesUISettingsPane.java
Labels: Needs L10N, New PR

#10311 Update OperationsPro help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Add to Next Test Release, Documentation

#10312 Update LogixNG action Listen On Beans
  java/src/jmri/jmrit/logixng/actions/ActionListenOnBeans.java
  java/src/jmri/jmrit/logixng/actions/ActionListenOnBeansTable.java
  java/src/jmri/jmrit/logixng/actions/ActionLocalVariable.java
  java/src/jmri/jmrit/logixng/actions/ActionMemory.java
  java/src/jmri/jmrit/logixng/actions/NamedBeanType.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionListenOnBeansTableXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionListenOnBeansXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionListenOnBeansTableSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/ListenOnBeansTableModel.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionLocalVariable.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionScript.java
  java/test/jmri/jmrit/logixng/RecursiveModuleTest.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  xml/schema/logixng/digital-actions/action-listen-on-beans-4.23.1.xsd
  xml/schema/logixng/digital-actions/action-listen-on-beans-table-4.23.1.xsd
Labels: Needs L10N

#10317 Add more listeners
  java/src/jmri/jmrit/logixng/actions/NamedBeanType.java
  java/test/jmri/jmrit/logixng/RecursiveModuleTest.java
  xml/schema/logixng/common-types-4.23.1.xsd
Labels: New PR

#10308 Update Simple programmer
  java/src/jmri/jmrit/progsupport/ProgModePane.java
  java/src/jmri/jmrit/progsupport/ProgOpsModePane.java
  java/src/jmri/jmrit/progsupport/ProgServiceModePane.java
  java/src/jmri/jmrit/progsupport/ProgSupportBundle.properties
  java/src/jmri/jmrit/simpleprog/SimpleProgFrame.java
Labels: Needs L10N

#10323 Improve ActionListenOnBeans
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionListenOnBeans.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionListenOnBeansXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionListenOnBeansSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  xml/schema/logixng/digital-actions/action-listen-on-beans-4.23.1.xsd
Labels: Needs L10N, New PR

#10314 Update WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantBundle.properties
Labels: New PR

#10316 Update Jemmy test library
  build.xml
  java/test/jmri/jmrit/throttle/SharingThrottleTest.java
  java/test/jmri/jmrit/throttle/StealingOrSharingThrottleTest.java
  java/test/jmri/jmrit/throttle/StealingThrottleTest.java
  java/test/jmri/jmrit/throttle/ThrottleFrameTest.java
  lib/README.md
  lib/jemmy-2.3.1.1-RELEASE125.jar
  lib/jemmy-22-00c9f753cd0a.jar
  lib/org/netbeans/external/jemmy/22-00c9f753cd0a/jemmy-22-00c9f753cd0a.jar
  lib/org/netbeans/external/jemmy/22-00c9f753cd0a/jemmy-22-00c9f753cd0a.jar.md5
  lib/org/netbeans/external/jemmy/22-00c9f753cd0a/jemmy-22-00c9f753cd0a.jar.sha1
  lib/org/netbeans/external/jemmy/22-00c9f753cd0a/jemmy-22-00c9f753cd0a.pom
  lib/org/netbeans/external/jemmy/22-00c9f753cd0a/jemmy-22-00c9f753cd0a.pom.md5
  lib/org/netbeans/external/jemmy/22-00c9f753cd0a/jemmy-22-00c9f753cd0a.pom.sha1
  lib/org/netbeans/external/jemmy/maven-metadata.xml
  lib/org/netbeans/external/jemmy/maven-metadata.xml.md5
  lib/org/netbeans/external/jemmy/maven-metadata.xml.sha1
  pom.xml
Labels: New PR

#10325 Add -T/-t options for Jemmy testing on Mac
  build.xml
  help/en/html/doc/Technical/JUnit.shtml
  help/en/html/doc/Technical/StartUpScripts.shtml
  runtest.csh
  scripts/AppScriptTemplate
Labels: dev/test/publish infrastructure, Documentation, New PR

#10324 Clear shutdown manager entries in testing
  java/test/apps/AppsLaunchFrameTest.java
  java/test/apps/gui3/dp3/DecoderPro3WindowTest.java
  java/test/apps/jmrit/log/Log4JTreePaneTest.java
  java/test/jmri/jmrit/beantable/AudioTableFrameTest.java
  java/test/jmri/jmrit/beantable/LightTableWindowTest.java
  java/test/jmri/jmrit/beantable/SensorTableActionTest.java
  java/test/jmri/jmrit/beantable/SignalHeadTableActionTest.java
  java/test/jmri/jmrit/beantable/oblock/BlockPathEditFrameTest.java
  java/test/jmri/jmrit/beantable/signalmast/SignalMastRepeaterJFrameTest.java
  java/test/jmri/jmrit/consisttool/ConsistToolFrameTest.java
  java/test/jmri/jmrit/roster/swing/RosterFrameTest.java
  java/test/jmri/jmrit/simpleclock/SimpleClockFrameTest.java
  java/test/jmri/jmrit/speedometer/SpeedometerActionTest.java
  java/test/jmri/jmrit/symbolicprog/PrintCvActionTest.java
  java/test/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrameTest.java
  java/test/jmri/jmrit/ussctc/OsIndicatorActionTest.java
  java/test/jmri/jmrix/bachrus/SpeedoConsoleActionTest.java
  java/test/jmri/jmrix/can/cbus/CbusCabSignalIT.java
  java/test/jmri/jmrix/can/cbus/CbusPredefinedMetersTest.java
  java/test/jmri/jmrix/can/cbus/swing/modeswitcher/SprogCbusSimpleModeSwitcherFrameTest.java
  java/test/jmri/jmrix/can/cbus/swing/modeswitcher/SprogCbusSprog3PlusModeSwitcherFrameTest.java
  java/test/jmri/jmrix/maple/nodeconfig/NodeConfigFrameTest.java
  java/test/jmri/jmrix/openlcb/swing/monitor/MonitorFrameDemo.java
  java/test/jmri/jmrix/openlcb/swing/tie/TieToolFrameTest.java
  java/test/jmri/jmrix/pricom/pockettester/MonitorFrameTest.java
  java/test/jmri/jmrix/rps/rpsmon/RpsMonTest.java
  java/test/jmri/jmrix/rps/swing/debugger/DebuggerTest.java
  java/test/jmri/jmrix/rps/swing/polling/PollTableActionTest.java
  java/test/jmri/jmrix/rps/trackingpanel/RpsTrackingFrameTest.java
  java/test/jmri/jmrix/secsi/serialmon/SerialMonFrameTest.java
  java/test/jmri/jmrix/tmcc/serialmon/SerialMonFrameTest.java
  java/test/jmri/util/JUnitUtil.java
Labels: New PR

#10327 Less agro memory check
  help/en/Acknowledgements.shtml
  java/src/jmri/jmrit/catalog/PreviewDialog.java
Labels: Documentation, New PR

#10329 Attempt to improve test robustness
  java/test/jmri/jmrit/operations/locations/tools/TrackDestinationEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarSetFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainEditFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainsTableFrameTest.java
Labels: Add to Next Test Release

#10328 add missing state descriptions, use bundle for text
  help/en/package/jmri/jmrit/withrottle/Protocol.shtml
  java/src/jmri/jmrit/withrottle/RouteController.java
  java/src/jmri/jmrit/withrottle/TurnoutController.java
  java/src/jmri/jmrit/withrottle/WiThrottleBundle.properties
Labels: Needs L10N, New PR

#10331 Update doc about TypeScript
  help/en/html/doc/Technical/Patterns.shtml
  web/ts/README.md
Labels: Documentation

#10330 Czech translation 2021-11-17
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/logix/WarrantBundle_cs.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/LogixNGParserBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/swing/ParserSwingBundle_cs.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_cs.properties
  java/src/jmri/util/UtilBundle_cs.properties
Labels: Needs L10N

#10337 Throttles documentation & minor fixes
  help/en/html/tools/throttle/AdvancedThrottleControl.shtml
  help/en/html/tools/throttle/BasicThrottleWindow.shtml
  help/en/html/tools/throttle/ThrottleToolBar.shtml
  help/en/html/tools/throttle/ThrottleWindowMenus.shtml
  help/en/html/tools/throttle/ThrottlesListWindow.shtml
  help/en/html/tools/throttle/ThrottlesPreferencesPane.shtml
  help/en/html/tools/throttle/images/BasicThrottleWindow.png
  help/en/html/tools/throttle/images/ControlPanelPreferences.png
  help/en/html/tools/throttle/images/FunctionButtonProperties.png
  help/en/html/tools/throttle/images/ThrottleListWindow.png
  help/en/html/tools/throttle/images/ThrottleToolBar.png
  help/en/html/tools/throttle/images/ThrottlesMenu1.png
  help/en/html/tools/throttle/images/ThrottlesMenu2.png
  help/en/html/tools/throttle/images/ThrottlesMenu3.png
  help/en/html/tools/throttle/images/ThrottlesPreferencesPane.png
  help/en/html/tools/throttle/images/throttles-preferences-steal-share-600x395.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
  java/src/jmri/jmrit/throttle/ThrottleFrameManager.java
  java/src/jmri/jmrit/throttle/ThrottlesListPanel.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferences.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesControlsSettingsPane.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesUISettingsPane.java
Labels: Documentation, Needs L10N

#10341 (Proposed) update to deprecation section of recommended practices doc
  help/en/html/doc/Technical/RP.shtml
Labels: Documentation

#10344 Improve font size ComboBox GUI. More test improvements.
  java/src/jmri/jmrit/operations/OperationsPanel.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterAction.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterAction.java
  java/src/jmri/jmrit/operations/setup/BuildReportOptionPanel.java
  java/src/jmri/jmrit/operations/setup/PrintOptionPanel.java
  java/test/jmri/jmrit/operations/automation/AutomationCopyFrameTest.java
  java/test/jmri/jmrit/operations/locations/SpurEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/divisions/DivisionEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/schedules/ScheduleCopyFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/LocationCopyFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarsSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/DeleteEngineRosterActionTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/EngineAttributeEditFrameTest.java
  java/test/jmri/jmrit/operations/routes/RouteEditFrameTest.java
  java/test/jmri/jmrit/operations/routes/tools/RouteCopyFrameTest.java
  java/test/jmri/jmrit/operations/routes/tools/SetTrainIconPositionFrameTest.java
  java/test/jmri/jmrit/operations/setup/OperationsSettingsFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainEditBuildOptionsFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainsTableFrameTest.java
Labels: Add to Next Test Release

#10339 J11: Remove deprecated JmriPlugin class
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/apps/Apps.java
  java/src/jmri/JmriPlugin.java
  java/test/jmri/JmriPluginTest.java
Labels: Java 11

#10315 Add clarifications to C/MRI help page
  help/en/html/hardware/cmri/CMRI.shtml
Labels: Documentation

#10340 J11: Remove deprecated apps.startup.StartupAction factory and kin
  java/src/apps/startup/AbstractStartupActionFactory.java
  java/src/apps/startup/StartupActionFactory.java
  java/src/jmri/util/startup/StartupActionModelUtil.java
  java/test/apps/startup/AbstractActionModelTest.java
  java/test/apps/startup/AbstractStartupActionFactoryTest.java
  java/test/apps/startup/StartupActionFactoryScaffold.java
  java/test/apps/startup/StartupActionFactoryScaffoldTest.java
  java/test/jmri/util/startup/StartupActionModelUtilTest.java
Labels: Java 11

#10347 fix PRT example
  help/en/package/jmri/jmrit/withrottle/Protocol.shtml
Labels: Documentation

#10348 J11 : remove deprecated forms
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/jmri/ReporterManager.java
  java/src/jmri/Section.java
  java/src/jmri/SensorManager.java
  java/src/jmri/Transit.java
  java/src/jmri/TurnoutManager.java
  java/src/jmri/managers/AbstractManager.java
  java/src/jmri/managers/AbstractProxyManager.java
  java/src/jmri/managers/ProxyReporterManager.java
  java/src/jmri/managers/ProxySensorManager.java
  java/src/jmri/managers/ProxyTurnoutManager.java
  java/test/jmri/jmrix/internal/InternalSensorManagerTest.java
  java/test/jmri/managers/TurnoutManagerScaffold.java
Labels: Java 11

#10349 More test improvements
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineEditFrameTest.java
  java/test/jmri/util/swing/JemmyUtil.java
Labels: Documentation

#10350 J11: Remove deprecated FileChooserUtil and Font methods in SystemConsolePreferences
  help/en/html/doc/Technical/Patterns.shtml
  help/en/package/jmri/jmrit/withrottle/Protocol.shtml
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/apps/systemconsole/SystemConsolePreferencesManager.java
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/logix/WarrantBundle_cs.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/LogixNGParserBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/swing/ParserSwingBundle_cs.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_cs.properties
  java/src/jmri/jmrit/withrottle/RouteController.java
  java/src/jmri/jmrit/withrottle/TurnoutController.java
  java/src/jmri/jmrit/withrottle/WiThrottleBundle.properties
  java/src/jmri/util/FileChooserFilter.java
  java/src/jmri/util/UtilBundle_cs.properties
  java/test/jmri/jmrit/operations/locations/tools/TrackDestinationEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarSetFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainEditFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainsTableFrameTest.java
  java/test/jmri/jmrix/loconet/SlotManagerTest.java
  java/test/jmri/util/FileChooserFilterTest.java
  web/ts/README.md
Labels: Java 11

#10346 Czech Translation 2021-11-19
  java/src/jmri/jmrit/timetable/TimeTableBundle_cs.properties
  java/src/jmri/jmrit/timetable/swing/TimeTableFrame.java
Labels: Needs L10N

#10353 Restore JmriUserPreferencesManager
  java/src/jmri/managers/JmriUserPreferencesManager.java
Labels: Bug

#10356 Eliminate deprecated function
  java/src/jmri/jmrit/operations/OperationsXml.java
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/divisions/Division.java
  java/src/jmri/jmrit/operations/routes/RouteLocation.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeEditFrameTest.java
  java/test/jmri/util/swing/JemmyUtil.java
Labels: Add to Next Test Release

#10363 J11 Remove deprecated methods in Manager
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/jmri/Manager.java
  java/src/jmri/NamedBeanHandleManager.java
  java/src/jmri/jmrit/entryexit/EntryExitPairs.java
  java/src/jmri/jmrix/ecos/EcosLocoAddressManager.java
  java/src/jmri/managers/AbstractManager.java
  java/src/jmri/managers/AbstractProxyManager.java
  java/src/jmri/managers/DefaultConditionalManager.java
  java/test/jmri/jmrix/internal/InternalSensorManagerTest.java
  java/test/jmri/jmrix/loconet/LnTurnoutManagerTest.java
  java/test/jmri/managers/AbstractSensorMgrTestBase.java
  java/test/jmri/managers/DefaultSignalSystemManagerTest.java
  java/test/jmri/managers/ProxySensorManagerTest.java
  java/test/jmri/managers/TurnoutManagerScaffold.java
Labels: Java 11

#10364 J11: Add comments to @Suppress("deprecation")
  java/src/jmri/implementation/DefaultConditional.java
  java/src/jmri/implementation/DefaultLightControl.java
  java/src/jmri/implementation/JmriClockPropertyListener.java
  java/src/jmri/jmrit/analogclock/AnalogClockFrame.java
  java/src/jmri/jmrit/dispatcher/ActiveTrain.java
  java/src/jmri/jmrit/display/AnalogClock2Display.java
  java/src/jmri/jmrit/display/layoutEditor/HitPointType.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutBlock.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/LayoutTrackEditor.java
  java/src/jmri/jmrit/display/layoutEditor/TrackSegment.java
  java/src/jmri/jmrit/entryexit/EntryExitPairs.java
  java/src/jmri/jmrit/lcdclock/LcdClockFrame.java
  java/src/jmri/jmrit/logix/OBlockManager.java
  java/src/jmri/jmrit/nixieclock/NixieClockFrame.java
  java/src/jmri/jmrit/pragotronclock/PragotronClockFrame.java
  java/src/jmri/jmrix/DefaultSystemConnectionMemo.java
  java/src/jmri/jmrix/loconet/LnClockControl.java
  java/src/jmri/jmrix/loconet/TranspondingTagManager.java
  java/src/jmri/jmrix/mrc/MrcClockControl.java
  java/src/jmri/jmrix/nce/NceClockControl.java
  java/src/jmri/jmrix/nce/clockmon/ClockMonPanel.java
  java/src/jmri/jmrix/pricom/downloader/LoaderPane.java
  java/src/jmri/jmrix/pricom/pockettester/DataSource.java
  java/src/jmri/managers/AbstractPowerManager.java
  java/src/jmri/managers/DefaultRailComManager.java
  java/src/jmri/profile/ProfileProperties.java
  java/src/jmri/server/json/JsonServerPreferences.java
  java/src/jmri/swing/EditableList.java
  java/src/jmri/util/prefs/JmriPreferencesProvider.java
Labels: Java 11

#10365 J11: Remove deprecations from ShutDownTask
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/jmri/ShutDownManager.java
  java/src/jmri/ShutDownTask.java
  java/src/jmri/implementation/AbstractShutDownTask.java
  java/src/jmri/managers/DefaultShutDownManager.java
  java/test/jmri/jmrit/catalog/ImageIndexEditorTest.java
  java/test/jmri/jmrit/operations/OperationsTestCase.java
  java/test/jmri/managers/DefaultShutDownManagerTest.java
  java/test/jmri/util/JUnitOperationsUtil.java
  java/test/jmri/util/JUnitUtil.java
  java/test/jmri/util/MockShutDownManagerTest.java
Labels: Java 11

#10367 J11 Remove deprecations from SSL
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/jmri/jmrit/blockboss/BlockBossLogic.java
  java/test/jmri/jmrit/blockboss/BlockBossLogicTest.java
  java/test/jmri/jmrit/blockboss/configurexml/BlockBossLogicXmlTest.java
Labels: Java 11

#10374 Move ImportEntryExitTest to Separate tests
  java/test/jmri/jmrit/logixng/tools/ImportEntryExitTest.java
Labels: New PR

#10379 Enable I18N for the default names for new Timetable items
  java/src/jmri/jmrit/timetable/Layout.java
  java/src/jmri/jmrit/timetable/Schedule.java
  java/src/jmri/jmrit/timetable/Segment.java
  java/src/jmri/jmrit/timetable/Station.java
  java/src/jmri/jmrit/timetable/TimeTableBundle.properties
  java/src/jmri/jmrit/timetable/Train.java
  java/src/jmri/jmrit/timetable/TrainType.java
  java/src/jmri/jmrit/timetable/swing/TimeTableFrame.java
Labels: Needs L10N

#10382 J11 Deprecations
  build.xml
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/jmri/server/json/JsonHttpService.java
  java/src/jmri/server/json/JsonNamedBeanHttpService.java
  java/src/jmri/server/json/JsonNonProvidedNamedBeanHttpService.java
  java/src/jmri/server/json/JsonSocketService.java
  java/src/jmri/server/json/consist/JsonConsistHttpService.java
  java/src/jmri/server/json/roster/JsonRosterHttpService.java
  java/src/jmri/server/json/schema/JsonSchemaServiceCache.java
  java/src/jmri/server/json/throttle/JsonThrottle.java
  java/src/jmri/server/json/throttle/JsonThrottleManager.java
  java/src/jmri/server/json/time/JsonTimeServiceFactory.java
  java/src/jmri/server/json/turnout/JsonTurnoutServiceFactory.java
  java/src/jmri/server/json/util/JsonUtilHttpService.java
  java/src/jmri/util/startup/StartupActionModelUtil.java
  java/src/jmri/web/server/WebServer.java
  java/src/jmri/web/server/WebServerPreferences.java
  java/src/jmri/web/server/WebServerPreferencesInstanceInitializer.java
  java/test/jmri/server/json/turnout/JsonTurnoutServiceFactoryTest.java
  java/test/jmri/util/JUnitUtil.java
  java/test/jmri/web/server/WebServerPreferencesInstanceInitializerTest.java
  java/test/jmri/web/server/WebServerTest.java
Labels: Java 11

#10383 J11 remove deprecated items in Beans, SPI, editor, scripts
  java/src/jmri/beans/Beans.java
  java/src/jmri/jmrit/display/EditorManager.java
  java/src/jmri/jmrit/display/PanelMenu.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderManager.java
  java/src/jmri/script/JmriScriptEngineManager.java
  java/src/jmri/spi/JsonServiceFactory.java
  java/test/jmri/beans/BeansTest.java
Labels: Java 11

#10385 Update operations help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Add to Next Test Release, Documentation

#10387 Fix NPE in ExecuteDelayed
  java/src/jmri/jmrit/logixng/actions/ExecuteDelayed.java
Labels: Bug

#10389 Add LogixNG action Show dialog
  java/src/jmri/jmrit/logixng/Module.java
  java/src/jmri/jmrit/logixng/SymbolTable.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/DigitalCallModule.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/ShowDialog.java
  java/src/jmri/jmrit/logixng/actions/configurexml/DigitalCallModuleXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ShowDialogXml.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/LogDataSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ShowDialogSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ShowDialogTableModel.java
  java/src/jmri/jmrit/logixng/expressions/DigitalCallModule.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/DigitalCallModuleXml.java
  java/src/jmri/jmrit/logixng/implementation/AbstractMaleSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultSymbolTable.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/AbstractMaleSocketXml.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/AbstractManagerXml.java
  java/src/jmri/jmrit/logixng/tools/swing/CallModuleParameterTableModel.java
  java/src/jmri/jmrit/logixng/tools/swing/LocalVariableTableModel.java
  java/src/jmri/jmrit/logixng/tools/swing/TreePane.java
  java/src/jmri/jmrit/logixng/util/parser/ExpressionNodeComparingOperator.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/show-dialog-4.25.7.xsd
Labels: Needs L10N, New PR

#10395 Czech Translation 2021-11-30
  java/src/apps/AppsConfigBundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle_cs.properties
  java/src/jmri/jmrit/logix/WarrantBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/CarEditFrame.java
  java/src/jmri/jmrit/progsupport/ProgSupportBundle_cs.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_cs.properties
  java/src/jmri/jmrit/timetable/TimeTableBundle_cs.properties
  java/src/jmri/jmrit/withrottle/WiThrottleBundle_cs.properties
Labels: Needs L10N, New PR
