Repository JMRI/JMRI, pull requests merged in 2021-04, with the labels that each got.

#9624 Bean edit action tabs - add persistence
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/beanedit/BeanEditAction.java
  java/src/jmri/jmrit/beantable/beanedit/BlockEditAction.java
  java/src/jmri/jmrit/beantable/beanedit/LightEditAction.java
  java/src/jmri/jmrit/beantable/beanedit/OBlockEditAction.java
  java/src/jmri/jmrit/beantable/beanedit/SensorDebounceEditAction.java
  java/src/jmri/jmrit/beantable/beanedit/SensorEditAction.java
  java/src/jmri/jmrit/beantable/beanedit/SensorPullUpEditAction.java
  java/src/jmri/jmrit/beantable/beanedit/TurnoutEditAction.java
  java/test/jmri/jmrit/beantable/beanedit/SensorDebounceEditActionTest.java
  java/test/jmri/jmrit/beantable/beanedit/SensorPullUpEditActionTest.java
Labels: Needs L10N

#9630 Create TSLR from Table - Use Exception text on failure
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/LightTableAction.java
  java/src/jmri/jmrit/beantable/ReporterTableAction.java
  java/src/jmri/jmrit/beantable/SensorTableAction.java
  java/src/jmri/jmrit/beantable/TurnoutTableAction.java
  java/test/jmri/jmrit/beantable/LightTableActionTest.java
  java/test/jmri/jmrit/beantable/ReporterTableActionTest.java
  java/test/jmri/jmrit/beantable/SensorTableActionTest.java
  java/test/jmri/jmrit/beantable/TurnoutTableActionTest.java
Labels: Needs L10N

#9632 Minor change to test 'documentation' labeling
  help/en/html/doc/Technical/Help.shtml
Labels: Documentation

#9634 Create a LogixNG Block Action
  java/src/jmri/jmrit/logixng/actions/ActionBlock.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionBlockXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionBlockSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/action-block-4.23.1.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
Labels: Needs L10N

#9637 Add warnings found dialog message to operations build report
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
Labels: Add to Next Test Release, Needs L10N

#9638 Adds an example command to run all junit tests in a package.
  help/en/html/doc/Technical/Ant.shtml
Labels: Documentation

#9655 Add SPROG Slot Monitor startup action
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/sprog/SprogActionListBundle.properties
  java/src/jmri/jmrix/sprog/SprogSystemConnectionMemo.java
  java/src/jmri/jmrix/sprog/sprogslotmon/SprogSlotMonAction.java
Labels: Needs L10N

#9671 Use UserPreferencesManager for CTC Editor window location and size
  help/en/package/jmri/jmrit/ctc/CTC.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/ctc/editor/code/AwtWindowProperties.java
Labels: Documentation

#9657 Use correct system name in error message
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
Labels: Needs L10N

#9679 createNewTurnout to throw IAE, not return null
  java/src/jmri/TurnoutManager.java
  java/src/jmri/jmrix/acela/AcelaTurnoutManager.java
  java/src/jmri/jmrix/can/cbus/CbusTurnoutManager.java
  java/src/jmri/jmrix/cmri/serial/SerialTurnoutManager.java
  java/src/jmri/jmrix/dccpp/DCCppTurnoutManager.java
  java/src/jmri/jmrix/easydcc/EasyDccTurnoutManager.java
  java/src/jmri/jmrix/ecos/EcosTurnoutManager.java
  java/src/jmri/jmrix/grapevine/SerialTurnoutManager.java
  java/src/jmri/jmrix/ieee802154/xbee/XBeeTurnoutManager.java
  java/src/jmri/jmrix/internal/InternalTurnoutManager.java
  java/src/jmri/jmrix/ipocs/IpocsTurnoutManager.java
  java/src/jmri/jmrix/jmriclient/JMRIClientTurnoutManager.java
  java/src/jmri/jmrix/lenz/XNetTurnoutManager.java
  java/src/jmri/jmrix/lenz/hornbyelite/EliteXNetTurnoutManager.java
  java/src/jmri/jmrix/loconet/LnTurnoutManager.java
  java/src/jmri/jmrix/maple/SerialTurnoutManager.java
  java/src/jmri/jmrix/marklin/MarklinTurnoutManager.java
  java/src/jmri/jmrix/mqtt/MqttTurnoutManager.java
  java/src/jmri/jmrix/mrc/MrcTurnoutManager.java
  java/src/jmri/jmrix/nce/NceTurnoutManager.java
  java/src/jmri/jmrix/oaktree/SerialTurnoutManager.java
  java/src/jmri/jmrix/openlcb/OlcbTurnoutManager.java
  java/src/jmri/jmrix/pi/RaspberryPiTurnoutManager.java
  java/src/jmri/jmrix/powerline/SerialTurnoutManager.java
  java/src/jmri/jmrix/roco/z21/Z21XNetTurnoutManager.java
  java/src/jmri/jmrix/secsi/SerialTurnoutManager.java
  java/src/jmri/jmrix/sprog/SprogTurnoutManager.java
  java/src/jmri/jmrix/srcp/SRCPTurnoutManager.java
  java/src/jmri/jmrix/tams/TamsTurnoutManager.java
  java/src/jmri/jmrix/tmcc/SerialTurnoutManager.java
  java/src/jmri/jmrix/xpa/XpaTurnoutManager.java
  java/src/jmri/jmrix/zimo/Mx1TurnoutManager.java
  java/src/jmri/jmrix/ztc/ztc611/ZTC611XNetTurnoutManager.java
  java/src/jmri/managers/AbstractProvidingProxyManager.java
  java/src/jmri/managers/AbstractTurnoutManager.java
  java/src/jmri/managers/ProxyTurnoutManager.java
  java/test/jmri/util/managers/TurnoutManagerThrowExceptionScaffold.java
Labels: New PR

#9680 Throttle resizable control buttons
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/throttle/AddressPanel.java
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
  resources/icons/throttles/dirBckOff512.png
  resources/icons/throttles/dirBckOn512.png
  resources/icons/throttles/dirFwdOff512.png
  resources/icons/throttles/dirFwdOn512.png
  resources/icons/throttles/estop512.png
  resources/icons/throttles/estopOn512.png
  resources/icons/throttles/stop512.png
  resources/icons/throttles/stopOn512.png
Labels: Needs L10N

#9683 Default caboose addition later in train's route to lead engine road name
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
Labels: Add to Next Test Release, Needs L10N

#9686 Provide the linkage between the Where Used tool and LogixNG
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/Base.java
  java/src/jmri/jmrit/logixng/actions/ActionBlock.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionSensor.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionBlockSwing.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBlock.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionSensor.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionBlockSwing.java
  java/src/jmri/jmrit/logixng/implementation/AbstractBase.java
  java/src/jmri/jmrit/logixng/implementation/AbstractFemaleSocket.java
  java/src/jmri/jmrit/logixng/implementation/AbstractMaleSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultLogixNG.java
  java/src/jmri/jmrit/logixng/implementation/DefaultModule.java
  java/src/jmri/jmrit/whereused/BlockWhereUsed.java
  java/src/jmri/jmrit/whereused/Bundle.properties
  java/src/jmri/jmrit/whereused/EntryExitWhereUsed.java
  java/src/jmri/jmrit/whereused/LightWhereUsed.java
  java/src/jmri/jmrit/whereused/MemoryWhereUsed.java
  java/src/jmri/jmrit/whereused/OBlockWhereUsed.java
  java/src/jmri/jmrit/whereused/ReporterWhereUsed.java
  java/src/jmri/jmrit/whereused/RouteWhereUsed.java
  java/src/jmri/jmrit/whereused/SectionWhereUsed.java
  java/src/jmri/jmrit/whereused/SensorWhereUsed.java
  java/src/jmri/jmrit/whereused/SignalHeadWhereUsed.java
  java/src/jmri/jmrit/whereused/SignalMastWhereUsed.java
  java/src/jmri/jmrit/whereused/TurnoutWhereUsed.java
  java/src/jmri/jmrit/whereused/WarrantWhereUsed.java
  java/src/jmri/jmrit/whereused/WhereUsedCollectors.java
  java/test/jmri/jmrit/logixng/FemaleSocketTestBase.java
  java/test/jmri/jmrit/logixng/implementation/AbstractFemaleSocketTest.java
Labels: Needs L10N

#9695 Czech translation
  java/src/apps/ActionListBundle_cs.properties
  java/src/apps/AppsConfigBundle_cs.properties
  java/src/apps/startup/Bundle_cs.properties
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/implementation/swing/MessageBundle_cs.properties
  java/src/jmri/jmris/json/Bundle_cs.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/automat/monitor/AutomatTableBundle.properties
  java/src/jmri/jmrit/automat/monitor/AutomatTableBundle_cs.properties
  java/src/jmri/jmrit/automat/monitor/AutomatTableDataModel.java
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/LogixNGTableTableAction.java
  java/src/jmri/jmrit/blockboss/BlockBossBundle_cs.properties
  java/src/jmri/jmrit/conditional/ConditionalBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_cs.properties
  java/src/jmri/jmrit/jython/JythonBundle_cs.properties
  java/src/jmri/jmrit/logix/WarrantBundle_cs.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/implementation/ImplementationBundle_cs.properties
  java/src/jmri/jmrit/logixng/implementation/swing/ImplementationSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/ToolsBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/swing/SwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/UtilBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/LogixNGParserBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/swing/ParserSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/ztest/ZTestBundle_cs.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrit/speedometer/SpeedometerBundle_cs.properties
  java/src/jmri/jmrit/whereused/Bundle_cs.properties
  java/src/jmri/jmrix/JmrixBundle_cs.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_cs.properties
  java/src/jmri/jmrix/loconet/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/openlcb/Bundle_cs.properties
  java/src/jmri/jmrix/openlcb/swing/Bundle_cs.properties
  java/src/jmri/profile/Bundle_cs.properties
  java/src/jmri/util/startup/Bundle_cs.properties
Labels: Needs L10N

#9694 Update help and improve testing
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Add to Next Test Release, Documentation

#9693 Contributed LocoTracker script
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/LocoTracker.py
  jython/test/LocoTrackerTest.py
Labels: Documentation

#9702 Update logixng FunctionsBundle
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
Labels: Needs L10N, New PR

#9700 Update comments in LogixNG
  java/src/jmri/jmrit/logixng/Base.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/implementation/AbstractMaleSocket.java
  java/src/jmri/jmrit/logixng/tools/swing/EditCommentDialog.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/TreePane.java
  java/test/jmri/jmrit/logixng/tools/swing/EditCommentDialogTest.java
Labels: Needs L10N

#9713 Light-It more appropriate default address.
  xml/decoders/NCE_Light-It_accessory.xml
  xml/decoders/NCE_Light-It_signal.xml
Labels: Add to Next Test Release, Cleanup

#9718 New operations feature, railroad divisions for prototypical car movement
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/JmritOperationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/LocationManager.java
  java/src/jmri/jmrit/operations/locations/LocationManagerXml.java
  java/src/jmri/jmrit/operations/locations/LocationsTableModel.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/Xml.java
  java/src/jmri/jmrit/operations/locations/divisions/Bundle.java
  java/src/jmri/jmrit/operations/locations/divisions/Division.java
  java/src/jmri/jmrit/operations/locations/divisions/DivisionEditFrame.java
  java/src/jmri/jmrit/operations/locations/divisions/DivisionManager.java
  java/src/jmri/jmrit/operations/locations/divisions/Xml.java
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/Xml.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableModel.java
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/locations/divisions/BundleTest.java
  java/test/jmri/jmrit/operations/locations/divisions/DivisionEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/divisions/DivisionManagerTest.java
  java/test/jmri/jmrit/operations/locations/divisions/DivisionTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Add to Next Test Release, Documentation, Needs L10N

#9722 Update print tools to show divisions
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsAction.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterAction.java
Labels: Add to Next Test Release, Needs L10N

#9726 Fix SPROG Gen 5 connection type list
  java/src/jmri/jmrix/can/adapters/gridconnect/sproggen5/Bundle.properties
  java/src/jmri/jmrix/sproggen5/SprogGen5ConnectionTypeList.java
  java/test/jmri/jmrix/sproggen5/SprogGen5ConnectionTypeListTest.java
Labels: Needs L10N

#9723 Implement LogixNG ActionOBlock
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionOBlock.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionOBlockXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionOBlockSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/action-oblock-4.23.1.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
Labels: Needs L10N

#9687 VSDecoder: 'delete decoder' now removes audio objects
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/vsdecoder/EngineSound.java
  java/src/jmri/jmrit/vsdecoder/EngineSoundEvent.java
  java/src/jmri/jmrit/vsdecoder/LoadVSDFileAction.java
  java/src/jmri/jmrit/vsdecoder/Steam1Sound.java
  java/src/jmri/jmrit/vsdecoder/SteamSound.java
  java/src/jmri/jmrit/vsdecoder/VSDecoder.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderManager.java
  java/src/jmri/jmrit/vsdecoder/swing/DieselPane.java
  java/src/jmri/jmrit/vsdecoder/swing/ManageLocationsAction.java
  java/src/jmri/jmrit/vsdecoder/swing/ManageLocationsTableModel.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDConfigDialog.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDControl.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDManagerFrame.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDSwingBundle.properties
  java/src/jmri/jmrit/vsdecoder/swing/VSDSwingBundle_de.properties
  java/test/jmri/jmrit/vsdecoder/swing/VSDConfigDialogTest.java
Labels: Needs L10N

#9729 Update help and code cleanup
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/EditCar.png
  help/en/package/jmri/jmrit/operations/images/EditLocation.png
  help/en/package/jmri/jmrit/operations/images/SetCarLocation.png
  java/src/jmri/jmrit/operations/locations/InterchangeEditFrame.java
  java/src/jmri/jmrit/operations/locations/InterchangeTableModel.java
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/SpurEditFrame.java
  java/src/jmri/jmrit/operations/locations/SpurTableModel.java
  java/src/jmri/jmrit/operations/locations/StagingEditFrame.java
  java/src/jmri/jmrit/operations/locations/StagingTableModel.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/YardEditFrame.java
  java/src/jmri/jmrit/operations/locations/YardTableModel.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/locations/TrackEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/TrackTableModelTest.java
  java/test/jmri/jmrit/operations/locations/tools/AlternateTrackActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/AlternateTrackFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/ChangeTrackFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/ChangeTrackTypeActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/PoolTrackActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/PoolTrackFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/TrackEditCommentsActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/TrackLoadEditActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/TrackRoadEditActionTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
Labels: Add to Next Test Release, Documentation

#9730 Implement ActionWarrant for LogixNG
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionWarrant.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionWarrantXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionWarrantSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/action-warrant-4.23.1.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
Labels: Needs L10N

#9734 Add new CmdMapper script
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/CmdMapper.py
Labels: Documentation

#9733 LogixNG error dialog with multiple lines
  java/src/jmri/JmriMultiLineException.java
  java/src/jmri/Reference.java
  java/src/jmri/jmrit/logixng/actions/ActionBlock.java
  java/src/jmri/jmrit/logixng/actions/ActionClock.java
  java/src/jmri/jmrit/logixng/actions/ActionEntryExit.java
  java/src/jmri/jmrit/logixng/actions/ActionLight.java
  java/src/jmri/jmrit/logixng/actions/ActionMemory.java
  java/src/jmri/jmrit/logixng/actions/ActionOBlock.java
  java/src/jmri/jmrit/logixng/actions/ActionPower.java
  java/src/jmri/jmrit/logixng/actions/ActionScript.java
  java/src/jmri/jmrit/logixng/actions/ActionSensor.java
  java/src/jmri/jmrit/logixng/actions/ActionSignalHead.java
  java/src/jmri/jmrit/logixng/actions/ActionSignalMast.java
  java/src/jmri/jmrit/logixng/actions/ActionSimpleScript.java
  java/src/jmri/jmrit/logixng/actions/ActionThrottle.java
  java/src/jmri/jmrit/logixng/actions/ActionTurnout.java
  java/src/jmri/jmrit/logixng/actions/ActionTurnoutLock.java
  java/src/jmri/jmrit/logixng/actions/AnalogActionMemory.java
  java/src/jmri/jmrit/logixng/actions/EnableLogix.java
  java/src/jmri/jmrit/logixng/actions/TriggerRoute.java
  java/src/jmri/jmrit/logixng/implementation/AbstractMaleSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleAnalogActionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleAnalogExpressionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleDigitalActionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleDigitalBooleanActionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleDigitalExpressionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleStringActionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleStringExpressionSocket.java
  java/src/jmri/jmrit/logixng/implementation/ImplementationBundle.properties
  java/src/jmri/jmrit/logixng/implementation/swing/ErrorHandlingDialog_MultiLine.java
  java/src/jmri/util/ThreadingUtil.java
  java/test/jmri/JmriMultiLineExceptionTest.java
  java/test/jmri/jmrit/logixng/actions/AnalogActionMemoryTest.java
  java/test/jmri/jmrit/logixng/implementation/swing/ErrorHandlingDialog_MultiLineTest.java
Labels: Needs L10N, New PR
