Repository JMRI/JMRI, pull requests merged in 2021-08, with the labels that each got.

#10010 Czech translation 2021 07 31
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/implementation/ImplementationBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/ToolsBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrix/JmrixBundle_cs.properties
  java/src/jmri/swing/Bundle_cs.properties
  xml/decoders/MGP_BT_LocoBridge.xml
Labels: Needs L10N

#10003 Improve NCE connection status
  help/en/html/hardware/nce/NCE.shtml
  java/src/jmri/jmrix/nce/NceBinaryCommand.java
  java/src/jmri/jmrix/nce/NceClockControl.java
  java/src/jmri/jmrix/nce/NceConnectionStatus.java
  java/src/jmri/jmrix/nce/NceConsist.java
  java/src/jmri/jmrix/nce/NceMessage.java
  java/src/jmri/jmrix/nce/NceProgrammer.java
  java/src/jmri/jmrix/nce/NceThrottle.java
  java/src/jmri/jmrix/nce/clockmon/ClockMonPanel.java
  java/src/jmri/jmrix/nce/configurexml/NceLightManagerXml.java
  java/src/jmri/jmrix/nce/configurexml/NceSensorManagerXml.java
  java/src/jmri/jmrix/nce/consist/NceConsistEditPanel.java
  java/src/jmri/jmrix/nce/consist/NceConsistRestore.java
  java/src/jmri/jmrix/nce/macro/NceMacroGenPanel.java
  java/src/jmri/jmrix/nce/macro/NceMacroRestore.java
  java/src/jmri/jmrix/nce/ncemon/NceMonBinary.java
  java/src/jmri/jmrix/nce/ncemon/NceMonBinaryBundle.properties
  java/src/jmri/jmrix/nce/ncemon/NceMonBinaryBundle_da.properties
  java/src/jmri/jmrix/nce/ncemon/NceMonBinaryBundle_fr.properties
  java/src/jmri/jmrix/nce/ncemon/NceMonBinaryBundle_it.properties
  java/src/jmri/jmrix/nce/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/nce/usbinterface/UsbInterfacePanel.java
Labels: Add to Next Test Release, Documentation

#10014 Additional UK locale improvements. NCE code cleanup
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrix/nce/NceThrottle.java
Labels: Add to Next Test Release, Needs L10N, New PR

#10017 Update SystemStructure.shtml
  help/en/html/doc/Technical/SystemStructure.shtml
Labels: Documentation

#10020 Fix duplicate Operations Bundle keys
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
Labels: Needs L10N

#10022 Fix Thread Monitor Exceptions
  java/src/jmri/jmrit/automat/AutomatSummary.java
  java/src/jmri/jmrit/automat/monitor/AutomatTableDataModel.java
  java/test/jmri/jmrit/automat/monitor/AutomatTableDataModelTest.java
Labels: Add to Next Test Release

#10023 Update Transit Manager to nonnull beans with Exception
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/TransitManager.java
  java/src/jmri/configurexml/TransitManagerXml.java
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/display/layoutEditor/TransitCreationTool.java
Labels: Needs L10N

#10026 Fix Panel Editor and Switchboard Editor name check
  java/src/jmri/jmrit/display/panelEditor/PanelEditorAction.java
  java/src/jmri/jmrit/display/switchboardEditor/SwitchboardEditorAction.java
  java/src/jmri/jmrit/operations/routes/JmritOperationsRoutesBundle.properties
  java/src/jmri/jmrit/operations/routes/Route.java
  java/src/jmri/jmrit/operations/routes/RouteEditFrame.java
  java/src/jmri/jmrit/operations/routes/RouteEditTableModel.java
  java/src/jmri/jmrit/operations/routes/RoutesTableModel.java
  java/src/jmri/jmrit/operations/setup/Setup.java
Labels: Add to Next Test Release, Needs L10N

#10030 Attempt to fix operations Project All Tests failures
  java/test/jmri/util/swing/JemmyUtil.java
Labels: Add to Next Test Release

#10027 Signal Head Table, Signal Mast Logic Table Lint. Signalling annotations
  java/src/jmri/SignalGroup.java
  java/src/jmri/SignalHeadManager.java
  java/src/jmri/SignalMastLogic.java
  java/src/jmri/jmrit/beantable/SignalHeadTableAction.java
  java/src/jmri/jmrit/beantable/SignalMastLogicTableAction.java
  java/src/jmri/managers/AbstractManager.java
  java/test/jmri/managers/DefaultSignalMastLogicManagerTest.java
Labels: New PR

#10037 Fix Desktop access
  java/src/jmri/util/HelpUtil.java
Labels: Add to Next Test Release

#10039 Fix timing issue in LnTurnoutTest
  java/test/jmri/jmrix/loconet/LnTurnoutTest.java
  java/test/jmri/jmrix/loconet/LocoNetInterfaceScaffold.java
Labels: New PR

#10035 Catalogtree Manager Update
  java/src/jmri/CatalogTreeManager.java
  java/src/jmri/jmrit/catalog/CatalogTreeIndex.java
  java/src/jmri/jmrit/catalog/DefaultCatalogTreeManager.java
  java/src/jmri/jmrit/catalog/configurexml/DefaultCatalogTreeManagerXml.java
Labels: New PR

#10034 IdTag Manager / Table Update
  java/src/jmri/IdTagManager.java
  java/src/jmri/implementation/DefaultIdTag.java
  java/src/jmri/jmrit/beantable/IdTagTableAction.java
  java/src/jmri/jmrit/beantable/IdTagTableDataModel.java
  java/src/jmri/jmrix/loconet/TranspondingTagManager.java
  java/src/jmri/managers/DefaultIdTagManager.java
  java/src/jmri/managers/ProxyIdTagManager.java
  java/src/jmri/managers/configurexml/DefaultIdTagManagerXml.java
  java/test/jmri/jmrit/beantable/IdTagTableDataModelTest.java
Labels: New PR

#10036 BeanTable tweak / add test
  java/src/jmri/jmrit/beantable/MemoryTableDataModel.java
  java/src/jmri/jmrit/beantable/ReporterTableDataModel.java
  java/src/jmri/jmrit/beantable/RouteTableDataModel.java
  java/src/jmri/jmrit/beantable/SectionTableAction.java
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/beantable/signalmast/SignalMastTableDataModel.java
  java/test/jmri/jmrit/beantable/AbstractBeanTableDataModelBase.java
  java/test/jmri/jmrit/beantable/signalmast/SignalMastTableDataModelTest.java
Labels: New PR

#10044 Railcom lint / Railcom table
  java/src/jmri/RailCom.java
  java/src/jmri/implementation/DefaultRailCom.java
  java/src/jmri/jmrit/beantable/RailComTableAction.java
  java/src/jmri/jmrit/beantable/RailComTableDataModel.java
  java/src/jmri/managers/DefaultRailComManager.java
  java/test/jmri/implementation/DefaultRailComTest.java
  java/test/jmri/jmrit/beantable/RailComTableDataModelTest.java
Labels: New PR

#10056 Fix internal html links
  help/en/JmriHelp_enIndex.xml
  help/en/html/FAQ.shtml
  help/en/html/doc/Technical/githubdesktopintro.shtml
  help/en/html/hardware/arduino/ArduinoCMRIByteComm.shtml
  help/en/html/hardware/can/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/can/index.shtml
  help/en/html/tools/Lights.shtml
  help/en/html/tools/automation/index.shtml
  help/en/html/tools/logixng/reference/chapter11.shtml
  help/en/html/tools/logixng/reference/chapter4.shtml
  help/en/html/tools/signaling/SidebarToolLocalPart.shtml
  help/en/local/index.html
  help/en/local/jmri_map.xml
  help/en/manual/DecoderPro/Comp_Setup_Roster.shtml
  help/en/manual/DecoderPro3/Adv_FunctionLabel.shtml
  help/en/manual/DecoderPro3/dp3_menubar.shtml
  help/en/package/jmri/jmrit/beantable/SignalMastRepeater.shtml
  help/en/package/jmri/jmrit/logix/Tracker.shtml
  help/en/package/jmri/jmrix/loconet/locoio/LocoIOFrame.shtml
  help/en/package/jmri/jmrix/loconet/swing/lncvprog/LncvProgPane.shtml
  help/en/package/jmri/jmrix/zimo/swing/monitor/Mx1MonPanel.shtml
  help/en/webindex.shtml
  help/fr/format.xsl
  help/fr/webindex.shtml
  help/fr/webtoc.shtml
  java/src/jmri/jmrix/jinput/treecontrol/TreeFrame.java
  web/power.html
Labels: Documentation

#10057 Translators Helper
  help/en/html/doc/Technical/I8N.shtml
  help/en/html/doc/Technical/images/TranslatorsHelper.jar
  help/en/html/doc/Technical/images/TranslatorsHelperFiles.png
  help/en/html/doc/Technical/images/TranslatorsHelperLanguages.png
Labels: Documentation

#10058 Use local help if web help fails
  java/src/jmri/util/HelpUtil.java
  java/src/jmri/util/UtilBundle.properties
Labels: Needs L10N

#10060 Allow user to set the current item pointer in a schedule
  java/src/jmri/jmrit/operations/locations/schedules/ScheduleTableModel.java
  java/src/jmri/jmrit/operations/setup/AutoSave.java
  java/src/jmri/jmrit/operations/trains/TrainsTableModel.java
Labels: Add to Next Test Release

#10068 Fix save after rolling stock delete
  java/src/jmri/jmrit/operations/rollingstock/RollingStockEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineManager.java
Labels: Add to Next Test Release

#10070 SwingPropertyChangeListener was deferring work if not on GUI thread, …
  java/src/jmri/beans/SwingPropertyChangeListener.java
Labels: dev/test/publish infrastructure

#10069 Finish internal link fixes
  help/en/html/doc/Technical/IntroStructure.shtml
  help/en/html/tools/signaling/AspectSignaling.shtml
  help/en/html/tools/signaling/DefineNewAspects.shtml
  help/en/html/tools/signaling/SidebarToolLocalPart.shtml
  xml/signals/AAR-1946/index.shtml
  xml/signals/Amtrak-2010/index.shtml
  xml/signals/B&O-1957/index.shtml
  xml/signals/B&O-1980/index.shtml
  xml/signals/B&O-2009/index.shtml
  xml/signals/B&O-Semaphore/index.shtml
  xml/signals/BN-1989/index.shtml
  xml/signals/BNSF-1996/index.shtml
  xml/signals/BR-2003/index.shtml
  xml/signals/C&O-1980/index.shtml
  xml/signals/CCOR-1967/index.shtml
  xml/signals/CFL-2014/index.shtml
  xml/signals/CNJ-1974/index.shtml
  xml/signals/CROR-2008/index.shtml
  xml/signals/CSD-1962-cestova/index.shtml
  xml/signals/CSD-1962-mechaniky/index.shtml
  xml/signals/CSD-1962-vlozena/index.shtml
  xml/signals/CSD-1962-zakladni/index.shtml
  xml/signals/CSX-1998/index.shtml
  xml/signals/CSX-2014-Chessie/index.shtml
  xml/signals/CTC-MB/index.shtml
  xml/signals/DB-HV-1969/index.shtml
  xml/signals/DanishSimplified/index.shtml
  xml/signals/GWR-1931/index.shtml
  xml/signals/InfraBel-2013/index.shtml
  xml/signals/LMS-1932/index.shtml
  xml/signals/NS-2008/index.shtml
  xml/signals/NW-1981/index.shtml
  xml/signals/NYC-1956/index.shtml
  xml/signals/NYCS-1937/index.shtml
  xml/signals/PKP-PLK-2020/index.shtml
  xml/signals/PRR-1956/index.shtml
  xml/signals/ProRail-1954/index.shtml
  xml/signals/RG-1965/index.shtml
  xml/signals/SLSF-1973/index.shtml
  xml/signals/SOU-1981/index.shtml
  xml/signals/SPTCO-1930/index.shtml
  xml/signals/SPTCO-1960/index.shtml
  xml/signals/SPTCO-1969/index.shtml
  xml/signals/SZDC-2015-zakladni/index.shtml
  xml/signals/UP-2008/index.shtml
  xml/signals/WM-1980/index.shtml
  xml/signals/basic/index.shtml
  xml/signals/index.shtml
Labels: Documentation
