Repository JMRI/JMRI, pull requests merged in 2021-09, with the labels that each got.

#10077 Code cleanup. No functional changes.
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/schedules/Schedule.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockAttribute.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockManager.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLoads.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineManager.java
  java/src/jmri/jmrit/operations/setup/BackupBase.java
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/trains/Train.java
Labels: Add to Next Test Release, Needs L10N

#10075 Add unary logical not to LogixNG Formula reference page
  help/en/html/tools/logixng/reference/chapter9.shtml
Labels: Documentation

#10074 Added Last Will to MQTT connect and fixed a bug in MqttAdapter
  java/src/jmri/jmrix/mqtt/Bundle.properties
  java/src/jmri/jmrix/mqtt/MqttAdapter.java
Labels: Needs L10N

#10084 Code refactoring, no functional changes
  java/src/jmri/jmrit/operations/rollingstock/RollingStockGroupManager.java
  java/src/jmri/jmrit/operations/rollingstock/cars/Car.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManagerXml.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/KernelManager.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/ImportCars.java
  java/src/jmri/jmrit/operations/rollingstock/engines/ConsistManager.java
  java/src/jmri/jmrit/operations/rollingstock/engines/Engine.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineManager.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineManagerXml.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/EngineAttributeEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/ImportEngines.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/NceConsistEngines.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/server/json/operations/JsonOperationsHttpService.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarManagerTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/KernelManagerTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/ConsistManagerTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineManagerTest.java
  java/test/jmri/jmrit/operations/router/OperationsCarRouterTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderGuiTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
  java/test/jmri/server/json/operations/JsonOperationsHttpServiceTest.java
  java/test/jmri/server/json/operations/JsonOperationsSocketServiceTest.java
  java/test/jmri/util/JUnitOperationsUtil.java
Labels: Add to Next Test Release, New PR

#10087 Fix edit action/expression bug
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
Labels: New PR

#10086 New WPRR 1971 signal system
  help/en/Acknowledgements.shtml
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-A/dark.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-A/rule-281.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-A/rule-282.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-A/rule-285.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-A/rule-288.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-A/rule-292.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-P/dark.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-P/rule-281.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-P/rule-282.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-P/rule-285.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-high-P/rule-291.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-low-A/dark.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-low-A/rule-281.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-low-A/rule-282.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-low-A/rule-285.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-low-A/rule-288.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-low-A/rule-292.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-with-marker-high-P/dark.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-with-marker-high-P/rule-281.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-with-marker-high-P/rule-282.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-with-marker-high-P/rule-284.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-with-marker-high-P/rule-285.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-1-with-marker-high-P/rule-291.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-2-high-A/dark.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-2-high-A/rule-281.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-2-high-A/rule-282.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-2-high-A/rule-283.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-2-high-A/rule-285.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-2-high-A/rule-286.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-2-high-A/rule-287.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-2-high-A/rule-288-A.gif
  resources/icons/smallschematics/aspects/WPRR-1971/SL-2-high-A/rule-292.gif
  resources/icons/smallschematics/aspects/WPRR-1971/index.php
  xml/signals/WPRR-1971/appearance-WP71-SL-1-high-A.xml
  xml/signals/WPRR-1971/appearance-WP71-SL-1-high-P.xml
  xml/signals/WPRR-1971/appearance-WP71-SL-1-low-A.xml
  xml/signals/WPRR-1971/appearance-WP71-SL-1-with-Yel-marker-high-P.xml
  xml/signals/WPRR-1971/appearance-WP71-SL-2-high-A.xml
  xml/signals/WPRR-1971/aspects.xml
  xml/signals/WPRR-1971/index.shtml
  xml/signals/index.shtml
Labels: Documentation

#10097 Update Java recommendation
  help/en/html/setup/index.shtml
Labels: Documentation

#10095 Added last will
  help/en/html/hardware/mqtt/index.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation, New PR

#10099 Some refactoring. Fix AutoHPT model and road bugs.
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderBaseTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Add to Next Test Release, Needs L10N

#10100 Implement LogixNG ActionReporter and ExpressionReporter
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_item.png
  help/en/html/tools/logixng/reference/images/chapter6/digital_expression_item.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionReporter.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionReporterXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionReporterSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionReporter.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionReporterXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionReporterSwing.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalExpressionSocketTest.java
  xml/schema/logixng/digital-actions/action-reporter-4.23.1.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-expressions/digital-expressions-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-reporter-4.23.1.xsd
Labels: Needs L10N

#10103 Improve test coverage. Minor bug fix AutoHP
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderGuiTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Add to Next Test Release, Needs L10N

#10101 More USS CTC documentation
  help/en/html/tools/uss/Conventions.shtml
  help/en/html/tools/uss/index.shtml
  help/en/package/jmri/jmrit/ussctc/CodeButtonFrame.shtml
  help/en/package/jmri/jmrit/ussctc/OsIndicatorFrame.shtml
  help/en/package/jmri/jmrit/ussctc/SignalLeverFrame.shtml
  help/en/package/jmri/jmrit/ussctc/TurnoutLeverFrame.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/ussctc/CombinedLock.java
  java/src/jmri/jmrit/ussctc/Follower.java
  java/src/jmri/jmrit/ussctc/FollowerAction.java
  java/src/jmri/jmrit/ussctc/FollowerFrame.java
  java/src/jmri/jmrit/ussctc/FollowerPanel.java
  java/src/jmri/jmrit/ussctc/Lock.java
  java/src/jmri/jmrit/ussctc/LockLogger.java
  java/src/jmri/jmrit/ussctc/OccupancyLock.java
  java/src/jmri/jmrit/ussctc/OsIndicator.java
  java/src/jmri/jmrit/ussctc/OsIndicatorAction.java
  java/src/jmri/jmrit/ussctc/OsIndicatorFrame.java
  java/src/jmri/jmrit/ussctc/OsIndicatorPanel.java
  java/src/jmri/jmrit/ussctc/RouteLock.java
  java/src/jmri/jmrit/ussctc/SignalHeadSection.java
  java/src/jmri/jmrit/ussctc/TimeLock.java
  java/src/jmri/jmrit/ussctc/TrafficLock.java
  java/src/jmri/jmrit/ussctc/TrafficRelay.java
  java/src/jmri/jmrit/ussctc/TurnoutLock.java
  java/src/jmri/jmrit/ussctc/TurnoutSection.java
  java/src/jmri/jmrit/ussctc/package-info.java
  java/test/jmri/jmrit/ussctc/CombinedLockTest.java
  java/test/jmri/jmrit/ussctc/OccupancyLockTest.java
  java/test/jmri/jmrit/ussctc/RouteLockTest.java
  java/test/jmri/jmrit/ussctc/TimeLockTest.java
  java/test/jmri/jmrit/ussctc/TrafficLockTest.java
  java/test/jmri/jmrit/ussctc/TrafficRelayTest.java
  java/test/jmri/jmrit/ussctc/TurnoutLockTest.java
  jython/ctc/README.md
  jython/ctc/TwoColumnMachine.py
  jython/ctc/TwoColumnMachine.xml
  jython/ctc/index.php
Labels: Documentation

#10104 Add files via upload
  xml/decoders/SoundTraxx_MC.xml
  xml/decoders/SoundTraxx_MC_IMRC_OEM.xml
  xml/decoders/SoundTraxx_MC_Walthers.xml
  xml/decoders/SoundTraxx_OEM_36-557_MC1.xml
  xml/decoders/SoundTraxx_SndVal_Diesel_Walthers_Mainline.xml
  xml/decoders/SoundTraxx_Tsu_Diesel.xml
  xml/decoders/SoundTraxx_Tsu_Diesel_Bachmann.xml
  xml/decoders/SoundTraxx_Tsu_Diesel_Bachmann_SndVal.xml
  xml/decoders/SoundTraxx_Tsu_Diesel_Bowser.xml
  xml/decoders/SoundTraxx_Tsu_Diesel_Genesis.xml
  xml/decoders/SoundTraxx_Tsu_Diesel_IMRC.xml
  xml/decoders/SoundTraxx_Tsu_Diesel_Rapido.xml
  xml/decoders/SoundTraxx_Tsu_Diesel_Walthers.xml
  xml/decoders/SoundTraxx_Tsu_Electric_Bachmann_SndVal.xml
  xml/decoders/SoundTraxx_Tsu_SoundCar.xml
  xml/decoders/SoundTraxx_Tsu_SoundCar_Walthers.xml
  xml/decoders/SoundTraxx_Tsu_Steam.xml
  xml/decoders/SoundTraxx_Tsu_Steam_Bachmann.xml
  xml/decoders/SoundTraxx_Tsu_Steam_Bachmann_SndVal.xml
  xml/decoders/SoundTraxx_Tsu_Steam_Genesis.xml
  xml/decoders/SoundTraxx_Tsu_Steam_IMRC.xml
  xml/decoders/SoundTraxx_Tsu_Steam_Walthers.xml
Labels: New PR

#10109 Improve test coverage. Change train departure time bug fix.
  java/src/jmri/jmrit/operations/OperationsFrame.java
  java/src/jmri/jmrit/operations/OperationsPanel.java
  java/src/jmri/jmrit/operations/routes/RouteEditTableModel.java
  java/src/jmri/jmrit/operations/routes/RouteLocation.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/tools/ChangeDepartureTimesFrame.java
  java/test/jmri/jmrit/operations/routes/OperationsRoutesGuiTest.java
  java/test/jmri/jmrit/operations/routes/RouteEditFrameTest.java
  java/test/jmri/jmrit/operations/routes/RouteLocationTest.java
  java/test/jmri/jmrit/operations/routes/RoutesTableModelTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderGuiTest.java
  java/test/jmri/jmrit/operations/trains/TrainConductorFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainLoadOptionsFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainRoadOptionsFrameTest.java
  java/test/jmri/jmrit/operations/trains/tools/ChangeDepartureTimesFrameTest.java
Labels: Add to Next Test Release, Needs L10N

#10111 Fix test that needs to run headless
  jython/test/TwoColumnMachineTest.py
  jython/test/TwoColumnMachineTest.xml
Labels: dev/test/publish infrastructure, New PR

#10112 Allow user to optionally update routes when changing departure times
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/tools/ChangeDepartureTimesFrame.java
  java/test/jmri/jmrit/operations/routes/RouteEditFrameTest.java
  java/test/jmri/jmrit/operations/trains/tools/ChangeDepartureTimesFrameTest.java
Labels: Add to Next Test Release, Documentation, Needs L10N

#10115 Minor improvements in an attempt to fix test failures
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/tools/SetPhysicalLocationFrame.java
  java/src/jmri/jmrit/operations/trains/tools/ChangeDepartureTimesFrame.java
Labels: Add to Next Test Release

#10116 Update LogixNG Many actions
  java/src/jmri/jmrit/logixng/actions/AnalogMany.java
  java/src/jmri/jmrit/logixng/actions/DigitalMany.java
  java/src/jmri/jmrit/logixng/actions/StringMany.java
Labels: Bug

#10120 Improve help and test coverage
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/Cars.png
  help/en/package/jmri/jmrit/operations/images/PrintOptions.png
  java/src/jmri/jmrit/operations/CommonConductorYardmasterPanel.java
  java/src/jmri/jmrit/operations/routes/RoutesTableFrame.java
  java/test/jmri/jmrit/operations/routes/RoutesTableFrameTest.java
  java/test/jmri/jmrit/operations/routes/RoutesTableModelTest.java
  java/test/jmri/jmrit/operations/trains/TrainConductorFrameTest.java
Labels: Add to Next Test Release, Documentation, New PR

#10117 Updated the documentation about MQTT Last Will
  help/en/html/hardware/mqtt/index.shtml
Labels: Documentation, New PR

#10110 Czech translation 2021-09-14
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/jmrit/Bundle.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/ToolsMenu.java
  java/src/jmri/jmrit/consisttool/ConsistTool_cs.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/implementation/swing/ImplementationSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/EditCommentDialog.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_cs.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_cs.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_cs.properties
  java/src/jmri/jmrix/mqtt/Bundle_cs.properties
  java/src/jmri/util/UtilBundle_cs.properties
  java/src/jmri/web/server/Bundle_cs.properties
  xml/decoders/Public_Domain_dccdoma_UNI16ARD_NAV.xml
  xml/decoders/Public_Domain_dccdoma_UNI16ARD_NAV_EXT.xml
  xml/decoders/Public_Domain_dccdoma_UNI16ARD_NAV_MX.xml
  xml/decoders/Public_Domain_dccdoma_UNI16ARD_NAV_ST.xml
Labels: Needs L10N

#10121 Check for null
  java/src/jmri/implementation/DefaultConditionalAction.java
Labels: New PR

#10128 Test Windows CI
  java/test/jmri/jmrit/logixng/configurexml/LoadAndStoreTest.java
Labels: New PR

#10127 Improve test coverage.
  java/src/jmri/jmrit/operations/routes/RoutesTableFrame.java
  java/src/jmri/jmrit/operations/trains/TrainsTableFrame.java
  java/src/jmri/jmrit/operations/trains/schedules/TrainsScheduleTableFrame.java
  java/test/jmri/jmrit/operations/trains/TrainConductorFrameTest.java
  java/test/jmri/jmrix/nce/NceMessageTest.java
  java/test/jmri/jmrix/nce/NceReplyTest.java
  java/test/jmri/jmrix/nce/NceTrafficControlScaffold.java
  java/test/jmri/jmrix/nce/simulator/SimulatorAdapterTest.java
  java/test/jmri/util/swing/JemmyUtil.java
Labels: Add to Next Test Release

#10133 Improve test coverage and operations help
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/automation/AutomationTableModel.java
  java/src/jmri/jmrit/operations/locations/schedules/ScheduleTableModel.java
  java/src/jmri/jmrit/operations/locations/schedules/SchedulesTableModel.java
  java/src/jmri/jmrit/operations/trains/tools/TrainByCarTypeFrame.java
  java/test/jmri/jmrit/operations/automation/AutomationTableFrameTest.java
  java/test/jmri/jmrit/operations/locations/schedules/ScheduleEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/schedules/SchedulesTableFrameTest.java
Labels: Add to Next Test Release, Documentation

#10129 Add Dispatcher support to LogixNG
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_item.png
  help/en/html/tools/logixng/reference/images/chapter6/digital_expression_item.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionDispatcher.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionDispatcherXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionDispatcherSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionDispatcher.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionDispatcherXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionDispatcherSwing.java
  java/src/jmri/jmrit/logixng/util/DispatcherActiveTrainManager.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalExpressionSocketTest.java
  java/test/jmri/jmrit/logixng/util/DispatcherActiveTrainManagerTest.java
  xml/schema/logixng/digital-actions/action-dispatcher-4.23.1.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-expressions/digital-expressions-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-dispatcher-4.23.1.xsd
Labels: Needs L10N

#10132 Update logixng/reference/chapter3.shtml
  help/en/html/tools/logixng/reference/chapter3.shtml
Labels: Documentation

#10135 Show how many warnings in operations train build report
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchListText.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderGuiTest.java
Labels: Add to Next Test Release, Needs L10N

#10134 Help pages for new CBUS NV editor
  help/en/html/hardware/can/cbus/images/swing/node-config/cbus-node-nv-edit-generic-1070x739.png
  help/en/html/hardware/can/cbus/images/swing/node-config/cbus-node-nv-edit-gui-1070x739.png
  help/en/package/jmri/jmrix/can/cbus/swing/nodeconfig/NodeConfigToolPane.shtml
Labels: Documentation

#10138 BUGFIX: Contradictory to restart refreshTimer when nothing sent on loconet
  java/src/jmri/jmrix/loconet/LocoNetThrottle.java
Labels: Bug

#10140 Add Table tab to Local Variable and Memory Actions
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionLocalVariable.java
  java/src/jmri/jmrit/logixng/actions/ActionMemory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionLocalVariableXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionMemoryXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionLocalVariableSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionMemorySwing.java
  java/test/jmri/jmrit/logixng/actions/ActionMemoryTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  xml/schema/logixng/digital-actions/action-local-variable-4.23.1.xsd
  xml/schema/logixng/digital-actions/action-memory-4.23.1.xsd
Labels: Documentation, Needs L10N

#10142 Update CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
Labels: Needs L10N, New PR

#10143 Improve operations tests
  java/src/jmri/jmrit/operations/setup/BuildReportOptionPanel.java
  java/src/jmri/jmrit/operations/setup/EditManifestHeaderTextPanel.java
  java/src/jmri/jmrit/operations/setup/EditManifestTextPanel.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchListEditFrame.java
  java/test/jmri/jmrit/operations/trains/TrainConductorFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainSwitchListEditFrameTest.java
Labels: Add to Next Test Release, Needs L10N

#10144 add properties and comment for created turnouts, sensors, outputs
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/dccpp/DCCppConstants.java
  java/src/jmri/jmrix/dccpp/DCCppReply.java
  java/src/jmri/jmrix/dccpp/DCCppSensorManager.java
  java/src/jmri/jmrix/dccpp/DCCppTurnoutManager.java
  java/src/jmri/jmrix/dccpp/swing/ConfigBaseStationFrame.java
  java/test/jmri/jmrix/dccpp/DCCppReplyTest.java
Labels: New PR

#10139 Update Create / Edit LightControllers
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/light/AddEditSingleLightControlFrame.java
Labels: Needs L10N, New PR

#10146 Add new turnout defs to Config Base Station, fix bugs
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/dccpp/DCCppCommandStation.java
  java/src/jmri/jmrix/dccpp/swing/ConfigBaseStationFrame.java
  java/src/jmri/jmrix/dccpp/swing/DCCppSwingBundle.properties
  java/src/jmri/jmrix/dccpp/swing/DCCppTableModel.java
  java/test/jmri/jmrix/dccpp/DCCppCommandStationTest.java
  jython/SendDCCppMessages.py
Labels: Needs L10N
