Repository JMRI/JMRI, pull requests merged in 2021-05, with the labels that each got.

#9739 ESU switch Qualifiers to use Item rather than Label.
  xml/decoders/ESU_LokPilot_StandardV1_0.xml
  xml/decoders/ESU_Misc_LightingInterior.xml
  xml/decoders/esu/switchPilotFnOutCVs.xml
  xml/decoders/esu/switchPilotFnOutPane.xml
  xml/decoders/esu/v4fnOutCVs.xml
  xml/decoders/esu/v4fnOutPane.xml
  xml/decoders/esu/v5fnOutCVs.xml
Labels: Add to Next Test Release, Bug, Cleanup

#9748 Modify block options, support reference, local variables and formula
  java/src/jmri/jmrit/logixng/actions/ActionBlock.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionBlockXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionBlockSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBlock.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionBlockXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionBlockSwing.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  xml/schema/logixng/digital-actions/action-block-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-block-4.23.1.xsd
Labels: Needs L10N

#9749 Modify OBlock options, support Reference, Local varibles and formula
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionOBlock.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionOBlockXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionOBlockSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  xml/schema/logixng/digital-actions/action-oblock-4.23.1.xsd
Labels: Needs L10N

#9752 Update ActionWarrant, support Reference, Local Variable and Formula
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionWarrant.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionWarrantXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionWarrantSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  xml/schema/logixng/digital-actions/action-warrant-4.23.1.xsd
Labels: Needs L10N

#9758 Update ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
Labels: New PR

#9756 Update Logix import
  java/src/jmri/jmrit/logixng/tools/ImportConditional.java
  java/src/jmri/jmrit/logixng/tools/ToolsBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/ImportLogixFrame.java
Labels: Needs L10N

#9753 Update names of actions
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionScript.java
  java/src/jmri/jmrit/logixng/actions/ActionTimer.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionScriptXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionSimpleScriptXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionScriptSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/AbstractScriptDigitalExpression.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionScript.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionScriptXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionScriptSwing.java
  java/src/jmri/jmrit/logixng/tools/ImportConditional.java
  java/test/jmri/jmrit/beantable/LogixNGTableActionTest.java
  java/test/jmri/jmrit/logixng/actions/AbstractDigitalActionTestBase.java
  java/test/jmri/jmrit/logixng/actions/ActionAtomicBooleanTest.java
  java/test/jmri/jmrit/logixng/actions/ActionLightTest.java
  java/test/jmri/jmrit/logixng/actions/ActionMemoryTest.java
  java/test/jmri/jmrit/logixng/actions/ActionScriptTest.java
  java/test/jmri/jmrit/logixng/actions/ActionScriptTest.py
  java/test/jmri/jmrit/logixng/actions/ActionSensorTest.java
  java/test/jmri/jmrit/logixng/actions/ActionTurnoutLockTest.java
  java/test/jmri/jmrit/logixng/actions/ActionTurnoutTest.java
  java/test/jmri/jmrit/logixng/actions/AnalogActionMemoryTest.java
  java/test/jmri/jmrit/logixng/actions/ShutdownComputerTest.java
  java/test/jmri/jmrit/logixng/actions/StringActionMemoryTest.java
  java/test/jmri/jmrit/logixng/actions/configurexml/DigitalActionsXmlTest.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/expressions/AbstractDigitalExpressionTestBase.java
  java/test/jmri/jmrit/logixng/expressions/AbstractScriptDigitalExpressionTest.java
  java/test/jmri/jmrit/logixng/expressions/AnalogExpressionConstantTest.java
  java/test/jmri/jmrit/logixng/expressions/AnalogExpressionMemoryTest.java
  java/test/jmri/jmrit/logixng/expressions/ExpressionLightTest.java
  java/test/jmri/jmrit/logixng/expressions/ExpressionLocalVariableTest.java
  java/test/jmri/jmrit/logixng/expressions/ExpressionMemoryTest.java
  java/test/jmri/jmrit/logixng/expressions/ExpressionScriptTest.java
  java/test/jmri/jmrit/logixng/expressions/ExpressionScriptTest.py
  java/test/jmri/jmrit/logixng/expressions/ExpressionSensorTest.java
  java/test/jmri/jmrit/logixng/expressions/ExpressionTurnoutTest.java
  java/test/jmri/jmrit/logixng/expressions/StringExpressionMemoryTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/action-script-4.23.1.xsd
  xml/schema/logixng/digital-actions/action-simple-script-4.23.1.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-expressions/digital-expressions-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-script-4.23.1.xsd
Labels: Needs L10N

#9763 Store Item rather than Label in varValue.
  java/src/jmri/jmrit/roster/LocoFile.java
Labels: Add to Next Test Release, Bug, New PR

#9765 Check for partially built trains
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/LocationManager.java
  java/src/jmri/jmrit/operations/setup/OptionPanel.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/TrainsTableModel.java
  java/test/jmri/jmrit/operations/trains/TrainsTableFrameTest.java
  java/test/jmri/jmrit/operations/trains/XmlTest.java
Labels: Add to Next Test Release

#9762 Log warning when findVar matches by Label rather than Item.
  java/src/jmri/jmrit/symbolicprog/VariableTableModel.java
  java/test/jmri/jmrit/symbolicprog/tabbedframe/pass/DecoderWithQualifier.xml
Labels: Add to Next Test Release, Bug

#9767 Add staging division choices
  java/src/jmri/jmrit/operations/locations/LocationManager.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/locations/LocationManagerTest.java
  java/test/jmri/jmrit/operations/locations/TrackEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/AlternateTrackActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/AlternateTrackFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/ChangeTrackFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/ChangeTrackTypeActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/PoolTrackActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/PoolTrackFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/TrackEditCommentsActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/TrackLoadEditActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/TrackRoadEditActionTest.java
Labels: Add to Next Test Release, Needs L10N

#9773 Further formatting in VariableTableModel.
  java/src/jmri/jmrit/symbolicprog/VariableTableModel.java
Labels: Add to Next Test Release, Cleanup

#9780 Additional operations testing
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/LocationsTableModel.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainManagerTest.java
Labels: Add to Next Test Release, Documentation

#9777 Fix bug in LogixNG clipboard
  java/src/jmri/jmrit/logixng/implementation/DefaultClipboard.java
  java/src/jmri/jmrit/logixng/tools/swing/ClipboardEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/ConditionalNGEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/ModuleEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
Labels: New PR

#9768 Dispatcher Create Train update, Multi block stopping, and other
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/dispatcher/ActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoAllocate.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
  java/src/jmri/jmrit/dispatcher/OptionsFile.java
  java/src/jmri/jmrit/dispatcher/OptionsMenu.java
  java/src/jmri/jmrit/dispatcher/TrainInfo.java
  java/test/jmri/jmrit/dispatcher/AllocationPlanTest.java
  java/test/jmri/jmrit/dispatcher/AutoTrainsMultiBlockStopTest.java
  java/test/jmri/jmrit/dispatcher/DispatcherFrameTest.java
  java/test/jmri/jmrit/dispatcher/MultiBlockStop.xml
  java/test/jmri/jmrit/dispatcher/MultiBlockStopdispatcheroptions.xml
  java/test/jmri/jmrit/dispatcher/OptionsMenuTest.java
  java/test/jmri/jmrit/dispatcher/dispatcheroptions.xml
  java/test/jmri/jmrit/dispatcher/traininfo/FWDREV120.xml
  java/test/jmri/jmrit/dispatcher/traininfo/FWDREV40.xml
  java/test/jmri/jmrit/dispatcher/traininfo/FWDREV80.xml
  java/test/jmri/jmrit/dispatcher/traininfo/REVFWD120.xml
  java/test/jmri/jmrit/dispatcher/traininfo/REVFWD40.xml
  java/test/jmri/jmrit/dispatcher/traininfo/REVFWD80.xml
  java/test/jmri/jmrit/dispatcher/traininfo/SMLStopManualAuto.xml
Labels: Needs L10N

#9769 Move test to intermittent test
  java/test/jmri/jmrit/entryexit/AddEntryExitPairPanelTest.java
Labels: New PR

#9781 avoid ConcurrentModificationException, proposed fix for #9775
  java/src/jmri/jmrix/AbstractThrottleManager.java
Labels: New PR

#9784 Refactor ConditionalNGs to be children of LogixNGs
  java/src/jmri/jmrit/logixng/ConditionalNG_Manager.java
  java/src/jmri/jmrit/logixng/LogixNG.java
  java/src/jmri/jmrit/logixng/implementation/DefaultConditionalNG.java
  java/src/jmri/jmrit/logixng/implementation/DefaultConditionalNGManager.java
  java/src/jmri/jmrit/logixng/implementation/DefaultLogixNG.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultConditionalNGManagerXml.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultLogixNGManagerXml.java
  java/src/jmri/jmrit/logixng/tools/ImportConditional.java
  java/src/jmri/jmrit/logixng/tools/ImportLogix.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/test/jmri/jmrit/beantable/LogixNGTableActionTest.java
  java/test/jmri/jmrit/display/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/ConditionalNGTest.java
  java/test/jmri/jmrit/logixng/LogixNGTest.java
  java/test/jmri/jmrit/logixng/LogixNG_ManagerTest.java
  java/test/jmri/jmrit/logixng/actions/ActionThrottleTest.java
  java/test/jmri/jmrit/logixng/actions/SocketTest.java
  java/test/jmri/jmrit/logixng/actions/swing/ActionLightSwingTest.java
  java/test/jmri/jmrit/logixng/actions/swing/ActionSensorSwingTest.java
  java/test/jmri/jmrit/logixng/actions/swing/ActionTurnoutSwingTest.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/expressions/swing/ExpressionLightSwingTest.java
  java/test/jmri/jmrit/logixng/expressions/swing/ExpressionSensorSwingTest.java
  java/test/jmri/jmrit/logixng/expressions/swing/ExpressionTurnoutSwingTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleAnalogActionSocketTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalBooleanActionSocketTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleGenericExpressionSocket1_Test.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleStringActionSocketTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultLogixNGManagerTest.java
  java/test/jmri/jmrit/logixng/tools/swing/ConditionalNGDebuggerTest.java
  java/test/jmri/jmrit/logixng/tools/swing/ConditionalNGEditorTest.java
  java/test/jmri/jmrit/logixng/tools/swing/EditThreadsDialogTest.java
  java/test/jmri/jmrix/loconet/logixng/configurexml/StoreAndLoadTest.java
  xml/schema/logixng/digital-expressions/expression-warrant-4.23.1.xsd
Labels: Needs L10N

#9795 Create the LogixNG help configuration
  help/en/JmriHelp_enIndex.xml
  help/en/JmriHelp_enTOC.xml
  help/en/html/apps/LoadStoreWork.shtml
  help/en/html/tools/automation/index.shtml
  help/en/html/tools/index.shtml
  help/en/html/tools/logixng/LogixNG.shtml
  help/en/package/jmri/jmrit/logixng/ConditionalNGEditor.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGInitializationTable.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGModuleTable.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGTable.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGTableEditor.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGTableTable.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGTableTableEditor.shtml
  help/en/parts/SidebarLayoutAutomation.shtml
  help/en/parts/SidebarTools.shtml
  java/src/jmri/jmrit/beantable/AbstractLogixNGTableAction.java
  java/src/jmri/jmrit/beantable/LogixNGModuleTableAction.java
  java/src/jmri/jmrit/beantable/LogixNGTableAction.java
  java/src/jmri/jmrit/beantable/LogixNGTableTableAction.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGInitializationTable.java
  java/src/jmri/jmrit/logixng/tools/swing/TableEditor.java
  java/test/jmri/jmrit/beantable/LogixNGModuleTableActionTest.java
  java/test/jmri/jmrit/beantable/LogixNGTableActionTest.java
Labels: Documentation

#9794 Implement MQTT usn/pw Client Authentication
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/AbstractNetworkConnectionConfig.java
  java/src/jmri/jmrix/AbstractPortController.java
  java/src/jmri/jmrix/PortAdapter.java
  java/src/jmri/jmrix/mqtt/Bundle.properties
  java/src/jmri/jmrix/mqtt/MqttAdapter.java
  java/src/jmri/jmrix/mqtt/MqttSystemConnectionMemo.java
Labels: Needs L10N

#9796 Support new NCE Power Pro firmware.
  java/src/jmri/jmrix/nce/NceBundle.properties
  java/src/jmri/jmrix/nce/NceConnectionStatus.java
  java/src/jmri/jmrix/nce/NceProgrammer.java
  java/src/jmri/jmrix/nce/NceTrafficController.java
  java/src/jmri/jmrix/nce/simulator/Bundle.java
  java/src/jmri/jmrix/nce/simulator/SimulatorAdapter.java
  java/test/jmri/jmrix/nce/NceConnectionStatusTest.java
Labels: Add to Next Test Release, Needs L10N

#9797 VSDecoder: add option 'dynamic gain" for steam1
  help/en/manual/DecoderPro/VSD_File_and_Config.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/vsdecoder/Steam1Sound.java
  java/src/jmri/jmrit/vsdecoder/VSDecoder.java
Labels: Documentation

#9785 Let the user select if numbers should be shown
  java/src/jmri/jmrit/symbolicprog/SpeedTableNumbers.java
  java/src/jmri/jmrit/symbolicprog/SpeedTableVarValue.java
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
Labels: Needs L10N

#9803 Missing < in DispatcherPro/Sidebar.shtml
  help/en/html/apps/DispatcherPro/Sidebar.shtml
Labels: Documentation

#9682 Initial support for LocoNet Multi Sense Long OpCode
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_nl.properties
  java/test/jmri/jmrix/loconet/LnConstantsTest.java
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Needs L10N

#9809 Better handling of NCE Power Pro write CV>256 blocking.
  java/src/jmri/jmrix/nce/NceConnectionStatus.java
  java/src/jmri/jmrix/nce/NceProgrammer.java
  java/src/jmri/jmrix/nce/NceTrafficController.java
Labels: Add to Next Test Release, Bug

#9812 AAR-1946 aspect mapping SL-1 high-pbs and add CCOR-167
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/signals/AAR-1946/appearance-SL-1-high-pbs.xml
Labels: Documentation, New PR

#9814 Fix CCOR xml missing newline
  xml/signals/CCOR-1967/appearance-SL-1-high-pbs.xml
  xml/signals/CCOR-1967/appearance-SL-3-high.xml
Labels: New PR

#9813 Update help
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/divisions/DivisionEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/ImportRollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsSetFrame.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/tools/TrainByCarTypeFrame.java
Labels: Add to Next Test Release, Documentation, Needs L10N

#9821 Update SidebarTail
  help/en/parts/SidebarTail.shtml
Labels: Documentation

#9827 Logixng unselect bean
  java/src/jmri/jmrit/logixng/actions/swing/ActionBlockSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionEntryExitSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionLightSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionMemorySwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionOBlockSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionSensorSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionSignalHeadSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionSignalMastSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionTurnoutLockSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionTurnoutSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionWarrantSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/AnalogActionMemorySwing.java
  java/src/jmri/jmrit/logixng/actions/swing/EnableLogixSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/TableForEachSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/TriggerRouteSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionBlockSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionConditionalSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionEntryExitSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionLightSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionLocalVariableSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionMemorySwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionOBlockSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionSensorSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionSignalHeadSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionSignalMastSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionTurnoutSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionWarrantSwing.java
Labels: New PR

#9826 Export car and track division names
  java/src/jmri/jmrit/operations/locations/tools/ExportLocations.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/ExportCars.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
Labels: Add to Next Test Release, Needs L10N, New PR

#9825 Remove h3 tags from dt tags
  help/en/Acknowledgements.shtml
  help/en/html/SidebarCompact.shtml
  help/en/html/apps/DecoderPro/Sidebar.shtml
  help/en/html/apps/DecoderPro/SidebarAppLocalPart.shtml
  help/en/html/apps/DispatcherPro/Sidebar.shtml
  help/en/html/apps/DispatcherPro/SidebarAppLocalPart.shtml
  help/en/html/apps/PanelPro/Sidebar.shtml
  help/en/html/apps/PanelPro/SidebarAppLocalPart.shtml
  help/en/html/apps/SoundPro/Sidebar.shtml
  help/en/html/apps/SoundPro/SidebarAppLocalPart.shtml
  help/en/html/doc/Technical/Sidebar.shtml
  help/en/html/doc/Technical/index.shtml
  help/en/html/doc/Technical/logixng/Sidebar.shtml
  help/en/html/hardware/XBee/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/XPressNet/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/arduino/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/can/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/can/cbus/Sidebar.shtml
  help/en/html/hardware/cmri/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/dccpp/Sidebar.shtml
  help/en/html/hardware/grapevine/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/loconet/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/merg/Sidebar.shtml
  help/en/html/hardware/openlcb/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/powerline/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/raildriver/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/roco/z21/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/rps/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/sproggen5/Sidebar.shtml
  help/en/html/setup/Sidebar.shtml
  help/en/html/tools/Sidebar.shtml
  help/en/html/tools/automation/Sidebar.shtml
  help/en/html/tools/scripting/Sidebar.shtml
  help/en/html/tools/scripting/SidebarToolLocalPart.shtml
  help/en/html/tools/signaling/Sidebar.shtml
  help/en/html/tools/signaling/SidebarToolLocalPart.shtml
  help/en/html/tools/speedometer/Sidebar.shtml
  help/en/html/tools/speedometer/SidebarToolLocalPart.shtml
  help/en/html/tools/throttle/Sidebar.shtml
  help/en/html/tools/throttle/SidebarToolLocalPart.shtml
  help/en/html/web/Sidebar.shtml
  help/en/manual/DecoderPro/Sidebar
  help/en/manual/DecoderPro/Sidebar.shtml
  help/en/manual/DecoderPro3/Sidebar
  help/en/manual/DecoderPro3/Sidebar.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Sidebar
  help/en/manual/JMRI_OPS_UsersGuide/Sidebar.shtml
  help/en/manual/Sidebar.shtml
  help/en/manual/index.shtml
  help/en/parts/SidebarApplications.shtml
  help/en/parts/SidebarInstall.shtml
  help/en/parts/SidebarLayoutAutomation.shtml
  help/en/parts/SidebarSupportedHardware.shtml
  help/en/parts/SidebarTools.shtml
Labels: Documentation, New PR

#9835 Fix default speed step mode in throttle constructor
  java/src/jmri/jmrix/sprog/SprogCSThrottle.java
  java/src/jmri/jmrix/sprog/SprogThrottle.java
  java/test/jmri/jmrix/sprog/SprogCSThrottleTest.java
  java/test/jmri/jmrix/sprog/SprogThrottleTest.java
Labels: New PR

#9841 Remove name attribute from help document
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
Labels: Add to Next Test Release, Documentation, Needs L10N

#9844 Fix DTD schema
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/Xml.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/Xml.java
  xml/DTD/operations-cars.dtd
  xml/DTD/operations-locations.dtd
Labels: Add to Next Test Release
