Repository JMRI/JMRI, pull requests merged in 2021-03, with the labels that each got.

#9439 Add_Route tooltip
  .idea/JMRI.iml
  java/src/jmri/jmrit/ToolsMenu.java
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_ca.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_da.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_de.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_fr.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_nl.properties
  java/src/jmri/jmrit/beantable/LRouteTableBundle_ja_JP.properties
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle_ca.properties
  java/src/jmri/jmrit/conditional/ConditionalBundle_ca.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_ca.properties
  java/src/jmri/jmrit/roster/JmritRosterBundle_ca.properties
  java/src/jmri/jmrit/roster/swing/speedprofile/SpeedProfileBundle_ca.properties
  java/src/jmri/jmrix/JmrixBundle_ca.properties
  java/src/jmri/jmrix/cmri/CmriBundle_ca.properties
  java/src/jmri/jmrix/dcc4pc/swing/boardlists/BoardListBundle_ca.properties
  java/src/jmri/managers/ManagersBundle_ca.properties
Labels: Needs L10N

#9442 Fix manual/Sidebar.shtml tail placement
  help/en/manual/Sidebar.shtml
Labels: Documentation

#9445 Add links to githubdesktopintro.shtml
  help/en/html/doc/Technical/GitFAQ.shtml
  help/en/html/doc/Technical/Sidebar.shtml
  help/en/html/doc/Technical/getgitcode.shtml
  help/en/html/doc/Technical/githubdesktopintro.shtml
Labels: Documentation

#9451 Create page and links for Jython Apps that work with JMRI
  help/en/JmriHelp_enIndex.xml
  help/en/JmriHelp_enTOC.xml
  help/en/html/apps/index.shtml
  help/en/html/scripthelp/DispatcherSystem/DispatcherSystem.shtml
  help/en/html/tools/scripting/JythonApps.shtml
  help/en/html/tools/scripting/SidebarToolLocalPart.shtml
  help/en/html/tools/scripting/index.shtml
  help/en/parts/SidebarApplications.shtml
Labels: Documentation

#9455 Add an option to Preferences => Display to limit the number of combo box rows
  help/en/package/apps/TabbedPreferences.shtml
  help/en/package/apps/images/PrefsGui4_23.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/AppsConfigBundle.properties
  java/src/apps/GuiLafConfigPane.java
  java/src/jmri/util/gui/GuiLafPreferencesManager.java
  java/src/jmri/util/swing/JComboBoxUtil.java
Labels: Needs L10N

#9466 Fix place test icons on set train coordinates window
  java/src/apps/ActionListBundle.properties
  java/src/jmri/jmrit/display/EditorManager.java
  java/src/jmri/jmrit/operations/JmritOperationsBundle.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_ca.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_da.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_de.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_fr.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_nl.properties
  java/src/jmri/jmrit/operations/OperationsMenu.java
  java/src/jmri/jmrit/operations/OperationsStartupActionFactory.java
  java/src/jmri/jmrit/operations/locations/LocationsTableModel.java
  java/src/jmri/jmrit/operations/locations/tools/LocationTrackBlockingOrderFrame.java
  java/src/jmri/jmrit/operations/routes/RoutesTableModel.java
  java/src/jmri/jmrit/operations/routes/tools/SetTrainIconPositionFrame.java
  java/src/jmri/jmrit/operations/routes/tools/SetTrainIconRouteFrame.java
  java/src/jmri/jmrit/operations/setup/OperationsSettingsAction.java
  java/src/jmri/jmrit/operations/setup/OperationsSettingsFrame.java
  java/src/jmri/jmrit/operations/setup/OperationsSettingsPanel.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainsTableModel.java
  java/test/jmri/jmrit/operations/setup/OperationsSettingsActionTest.java
  java/test/jmri/jmrit/operations/setup/OperationsSettingsFrameTest.java
  java/test/jmri/jmrit/operations/setup/OperationsSettingsPanelTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Add to Next Test Release

#9458 Fix several broken links in documentation
  help/en/html/FAQ.shtml
  help/en/html/hardware/arduino/index.shtml
  help/en/html/tools/Lights.shtml
Labels: Documentation

#9460 DCC++ spotbugs
  java/src/jmri/Programmer.java
  java/src/jmri/jmrix/AbstractMRReply.java
  java/src/jmri/jmrix/AbstractProgrammer.java
  java/src/jmri/jmrix/AbstractProgrammerFacade.java
  java/src/jmri/jmrix/dccpp/DCCppBundle_nl.properties
  java/src/jmri/jmrix/dccpp/DCCppMessage.java
  java/src/jmri/jmrix/dccpp/DCCppOpsModeProgrammer.java
  java/src/jmri/jmrix/dccpp/DCCppPacketizer.java
  java/src/jmri/jmrix/dccpp/DCCppProgrammer.java
  java/src/jmri/jmrix/dccpp/DCCppReply.java
  java/src/jmri/jmrix/dccpp/DCCppSensor.java
  java/src/jmri/jmrix/dccpp/DCCppSensorManager.java
  java/src/jmri/jmrix/dccpp/configurexml/AbstractDCCppSerialConnectionConfigXml.java
  java/src/jmri/jmrix/dccpp/configurexml/DCCppLightManagerXml.java
  java/src/jmri/jmrix/dccpp/configurexml/DCCppSensorManagerXml.java
  java/src/jmri/jmrix/dccpp/dccppovertcp/ClientRxHandler.java
  java/src/jmri/jmrix/dccpp/dccppovertcp/DCCppOverTcpPacketizer.java
  java/src/jmri/jmrix/dccpp/dccppovertcp/ServerFrame.java
  java/src/jmri/jmrix/dccpp/network/DCCppEthernetPacketizer.java
  java/src/jmri/jmrix/dccpp/simulator/DCCppSimulatorAdapter.java
  java/src/jmri/jmrix/dccpp/simulator/configurexml/ConnectionConfigXml.java
  java/src/jmri/jmrix/easydcc/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/loconet/LnDeferProgrammer.java
  java/test/jmri/ProgrammerScaffold.java
  java/test/jmri/jmrix/AbstractConnectionConfigTestBase.java
  java/test/jmri/jmrix/AbstractProgrammerTest.java
  java/test/jmri/jmrix/dccpp/DCCppStreamConnectionConfigTest.java
  java/test/jmri/jmrix/dccpp/dccppovertcp/ConnectionConfigTest.java
  java/test/jmri/jmrix/dccpp/network/ConnectionConfigTest.java
  java/test/jmri/jmrix/dccpp/serial/ConnectionConfigTest.java
  java/test/jmri/jmrix/dccpp/simulator/ConnectionConfigTest.java
Labels: Needs L10N

#9467 Warrant spotbugs
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/logix/SCWarrant.java
  java/test/jmri/jmrit/logix/EngineerTest.java
  java/test/jmri/jmrit/logix/LearnControlPanelTest.java
  java/test/jmri/jmrit/logix/LearnSpeedPanelTest.java
  java/test/jmri/jmrit/logix/LearnThrottleFrameTest.java
  java/test/jmri/jmrit/logix/LearnWarrantTest.java
  java/test/jmri/jmrit/logix/LinkedWarrantTest.java
  java/test/jmri/jmrit/logix/LogixActionTest.java
  java/test/jmri/jmrit/logix/NXFrameTest.java
  java/test/jmri/jmrit/logix/PortalManagerTest.java
  java/test/jmri/jmrit/logix/PortalTest.java
  java/test/jmri/jmrit/logix/RampDataTest.java
  java/test/jmri/jmrit/logix/SCWarrantTest.java
  java/test/jmri/jmrit/logix/SchemaTest.java
  java/test/jmri/jmrit/logix/SpeedUtilTest.java
  java/test/jmri/jmrit/logix/TrackerTableActionTest.java
  java/test/jmri/jmrit/logix/TrackerTest.java
  java/test/jmri/jmrit/logix/WarrantFrameTest.java
  java/test/jmri/jmrit/logix/WarrantManagerTest.java
  java/test/jmri/jmrit/logix/WarrantPreferencesPanelTest.java
  java/test/jmri/jmrit/logix/WarrantShutdownTaskTest.java
  java/test/jmri/jmrit/logix/WarrantTableActionTest.java
  java/test/jmri/jmrit/logix/WarrantTableFrameTest.java
  java/test/jmri/jmrit/logix/WarrantTableModelTest.java
  java/test/jmri/jmrit/logix/WarrantTest.java
Labels: Cleanup

#9472 Add "All Types" to web tables menu
  help/en/html/web/TablesServlet.shtml
  java/src/jmri/web/servlet/tables/Bundle.properties
  java/src/jmri/web/servlet/tables/TablesServlet.java
  java/test/jmri/web/servlet/tables/BundleTest.java
  web/js/tables.js
  web/servlet/NavBar.html
  web/servlet/NavBar_cs.html
  web/servlet/NavBar_de.html
  web/servlet/NavBar_nl.html
  web/servlet/tables/Tables.html
Labels: Needs L10N

#9461 Create apps/OperationsPro/index.shtml
  help/en/html/apps/OperationsPro/images/opspropulldownrel422.jpg
  help/en/html/apps/OperationsPro/images/temp1
  help/en/html/apps/OperationsPro/index.shtml
Labels: Documentation

#9474 New email address
  help/en/html/doc/Technical/index.shtml
  help/fr/html/doc/Technical/index.shtml
Labels: Documentation

#9483 Fix bug with operations automation run switch list changes
  java/src/jmri/jmrit/operations/automation/actions/RunSwitchListChangesAction.java
  java/src/jmri/jmrit/operations/automation/actions/RunTrainAction.java
  java/src/jmri/jmrit/operations/automation/actions/TerminateTrainAction.java
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/excel/TrainCustomCommon.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
Labels: Add to Next Test Release

#9482 PanelPro Menu Reorg - Phase 1
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/apps/Apps.java
  java/src/apps/AppsLaunchFrame.java
  java/src/apps/AppsMainMenu.java
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/configurexml/Bundle.properties
  java/src/jmri/configurexml/ConfigureXmlStartupActionFactory.java
  java/src/jmri/configurexml/LoadXmlConfigAction.java
  java/src/jmri/configurexml/LoadXmlUserAction.java
  java/src/jmri/configurexml/StoreMenu.java
  java/src/jmri/configurexml/StoreXmlUserAction.java
  java/src/jmri/jmrit/automat/monitor/AutomatTableBundle.properties
  java/src/jmri/jmrit/display/DisplayBundle.properties
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/EditorManager.java
  java/src/jmri/jmrit/display/PanelDeleteAction.java
  java/src/jmri/jmrit/display/PanelMenu.java
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/panelEditor/PanelEditor.java
  java/src/jmri/jmrit/display/switchboardEditor/SwitchboardEditor.java
  java/src/jmri/jmrit/jython/JythonBundle.properties
  java/test/apps/AppsMainMenuTest.java
  java/test/jmri/jmrit/display/EditorFrameOperator.java
  java/test/jmri/jmrit/display/PanelDeleteActionTest.java
Labels: Needs L10N

#9489 Zimo Swiss Mapping
  xml/decoders/zimo/CVSwissMapping_v36.xml
  xml/decoders/zimo/Choice-M-key_v34.xml
  xml/decoders/zimo/PaneInputMapping.xml
  xml/decoders/zimo/PaneSwissMapping_v36.xml
Labels: Enhancement

#9488 Fix up new OperationsPro/index, add links, etc
  help/en/JmriHelp_enIndex.xml
  help/en/JmriHelp_enTOC.xml
  help/en/html/FAQ.shtml
  help/en/html/apps/OperationsPro/images/OpsProPulldownRel422.jpg
  help/en/html/apps/OperationsPro/images/opspropulldownrel422.jpg
  help/en/html/apps/OperationsPro/images/temp1
  help/en/html/apps/OperationsPro/index.shtml
  help/en/html/apps/index.shtml
  help/en/html/tools/index.shtml
  help/en/html/web/Operations.shtml
  help/en/parts/SidebarApplications.shtml
Labels: Documentation

#9494 Fix GUI to allow user to change set out and pick up comment header text
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/schedules/LocationTrackPair.java
  java/src/jmri/jmrit/operations/locations/schedules/ScheduleManager.java
  java/src/jmri/jmrit/operations/locations/schedules/SchedulesTableModel.java
  java/src/jmri/jmrit/operations/locations/tools/ExportLocations.java
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsAction.java
  java/src/jmri/jmrit/operations/setup/OptionPanel.java
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/jmrit/operations/trains/TrainEditBuildOptionsFrame.java
  java/test/jmri/jmrit/operations/locations/schedules/LocationTrackPairTest.java
  java/test/jmri/jmrit/operations/locations/schedules/ScheduleManagerTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderGuiTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainSwitchListsTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
  java/test/jmri/jmrit/operations/trains/XmlTest.java
Labels: Add to Next Test Release, Needs L10N

#9505 LogixNG - Update release notes
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/apps/Apps.java
  java/src/jmri/configurexml/LoadXmlConfigAction.java
  release.properties
Labels: Needs L10N

#9507 PanelPro Menu Reorg - Phase 2a
  help/en/releasenotes/current-draft-note.shtml
  java/acceptancetest/features/web/WebPanel.feature
  java/acceptancetest/features/web/WebServer.feature
  java/acceptancetest/features/web/WebTable.feature
  java/acceptancetest/features/web/WebTableClick.feature
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/configurexml/LoadXmlConfigAction.java
  java/src/jmri/jmrit/display/DisplayBundle.properties
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/EditorManager.java
  java/test/jmri/jmrit/display/EditorFrameOperator.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorTest.java
  java/test/jmri/jmrit/entryexit/AddEntryExitPairPanelTest.java
  java/test/jmri/jmrit/entryexit/EntryExitPairsTest.java
  java/test/jmri/util/JUnitUtil.java
Labels: Needs L10N

#9514 SPROG Throttle Slots
  java/src/jmri/jmrix/sprog/SprogBundle.properties
  java/src/jmri/jmrix/sprog/SprogCSThrottle.java
  java/src/jmri/jmrix/sprog/SprogCommandStation.java
  java/src/jmri/jmrix/sprog/SprogConstants.java
  java/src/jmri/jmrix/sprog/SprogSlot.java
  java/src/jmri/jmrix/sprog/SprogSystemConnectionMemo.java
  java/src/jmri/jmrix/sprog/serialdriver/SerialDriverAdapter.java
  java/src/jmri/jmrix/sprog/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/sprog/sprogCS/SprogCSSerialDriverAdapter.java
  java/src/jmri/jmrix/sprog/sprogslotmon/SprogSlotMonAction.java
  java/src/jmri/jmrix/sprog/sprogslotmon/SprogSlotMonDataModel.java
  java/src/jmri/jmrix/sprog/sprogslotmon/SprogSlotMonFrame.java
  java/test/jmri/jmrix/sprog/sprogslotmon/SprogSlotMonDataModelTest.java
Labels: Needs L10N

#9512 LightTableAction refactor
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BeanTableDataModel.java
  java/src/jmri/jmrit/beantable/LRouteTableAction.java
  java/src/jmri/jmrit/beantable/LightTableAction.java
  java/src/jmri/jmrit/beantable/LogixTableAction.java
  java/src/jmri/jmrit/beantable/SignalGroupTableAction.java
  java/src/jmri/jmrit/beantable/beanedit/BeanEditAction.java
  java/src/jmri/jmrit/beantable/beanedit/BeanItemPanel.java
  java/src/jmri/jmrit/beantable/beanedit/LightEditAction.java
  java/src/jmri/jmrit/beantable/light/AddEditSingleLightControlFrame.java
  java/src/jmri/jmrit/beantable/light/Bundle.java
  java/src/jmri/jmrit/beantable/light/LightControlPane.java
  java/src/jmri/jmrit/beantable/light/LightControlTableModel.java
  java/src/jmri/jmrit/beantable/light/LightIntensityPane.java
  java/src/jmri/jmrit/beantable/light/LightTableDataModel.java
  java/test/jmri/jmrit/beantable/AbstractBeanTableDataModelBase.java
  java/test/jmri/jmrit/beantable/LightTableActionTest.java
  java/test/jmri/jmrit/beantable/beanedit/LightEditActionTest.java
  java/test/jmri/jmrit/beantable/light/AddEditSingleLightControlFrameTest.java
  java/test/jmri/jmrit/beantable/light/BundleTest.java
  java/test/jmri/jmrit/beantable/light/LightControlPaneTest.java
  java/test/jmri/jmrit/beantable/light/LightControlTableModelTest.java
  java/test/jmri/jmrit/beantable/light/LightIntensityPaneTest.java
  java/test/jmri/jmrit/beantable/light/LightTableDataModelTest.java
Labels: Needs L10N

#9518 Minor text change to operations GUI
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
Labels: Add to Next Test Release, Needs L10N

#9522 PanelPro Menu Reorg - Phase 3
  help/en/html/FAQ.shtml
  help/en/html/apps/DataManagement.shtml
  help/en/html/apps/DispatcherSystem/DispatcherSystem.shtml
  help/en/html/apps/LoadStoreWork.shtml
  help/en/html/apps/PanelPro/FAQ.shtml
  help/en/html/apps/PanelPro/GettingStarted.shtml
  help/en/html/apps/PanelPro/ShowPanel.shtml
  help/en/html/apps/PanelPro/SidebarAppLocalPart.shtml
  help/en/html/apps/PanelPro/index.shtml
  help/en/html/apps/StoringYourWork.shtml
  help/en/html/doc/Technical/Help.shtml
  help/en/html/doc/Technical/I8N.shtml
  help/en/html/hardware/loconet/Addressing.shtml
  help/en/html/scripthelp/yaat/YAAT.shtml
  help/en/html/tools/Blocks.shtml
  help/en/html/tools/IdTags.shtml
  help/en/html/tools/LRoutes.shtml
  help/en/html/tools/Lights.shtml
  help/en/html/tools/Logix.shtml
  help/en/html/tools/Memories.shtml
  help/en/html/tools/Reporters.shtml
  help/en/html/tools/Routes.shtml
  help/en/html/tools/Sections.shtml
  help/en/html/tools/Sensors.shtml
  help/en/html/tools/Transits.shtml
  help/en/html/tools/Turnouts.shtml
  help/en/html/tools/automation/viaJava.shtml
  help/en/html/tools/index.shtml
  help/en/html/tools/scripting/Examples.shtml
  help/en/html/tools/scripting/HowTo.shtml
  help/en/html/tools/scripting/Start.shtml
  help/en/html/tools/scripting/index.shtml
  help/en/html/tools/signaling/SignalGroups.shtml
  help/en/html/tools/signaling/SignalHeads.shtml
  help/en/html/tools/signaling/SignalMasts.shtml
  help/en/html/tools/signaling/SimpleSignalExample.shtml
  help/en/package/apps/TabbedPreferences.shtml
  help/en/package/jmri/jmrit/beantable/LightTable.shtml
  help/en/package/jmri/jmrit/beantable/LogixTable.shtml
  help/en/package/jmri/jmrit/beantable/RouteAddEdit.shtml
  help/en/package/jmri/jmrit/beantable/SectionTable.shtml
  help/en/package/jmri/jmrit/beantable/SignalHeadTable.shtml
  help/en/package/jmri/jmrit/beantable/SignalMastRepeater.shtml
  help/en/package/jmri/jmrit/beantable/SignalMastTable.shtml
  help/en/package/jmri/jmrit/beantable/TransitTable.shtml
  help/en/package/jmri/jmrit/blockboss/BlockBossFrame.shtml
  help/en/package/jmri/jmrit/ctc/CTC.shtml
  help/en/package/jmri/jmrit/display/ControlPanelEditor.shtml
  help/en/package/jmri/jmrit/display/LayoutEditor.shtml
  help/en/package/jmri/jmrit/display/PanelEditor.shtml
  help/en/package/jmri/jmrit/display/PanelMenuHelp.shtml
  help/en/package/jmri/jmrit/display/PanelTarget.shtml
  help/en/package/jmri/jmrit/display/SwitchboardEditor.shtml
  help/en/package/jmri/jmrit/simpleclock/SimpleClockFrame.shtml
  help/en/package/jmri/jmrit/vsdecoder/swing/ManageLocationsFrame.shtml
Labels: Documentation

#9531 Fix staging custom load generation for cabooses and FRED to spurs
  help/en/package/jmri/jmrix/nce/packetgen/NcePacketGenFrame.shtml
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
Labels: Add to Next Test Release, Needs L10N

#9532 Sensor / Turnout Tables, Forget / Query Column headings
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_ca.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_nl.properties
  java/src/jmri/jmrit/beantable/beanedit/LightEditAction.java
  java/src/jmri/jmrit/beantable/sensor/SensorTableDataModel.java
  java/src/jmri/jmrit/beantable/turnout/TurnoutTableDataModel.java
Labels: Needs L10N

#9536 Roster Entry Copy
  java/src/jmri/jmrit/roster/AbstractRosterItemAction.java
  java/src/jmri/jmrit/roster/JmritRosterBundle.properties
  java/src/jmri/jmrit/roster/JmritRosterBundle_nl.properties
Labels: Needs L10N

#9538 Fix automation for run excel for train to correctly report failure
  java/src/jmri/jmrit/operations/automation/actions/RunSwitchListChangesAction.java
  java/src/jmri/jmrit/operations/automation/actions/RunTrainAction.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchListEditFrame.java
  java/src/jmri/jmrit/operations/trains/TrainsTableFrame.java
  java/src/jmri/jmrit/operations/trains/excel/TrainCustomCommon.java
  java/src/jmri/jmrit/operations/trains/schedules/TrainsScheduleTableFrame.java
Labels: Add to Next Test Release

#9547 Fix operations automation race condition
  java/src/jmri/jmrit/operations/automation/actions/RunSwitchListChangesAction.java
  java/src/jmri/jmrit/operations/automation/actions/RunTrainAction.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchListEditFrame.java
  java/src/jmri/jmrit/operations/trains/TrainsTableFrame.java
  java/src/jmri/jmrit/operations/trains/excel/TrainCustomCommon.java
  java/src/jmri/jmrit/operations/trains/schedules/TrainsScheduleTableFrame.java
  java/test/jmri/jmrit/operations/trains/TrainCsvManifestTest.java
Labels: Add to Next Test Release

#9545 Beantables New Bean Frames - Escape to exit / Default button
  java/src/jmri/jmrit/beantable/AddNewBeanPanel.java
  java/src/jmri/jmrit/beantable/AudioTableAction.java
  java/src/jmri/jmrit/beantable/IdTagTableAction.java
  java/src/jmri/jmrit/beantable/LRouteTableAction.java
  java/src/jmri/jmrit/beantable/LightTableAction.java
  java/src/jmri/jmrit/beantable/LogixTableAction.java
  java/src/jmri/jmrit/beantable/MemoryTableAction.java
  java/src/jmri/jmrit/beantable/OBlockTableAction.java
  java/src/jmri/jmrit/beantable/ReporterTableAction.java
  java/src/jmri/jmrit/beantable/RouteTableAction.java
  java/src/jmri/jmrit/beantable/SectionTableAction.java
  java/src/jmri/jmrit/beantable/SensorTableAction.java
  java/src/jmri/jmrit/beantable/SignalGroupTableAction.java
  java/src/jmri/jmrit/beantable/SignalHeadTableAction.java
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/beantable/TurnoutTableAction.java
  java/src/jmri/jmrit/beantable/oblock/PortalEditFrame.java
  java/src/jmri/jmrit/beantable/oblock/SignalEditFrame.java
  java/src/jmri/jmrit/beantable/signalmast/AddSignalMastJFrame.java
  java/src/jmri/jmrit/signalling/SignallingBundle.properties
  java/src/jmri/jmrit/signalling/SignallingBundle_en_GB.properties
  java/test/jmri/jmrit/beantable/AbstractTableActionBase.java
  java/test/jmri/jmrit/beantable/IdTagTableActionTest.java
  java/test/jmri/jmrit/beantable/LightTableWindowTest.java
  java/test/jmri/jmrit/beantable/SensorTableWindowTest.java
  java/test/jmri/jmrit/picker/PickFrameTest.java
  java/test/jmri/jmrit/picker/PickSinglePanelTest.java
Labels: Needs L10N

#9565 Add a `New PR` label to new PRs and removes once 1 day old
  .github/mergeable.yml
Labels: Developer, dev/test/publish infrastructure

#9563 Update LoadStoreWork.shtml
  help/en/html/apps/LoadStoreWork.shtml
Labels: Documentation

#9568 Sensor_Scan.py use Invert flag when setting Sensor state
  jython/serialinput/Sensor_Channel_To_JMRI/Sensor_Scan.py
Labels: New PR

#9576 Fix ImportExpressionClockTest
  java/test/jmri/jmrit/logixng/tools/ImportExpressionClockTest.java
Labels: New PR

#9572 Update the SSL Tool
  help/en/images/SslExample.png
  help/en/package/jmri/jmrit/blockboss/BlockBossFrame.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/AppsMainMenu.java
  java/src/jmri/jmrit/automat/Siglet.java
  java/src/jmri/jmrit/blockboss/BlockBossBundle.properties
  java/src/jmri/jmrit/blockboss/BlockBossFrame.java
  java/src/jmri/jmrit/blockboss/configurexml/BlockBossLogicProviderXml.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorTools.java
  java/test/jmri/jmrit/automat/SigletTest.java
  java/test/jmri/jmrit/blockboss/BlockBossFrameTest.java
Labels: Needs L10N

#9582 IconAdder - Fix Create New Bean Exception
  java/src/jmri/jmrit/display/DisplayBundle.properties
  java/src/jmri/jmrit/display/DisplayBundle_ca.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_da.properties
  java/src/jmri/jmrit/display/DisplayBundle_de.properties
  java/src/jmri/jmrit/display/DisplayBundle_fr.properties
  java/src/jmri/jmrit/display/DisplayBundle_it.properties
  java/src/jmri/jmrit/display/DisplayBundle_ja_JP.properties
  java/src/jmri/jmrit/display/DisplayBundle_nl.properties
  java/src/jmri/jmrit/display/IconAdder.java
  java/src/jmri/jmrit/picker/PickListModel.java
  java/src/jmri/jmrit/picker/PickSinglePanel.java
Labels: Needs L10N

#9575 Throttles evols & restore RailDriver Java code
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/throttle/FunctionButton.java
  java/src/jmri/jmrit/throttle/FunctionButtonPropertyEditor.java
  java/src/jmri/jmrit/throttle/FunctionPanel.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
  java/src/jmri/util/usb/RailDriverMenuItem.java
  java/test/jmri/jmrit/roster/ACL1012-DTD.xml
  java/test/jmri/jmrit/roster/ACL1012-Schema.xml
  java/test/jmri/util/usb/RailDriverMenuItemTest.java
Labels: Needs L10N

#9583 CbusLight - Tweak entry ToolTip
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusLightManager.java
Labels: Needs L10N

#9595 Update template shtml files to use style include
  help/en/TemplateBar.shtml
  help/en/TemplatePlain.shtml
Labels: Documentation

#9596 Throttles keyboard controls preferences
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/throttle/AddressPanel.java
  java/src/jmri/jmrit/throttle/BackgroundPanel.java
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/ControlPanelCustomSliderUI.java
  java/src/jmri/jmrit/throttle/ControlPanelPropertyEditor.java
  java/src/jmri/jmrit/throttle/FunctionButton.java
  java/src/jmri/jmrit/throttle/FunctionPanel.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
  java/src/jmri/jmrit/throttle/ThrottleFrame.java
  java/src/jmri/jmrit/throttle/ThrottleFrameManager.java
  java/src/jmri/jmrit/throttle/ThrottleWindow.java
  java/src/jmri/jmrit/throttle/ThrottleWindowInputsListener.java
  java/src/jmri/jmrit/throttle/ThrottleWindowKeyboardControls.java
  java/src/jmri/jmrit/throttle/ThrottlesListPanel.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferences.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesControlsSettingsPane.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesPane.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesUISettingsPane.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesWindow.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesWindowKeyboardControls.java
  java/src/jmri/jmrit/throttle/ThrottlesTableCellRenderer.java
  java/src/jmri/jmrit/throttle/ThrottlesTableModel.java
  java/test/jmri/jmrit/throttle/ControlPanelTest.java
  java/test/jmri/jmrit/throttle/ThrottlesPreferencesWindowTest.java
Labels: Needs L10N

#9599 Fix bug when importing Logix to LogixNG
  java/src/jmri/jmrit/logixng/tools/ImportConditional.java
  java/src/jmri/jmrit/logixng/util/UtilBundle.properties
  java/test/jmri/jmrit/logixng/actions/ExecuteDelayedTest.java
Labels: Needs L10N

#9603 Add Not expression. Fix bug in ImportConditional
  java/src/jmri/jmrit/logixng/MaleSocket.java
  java/src/jmri/jmrit/logixng/expressions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionLocalVariable.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionMemory.java
  java/src/jmri/jmrit/logixng/expressions/Not.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/NotXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionLocalVariableSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionMemorySwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/NotSwing.java
  java/src/jmri/jmrit/logixng/implementation/AbstractMaleSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultClipboard.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleAnalogActionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleAnalogExpressionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleDigitalActionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleDigitalBooleanActionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleDigitalExpressionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleStringActionSocket.java
  java/src/jmri/jmrit/logixng/implementation/DefaultMaleStringExpressionSocket.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultAnalogActionManagerXml.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultAnalogExpressionManagerXml.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultDigitalActionManagerXml.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultDigitalBooleanActionManagerXml.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultDigitalExpressionManagerXml.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultMaleDigitalExpressionSocketXml.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultStringActionManagerXml.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultStringExpressionManagerXml.java
  java/src/jmri/jmrit/logixng/implementation/swing/AbstractMaleSocketSwing.java
  java/src/jmri/jmrit/logixng/implementation/swing/DefaultMaleDigitalExpressionSocketSwing.java
  java/src/jmri/jmrit/logixng/implementation/swing/ImplementationSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/ImportConditional.java
  java/src/jmri/jmrit/logixng/tools/debugger/AbstractDebuggerMaleSocket.java
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerMaleAnalogActionSocket.java
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerMaleAnalogExpressionSocket.java
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerMaleDigitalActionSocket.java
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerMaleDigitalBooleanActionSocket.java
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerMaleDigitalExpressionSocket.java
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerMaleStringActionSocket.java
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerMaleStringExpressionSocket.java
  java/src/jmri/jmrit/logixng/tools/swing/ModuleEditorMaleSocket.java
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
  java/test/jmri/jmrit/logixng/FemaleSocketTestBase.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/expressions/NotTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalExpressionSocketTest.java
  xml/schema/logixng/digital-expressions/digital-expressions-4.23.1.xsd
  xml/schema/logixng/digital-expressions/not-4.23.3.xsd
  xml/schema/logixng/male-socket-4.23.1.xsd
Labels: Needs L10N

#9586 Allow streaming sound to loop
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/Sound.java
Labels: New PR

#9614 Fnc images
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/roster/FunctionLabelPane.java
  java/src/jmri/jmrit/roster/JmritRosterBundle.properties
  java/src/jmri/jmrit/roster/JmritRosterBundle_fr.properties
  java/src/jmri/jmrit/throttle/FunctionButtonPropertyEditor.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
  java/src/jmri/util/swing/EditableResizableImagePanel.java
Labels: Needs L10N

#9619 Add info about mosquitto v2 to MQTT/index.shtml
  help/en/html/hardware/mqtt/index.shtml
Labels: Documentation

#9626 More selective rule for adding documentation label
  .github/mergeable.yml
Labels: New PR

#9625 Adds OpenLCB updates to the current draft release notes
  help/en/releasenotes/current-draft-note.shtml
Labels: New PR

#9620 Update openlcb library to 0.7.28
  java/src/jmri/jmrix/openlcb/OlcbSignalMast.java
  java/src/jmri/jmrix/openlcb/swing/send/OpenLcbCanSendPane.java
  java/test/jmri/jmrix/openlcb/OlcbSignalMastTest.java
  lib/README.md
  lib/openlcb.jar
  pom.xml
Labels: New PR

#9623 fix: DCC-EX startVal support should start at 3.0.0
  java/src/jmri/jmrix/dccpp/DCCppCommandStation.java
  java/test/jmri/jmrix/dccpp/DCCppProgrammerTest.java
Labels: New PR

#9622 Add script BXPA1 Autoreverse msg to Sensor
  help/en/releasenotes/current-draft-note.shtml
  jython/SensorFromBxpa1AutoRev.py
Labels: Documentation, Enhancement, New PR, javascript
