Repository JMRI/JMRI, pull requests merged in 2022-03, with the labels that each got.

#10763 Threewayturnouticon on webserver fix
  web/js/panel.js
Labels: Bug

#10765 IntelliJ Java11 configuration
  .idea/JMRI.iml
  .idea/ant.xml
  .idea/checkstyle-idea.xml
  .idea/codeStyleSettings.xml
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  help/en/html/doc/Technical/IntelliJ.shtml
  help/en/html/doc/Technical/images/IntelliJ/IjAntBuildFilePropertiesPane.png
  help/en/html/doc/Technical/images/IntelliJ/IjAntErrorDialog.png
  help/en/html/doc/Technical/images/IntelliJ/IjPlatformDownloadJdk.png
  help/en/html/doc/Technical/images/IntelliJ/IjPlatformSettings.png
  help/en/html/doc/Technical/images/IntelliJ/IjPrefsAddGithub.png
  help/en/html/doc/Technical/images/IntelliJ/IjPrefsGitHubLogin.png
  help/en/html/doc/Technical/images/IntelliJ/IjPrefsGitLogin.png
  help/en/html/doc/Technical/images/IntelliJ/IjPrefsJava11.png
  help/en/html/doc/Technical/images/IntelliJ/IjPrefsJava18.png
  help/en/html/doc/Technical/images/IntelliJ/IjProjectSettingsSdk.png
  help/en/html/doc/Technical/images/IntelliJ/IjProjectSettingsSdkDropdown.png
Labels: Documentation

#10772 Tech doc responsive
  help/en/html/doc/Technical/Ant.shtml
  help/en/html/doc/Technical/AppPreferences.shtml
  help/en/html/doc/Technical/AppPreferences.txt
  help/en/html/doc/Technical/ContinuousIntegration.shtml
  help/en/html/doc/Technical/Eclipse.shtml
  help/en/html/doc/Technical/GitFAQ.shtml
  help/en/html/doc/Technical/I8N.shtml
  help/en/html/doc/Technical/IntelliJ.shtml
  help/en/html/doc/Technical/IntroStructure.shtml
  help/en/html/doc/Technical/JUnit.shtml
  help/en/html/doc/Technical/Names.shtml
  help/en/html/doc/Technical/NetBeans.shtml
  help/en/html/doc/Technical/Swing.shtml
  help/en/html/doc/Technical/UpdatingDocs.shtml
  help/en/html/doc/Technical/XmlView.shtml
  help/en/html/doc/Technical/getgitcode.shtml
  help/en/html/doc/Technical/githubdesktopintro.shtml
  help/en/html/doc/Technical/images/IntelliJ/IjVMOptionsMenu.png
  help/en/html/doc/Technical/logixng/Tutorial/LogixNG.shtml
  help/en/html/doc/Technical/plugins.shtml
  help/fr/html/doc/Technical/Eclipse.shtml
Labels: Documentation

#10776 Catch Illegal Argument Exception when user enters improper format.
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/Train.java
Labels: Add to Next Test Release, Documentation

#10780 Copy an existing Route when creating a new Route
  help/en/html/tools/Routes.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/routetable/AbstractRouteAddEditFrame.java
  java/src/jmri/jmrit/beantable/routetable/RouteAddFrame.java
  java/src/jmri/jmrit/beantable/routetable/RouteEditFrame.java
Labels: Documentation, Needs L10N

#10784 Tech doc
  help/en/html/doc/Technical/IntelliJ.shtml
  help/en/html/doc/Technical/SpotBugs.shtml
  help/en/html/doc/Technical/TechRoadMap.shtml
  help/en/html/doc/Technical/githubdesktopintro.shtml
  help/en/html/doc/Technical/images/IntelliJ/IjAntBuildFilePropertiesPane.png
  help/en/html/doc/Technical/images/IntelliJ/IjDebugPrefs.png
  help/en/html/doc/Technical/plugins.shtml
  help/en/manual/DecoderPro/Main_CMRI.shtml
  help/en/manual/DecoderPro3/Main_CMRI.shtml
Labels: Documentation

#10785 Fix operation scripts to use KernelManager
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineManager.java
  jython/operations/OperationsAssignUnitsToFlatcars.py
  jython/operations/OperationsRemoveCarKernels.py
Labels: Add to Next Test Release

#10786 Initial support for KPF-Zeller speedometer
  help/en/Acknowledgements.shtml
  help/en/html/hardware/bachrus/index.shtml
  help/en/html/hardware/index.shtml
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/jmri4.99-master.shtml
  java/src/jmri/jmrix/bachrus/BachrusBundle.properties
  java/src/jmri/jmrix/bachrus/KPFConnectionTypeList.java
  java/src/jmri/jmrix/bachrus/SpeedoConsoleFrame.java
  java/src/jmri/jmrix/bachrus/SpeedoReply.java
  java/src/jmri/jmrix/bachrus/kpfserialdriver/Bundle.java
  java/src/jmri/jmrix/bachrus/kpfserialdriver/COPYING
  java/src/jmri/jmrix/bachrus/kpfserialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/bachrus/kpfserialdriver/SerialDriverAdapter.java
  java/src/jmri/jmrix/bachrus/kpfserialdriver/configurexml/COPYING
  java/src/jmri/jmrix/bachrus/kpfserialdriver/configurexml/ConnectionConfigXml.java
  java/src/jmri/jmrix/bachrus/package-info.java
  java/test/jmri/jmrix/bachrus/SpeedoReplyTest.java
Labels: Needs L10N

#10789 Improve & declutter LokProgrammer Import log.
  java/src/jmri/jmrit/symbolicprog/LokProgImporter.java
Labels: Enhancement, Cleanup

#10793 Logix copy: replace text system name field with editable combo box
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/LogixTableAction.java
Labels: Needs L10N

#10800 Improve Zeller speedometer support
  java/src/jmri/jmrix/bachrus/BachrusBundle.properties
  java/src/jmri/jmrix/bachrus/BachrusBundle_fr.properties
  java/src/jmri/jmrix/bachrus/BachrusBundle_it.properties
  java/src/jmri/jmrix/bachrus/DccSpeedProfile.java
  java/src/jmri/jmrix/bachrus/SpeedoConsoleFrame.java
  java/src/jmri/jmrix/bachrus/kpfserialdriver/package-info.java
Labels: Needs L10N

#10799 Add a Copy Stops button for new trains
  help/en/html/tools/TimeTable.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/routetable/RouteAddFrame.java
  java/src/jmri/jmrit/timetable/TimeTableBundle.properties
  java/src/jmri/jmrit/timetable/swing/TimeTableFrame.java
  java/src/jmri/jmrit/timetable/swing/TimeTableGraphCommon.java
Labels: Documentation, Needs L10N

#10801 Update XmlView help, fix broken link
  help/en/html/doc/Technical/XmlView.shtml
  xml/samples/TwoColumnMachine.xml
Labels: Documentation

#10806 Remove store only tables option; don't load panels when running JmriFaceless
  help/en/html/apps/DataManagement.shtml
  help/en/html/apps/LoadStoreWork.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/configurexml/StoreMenu.java
  java/src/jmri/jmrit/display/controlPanelEditor/configurexml/ControlPanelEditorXml.java
  java/src/jmri/jmrit/display/layoutEditor/configurexml/LayoutEditorXml.java
  java/src/jmri/jmrit/display/panelEditor/configurexml/PanelEditorXml.java
  java/src/jmri/jmrit/display/switchboardEditor/configurexml/SwitchboardEditorXml.java
Labels: Documentation

#10807 fix numbering on startup-scripts web page
  help/en/html/doc/Technical/StartUpScripts.shtml
Labels: Documentation

#10808 Minor improvement to operations help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Add to Next Test Release, Documentation

#10811 Add transits and sections to scripting shortcuts.
  help/en/html/tools/scripting/Start.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/script/JmriScriptEngineManager.java
Labels: Documentation, New PR

#10812 Implement a viewOnly attribute for the pane 'display' element.
  help/en/html/apps/DecoderPro/Programmer.shtml
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgPane.java
  xml/decoders/ESU_SwitchPilot.xml
  xml/schema/types/panetype.xsd
Labels: Enhancement, Add to Next Test Release, Documentation, New PR

#10816 Fix router bug through staging
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle.properties
  java/src/jmri/jmrit/operations/router/Router.java
Labels: Add to Next Test Release, Needs L10N

#10817 Fix NPEs
  java/src/jmri/jmrit/operations/trains/tools/ExportTimetable.java
Labels: Add to Next Test Release

#10819 Change operations schedule max wait from 10 to 100
  java/src/jmri/jmrit/operations/locations/schedules/ScheduleTableModel.java
Labels: Add to Next Test Release

#10822 Check help files for UTF-8 characters
  help/en/Acknowledgements.shtml
  help/en/glossary/index.shtml
  help/en/html/apps/DataManagement.shtml
  help/en/html/apps/DecoderPro/CreateDecoder.shtml
  help/en/html/apps/DecoderPro/CreateDecoderAdvanced.shtml
  help/en/html/apps/OperationsPro/index.shtml
  help/en/html/apps/PanelPro/GettingStarted.shtml
  help/en/html/apps/index.shtml
  help/en/html/doc/Technical/NetBeans.shtml
  help/en/html/hardware/SRCP/index.shtml
  help/en/html/hardware/cmri/CMRI.shtml
  help/en/html/hardware/index.shtml
  help/en/html/hardware/jmriclient/index.shtml
  help/en/html/hardware/loconet/CommandStationConfig.shtml
  help/en/html/hardware/loconet/LocoNetServer.shtml
  help/en/html/hardware/loconet/LocoNetSim.shtml
  help/en/html/hardware/loconet/LocoNetTools.shtml
  help/en/html/hardware/loconet/StandaloneLocoNet.shtml
  help/en/html/hardware/loconet/Uhlenbrock.shtml
  help/en/html/hardware/marklin/index.shtml
  help/en/html/hardware/tams/index.shtml
  help/en/html/scripthelp/DispatcherSystem/DispatcherSystem.shtml
  help/en/html/scripthelp/yaat/YAAT.shtml
  help/en/html/setup/Dropbox.shtml
  help/en/html/tools/EntryExit.shtml
  help/en/html/tools/Logix.shtml
  help/en/html/tools/TimeTable.shtml
  help/en/html/tools/Transits.shtml
  help/en/html/tools/consisttool/ConsistTool.shtml
  help/en/html/tools/fastclock/index.shtml
  help/en/html/tools/index.shtml
  help/en/html/tools/scripting/HowTo.shtml
  help/en/html/web/JsonServlet.shtml
  help/en/html/web/Operations.shtml
  help/en/html/web/XMLIO.shtml
  help/en/html/web/index.shtml
  help/en/manual/DecoderPro/Basic_BasicPane.shtml
  help/en/manual/DecoderPro/Main_Throttle_menubar.shtml
  help/en/manual/DecoderPro/Start_Preferences.shtml
  help/en/manual/DecoderPro/index.shtml
  help/en/manual/DecoderPro3/Start_Preferences.shtml
  help/en/manual/DecoderPro3/dp3_Main_Throttle_menubar.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Installing_JMRI.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Settings.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Trains.shtml
  help/en/manual/JMRI_OPS_UsersGuide/index.shtml
  help/en/manual/index.shtml
  help/en/package/apps/TabbedPreferences.shtml
  help/en/package/jmri/jmrit/conditional/ConditionalTreeEditor.shtml
  help/en/package/jmri/jmrit/display/LayoutEditor.shtml
  help/en/package/jmri/jmrit/display/SwitchboardEditor.shtml
  help/en/package/jmri/jmrit/entryexit/EntryExitFrame.shtml
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrix/marklin/swing/packetgen/PacketGenFrame.shtml
  java/test/jmri/util/CheckHelpFilesForUTF8Test.java
Labels: Documentation

#10823 Allow user to add schedule item to middle of a schedule.
  java/src/jmri/jmrit/operations/locations/schedules/Schedule.java
  java/src/jmri/jmrit/operations/locations/schedules/ScheduleEditFrame.java
Labels: Add to Next Test Release

#10833 Improve train building when using aggressive mode
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
Labels: Add to Next Test Release, Needs L10N

#10821 VSDecoder: location following based on LE Train Simulator
  help/en/manual/DecoderPro/Main_VSD.shtml
  help/en/manual/DecoderPro/VSD_File_and_Config.shtml
  help/en/manual/DecoderPro/VSD_Headless.shtml
  help/en/manual/DecoderPro/VSD_LocationsMgr.shtml
  help/en/manual/DecoderPro/VSD_Manager.shtml
  help/en/manual/DecoderPro/images/VSD_Preferences.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/vsdecoder/VSDGeoFile.java
  java/src/jmri/jmrit/vsdecoder/VSDNavigation.java
  java/src/jmri/jmrit/vsdecoder/VSDecoder.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderManager.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderPreferences.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDSwingBundle.properties
  java/src/jmri/jmrit/vsdecoder/swing/VSDecoderPreferencesPane.java
  java/src/jmri/util/MathUtil.java
  java/test/jmri/jmrit/vsdecoder/VSDNavigationTest.java
Labels: Needs L10N

#10843 It's called macOS now
  help/en/html/doc/Technical/JVMCapabilities.shtml
  help/en/html/doc/Technical/JVMCapabilitiesOlder.shtml
  help/en/html/setup/index.shtml
  help/en/manual/DecoderPro/Installing_JMRI.shtml
  help/en/manual/DecoderPro3/Installing_JMRI.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Installing_JMRI.shtml
  help/en/parts/SidebarInstall.shtml
Labels: Documentation
