Repository JMRI/JMRI, pull requests merged in 2022-07, with the labels that each got.

#11145 Update operations help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#11143 Fix file name, spelling, other cleanup MQTT documentation
  help/en/html/hardware/mqtt/images/MQTTSchematic.JPG
  help/en/html/hardware/mqtt/images/MQTTSchematic.jpg
  help/en/html/hardware/mqtt/index.shtml
Labels: Documentation

#11148 Use Throttle.getFunction(int) instead of getF0()
  java/src/jmri/Throttle.java
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/tracker/StoppingBlock.java
  java/src/jmri/jmrit/withrottle/ThrottleController.java
  java/src/jmri/jmrix/AbstractThrottle.java
  java/src/jmri/jmrix/direct/Throttle.java
  java/src/jmri/jmrix/easydcc/EasyDccThrottle.java
  java/src/jmri/jmrix/lenz/XNetThrottle.java
  java/src/jmri/jmrix/loconet/Ib1Throttle.java
  java/src/jmri/jmrix/loconet/Ib2Throttle.java
  java/src/jmri/jmrix/loconet/LocoNetThrottle.java
  java/src/jmri/jmrix/loconet/Pr2Throttle.java
  java/src/jmri/jmrix/loconet/slotmon/SlotMonDataModel.java
  java/src/jmri/jmrix/nce/NceThrottle.java
  java/src/jmri/jmrix/rps/Engine.java
  java/src/jmri/jmrix/sprog/SprogCSThrottle.java
  java/src/jmri/jmrix/sprog/SprogThrottle.java
  java/src/jmri/util/usb/RailDriverMenuItem.java
  java/test/jmri/server/json/throttle/JsonThrottleSocketServiceTest.java
Labels: Cleanup, New PR

#11155 Move panel icons on Windows
  java/src/jmri/util/swing/JmriMouseEvent.java
Labels: Bug

#11161 Check both META_DOWN_MASK and BUTTON3_DOWN_MASK
  java/src/jmri/util/swing/JmriMouseEvent.java
Labels: Bug

#11162 Test Method names, general tweaks
  java/test/jmri/AudioExceptionTest.java
  java/test/jmri/JmriExceptionTest.java
  java/test/jmri/ProgReadExceptionTest.java
  java/test/jmri/ProgWriteExceptionTest.java
  java/test/jmri/ProgrammerExceptionTest.java
  java/test/jmri/ProgrammerScaffold.java
  java/test/jmri/ScaleTest.java
  java/test/jmri/SectionTest.java
  java/test/jmri/TimebaseRateExceptionTest.java
  java/test/jmri/TransitSectionActionTest.java
  java/test/jmri/TransitSectionTest.java
  java/test/jmri/TransitTest.java
  java/test/jmri/implementation/DefaultSectionTest.java
  java/test/jmri/progdebugger/DebugProgrammerTest.java
  java/test/jmri/util/JUnitSwingUtil.java
  java/test/jmri/util/JUnitSwingUtilTest.java
  java/test/jmri/util/MathUtilTest.java
  java/test/jmri/util/StringUtilTest.java
  java/test/jmri/util/swing/JmriColorChooserTest.java
Labels: New PR

#11168 MQTT channel default is now the null string
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/mqtt/Bundle.properties
Labels: Needs L10N

#11170 Fixes and update MQTT documentation for rel 5.1.2
  help/en/html/hardware/mqtt/images/MQTTPrefs_rel5_0.jpg
  help/en/html/hardware/mqtt/index.shtml
Labels: Documentation, New PR

#11171 Czech translation 2022-07-10
  java/src/apps/ActionListBundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/JmritBeantablePhysicalLocationBundle_cs.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_cs.properties
  java/src/jmri/jmrit/logix/WarrantBundle_cs.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrix/JmrixBundle_cs.properties
  web/servlet/Footer_cs.html
  web/servlet/home/Home_cs.html
Labels: Needs L10N

#11178 Correction to CMRI.shtml regarding escape bytes
  help/en/html/hardware/cmri/CMRI.shtml
Labels: Documentation

#11181 Minor operations help update
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Add to Next Test Release, Documentation

#11179 Add LogixNG action SimulateTurnoutFeedback
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/SimulateTurnoutFeedback.java
  java/src/jmri/jmrit/logixng/actions/configurexml/SimulateTurnoutFeedbackXml.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/SimulateTurnoutFeedbackSwing.java
  java/src/jmri/jmrit/logixng/expressions/ConnectionName.java
  java/src/jmri/jmrit/logixng/expressions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/configurexml/ConnectionNameXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/ConnectionNameSwing.java
  java/test/jmri/jmrit/logixng/ActionsAndExpressionsTest.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/SocketOperationTest.java
  java/test/jmri/jmrit/logixng/TestSwingClasses.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalExpressionSocketTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleGenericExpressionSocket1_Test.java
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/simulate-turnout-feedback-5.1.3.xsd
  xml/schema/logixng/digital-expressions/connection-name-5.1.3.xsd
  xml/schema/logixng/digital-expressions/digital-expressions-4.23.1.xsd
Labels: Needs L10N

#11197 Czech translation 2022-07-18
  java/src/apps/util/issuereporter/swing/Bundle_cs.properties
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/configurexml/Bundle_cs.properties
  java/src/jmri/configurexml/swing/Bundle_cs.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/conditional/ConditionalBundle_cs.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_cs.properties
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantBundle_cs.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/UtilBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/LogixNGParserBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/swing/SwingBundle_cs.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_cs.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_cs.properties
  java/src/jmri/jmrit/timetable/TimeTableBundle_cs.properties
  java/src/jmri/jmrit/vsdecoder/swing/VSDSwingBundle_cs.properties
  java/src/jmri/jmrix/dccpp/swing/DCCppSwingBundle_cs.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_cs.properties
  java/src/jmri/jmrix/mqtt/Bundle_cs.properties
  java/src/jmri/script/Bundle_cs.properties
Labels: Needs L10N

#11198 Update LogixNG reference
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_other.png
  help/en/html/tools/logixng/reference/images/chapter6/connection_expression.png
  help/en/html/tools/logixng/reference/images/chapter6/digital_expression_other.png
  java/src/jmri/jmrit/logixng/expressions/swing/ConnectionNameSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
Labels: Documentation, Needs L10N

#11206 Fix Windows CI images on master
  java/test/jmri/jmrit/display/layoutEditor/loadref/windows/Jlang-Panel-4-19-6.xml.1.png
  java/test/jmri/jmrit/display/layoutEditor/loadref/windows/Jlang-Panel-4-19-6.xml.2.png
  java/test/jmri/jmrit/display/layoutEditor/loadref/windows/Sidlo-2020-04-Chotebor.xml.1.png
  java/test/jmri/jmrit/display/layoutEditor/loadref/windows/Sidlo-2020-04-Chotebor.xml.2.png
  java/test/jmri/jmrit/display/layoutEditor/loadref/windows/Sidlo-2020-04-Chotebor.xml.5.png
  java/test/jmri/jmrit/display/layoutEditor/loadref/windows/Sidlo-2020-04-Chotebor.xml.6.png
Labels: New PR

#11202 nx warrant & noRamp option change
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/NXFrame.java
  java/src/jmri/jmrit/logix/RampData.java
  java/src/jmri/jmrit/logix/SpeedUtil.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantTableModel.java
  java/test/jmri/jmrit/logix/RampDataTest.java
  java/test/jmri/jmrit/logix/WarrantTest.java
Labels: Needs L10N

#11216 update Dispatcher LoadAtStartUp Test
  java/test/jmri/jmrit/dispatcher/LoadAtStartUpTest.java
Labels: New PR

#11212 Digikeijs DR5088RC definition
  help/en/html/hardware/digirails/index.shtml
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/LocoNetSim.shtml
  help/en/html/hardware/loconet/LocoNetTools.shtml
  help/en/package/jmri/jmrix/loconet/locoio/LocoIOFrame.shtml
  help/en/package/jmri/jmrix/loconet/swing/lncvprog/LncvProgPane.shtml
  help/en/package/jmri/jmrix/loconet/swing/lncvprog/images/LNCVToolEntry.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/NamedBeanBundle_nl.properties
  java/src/jmri/UserPreferencesManager.java
  java/src/jmri/jmrix/loconet/LnOpsModeProgrammer.java
  java/src/jmri/jmrix/loconet/LncvDevicesManager.java
  java/src/jmri/jmrix/loconet/LocoNetBundle.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_nl.properties
  java/src/jmri/jmrix/loconet/swing/LocoNetMenu.java
  java/src/jmri/jmrix/loconet/swing/lncvprog/LncvProgPane.java
  java/src/jmri/jmrix/loconet/swing/lncvprog/LncvProgTableModel.java
  java/src/jmri/jmrix/loconet/uhlenbrock/LncvDevices.java
  java/src/jmri/jmrix/loconet/uhlenbrock/LncvMessageContents.java
  java/test/jmri/jmrix/loconet/LncvDevicesManagerTest.java
  java/test/jmri/jmrix/loconet/swing/lncvprog/LncvProgPaneTest.java
  java/test/jmri/jmrix/loconet/swing/lncvprog/LncvProgTableModelTest.java
  java/test/jmri/jmrix/loconet/uhlenbrock/LncvDeviceTest.java
  java/test/jmri/jmrix/loconet/uhlenbrock/LncvDevicesTest.java
  java/test/jmri/jmrix/loconet/uhlenbrock/LncvMessageContentsTest.java
  xml/decoders/Digikeijs_DR5033.xml
  xml/decoders/Digikeijs_DR5039.xml
  xml/decoders/Digikeijs_DR5088.xml
  xml/decoders/Digikeijs_Stationary.xml
  xml/decoders/Uhlenbrock_63410.xml
  xml/decoders/Uhlenbrock_DaisyII.xml
  xml/decoders/Uhlenbrock_FunkMaster.xml
  xml/decoders/Uhlenbrock_IntelliLight2800.xml
  xml/decoders/Uhlenbrock_IntelliLight2820.xml
  xml/decoders/Uhlenbrock_Power4.xml
  xml/decoders/Uhlenbrock_Power8.xml
  xml/decoders/Uhlenbrock_TrackControl_6922.xml
  xml/decoders/Uhlenbrock_TrackControl_6923.xml
Labels: Documentation, Needs L10N

#11217 Enhance operations help with A/D track instructions
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/SettingsOptions.png
Labels: Add to Next Test Release, Documentation

#11214 Wide help lines
  help/en/Acknowledgements.shtml
  help/en/html/apps/DecoderPro/index.shtml
  help/en/html/doc/Technical/Eclipse.shtml
  help/en/html/doc/Technical/Names.shtml
  help/en/html/doc/Technical/NetBeans.shtml
  help/en/html/doc/Technical/gitdeveloper.shtml
  help/en/html/doc/Technical/githubdesktopintro.shtml
  help/en/html/hardware/Sidebar.shtml
  help/en/html/hardware/index.shtml
  help/en/html/tools/Memories.shtml
  help/en/manual/DecoderPro/index.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Installing_JMRI.shtml
  help/en/manual/JMRI_OPS_UsersGuide/index.shtml
  help/en/manual/index.shtml
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/jmri5.1-master.shtml
  help/fr/html/apps/DecoderPro/index.shtml
Labels: Documentation

#11196 Remove single Layout Editor panel restriction from Dispatcher
  help/en/package/jmri/jmrit/dispatcher/Dispatcher.shtml
  help/en/package/jmri/jmrit/dispatcher/Options.shtml
  help/en/package/jmri/jmrit/dispatcher/images/OptionsWindow.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/Section.java
  java/src/jmri/SectionManager.java
  java/src/jmri/implementation/DefaultSection.java
  java/src/jmri/jmrit/beantable/SectionTableAction.java
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle.properties
  java/src/jmri/jmrit/dispatcher/ActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoAllocate.java
  java/src/jmri/jmrit/dispatcher/AutoTurnouts.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
  java/src/jmri/jmrit/dispatcher/OptionsFile.java
  java/src/jmri/jmrit/dispatcher/OptionsMenu.java
  java/src/jmri/managers/DefaultSectionManager.java
  java/test/jmri/jmrit/dispatcher/AllocationPlanTest.java
  java/test/jmri/jmrit/dispatcher/AutoAllocateTest.java
Labels: Needs L10N

#11229 New operations feature, routed cars only for staging tracks
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/LocationsTableFrame.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/tools/TrackDestinationEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarRosterMenu.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineRosterMenu.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableFrame.java
  java/src/jmri/jmrit/operations/routes/JmritOperationsRoutesBundle.properties
  java/src/jmri/jmrit/operations/routes/RoutesTableFrame.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainsTableFrame.java
Labels: Documentation, Needs L10N

#11228 Uhlenbrock 63320/30
  xml/decoders/Digikeijs_DR5033.xml
  xml/decoders/Digikeijs_DR5039.xml
  xml/decoders/Digikeijs_DR5088.xml
  xml/decoders/Uhlenbrock_63320.xml
  xml/decoders/Uhlenbrock_63330.xml
  xml/decoders/Uhlenbrock_63340.xml
  xml/decoders/Uhlenbrock_63350.xml
  xml/decoders/Uhlenbrock_63410.xml
  xml/decoders/Uhlenbrock_63810.xml
  xml/decoders/Uhlenbrock_63880.xml
  xml/decoders/Uhlenbrock_DaisyII.xml
  xml/decoders/Uhlenbrock_FunkMaster.xml
  xml/decoders/Uhlenbrock_IntelliLight2800.xml
  xml/decoders/Uhlenbrock_IntelliLight2820.xml
  xml/decoders/Uhlenbrock_Power22.xml
  xml/decoders/Uhlenbrock_Power4.xml
  xml/decoders/Uhlenbrock_Power40.xml
  xml/decoders/Uhlenbrock_Power7.xml
  xml/decoders/Uhlenbrock_Power70.xml
  xml/decoders/Uhlenbrock_Power8.xml
  xml/decoders/Uhlenbrock_TrackControl_6922.xml
  xml/decoders/Uhlenbrock_TrackControl_6923.xml
Labels: New PR

#11192 logixng action for Current Location of warrant
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionOBlock.java
  java/src/jmri/jmrit/logixng/actions/ActionWarrant.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionOBlockXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionWarrantXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionOBlockSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionWarrantSwing.java
  java/src/jmri/jmrit/logixng/tools/ImportConditional.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.5.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.3.xml
  xml/schema/logixng/digital-actions/action-oblock-4.23.1.xsd
  xml/schema/logixng/digital-actions/action-warrant-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-oblock-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-warrant-4.23.1.xsd
Labels: Needs L10N

#11240 Operations help improvements
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Documentation

#11254 Add train direction to build report
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/tools/PoolTrackFrame.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Needs L10N

#11259 Improvements to train build and report when using staging
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/setup/BackupBase.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/router/OperationsCarRouterTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
Labels: Needs L10N
