Repository JMRI/JMRI, pull requests merged in 2022-10, with the labels that each got.

#11481 Fix bug in LogixNG action/expression ExecuteDelayed
  java/src/jmri/jmrit/logixng/ConditionalNG.java
  java/src/jmri/jmrit/logixng/actions/DigitalCallModule.java
  java/src/jmri/jmrit/logixng/expressions/DigitalCallModule.java
  java/src/jmri/jmrit/logixng/implementation/DefaultConditionalNG.java
Labels: Bug

#11497 Throttle SpeedSlider move slider to exact click location
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
Labels: Needs L10N, New PR

#11500 Reduce mDNS logging of normal conditions as warnings
  default.lcf
Labels: New PR

#11503 Operations refactoring. No functional changes.
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderEngines.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Needs L10N

#11515 Improve Global Variable table browser content
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/AbstractLogixNGTableAction.java
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/LogixNGGlobalVariableTableAction.java
  java/src/jmri/jmrit/beantable/LogixNGModuleTableAction.java
  java/src/jmri/jmrit/beantable/LogixNGTableAction.java
  java/src/jmri/jmrit/beantable/LogixNGTableTableAction.java
Labels: Needs L10N, New PR

#11513 Update CMRI Lights - MultipleAdditions
  java/src/jmri/jmrix/cmri/serial/SerialLightManager.java
  java/test/jmri/jmrix/cmri/serial/SerialLightManagerTest.java
Labels: New PR

#11518 Operations, improve the show trains for a location or track tool
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_de.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/LocationsTableFrame.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/schedules/SchedulesTableFrame.java
  java/src/jmri/jmrit/operations/locations/tools/ShowTrainsServingLocationAction.java
  java/src/jmri/jmrit/operations/locations/tools/ShowTrainsServingLocationFrame.java
  java/src/jmri/jmrit/operations/trains/TrainEditFrame.java
  java/src/jmri/jmrit/operations/trains/TrainsTableFrame.java
  java/test/jmri/jmrit/operations/locations/tools/ShowTrainsServingLocationFrameTest.java
Labels: Documentation, Needs L10N

#11519 Delete all ConditionalNGs of a LogixNG. Add boolean XOR to LogixNG Formula
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/LogixNGPreferences.java
  java/src/jmri/jmrit/logixng/implementation/DefaultConditionalNGManager.java
  java/src/jmri/jmrit/logixng/implementation/DefaultLogixNGManager.java
  java/src/jmri/jmrit/logixng/util/parser/ExpressionNodeBooleanOperator.java
  java/src/jmri/jmrit/logixng/util/parser/RecursiveDescentParser.java
  java/src/jmri/jmrit/logixng/util/parser/TokenType.java
  java/src/jmri/jmrit/logixng/util/parser/Tokenizer.java
  java/test/jmri/jmrit/logixng/util/parser/ExpressionNodeBooleanOperatorTest.java
  java/test/jmri/jmrit/logixng/util/parser/RecursiveDescentParserTest.java
Labels: Bug, New PR

#11522 Operations, clear dirty bit when loading setup files
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/setup/OperationsSetupXml.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainManagerXml.java
  java/src/jmri/jmrit/operations/trains/schedules/TrainsScheduleTableFrame.java
Labels: Documentation, Needs L10N

#11523 Add "Paste copy" to the ConditionalNG editor
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
Labels: Needs L10N

#11525 Update XML schema: A local variable is not a named bean
  xml/schema/logixng/digital-actions/action-local-variable-4.23.1.xsd
Labels: New PR

#11532 Operations, fix web server train manifest local moves
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/server/json/operations/JsonUtil.java
  java/src/jmri/server/json/operations/car-client.json
  java/src/jmri/server/json/operations/car-server.json
  java/src/jmri/web/servlet/operations/HtmlManifest.java
  java/test/jmri/server/json/operations/JsonOperationsHttpServiceTest.java
Labels: Documentation, New PR

#11529 Update LogixNG expression Power
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/Is_IsNot_Enum.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionPower.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionPowerXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionPowerSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.5.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.4.xml
  java/test/jmri/jmrit/logixng/expressions/ExpressionPowerTest.java
  xml/schema/logixng/digital-expressions/expression-power-4.23.1.xsd
Labels: Needs L10N

#11535 Operations, add show locomotive attribute quantities
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/RollingStockAttributeEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeAction.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarDeleteAttributeAction.java
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/EngineAttributeAction.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/EngineAttributeEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/EngineDeleteAttributeAction.java
  java/test/jmri/jmrit/operations/rollingstock/RollingStockAttributeEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeActionTest.java
Labels: Needs L10N

#11533 Add support for multiple types of CSV's to LogixNG tables
  help/en/package/jmri/jmrit/beantable/LogixNGTableTable.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGTableTableEditor.shtml
  help/en/package/jmri/jmrit/logixng/images/AddTable.png
  help/en/package/jmri/jmrit/logixng/images/TablesEditor.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/LogixNGTableTableAction.java
  java/src/jmri/jmrit/logixng/LogixNGBundle.properties
  java/src/jmri/jmrit/logixng/NamedTableManager.java
  java/src/jmri/jmrit/logixng/Table.java
  java/src/jmri/jmrit/logixng/implementation/AbstractNamedTable.java
  java/src/jmri/jmrit/logixng/implementation/DefaultCsvNamedTable.java
  java/src/jmri/jmrit/logixng/implementation/DefaultNamedTableManager.java
  java/src/jmri/jmrit/logixng/implementation/configurexml/DefaultCsvNamedTableXml.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/TableEditor.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.4.99.3.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.4.99.5.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.5.1.3.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.5.1.4.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG_ActionMemory_ActionLocalVariable - 4.99.2.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.5.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.4.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG_ActionMemory_ActionLocalVariable - 4.99.2.xml
  java/test/jmri/jmrit/logixng/implementation/DefaultNamedTableTest.java
  java/test/jmri/jmrit/logixng/util/ReferenceUtilTest.java
  xml/schema/logixng/common-types-4.23.1.xsd
  xml/schema/logixng/logixng-4.23.1.xsd
Labels: Needs L10N

#11547 LocoNet Monitor Slots - Add Save to csv
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/loconet/slotmon/SlotMonDataModel.java
  java/src/jmri/jmrix/loconet/slotmon/SlotMonPane.java
  java/src/jmri/jmrix/loconet/slotmon/TODO
Labels: Needs L10N

#11549 fix SimpleClockBundle_fr , update error msg for dateformat
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle.properties
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle_ca.properties
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle_cs.properties
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle_da.properties
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle_de.properties
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle_es.properties
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle_fr.properties
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle_it.properties
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle_nl.properties
  java/src/jmri/jmrit/simpleclock/SimpleTimebase.java
Labels: Needs L10N
