Repository JMRI/JMRI, pull requests merged in 2022-04, with the labels that each got.

#10853 Select which connection a throttle should use
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/Bundle.properties
  java/src/jmri/jmrit/ToolsMenu.java
  java/src/jmri/jmrit/throttle/AddressPanel.java
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/LoadXmlThrottlesLayoutAction.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleCreationAction.java
  java/src/jmri/jmrit/throttle/ThrottleFrame.java
  java/src/jmri/jmrit/throttle/ThrottleFrameManager.java
  java/src/jmri/jmrit/throttle/ThrottleWindow.java
  java/src/jmri/jmrit/throttle/ThrottlesTableModel.java
  java/test/jmri/jmrit/throttle/AddressPanelTest.java
  xml/schema/throttle-layout-config.xsd
Labels: Needs L10N

#10858 Minor doc improvements
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/LocationManager.java
Labels: Add to Next Test Release, Documentation, New PR

#10854 More speedometer stuff
  help/en/html/hardware/bachrus/images/SpeedMatchSection.png
  help/en/html/hardware/bachrus/index.shtml
  help/en/package/jmri/jmrix/bachrus/SpeedoConsoleFrame.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/bachrus/BachrusBundle.properties
  java/src/jmri/jmrix/bachrus/SpeedoConsoleFrame.java
Labels: Documentation, Needs L10N

#10855 Spanish translations of some decoder files
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/nmra/accelDecel.xml
  xml/decoders/nmra/accelDecel_254.xml
  xml/decoders/nmra/accelDecel_255.xml
  xml/decoders/nmra/accelDecel_31.xml
  xml/decoders/nmra/analogModeFunction.xml
  xml/decoders/nmra/analogModeFunction_F12.xml
  xml/decoders/nmra/analogModeFunction_F15.xml
  xml/decoders/nmra/consistAccelDecelSigned.xml
  xml/decoders/nmra/consistAddr.xml
  xml/decoders/nmra/consistAddrDirection.xml
  xml/decoders/nmra/cv21.22.xml
  xml/decoders/nmra/cv21.22_F12.xml
  xml/decoders/nmra/cv21.22_F15.xml
  xml/decoders/nmra/cv21_lsb.xml
  xml/decoders/nmra/cv21_lsb_MRC.xml
  xml/decoders/nmra/cv29AdvAck.xml
  xml/decoders/nmra/cv29RailCom.xml
  xml/decoders/nmra/cv29address.xml
  xml/decoders/nmra/cv29analog.xml
  xml/decoders/nmra/cv29direction.xml
  xml/decoders/nmra/cv29speedSteps.xml
  xml/decoders/nmra/cv29table1-28.xml
  xml/decoders/nmra/cv29table3-28.xml
  xml/decoders/nmra/cv50_DCbrake.xml
  xml/decoders/nmra/cv51_DirectionalHeadlights.xml
  xml/decoders/nmra/cv67speedTableBasic.xml
  xml/decoders/nmra/decoderLockId16.xml
  xml/decoders/nmra/functionmap.xml
  xml/decoders/nmra/fwdTrim.xml
  xml/decoders/nmra/fwdTrim128.xml
  xml/decoders/nmra/kickStart.xml
  xml/decoders/nmra/kickStart_63.xml
  xml/decoders/nmra/mfgVersionId.xml
  xml/decoders/nmra/outputs1-4.xml
  xml/decoders/nmra/revTrim.xml
  xml/decoders/nmra/revTrim128.xml
  xml/decoders/nmra/shortAddressOnly.xml
  xml/decoders/nmra/shortAndLongAddress.xml
  xml/decoders/nmra/userId.xml
  xml/decoders/nmra/vStartHighMid.xml
Labels: Documentation

#10794 New CBUS Bootloader Protocol
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusConstants.java
  java/src/jmri/jmrix/can/cbus/CbusMessage.java
  java/src/jmri/jmrix/can/cbus/CbusOpCodes.java
  java/src/jmri/jmrix/can/cbus/node/CbusNode.java
  java/src/jmri/jmrix/can/cbus/swing/bootloader/CbusBootloaderPane.java
  java/src/jmri/jmrix/can/cbus/swing/bootloader/CbusParameters.java
  java/src/jmri/jmrix/can/cbus/swing/bootloader/CbusPicHexFile.java
  java/src/jmri/jmrix/can/cbus/swing/bootloader/HexFile.java
  java/src/jmri/jmrix/can/cbus/swing/bootloader/HexRecord.java
  java/test/jmri/jmrix/can/cbus/CbusMessageTest.java
  java/test/jmri/jmrix/can/cbus/CbusOpCodesTest.java
  java/test/jmri/jmrix/can/cbus/swing/bootloader/HexFileTest.java
Labels: Needs L10N

#10861 Operations, automatically change font size to smallest when using text
  java/src/jmri/jmrit/operations/setup/BuildReportOptionPanel.java
Labels: Add to Next Test Release, New PR

#10862 More Spanish updates for decoders and programmers
  xml/decoders/nmra/consistAddrDirection.xml
  xml/decoders/parts/enum-ConsistAddress.xml
  xml/decoders/parts/enum-NormRev.xml
  xml/programmers/parts/AdvancedPane.xml
  xml/programmers/parts/AnalogControlsPane.xml
  xml/programmers/parts/BasicPane.xml
  xml/programmers/parts/BasicSpeedControlPane.xml
  xml/programmers/parts/BasicSpeedControlTrimPane.xml
  xml/programmers/parts/CVsPane.xml
  xml/programmers/parts/ConsistPane.xml
  xml/programmers/parts/FunctionMapPane.xml
  xml/programmers/parts/LightsPane.xml
  xml/programmers/parts/MotorPane.xml
  xml/programmers/parts/SoundLevelsPane.xml
  xml/programmers/parts/SoundPane.xml
  xml/programmers/parts/SpeedTablePane.xml
Labels: New PR

#10863 A bit more tech info
  help/en/html/doc/Technical/IntroStructure.shtml
Labels: Documentation, New PR

#10868 zsh options handling for ./runtest.csh
  java/test/jmri/util/junit/TestClassMainMethod.java
Labels: dev/test/publish infrastructure

#10875 Don't show error dialog if file is not found
  java/src/jmri/jmrit/throttle/ThrottleFrame.java
Labels: Bug, New PR

#10872 Improve RWE and RWL warning messages
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/CarSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_it.properties
Labels: Add to Next Test Release, Documentation, Needs L10N

#10877 Increase number of trains when routing to 7
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/router/Router.java
  java/test/jmri/jmrit/operations/router/OperationsCarRouterTest.java
Labels: Add to Next Test Release, Documentation

#10882 Improve build report messages
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle.properties
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
Labels: Needs L10N

#10884 Improve router performance
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle.properties
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainEditFrame.java
  java/src/jmri/jmrit/operations/trains/tools/PrintSavedBuildReportAction.java
  java/test/jmri/jmrit/operations/locations/LocationManagerTest.java
  java/test/jmri/jmrit/operations/trains/tools/PrintSavedBuildReportActionTest.java
Labels: Add to Next Test Release, Needs L10N, New PR

#10886 Improve Handling of out-of-range & un-parseable text entry in decVal.
  java/src/jmri/jmrit/symbolicprog/DecVariableValue.java
  java/test/jmri/jmrit/symbolicprog/DecVariableValueTest.java
Labels: Bug, Add to Next Test Release, New PR

#10885 Add D&H PD10MU + Kato EM13 (Digitrax) + Zimo MX605N
  xml/decoders/Digitrax_Kato_EM13.xml
  xml/decoders/Doehler_Haass_fw3.12_DH05-10C_12-16-18-21-22A_PD05-12A.xml
  xml/decoders/Zimo_Unified_software_v37_MX605N.xml
  xml/decoders/Zimo_Unified_software_v39_MX60x-MX63x.xml
  xml/decoders/Zimo_Unified_software_v40_MX60x-MX63x.xml
  xml/decoders/doehler_haass/cv260-265_fw3.06.xml
  xml/decoders/zimo/CV250-CV253.xml
  xml/decoders/zimo/CV250_ProductID_enum.xml
  xml/decoders/zimo/PaneLoadCode.xml
Labels: Enhancement, Add to Next Test Release

#10880 CbusOpCodes - Translate Loco Speed / Direction messages
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/can/CanListener.java
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusOpCodes.java
  java/src/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorDataModel.java
  java/src/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorSession.java
  java/test/jmri/jmrix/can/cbus/CbusOpCodesTest.java
  java/test/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorDataModelTest.java
  java/test/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorPaneTest.java
  java/test/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorSessionTest.java
  xml/cbus/CbusOpcData.xml
Labels: Needs L10N, New PR

#10890 Shared Turnouts
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/IndicatorTurnoutIcon.java
  java/src/jmri/jmrit/logix/BlockOrder.java
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/NXFrame.java
  java/src/jmri/jmrit/logix/OBlock.java
  java/src/jmri/jmrit/logix/RouteFinder.java
  java/src/jmri/jmrit/logix/SpeedUtil.java
  java/src/jmri/jmrit/logix/TrainOrder.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantFrame.java
  java/src/jmri/jmrit/logix/WarrantTableAction.java
  java/src/jmri/jmrit/logix/WarrantTableFrame.java
  java/src/jmri/jmrit/logix/WarrantTableModel.java
  java/src/jmri/jmrit/logix/configurexml/WarrantManagerXml.java
  java/test/jmri/implementation/DefaultConditionalActionTest.java
  java/test/jmri/jmrit/beantable/OBlockTableActionTest.java
  java/test/jmri/jmrit/logix/BlockOrderTest.java
  java/test/jmri/jmrit/logix/LinkedWarrantTest.java
  java/test/jmri/jmrit/logix/OBlockTest.java
  java/test/jmri/jmrit/logix/TrainOrderTest.java
Labels: Needs L10N

#10888 Remove listener from throttle manager
  java/src/jmri/jmrit/throttle/ThrottleFrame.java
  java/src/jmri/jmrit/throttle/ThrottlesTableModel.java
Labels: Bug

#10891 Update Jsoup library to version 1.14.3
  build.xml
  help/en/releasenotes/current-draft-note.shtml
  lib/jsoup-1.13.1-javadoc.jar
  lib/jsoup-1.13.1.jar
  lib/jsoup-1.14.3.jar
  pom.xml
Labels: dev/test/publish infrastructure, New PR

#10895 Issue-8503: User names compare before system names always
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/util/NamedBeanUserNameComparator.java
  java/test/jmri/swing/NamedBeanComboBoxTest.java
  java/test/jmri/util/NamedBeanUserNameComparatorTest.java
Labels: New PR

#10897 Improve operations build report
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
Labels: Add to Next Test Release, Needs L10N

#10900 Update SimpleTimebase initializeHardwareClock
  java/src/jmri/jmrit/simpleclock/SimpleTimebase.java
Labels: New PR

#10904 Update LogixNG clock action help for PR 10894
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter5/clock_action.png
  help/en/html/tools/logixng/reference/images/chapter5/clock_memory.png
  help/en/html/tools/logixng/reference/images/chapter5/clock_rate_action.png
  help/en/html/tools/logixng/reference/images/chapter9/functions_clock.png
Labels: Documentation

#10908 Clean up warn logging messages
  java/test/jmri/jmrit/logixng/tools/ImportActionTestBase.java
  java/test/jmri/jmrit/logixng/tools/ImportEntryExitTest.java
  java/test/jmri/jmrit/logixng/tools/ImportExpressionComplexTestBase.java
  java/test/jmri/jmrit/logixng/tools/ImportExpressionTestBase.java
  java/test/jmri/jmrit/logixng/tools/ImportExpressionWarrantTest.java
  java/test/jmri/jmrit/logixng/tools/ImportTest.java
  java/test/jmri/jmrit/logixng/tools/Import_AndOrMixed_Test.java
  java/test/jmri/jmrit/logixng/tools/Import_TriggerOnChange_Test.java
Labels: New PR

#10919 Create help for LogixNG Global Variables
  help/en/html/tools/logixng/SidebarToolLocalPart.shtml
  help/en/html/tools/logixng/reference/chapter11.shtml
  help/en/html/tools/logixng/reference/chapter12.shtml
  help/en/html/tools/logixng/reference/chapter8.shtml
  help/en/html/tools/logixng/reference/images/chapter8/log_variables.png
  help/en/html/tools/logixng/reference/index.shtml
  help/en/package/jmri/jmrit/beantable/LogixNGGlobalVariables.shtml
  help/en/package/jmri/jmrit/logixng/images/AddGlobalVariable.png
  help/en/package/jmri/jmrit/logixng/images/DeleteGlobalVariable.png
  help/en/package/jmri/jmrit/logixng/images/SelectActionsNoEdit.png
  help/en/package/jmri/jmrit/logixng/images/SelectGlobalVariableType.png
Labels: Documentation

#10920 VSDecoder: update SidebarTools.shtml
  help/en/parts/SidebarTools.shtml
Labels: Documentation
