Repository JMRI/JMRI, pull requests merged in 2022-09, with the labels that each got.

#11376 Ij UTF-8 encoding
  .idea/encodings.xml
Labels: Developer

#11374 OperationsPro, provide unique table name for car road
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/TrainsTableModel.java
Labels: Needs L10N

#11377 Check for edge connector and nx references before deleting le panels
  java/src/jmri/jmrit/display/PanelDeleteAction.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle.properties
Labels: Needs L10N

#11379 IntelliJ help
  help/en/html/doc/Technical/IntelliJ.shtml
  help/en/html/doc/Technical/images/IntelliJ/IjPrefsFileEncodings.png
  help/en/html/doc/Technical/images/IntelliJ/IjResourceBundleEditorPlugin.png
Labels: Documentation

#11380 NCE tools i18n
  java/src/jmri/NamedBeanBundle_nl.properties
  java/src/jmri/jmrix/nce/NceActionListBundle.properties
  java/src/jmri/jmrix/nce/NceActionListBundle_de.properties
  java/src/jmri/jmrix/nce/NceActionListBundle_es.properties
  java/src/jmri/jmrix/nce/NceActionListBundle_it.properties
  java/src/jmri/jmrix/nce/NceActionListBundle_ja.properties
  java/src/jmri/jmrix/nce/NceActionListBundle_ja_JP.properties
  java/src/jmri/jmrix/nce/NceActionListBundle_nl.properties
  java/src/jmri/jmrix/nce/NceBundle.properties
  java/src/jmri/jmrix/nce/NceBundle_da.properties
  java/src/jmri/jmrix/nce/NceBundle_de.properties
  java/src/jmri/jmrix/nce/NceBundle_ja_JP.properties
  java/src/jmri/jmrix/nce/NceBundle_nl.properties
  java/src/jmri/jmrix/nce/NceConnectionStatus.java
  java/src/jmri/jmrix/nce/boosterprog/BoosterProgBundle.properties
  java/src/jmri/jmrix/nce/boosterprog/BoosterProgBundle_de.properties
  java/src/jmri/jmrix/nce/boosterprog/BoosterProgBundle_fr.properties
  java/src/jmri/jmrix/nce/boosterprog/BoosterProgBundle_nl.properties
  java/src/jmri/jmrix/nce/boosterprog/BoosterProgPanel.java
  java/src/jmri/jmrix/nce/cab/NceShowCabBundle_fr.properties
  java/src/jmri/jmrix/nce/cab/NceShowCabBundle_nl.properties
  java/src/jmri/jmrix/nce/cab/NceShowCabPanel.java
  java/src/jmri/jmrix/nce/clockmon/ClockMonBundle.properties
  java/src/jmri/jmrix/nce/clockmon/ClockMonBundle_da.properties
  java/src/jmri/jmrix/nce/clockmon/ClockMonBundle_de.properties
  java/src/jmri/jmrix/nce/clockmon/ClockMonBundle_fr.properties
  java/src/jmri/jmrix/nce/clockmon/ClockMonBundle_it.properties
  java/src/jmri/jmrix/nce/clockmon/ClockMonBundle_ja_JP.properties
  java/src/jmri/jmrix/nce/clockmon/ClockMonBundle_nl.properties
  java/src/jmri/jmrix/nce/clockmon/ClockMonPanel.java
  java/src/jmri/jmrix/nce/consist/NceConsistBackup.java
  java/src/jmri/jmrix/nce/consist/NceConsistBundle.properties
  java/src/jmri/jmrix/nce/consist/NceConsistBundle_da.properties
  java/src/jmri/jmrix/nce/consist/NceConsistBundle_fr.properties
  java/src/jmri/jmrix/nce/consist/NceConsistBundle_it.properties
  java/src/jmri/jmrix/nce/consist/NceConsistBundle_nl.properties
  java/src/jmri/jmrix/nce/consist/NceConsistEditPanel.java
  java/src/jmri/jmrix/nce/consist/NceConsistRestore.java
  java/src/jmri/jmrix/nce/consist/NceConsistRoster.java
  java/src/jmri/jmrix/nce/consist/NceConsistRosterEntry.java
  java/src/jmri/jmrix/nce/consist/PrintNceConsistRosterAction.java
  java/src/jmri/jmrix/nce/macro/NceMacroBackup.java
  java/src/jmri/jmrix/nce/macro/NceMacroBundle.properties
  java/src/jmri/jmrix/nce/macro/NceMacroBundle_nl.properties
  java/src/jmri/jmrix/nce/macro/NceMacroEditPanel.java
  java/src/jmri/jmrix/nce/macro/NceMacroGenPanel.java
  java/src/jmri/jmrix/nce/macro/NceMacroRestore.java
  java/src/jmri/jmrix/nce/ncemon/NceMonBinaryBundle.properties
  java/src/jmri/jmrix/nce/ncemon/NceMonPanel.java
  java/src/jmri/jmrix/nce/packetgen/NcePacketGenBundle.properties
  java/src/jmri/jmrix/nce/packetgen/NcePacketGenBundle_de.properties
  java/src/jmri/jmrix/nce/packetgen/NcePacketGenBundle_nl.properties
  java/src/jmri/jmrix/nce/packetgen/NcePacketGenPanel.java
  java/src/jmri/jmrix/nce/swing/NceNamedPaneAction.java
  java/src/jmri/jmrix/nce/swing/NcePanel.java
  java/src/jmri/jmrix/nce/swing/NcePanelInterface.java
  java/src/jmri/jmrix/nce/usbinterface/UsbInterfaceBundle_nl.properties
Labels: Needs L10N

#11385 Operations, improve copy car type for trains and locations
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/tools/LocationsByCarTypeFrame.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/tools/TrainsByCarTypeFrame.java
  java/test/jmri/ArchitectureTest.java
  java/test/jmri/jmrit/operations/locations/LocationEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/XmlTest.java
  java/test/jmri/jmrit/operations/locations/tools/LocationTrackBlockingOrderFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/LocationsByCarTypeFrameTest.java
  java/test/jmri/jmrit/operations/routes/tools/SetTrainIconPositionFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainManagerTest.java
  java/test/jmri/jmrit/operations/trains/tools/TrainsByCarTypeFrameTest.java
Labels: Documentation, Needs L10N

#11388 Note on i18n
  help/en/html/doc/Technical/Ant.shtml
  help/en/html/doc/Technical/AppStructure.shtml
  help/en/html/doc/Technical/Eclipse.shtml
  help/en/html/doc/Technical/GitFAQ.shtml
  help/en/html/doc/Technical/I8N.shtml
  help/en/html/doc/Technical/IntroStructure.shtml
  help/en/html/doc/Technical/JUnit.shtml
  help/en/html/doc/Technical/Names.shtml
  help/en/html/doc/Technical/Patterns.shtml
  help/en/html/doc/Technical/Swing.shtml
  help/en/html/doc/Technical/SystemStructure.shtml
  help/en/html/doc/Technical/Threads.shtml
  help/en/html/doc/Technical/WebSite.shtml
  help/en/html/doc/Technical/XmlSchema.shtml
  help/en/html/doc/Technical/githubdesktopintro.shtml
  help/en/html/doc/Technical/plugins.shtml
  help/en/releasenotes/current-draft-note.shtml
  help/fr/index.shtml
Labels: Documentation

#11387 update SimpleTimebase / SimpleClockFrame / JsonTimeSocketService Test
  java/src/jmri/jmrit/simpleclock/SimpleClockBundle.properties
  java/src/jmri/jmrit/simpleclock/SimpleClockFrame.java
  java/src/jmri/jmrit/simpleclock/SimpleTimebase.java
  java/test/jmri/jmrit/simpleclock/SimpleTimebaseTest.java
  java/test/jmri/server/json/time/JsonTimeSocketServiceTest.java
Labels: Needs L10N

#11397 20220909 auto trains frame
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/dispatcher/AutoTrainsFrame.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
Labels: Needs L10N

#11403 Update some jmri.util.web Tests
  java/test/jmri/RunCucumberIT.java
  java/test/jmri/util/web/BrowserFactory.java
  java/test/jmri/util/zeroconf/MockZeroConfServiceManager.java
  java/test/jmri/util/zeroconf/ZeroConfServiceEventTest.java
  java/test/jmri/web/servlet/directory/DirectoryResourceTest.java
  java/test/jmri/web/servlet/panel/AbstractPanelServletTest.java
  java/test/jmri/web/servlet/roster/MultipartRequestHandlerTest.java
Labels: New PR

#11401 Update some jmri.util startup / swing Tests
  java/test/jmri/util/iharder/dnd/FileDropEventTest.java
  java/test/jmri/util/startup/AbstractActionModelTest.java
  java/test/jmri/util/startup/AbstractStartupModelTest.java
  java/test/jmri/util/swing/ButtonTestAction.java
  java/test/jmri/util/swing/JCBHandleTest.java
  java/test/jmri/util/swing/XTableColumnModelTest.java
  java/test/jmri/util/table/ProgressCellRenderTest.java
Labels: New PR

#11399 More jmri.util test updates
  java/test/jmri/util/FileUtilSupportTest.java
  java/test/jmri/util/FileUtilTest.java
  java/test/jmri/util/GetJavaPropertyTest.java
  java/test/jmri/util/PropertyChangeEventQueueTest.java
  java/test/jmri/util/SystemTypeTest.java
  java/test/jmri/util/TimerUtilTest.java
  java/test/jmri/util/UnzipFileClassTest.java
  java/test/jmri/util/i18n/PropertiesMergeTool.java
Labels: New PR

#11402 Update jmri.util.prefs Tests
  java/test/jmri/util/ConnectionNameFromSystemNameTest.java
  java/test/jmri/util/exceptionhandler/UncaughtExceptionHandlerTest.java
  java/test/jmri/util/prefs/HasConnectionButUnableToConnectExceptionTest.java
  java/test/jmri/util/prefs/InitializationExceptionTest.java
  java/test/jmri/util/prefs/JmriConfigurationProviderTest.java
  java/test/jmri/util/prefs/JmriPreferencesProviderTest.java
  java/test/jmri/util/usb/UsbBrowserPanelTest.java
  java/test/jmri/util/usb/UsbUtilTest.java
Labels: New PR

#11412 Fix issue #11400
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/NamedBeanBundle_ca.properties
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/NamedBeanBundle_da.properties
  java/src/jmri/NamedBeanBundle_de.properties
  java/src/jmri/NamedBeanBundle_es.properties
  java/src/jmri/NamedBeanBundle_fr.properties
  java/src/jmri/NamedBeanBundle_it.properties
  java/src/jmri/NamedBeanBundle_ja.properties
  java/src/jmri/NamedBeanBundle_ja_JP.properties
  java/src/jmri/NamedBeanBundle_sv.properties
  java/src/jmri/jmrit/Bundle.properties
  java/src/jmri/jmrit/Bundle_ca.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/Bundle_da.properties
  java/src/jmri/jmrit/Bundle_de.properties
  java/src/jmri/jmrit/Bundle_es.properties
  java/src/jmri/jmrit/Bundle_fr.properties
  java/src/jmri/jmrit/Bundle_it.properties
  java/src/jmri/jmrit/Bundle_ja_JP.properties
  java/src/jmri/jmrit/Bundle_nl.properties
Labels: Needs L10N

#11414 SPROG 3 Plus DCC Accessory Offset
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/node/CbusNodeConstants.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeParameterManager.java
  java/src/jmri/jmrix/can/cbus/swing/bootloader/CbusParameters.java
  java/src/jmri/jmrix/can/cbus/swing/bootloader/CbusPicHexFile.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/Sprog3PlusEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/Sprog3PlusPaneProvider.java
  java/test/jmri/jmrix/can/cbus/node/CbusNodeParameterManagerTest.java
Labels: Needs L10N

#11416 Update releasee note for help stub change
  help/en/releasenotes/current-draft-note.shtml
Labels: New PR

#11417 Update beantable Maintenance tests
  java/src/jmri/jmrit/beantable/Maintenance.java
  java/test/jmri/jmrit/beantable/BeanTableDataModelTest.java
  java/test/jmri/jmrit/beantable/BlockTableActionTest.java
  java/test/jmri/jmrit/beantable/MaintenanceTest.java
Labels: New PR

#11418 Operations help cleanup
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_da.properties
Labels: Documentation, Needs L10N, New PR

#11419 Update DccLocoAddressSelector
  java/src/jmri/jmrit/DccLocoAddressSelector.java
Labels: New PR

#11420 Update JUnit.shtml
  help/en/html/doc/Technical/JUnit.shtml
Labels: Documentation, New PR

#11415 LogixNG - Show "listen" property
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/Base.java
  java/src/jmri/jmrit/logixng/LogixNGBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionLocalVariable.java
  java/src/jmri/jmrit/logixng/implementation/AbstractMaleSocket.java
  java/src/jmri/jmrit/logixng/swing/SwingConfiguratorInterface.java
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectDouble.java
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectEnum.java
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectInteger.java
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectNamedBean.java
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectString.java
  java/test/jmri/ArchitectureTest.java
  java/test/jmri/jmrit/beantable/LogixNGTableActionTest.java
Labels: Needs L10N

#11435 More OperationsPro refactoring
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/tools/TrackDestinationEditFrame.java
  java/src/jmri/jmrit/operations/trains/Train.java
Labels: Documentation

#11441 Cancel timers on stop immediate
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/TransitSectionAction.java
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle.properties
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoTrainAction.java
  java/src/jmri/jmrit/dispatcher/AutoTrainsFrame.java
Labels: Needs L10N

#11442 Evolution series 21-23 opsw hints
  java/src/jmri/jmrix/loconet/cmdstnconfig/CmdStnConfigPane.java
  java/src/jmri/jmrix/loconet/cmdstnconfig/DCS210Plusoptions.properties
  java/src/jmri/jmrix/loconet/cmdstnconfig/DCS210options.properties
  java/src/jmri/jmrix/loconet/cmdstnconfig/DCS240Plusoptions.properties
  java/src/jmri/jmrix/loconet/cmdstnconfig/DCS240options.properties
  java/src/jmri/jmrix/loconet/cmdstnconfig/DCS52options.properties
Labels: Needs L10N

#11448 Minor improvements to OperationsPro import cars and locomotives
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/ImportCars.java
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_nl.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/ImportEngines.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/ImportCarsTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/ImportEnginesTest.java
Labels: Needs L10N

#11462 LogixNG thread and debug help
  help/en/html/tools/logixng/LogixNG.shtml
  help/en/package/jmri/jmrit/logixng/ConditionalNGDebugger.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGTableEditor.shtml
  help/en/package/jmri/jmrit/logixng/images/DebugAfter.png
  help/en/package/jmri/jmrit/logixng/images/DebugBefore.png
  help/en/package/jmri/jmrit/logixng/images/DebugBreakpoint.png
  help/en/package/jmri/jmrit/logixng/images/DebugBreakpointActive.png
  help/en/package/jmri/jmrit/logixng/images/DebugBreakpointSet.png
  help/en/package/jmri/jmrit/logixng/images/DebugMenu.png
  help/en/package/jmri/jmrit/logixng/images/DebugPane.png
  help/en/package/jmri/jmrit/logixng/images/EditThreads.png
Labels: Documentation

#11460 Update JUnit / CI support pages
  help/en/html/doc/Technical/ContinuousIntegration.shtml
  help/en/html/doc/Technical/JUnit.shtml
Labels: Documentation

#11465 Add new LogixNG actions
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/ShutDownTask.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionShutDownTask.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionShutDownTaskXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionShutDownTaskSwing.java
  java/src/jmri/jmrix/loconet/logixng/ActionFactory.java
  java/src/jmri/jmrix/loconet/logixng/LogixNGBundle.properties
  java/src/jmri/jmrix/loconet/logixng/SetSpeedZero.java
  java/src/jmri/jmrix/loconet/logixng/configurexml/SetSpeedZeroXml.java
  java/src/jmri/jmrix/loconet/logixng/swing/SetSpeedZeroSwing.java
  java/src/jmri/managers/DefaultShutDownManager.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/action-loconet-set-speed-zero-5.1.5.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/shut-down-task-5.1.5.xsd
Labels: Needs L10N

#11474 Add note about ordering of defaultItem elements inside variable
  help/en/html/apps/DecoderPro/CreateDecoderAdvanced.shtml
Labels: Documentation

#11475 Fix bug in LogixNG action IfThenElse
  java/src/jmri/jmrit/logixng/actions/IfThenElse.java
Labels: Bug
