Repository JMRI/JMRI, pull requests merged in 2022-05, with the labels that each got.

#10925 Code refactor & minor updates; help tweaks
  help/en/html/hardware/loconet/CommandStationConfig.shtml
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/StandaloneLocoNet.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/LocoNetMessage.java
  java/src/jmri/jmrix/loconet/alm/Alm.java
  java/src/jmri/jmrix/loconet/alm/AlmMsgTypes.java
  java/src/jmri/jmrix/loconet/alm/almi/Almi.java
  java/src/jmri/jmrix/loconet/alm/almi/Almi.properties
  java/src/jmri/jmrix/loconet/alm/almi/Almir.java
  java/src/jmri/jmrix/loconet/alm/almi/Bundle.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/alm/almi/AlmiTest.java
  java/test/jmri/jmrix/loconet/alm/almi/AlmirTest.java
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Enhancement, Documentation, Needs L10N

#10926 Allow run of javadoc via ant when classpath is loooooong
  build.xml
Labels: dev/test/publish infrastructure

#10928 WarrantSharedTurnoutFixes
  java/src/jmri/jmrit/logix/BlockOrder.java
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/NXFrame.java
  java/src/jmri/jmrit/logix/OBlock.java
  java/src/jmri/jmrit/logix/SpeedUtil.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantFrame.java
  java/test/jmri/jmrit/logix/WarrantTest.java
Labels: Add to Next Test Release, Needs L10N

#10927 TabbedOBlockIssue
  java/src/jmri/jmrit/beantable/oblock/BlockPathTableModel.java
  java/src/jmri/jmrit/beantable/oblock/TableFrames.java
Labels: Add to Next Test Release

#10929 LogixNG: Show the type of action or expression
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
Labels: Needs L10N

#10932 Update operations help
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
Labels: Add to Next Test Release, Documentation, Needs L10N

#10931 allow extensions to add LocoNet menu items
  java/src/jmri/jmrix/loconet/swing/LocoNetMenu.java
  java/src/jmri/jmrix/loconet/swing/LocoNetMenuItem.java
  java/src/jmri/jmrix/loconet/swing/menuitemspi/MenuItemsService.java
  java/src/jmri/jmrix/loconet/swing/menuitemspi/spi/MenuItemsInterface.java
  java/test/jmri/jmrix/loconet/swing/LocoNetMenuItemTest.java
  java/test/jmri/jmrix/loconet/swing/menuitemspi/MenuItemsServiceTest.java
Labels: Enhancement

#10936 Add to LocoNet device interpretation
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Enhancement, Add to Next Test Release, Needs L10N

#10938 Automatically reset a LogixNG Sequence when done
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter5/action_sequence_options.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/Sequence.java
Labels: Documentation

#10937 New decoder definition for Mixion HDD turntable decoder
  help/en/Acknowledgements.shtml
  help/en/html/apps/DecoderPro/Programmer.shtml
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/jmri4.99-master.shtml
  java/test/jmri/jmrit/symbolicprog/CombinedLocoSelListPaneTest.java
  xml/decoderIndex.xml
  xml/decoders/MDE_HDD.xml
  xml/decoders/mde/ChoiceHDDSpecialFunction.xml
  xml/decoders/nmra/decoderLockId16.xml
Labels: Documentation

#10945 Update LogixNG DefaultGlobalVariable Test - Temp Profile Directory
  java/test/jmri/jmrit/logixng/implementation/DefaultGlobalVariableTest.java
Labels: New PR

#10944 MQTT support for LogixNG
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/util/configurexml/LogixNG_SelectStringXml.java
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/MathFunctions.java
  java/src/jmri/jmrit/logixng/util/swing/LogixNG_SelectStringSwing.java
  java/src/jmri/jmrix/mqtt/logixng/ActionFactory.java
  java/src/jmri/jmrix/mqtt/logixng/Bundle.java
  java/src/jmri/jmrix/mqtt/logixng/Bundle.properties
  java/src/jmri/jmrix/mqtt/logixng/CategoryMqtt.java
  java/src/jmri/jmrix/mqtt/logixng/Publish.java
  java/src/jmri/jmrix/mqtt/logixng/Subscribe.java
  java/src/jmri/jmrix/mqtt/logixng/configurexml/PublishXml.java
  java/src/jmri/jmrix/mqtt/logixng/configurexml/SubscribeXml.java
  java/src/jmri/jmrix/mqtt/logixng/swing/Bundle.java
  java/src/jmri/jmrix/mqtt/logixng/swing/Bundle.properties
  java/src/jmri/jmrix/mqtt/logixng/swing/PublishSwing.java
  java/src/jmri/jmrix/mqtt/logixng/swing/SubscribeSwing.java
  java/test/jmri/jmrix/mqtt/logixng/PublishTest.java
  java/test/jmri/jmrix/mqtt/logixng/configurexml/StoreAndLoadTest.java
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/mqtt-publish-4.99.7.xsd
  xml/schema/logixng/digital-actions/mqtt-subscribe-4.99.7.xsd
Labels: Needs L10N

#10941 Update LogixNG scripting related help
  help/en/html/tools/logixng/reference/chapter12.shtml
  help/en/html/tools/logixng/reference/chapter13.shtml
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/chapter8.shtml
  help/en/html/tools/logixng/reference/chapter9.shtml
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_mqtt.png
  help/en/html/tools/logixng/reference/images/chapter5/mqtt_publish.png
  help/en/html/tools/logixng/reference/images/chapter5/mqtt_subscribe.png
  help/en/html/tools/logixng/reference/images/chapter6/script_expression.png
  help/en/html/tools/logixng/reference/images/chapter8/local_variable_table_type.png
  help/en/html/tools/logixng/reference/images/chapter8/local_variable_types.png
  help/en/html/tools/logixng/reference/images/chapter9/functions_math.png
  help/en/html/tools/logixng/reference/index.shtml
Labels: Documentation

#10948 WarrantMessagesAndTiming
  default.lcf
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
Labels: Needs L10N

#10947 DCC++EX: parse more new messages, update simulator
  java/src/jmri/jmrix/dccpp/DCCppConstants.java
  java/src/jmri/jmrix/dccpp/DCCppMessage.java
  java/src/jmri/jmrix/dccpp/DCCppReply.java
  java/src/jmri/jmrix/dccpp/DCCppThrottle.java
  java/src/jmri/jmrix/dccpp/DCCppThrottleManager.java
  java/src/jmri/jmrix/dccpp/simulator/DCCppSimulatorAdapter.java
  java/src/jmri/jmrix/dccpp/swing/ConfigBaseStationFrame.java
  java/src/jmri/jmrix/dccpp/swing/DCCppSwingBundle.properties
  java/test/jmri/jmrix/dccpp/DCCppMessageTest.java
  java/test/jmri/jmrix/dccpp/DCCppReplyTest.java
  java/test/jmri/jmrix/dccpp/DCCppThrottleTest.java
Labels: Needs L10N

#10950 Update operations help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Add to Next Test Release, Documentation, New PR

#10958 Fix bugs in LogixNG_SelectNamedBeanSwing
  java/src/jmri/jmrit/logixng/util/swing/LogixNG_SelectNamedBeanSwing.java
Labels: Bug, New PR

#10961 Fix bug in LogixNG action/expression SignalHead
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionSignalHeadXml.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionSignalHeadXml.java
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.5.xml
Labels: Bug, New PR

#10955 Add checkbox "Hold cars with custom loads when spurs are full" in spur
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/tools/TrackLoadEditFrame.java
Labels: Add to Next Test Release, Documentation, Needs L10N

#10963 Add tool tips to table checkboxes
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
Labels: Add to Next Test Release, Needs L10N

#10965 Migrate SoundTraxx OEM Indexed CVs to full NMRA format.
  xml/decoders/SoundTraxx_Eco_Diesel_OEM_Bachmann_SndVal.xml
  xml/decoders/SoundTraxx_Eco_Steam_OEM_Bachmann_SndVal.xml
  xml/decoders/soundtraxx/OEMBachmannCV.xml
Labels: Bug, Add to Next Test Release

#10969 Validate formula
  java/src/jmri/jmrit/logixng/actions/swing/ActionLocalVariableSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionMemorySwing.java
Labels: Bug, Add to Next Test Release

#10970 fix ramp timing calculation
  default.lcf
  java/src/jmri/jmrit/logix/Warrant.java
Labels: Add to Next Test Release

#10972 Remaining Spotbugs UWF_FIELD_NOT_INITIALIZED
  .spotbugs-check.xml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ExecuteDelayed.java
  java/src/jmri/jmrit/logixng/actions/Timeout.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionListenOnBeansTableSwing.java
  java/src/jmri/jmrit/logixng/implementation/swing/AbstractMaleSocketSwing.java
  java/src/jmri/jmrix/internal/configurexml/ConnectionConfigXml.java
  java/src/jmri/jmrix/loconet/spjfile/SpjFile.java
Labels: New PR

#10976 Run SocketOperationTest on Intermittent CI
  java/test/jmri/jmrit/logixng/SocketOperationTest.java
Labels: New PR

#10977 Use the given name to create NamedBeanHandle
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectNamedBean.java
  java/src/jmri/jmrit/logixng/util/configurexml/LogixNG_SelectNamedBeanXml.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/configurexml/LoadAndStoreTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/expressions/ExpressionLightTest.java
  java/test/jmri/jmrit/logixng/expressions/ExpressionMemoryTest.java
  java/test/jmri/jmrit/logixng/expressions/ExpressionReporterTest.java
Labels: New PR

#10978 Check not null
  java/src/jmri/jmrit/logixng/SymbolTable.java
Labels: Bug

#10973 New "Add a sequential range" method for Sensors/Turnouts/Reporters/Lights
  help/en/package/jmri/jmrit/beantable/LightAddEdit.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/LightManager.java
  java/src/jmri/Manager.java
  java/src/jmri/NameIncrementingManager.java
  java/src/jmri/ReporterManager.java
  java/src/jmri/SensorManager.java
  java/src/jmri/Turnout.java
  java/src/jmri/TurnoutManager.java
  java/src/jmri/VariableControlSpanBean.java
  java/src/jmri/jmrit/Bundle.properties
  java/src/jmri/jmrit/beantable/LightTableAction.java
  java/src/jmri/jmrit/beantable/ReporterTableAction.java
  java/src/jmri/jmrit/beantable/SensorTableAction.java
  java/src/jmri/jmrit/beantable/TurnoutTableAction.java
  java/src/jmri/jmrix/can/cbus/CbusLightManager.java
  java/src/jmri/jmrix/can/cbus/CbusSensorManager.java
  java/src/jmri/jmrix/can/cbus/CbusTurnoutManager.java
  java/src/jmri/jmrix/cmri/serial/SerialSensorManager.java
  java/src/jmri/jmrix/cmri/serial/SerialTurnoutManager.java
  java/src/jmri/jmrix/dcc4pc/Dcc4PcSensorManager.java
  java/src/jmri/jmrix/dccpp/DCCppSensorManager.java
  java/src/jmri/jmrix/grapevine/SerialTurnoutManager.java
  java/src/jmri/jmrix/lenz/XNetSensorManager.java
  java/src/jmri/jmrix/maple/SerialSensorManager.java
  java/src/jmri/jmrix/marklin/MarklinSensorManager.java
  java/src/jmri/jmrix/nce/NceSensorManager.java
  java/src/jmri/jmrix/openlcb/OlcbSensorManager.java
  java/src/jmri/jmrix/openlcb/OlcbTurnoutManager.java
  java/src/jmri/jmrix/powerline/SerialSensorManager.java
  java/src/jmri/jmrix/powerline/SerialTurnoutManager.java
  java/src/jmri/jmrix/roco/z21/Z21SensorManager.java
  java/src/jmri/jmrix/tams/TamsSensorManager.java
  java/src/jmri/managers/AbstractLightManager.java
  java/src/jmri/managers/AbstractManager.java
  java/src/jmri/managers/AbstractProxyManager.java
  java/src/jmri/managers/AbstractReporterManager.java
  java/src/jmri/managers/AbstractSensorManager.java
  java/src/jmri/managers/AbstractTurnoutManager.java
  java/src/jmri/managers/ProxyLightManager.java
  java/src/jmri/managers/ProxyReporterManager.java
  java/src/jmri/managers/ProxySensorManager.java
  java/src/jmri/managers/ProxyTurnoutManager.java
  java/test/jmri/ManagerTest.java
  java/test/jmri/NameIncrementingManagerTest.java
  java/test/jmri/jmrix/can/cbus/CbusLightManagerTest.java
  java/test/jmri/jmrix/can/cbus/CbusSensorManagerTest.java
  java/test/jmri/jmrix/can/cbus/CbusTurnoutManagerTest.java
  java/test/jmri/jmrix/internal/InternalLightManagerTest.java
  java/test/jmri/jmrix/internal/InternalReporterManagerTest.java
  java/test/jmri/jmrix/internal/InternalSensorManagerTest.java
  java/test/jmri/jmrix/internal/InternalTurnoutManagerTest.java
  java/test/jmri/jmrix/tams/TamsSensorManagerTest.java
  java/test/jmri/managers/AbstractLightMgrTestBase.java
  java/test/jmri/managers/AbstractReporterMgrTestBase.java
  java/test/jmri/managers/AbstractSensorMgrTestBase.java
  java/test/jmri/managers/AbstractTurnoutMgrTestBase.java
  java/test/jmri/managers/ProxyReporterManagerTest.java
  java/test/jmri/managers/ProxyTurnoutManagerTest.java
  java/test/jmri/managers/TurnoutManagerScaffold.java
Labels: Needs L10N

#10986 Update help for Issue-10834 comments
  help/en/html/apps/DecoderPro/CreateDecoder.shtml
Labels: Documentation

#10988 Update xercesImpl 2.12.0 to 2.12.2
  build.xml
  help/en/releasenotes/current-draft-note.shtml
  java/test/apps/jmrit/XmlFileValidateRunnerTest.java
  java/test/jmri/jmrit/XmlFileValidateActionTest.java
  lib/README.md
  lib/xercesImpl-2.12.0.jar
  lib/xercesImpl-2.12.2.jar
  pom.xml
Labels: dependencies

#10990 Add ScriptEngineSelector to select script engine
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionScript.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionScriptXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionScriptSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionScript.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionScriptXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionScriptSwing.java
  java/src/jmri/jmrit/logixng/tools/ImportConditional.java
  java/src/jmri/script/InternalScriptEngineSelector.java
  java/src/jmri/script/ScriptEngineSelector.java
  java/src/jmri/script/configurexml/ScriptEngineSelectorXml.java
  java/src/jmri/script/swing/InputWindow.java
  java/src/jmri/script/swing/ScriptEngineSelector.java
  java/src/jmri/script/swing/ScriptEngineSelectorSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/actions/ActionScriptTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.5.xml
  java/test/jmri/jmrit/logixng/expressions/ExpressionScriptTest.java
  java/test/jmri/script/ScriptEngineSelectorTest.java
  xml/schema/layout-4-19-2.xsd
  xml/schema/logixng/digital-actions/action-script-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-script-4.23.1.xsd
  xml/schema/types/script.xsd
Labels: Enhancement, Needs L10N

#11016 Check GIF images for the Netscape extension
  java/test/jmri/CheckNetscapeExtensionTest.java
Labels: New PR

#11026 Show staging in the location print track analysis tool.
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsAction.java
  java/src/jmri/jmrit/operations/trains/tools/ShowCarsInTrainFrame.java
Labels: Add to Next Test Release, Documentation, Needs L10N

#11028 Spanish translation
  build.xml
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/ActionListBundle_es.properties
  java/src/apps/ActionListCoreBundle_es.properties
  java/src/apps/AppsBundle_es.properties
  java/src/apps/AppsConfigBundle_es.properties
  java/src/apps/TrainCrew/TrainCrew_es.properties
  java/src/apps/configurexml/Bundle_es.properties
  java/src/apps/gui3/dp3/Bundle_es.properties
  java/src/apps/gui3/dp3/DecoderPro3ActionListBundle_es.properties
  java/src/apps/startup/Bundle_es.properties
  java/src/apps/swing/Bundle_es.properties
  java/src/apps/util/issuereporter/Bundle_es.properties
  java/src/apps/util/issuereporter/swing/Bundle_es.properties
  java/src/jmri/configurexml/Bundle_es.properties
  java/src/jmri/implementation/ImplementationBundle_es.properties
  java/src/jmri/implementation/swing/MessageBundle_es.properties
  java/src/jmri/jmris/JmriServerBundle_es.properties
  java/src/jmri/jmris/simpleserver/SimpleServerBundle_es.properties
  java/src/jmri/jmris/srcp/JmriSRCPServerBundle_es.properties
  java/src/jmri/jmrit/analogclock/Bundle_es.properties
  java/src/jmri/jmrit/audio/swing/AudioTableBundle_es.properties
  java/src/jmri/jmrit/automat/monitor/AutomatTableBundle_es.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_es.properties
  java/src/jmri/jmrit/beantable/JmritBeantablePhysicalLocationBundle_es.properties
  java/src/jmri/jmrit/beantable/LRouteTableBundle_es.properties
  java/src/jmri/jmrit/beantable/MaintenanceBundle_es.properties
  java/src/jmri/jmrit/beantable/OBlockTableBundle_es.properties
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle_es.properties
  java/src/jmri/jmrit/beantable/beanedit/BeanEditBundle_es.properties
  java/src/jmri/jmrit/beantable/signalmast/RepeaterBundle_es.properties
  java/src/jmri/jmrit/blockboss/BlockBossBundle_es.properties
  java/src/jmri/jmrit/cabsignals/CabSignalBundle_es.properties
  java/src/jmri/jmrit/catalog/CatalogBundle_es.properties
Labels: Documentation

#11029 Fix test race conditions when using dialogs
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/EngineAttributeEditFrameTest.java
Labels: Add to Next Test Release

#11020 Edit speed profile from warrant edit window
  java/src/jmri/jmrit/logix/BlockOrder.java
  java/src/jmri/jmrit/logix/BlockSpeedInfo.java
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/MergePrompt.java
  java/src/jmri/jmrit/logix/NXFrame.java
  java/src/jmri/jmrit/logix/RouteFinder.java
  java/src/jmri/jmrit/logix/SpeedUtil.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantFrame.java
  java/src/jmri/jmrit/logix/WarrantManager.java
  java/src/jmri/jmrit/logix/WarrantRoute.java
  java/src/jmri/jmrit/logix/WarrantShutdownTask.java
  java/src/jmri/jmrit/logix/WarrantTableModel.java
  java/src/jmri/jmrit/roster/RosterSpeedProfile.java
  java/test/jmri/jmrit/logix/BlockSpeedInfoTest.java
Labels: Needs L10N

#11033 Minor improvement to Operations print location details
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsAction.java
Labels: Add to Next Test Release, Needs L10N

#11034 jmrix d-j SLF4J Spotbugs
  java/src/jmri/jmrix/dcc4pc/Dcc4PcBoardManager.java
  java/src/jmri/jmrix/dcc4pc/Dcc4PcSensorManager.java
  java/src/jmri/jmrix/dcc4pc/Dcc4PcTrafficController.java
  java/src/jmri/jmrix/dccpp/network/DCCppEthernetPacketizer.java
  java/src/jmri/jmrix/direct/TrafficController.java
  java/src/jmri/jmrix/direct/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/easydcc/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/ecos/EcosLocoAddressManager.java
  java/src/jmri/jmrix/ecos/utilities/EcosLocoToRoster.java
  java/src/jmri/jmrix/grapevine/GrapevineSystemConnectionMemo.java
  java/src/jmri/jmrix/grapevine/SerialAddress.java
  java/src/jmri/jmrix/grapevine/SerialNode.java
  java/src/jmri/jmrix/grapevine/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/internal/InternalSensorManager.java
  java/src/jmri/jmrix/jinput/TreeModel.java
Labels: New PR

#11035 jmrix l-o SLF4J Spotbugs
  java/src/jmri/jmrix/lenz/XNetConsist.java
  java/src/jmri/jmrix/loconet/AbstractBoardProgPanel.java
  java/src/jmri/jmrix/loconet/LnThrottleManager.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/DuplexGroupScanPanel.java
  java/src/jmri/jmrix/loconet/locomon/LocoMonPane.java
  java/src/jmri/jmrix/loconet/slotmon/SlotMonDataModel.java
  java/src/jmri/jmrix/loconet/soundloader/LoaderEngine.java
  java/src/jmri/jmrix/loconet/spjfile/SpjFile.java
  java/src/jmri/jmrix/maple/SerialNode.java
  java/src/jmri/jmrix/maple/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/marklin/MarklinSensorManager.java
  java/src/jmri/jmrix/mrc/MrcPacketizer.java
  java/src/jmri/jmrix/mrc/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/nce/NceClockControl.java
  java/src/jmri/jmrix/nce/NceSensorManager.java
  java/src/jmri/jmrix/nce/NceTrafficController.java
  java/src/jmri/jmrix/nce/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/oaktree/SerialNode.java
  java/src/jmri/jmrix/oaktree/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/openlcb/OlcbSensorManager.java
  java/src/jmri/jmrix/openlcb/swing/downloader/LoaderPane.java
  java/src/jmri/jmrix/openlcb/swing/hub/HubPane.java
Labels: New PR

#11037 jmrix final SLF4J Spotbugs
  java/src/jmri/jmrix/UsbPortAdapter.java
  java/src/jmri/jmrix/powerline/insteon2412s/SpecificTrafficController.java
  java/src/jmri/jmrix/powerline/simulator/SpecificTrafficController.java
  java/src/jmri/jmrix/secsi/SerialNode.java
  java/src/jmri/jmrix/secsi/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/sprog/console/SprogConsoleFrame.java
  java/src/jmri/jmrix/sprog/pi/pisprogonecs/PiSprogOneCSSerialDriverAdapter.java
  java/src/jmri/jmrix/sprog/serialdriver/SerialDriverAdapter.java
  java/src/jmri/jmrix/sprog/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/sprog/sprogCS/SprogCSSerialDriverAdapter.java
  java/src/jmri/jmrix/sprog/update/SprogIIUpdateFrame.java
  java/src/jmri/jmrix/tams/TamsReply.java
  java/src/jmri/jmrix/tams/TamsThrottle.java
  java/src/jmri/jmrix/tams/simulator/SimulatorAdapter.java
  java/src/jmri/jmrix/tams/swing/locodatabase/LocoDataModel.java
  java/src/jmri/jmrix/tmcc/simulator/SimulatorAdapter.java
  java/src/jmri/managers/DefaultSectionManager.java
Labels: New PR

#11036 Spotbugs SLF4J_FORMAT_SHOULD_BE_CONST
  .spotbugs-check.xml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logix/SpeedUtil.java
Labels: New PR

#11039 New MQTT script
  help/en/releasenotes/current-draft-note.shtml
  jython/MQTT/MqttSignalHead.py
Labels: New PR

#11044 Fix operations test failures
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsAction.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeEditFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/EngineAttributeEditFrameTest.java
Labels: Add to Next Test Release
