Repository JMRI/JMRI, pull requests merged in 2022-01, with the labels that each got.

#10538 2022 copyright notices
  build.xml
  help/en/indexheader
  help/en/tocheader
  java/src/jmri/Version.java
  scripts/HOWTO-distribution.md
  scripts/WinInstallFiles/LaunchJMRI.nsi
  xml/XSLT/CSVsummary.xsl
  xml/XSLT/CVsummary.xsl
  xml/XSLT/DecoderID.xsl
  xml/XSLT/DecoderMfgIndex.xsl
  xml/XSLT/DecoderModelIndex.xsl
  xml/XSLT/DecoderModelList.xsl
  xml/XSLT/LogixToCode.xsl
  xml/XSLT/SelectionGuide.xsl
  xml/XSLT/appearancetable.xsl
  xml/XSLT/aspecttable.xsl
  xml/XSLT/build.xml
  xml/XSLT/consistRoster.xsl
  xml/XSLT/decoder-with-form.xsl
  xml/XSLT/decoder.xsl
  xml/XSLT/decoderAddPaneLabelTextElement.xsl
  xml/XSLT/decoderLabelToItem.xsl
  xml/XSLT/decoderPaneAddI18nName.xsl
  xml/XSLT/decoderPaneAddNameElement.xsl
  xml/XSLT/decoderPaneLabelToText.xsl
  xml/XSLT/decoderPaneSuppressLabelAttribute.xsl
  xml/XSLT/decoderPaneSuppressNameAttribute.xsl
  xml/XSLT/decoderPromoteQualifier.xsl
  xml/XSLT/decoderSuppressRedundantLabel.xsl
  xml/XSLT/idtags.xsl
  xml/XSLT/locomotive.xsl
  xml/XSLT/mfgID.xsl
  xml/XSLT/panelfile-2-9-6.xsl
  xml/XSLT/panelfile-4-19-2.xsl
  xml/XSLT/panelfile.xsl
  xml/XSLT/reservedCSV.xsl
  xml/XSLT/roster.xsl
  xml/XSLT/roster2array.xsl
  xml/XSLT/roster2text.xsl
  xml/XSLT/roster4web-simple.xsl
  xml/XSLT/roster4web.xsl
  xml/XSLT/rpsfile.xsl
  xml/XSLT/show-revhistory.xsl
  xml/XSLT/speedometer.xsl
  xml/XSLT/throttle.xsl
  xml/XSLT/transformIVariableToVariable.xsl
  xml/XSLT/vsdecoder-config.xsl
Labels: Documentation

#10539 Z21/z21 default connection
  help/en/html/hardware/roco/z21/Z21-defaults.png
  help/en/html/hardware/roco/z21/index.shtml
Labels: Documentation

#10543 Change label for MQTT topic entry
  java/src/jmri/jmrix/mqtt/Bundle.properties
  java/src/jmri/jmrix/mqtt/MqttSignalMastAddPane.java
Labels: Needs L10N

#10544 Minor improvements to the operations build report
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
Labels: Add to Next Test Release, Needs L10N

#10545 Update setup/index regarding Java recommendations
  help/en/html/setup/index.shtml
Labels: Documentation

#10552 Add Import to Operations Pro Locations Page
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/LocationsTableFrame.java
  java/src/jmri/jmrit/operations/locations/tools/ImportLocations.java
  java/src/jmri/jmrit/operations/locations/tools/ImportLocationsRosterAction.java
  java/test/jmri/jmrit/operations/locations/tools/ImportLocationsActionTest.java
Labels: Needs L10N

#10548 Update command station type for Loconet over TCP
  help/en/html/hardware/digirails/index.shtml
Labels: Documentation

#10556 Only export and store rolling stock type names serviced by location and
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsAction.java
  java/test/jmri/util/swing/JemmyUtil.java
Labels: Add to Next Test Release, Documentation

#10557 J11: Refactoring of script selection GUI
  build.xml
  java/src/jmri/script/Bundle.properties
  java/src/jmri/script/Bundle_ca.properties
  java/src/jmri/script/Bundle_cs.properties
  java/src/jmri/script/Bundle_de.properties
  java/src/jmri/script/Bundle_fr.properties
  java/src/jmri/script/Bundle_nl.properties
  java/src/jmri/script/JmriScriptEngineManager.java
  java/src/jmri/script/swing/Bundle.properties
  java/src/jmri/script/swing/Bundle_ca.properties
  java/src/jmri/script/swing/Bundle_cs.properties
  java/src/jmri/script/swing/Bundle_da.properties
  java/src/jmri/script/swing/Bundle_de.properties
  java/src/jmri/script/swing/Bundle_es.properties
  java/src/jmri/script/swing/Bundle_fr.properties
  java/src/jmri/script/swing/Bundle_it.properties
  java/src/jmri/script/swing/Bundle_ja.properties
  java/src/jmri/script/swing/Bundle_ja_JP.properties
  java/src/jmri/script/swing/Bundle_nl.properties
  java/src/jmri/script/swing/InputWindow.java
  java/src/jmri/script/swing/ScriptEngineSelector.java
  java/src/jmri/script/swing/ScriptFileChooser.java
Labels: Needs L10N, Java 11

#10560 Show in table if C/I track is only for routing cars
  java/src/jmri/jmrit/operations/locations/InterchangeEditFrame.java
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/SpurEditFrame.java
  java/src/jmri/jmrit/operations/locations/StagingEditFrame.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/YardEditFrame.java
  java/src/jmri/jmrit/operations/locations/tools/TrackDestinationEditFrame.java
Labels: Add to Next Test Release, Needs L10N

#10563 Add LDH35 command station to CS read back
  java/src/jmri/jmrix/lenz/XNetBundle.properties
  java/src/jmri/jmrix/lenz/XNetConstants.java
  java/src/jmri/jmrix/lenz/swing/systeminfo/SystemInfoFrame.java
Labels: Needs L10N

#10567 Update Acknowledgements.shtml
  help/en/Acknowledgements.shtml
Labels: Documentation

#10566 Allow user to delete all cars at a location
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/DeleteCarRosterAction.java
Labels: Add to Next Test Release, Needs L10N

#10576 LogixNG - set throttle function
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/jmrit/logixng/Base.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionThrottle.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionThrottleXml.java
  java/src/jmri/jmrit/logixng/implementation/AbstractMaleSocket.java
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
  java/test/jmri/jmrit/logixng/actions/ActionThrottleTest.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  xml/schema/logixng/digital-actions/throttle-4.23.1.xsd
Labels: Needs L10N, New PR

#10447 Speed change checking
  java/src/jmri/implementation/SignalSpeedMap.java
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/NXFrame.java
  java/src/jmri/jmrit/logix/OBlock.java
  java/src/jmri/jmrit/logix/SpeedUtil.java
  java/src/jmri/jmrit/logix/ThrottleSetting.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantFrame.java
  java/src/jmri/jmrit/logix/WarrantManager.java
  java/src/jmri/jmrit/logix/WarrantTableAction.java
  java/src/jmri/jmrit/logix/WarrantTableModel.java
  java/src/jmri/jmrit/logix/configurexml/OBlockManagerXml.java
  java/test/jmri/jmrit/logix/LinkedWarrantTest.java
  java/test/jmri/jmrit/logix/NXFrameTest.java
  java/test/jmri/jmrit/logix/OBlockTest.java
  java/test/jmri/jmrit/logix/RampDataTest.java
  java/test/jmri/jmrit/logix/valid/ShortBlocksTest.xml
Labels: Add to Next Test Release, Needs L10N

#10579 Update Python 3 doc & release note
  help/en/html/tools/scripting/Python3.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation, New PR, Java 11

#10582 J11: rm Cucumber script
  java/test/apps/PanelPro/profiles/Prevent_Init_Loop/profile/profile.xml
Labels: Java 11

#10581 TurnoutManagers - remove changeListeners on dispose
  java/src/jmri/jmrit/beantable/LRouteTableAction.java
  java/src/jmri/managers/AbstractTurnoutManager.java
  java/test/jmri/jmrix/ipocs/IpocsSystemConnectionMemoTest.java
Labels: New PR

#10591 Show the current name when editing the title of a panel
  java/src/jmri/jmrit/display/panelEditor/PanelEditor.java
Labels: New PR

#10586 Show display name in tooltips
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/CoordinateEdit.java
  java/src/jmri/jmrit/display/DisplayBundle.properties
  java/src/jmri/jmrit/display/DisplayBundle_ca.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_da.properties
  java/src/jmri/jmrit/display/DisplayBundle_de.properties
  java/src/jmri/jmrit/display/DisplayBundle_fr.properties
  java/src/jmri/jmrit/display/DisplayBundle_it.properties
  java/src/jmri/jmrit/display/DisplayBundle_nl.properties
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/IndicatorTrackIcon.java
  java/src/jmri/jmrit/display/IndicatorTurnoutIcon.java
  java/src/jmri/jmrit/display/ToolTip.java
  java/src/jmri/jmrit/display/configurexml/PositionableLabelXml.java
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelEditor.java
  java/src/jmri/jmrit/display/controlPanelEditor/EditCircuitFrame.java
  java/src/jmri/jmrit/display/controlPanelEditor/PortalIcon.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/panelEditor/PanelEditor.java
  java/test/jmri/jmrit/display/PositionableTestBase.java
  java/test/jmri/jmrit/display/ToolTipTest.java
  xml/schema/types/editors.xsd
Labels: Needs L10N

#10610 Set accessible context name on representation
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/symbolicprog/CompositeVariableValue.java
  java/src/jmri/jmrit/symbolicprog/DecVarSlider.java
  java/src/jmri/jmrit/symbolicprog/DecVariableValue.java
  java/src/jmri/jmrit/symbolicprog/EnumVariableValue.java
  java/src/jmri/jmrit/symbolicprog/LongAddrVariableValue.java
Labels: New PR

#10614 Update JMRI help with the panel tooltip changes.
  help/en/html/apps/PanelPro/SidebarAppLocalPart.shtml
  help/en/package/jmri/jmrit/display/ControlPanelEditor.shtml
  help/en/package/jmri/jmrit/display/LayoutEditor.shtml
  help/en/package/jmri/jmrit/display/PanelEditor.shtml
  help/en/package/jmri/jmrit/display/Tooltips.shtml
  help/en/package/jmri/jmrit/display/images/PanelEditor.png
  help/en/package/jmri/jmrit/display/images/PanelEditor2.png
  help/en/package/jmri/jmrit/display/images/tooltips-cpe.png
  help/en/package/jmri/jmrit/display/images/tooltips-default.png
  help/en/package/jmri/jmrit/display/images/tooltips-le.png
  help/en/package/jmri/jmrit/display/images/tooltips-menu.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/ToolTip.java
  jython/ClearTooltips.py
Labels: Documentation, New PR

#10620 Correct LocoNet Attached Board programming range
  java/src/jmri/jmrit/progsupport/ProgOpsModePane.java
  java/src/jmri/jmrit/progsupport/ProgSupportBundle.properties
  java/src/jmri/jmrix/loconet/LnProgrammerManager.java
Labels: Needs L10N

#10630 Merge master into j11master
  help/en/html/apps/PanelPro/SidebarAppLocalPart.shtml
  help/en/package/jmri/jmrit/display/ControlPanelEditor.shtml
  help/en/package/jmri/jmrit/display/LayoutEditor.shtml
  help/en/package/jmri/jmrit/display/PanelEditor.shtml
  help/en/package/jmri/jmrit/display/Tooltips.shtml
  help/en/package/jmri/jmrit/display/images/PanelEditor.png
  help/en/package/jmri/jmrit/display/images/PanelEditor2.png
  help/en/package/jmri/jmrit/display/images/tooltips-cpe.png
  help/en/package/jmri/jmrit/display/images/tooltips-default.png
  help/en/package/jmri/jmrit/display/images/tooltips-le.png
  help/en/package/jmri/jmrit/display/images/tooltips-menu.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/dispatcher/AutoAllocate.java
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
  java/src/jmri/jmrit/display/CoordinateEdit.java
  java/src/jmri/jmrit/display/DisplayBundle.properties
  java/src/jmri/jmrit/display/DisplayBundle_ca.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_da.properties
  java/src/jmri/jmrit/display/DisplayBundle_de.properties
  java/src/jmri/jmrit/display/DisplayBundle_fr.properties
  java/src/jmri/jmrit/display/DisplayBundle_it.properties
  java/src/jmri/jmrit/display/DisplayBundle_nl.properties
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/IndicatorTrackIcon.java
  java/src/jmri/jmrit/display/IndicatorTurnoutIcon.java
  java/src/jmri/jmrit/display/ToolTip.java
  java/src/jmri/jmrit/display/configurexml/PositionableLabelXml.java
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelEditor.java
  java/src/jmri/jmrit/display/controlPanelEditor/EditCircuitFrame.java
  java/src/jmri/jmrit/display/controlPanelEditor/PortalIcon.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTurnoutView.java
  java/src/jmri/jmrit/display/panelEditor/PanelEditor.java
  java/src/jmri/jmrix/can/cbus/swing/eventtable/CbusEventTablePane.java
  java/test/jmri/LightTest.java
  java/test/jmri/jmrit/display/PositionableTestBase.java
  java/test/jmri/jmrit/display/ToolTipTest.java
  java/test/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorPaneTest.java
  java/test/jmri/jmrix/can/cbus/swing/eventtable/CbusEventTablePaneTest.java
  java/test/jmri/jmrix/dccpp/DCCppStreamPortControllerTest.java
  java/test/jmri/jmrix/xpa/XpaTurnoutManagerTest.java
  java/test/jmri/managers/ManagerDefaultSelectorTest.java
  java/test/jmri/managers/ProxyAnalogIOManagerTest.java
  java/test/jmri/util/ReflectionUtilScaffoldTest.java
  jython/ClearTooltips.py
  xml/decoders/MGP_Servo5.xml
  xml/schema/types/editors.xsd
Labels: Documentation, Needs L10N, New PR

#10629 Make throttle doc more accessible
  help/en/html/tools/throttle/SidebarToolLocalPart.shtml
  help/en/html/tools/throttle/ThrottleMain.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#10626 Update Apache Commons CSV to 1.9.0
  build.xml
  java/src/jmri/jmrit/ctc/ctcserialdata/ProjectsCommonSubs.java
  java/src/jmri/jmrit/ctc/editor/code/CommonSubs.java
  java/src/jmri/jmrix/rps/swing/debugger/DebuggerFrame.java
  jython/TurnoutStatePersistence.py
  lib/README.md
  lib/commons-csv-1.7.jar
  lib/commons-csv-1.9.0.jar
  pom.xml
Labels: New PR
