Repository JMRI/JMRI, pull requests merged in 2022-02, with the labels that each got.

#10634 Minor code cleanup.
  java/src/jmri/jmrit/operations/locations/InterchangeEditFrame.java
  java/src/jmri/jmrit/operations/locations/InterchangeTableModel.java
  java/src/jmri/jmrit/operations/locations/SpurEditFrame.java
  java/src/jmri/jmrit/operations/locations/SpurTableModel.java
  java/src/jmri/jmrit/operations/locations/StagingEditFrame.java
  java/src/jmri/jmrit/operations/locations/StagingTableModel.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/YardEditFrame.java
  java/src/jmri/jmrit/operations/locations/YardTableModel.java
Labels: Add to Next Test Release

#10641 Remove color attribute from Web Server OperationsPro comments
  java/src/jmri/jmrit/operations/trains/JsonManifest.java
  java/src/jmri/server/json/operations/JsonOperationsHttpService.java
  java/src/jmri/server/json/operations/JsonUtil.java
  java/src/jmri/web/servlet/operations/HtmlConductor.java
  java/src/jmri/web/servlet/operations/HtmlManifest.java
  java/src/jmri/web/servlet/operations/HtmlTrainCommon.java
  java/src/jmri/web/servlet/operations/OperationsServlet.java
Labels: Add to Next Test Release

#10640 Update creating custom functions using Jython
  help/en/html/tools/logixng/reference/chapter9.shtml
Labels: Documentation

#10637 Add "Open clipboard" to the LogixNG table Tools menu
  java/src/jmri/jmrit/beantable/AbstractLogixNGTableAction.java
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
Labels: New PR

#10645 Fix bug in ActionBlock
  java/src/jmri/jmrit/logixng/actions/ActionBlock.java
Labels: Bug

#10646 Code cleanup
  java/src/jmri/jmrit/operations/CommonConductorYardmasterPanel.java
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/YardmasterByTrackPanel.java
  java/src/jmri/jmrit/operations/locations/tools/ExportLocations.java
  java/src/jmri/jmrit/operations/locations/tools/TrackEditCommentsFrame.java
  java/src/jmri/jmrit/operations/trains/JsonManifest.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/jmrit/operations/trains/TrainCsvCommon.java
  java/src/jmri/jmrit/operations/trains/TrainCsvManifest.java
  java/src/jmri/jmrit/operations/trains/TrainCsvSwitchLists.java
  java/src/jmri/jmrit/operations/trains/TrainEditFrame.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/TrainManifest.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchListEditFrame.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchLists.java
  java/src/jmri/server/json/operations/JsonOperationsHttpService.java
  java/src/jmri/server/json/operations/JsonUtil.java
  java/src/jmri/web/servlet/operations/HtmlConductor.java
  java/src/jmri/web/servlet/operations/HtmlManifest.java
  java/src/jmri/web/servlet/operations/HtmlTrainCommon.java
  java/test/jmri/jmrit/operations/locations/LocationTest.java
  java/test/jmri/jmrit/operations/locations/XmlTest.java
  java/test/jmri/jmrit/operations/locations/tools/TrackEditCommentsFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainEditFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainSwitchListEditFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
  java/test/jmri/jmrit/operations/trains/XmlTest.java
  java/test/jmri/server/json/operations/JsonOperationsHttpServiceTest.java
Labels: Add to Next Test Release

#10643 Update LogixNG action Local Variable
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionLocalVariable.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionLocalVariableXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionLocalVariableSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  xml/schema/logixng/digital-actions/action-local-variable-4.23.1.xsd
Labels: Needs L10N

#10642 Update Typescript methodology
  .github/workflows/typescript-check.yml
  help/en/html/doc/Technical/Patterns.shtml
  help/en/releasenotes/current-draft-note.shtml
  web/ts/bootstrap.js
  web/ts/bootstrap.min.js
  web/ts/build.xml
  web/ts/faq.js
  web/ts/frame_server_ajax.js
  web/ts/here.js
  web/ts/home.js
  web/ts/jquery-1.11.2.min.js
  web/ts/jquery-1.8.2.min.js
  web/ts/jquery-2.0.3.min.js
  web/ts/jquery-2.2.4.min.js
  web/ts/jquery.fileupload.js
  web/ts/jquery.iframe-transport.js
  web/ts/jquery.jmri.js
  web/ts/jquery.jmriConnect.js
  web/ts/jquery.jscrollpane.min.js
  web/ts/jquery.mobile-1.2.0.min.js
  web/ts/jquery.mousewheel.js
  web/ts/jquery.qrcode.min.js
  web/ts/jquery.tmpl.min.js
  web/ts/jquery.ui.widget.js
  web/ts/jquery.websocket.js
  web/ts/json-console.js
  web/ts/json2.js
  web/ts/logger.js
  web/ts/main.js
  web/ts/modernizr-2.6.2-respond-1.1.0.min.js
  web/ts/npm.js
  web/ts/operations.js
  web/ts/panel.js
  web/ts/roster.js
  web/ts/simple-console.js
  web/ts/sorttable.js
  web/ts/tables.js
  web/ts/user.js
  web/ts/webThrottle.js
Labels: Documentation

#10648 Add a new contributor to Acknowledgements
  help/en/Acknowledgements.shtml
Labels: Documentation

#10649 20220130 auto trains
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/dispatcher/ActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoTrainsFrame.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
  java/test/jmri/jmrit/dispatcher/AutoTrainsFrameStopManualTest.java
Labels: Needs L10N

#10657 Improve operations "Yardmaster by track" tool
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/locations/YardmasterByTrackPanel.java
Labels: Add to Next Test Release, Needs L10N

#10656 J11: use native annotation
  java/src/jmri/Generated.java
  java/src/jmri/jmris/simpleserver/parser/package-info.java
  java/src/jmri/jmris/srcp/parser/package-info.java
  java/src/jmri/jmrix/srcp/parser/package-info.java
Labels: Java 11

#10659 Release rolling stock from trains that fail to build
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
Labels: Add to Next Test Release, Documentation, Needs L10N

#10662 On storing user files in Git
  help/en/html/setup/git.shtml
Labels: Documentation

#10664 Redo #10660: Create a window showing RFID tags with associated Cars
  help/en/html/hardware/rfid/index.shtml
  help/en/package/jmri/jmrix/rfid/swing/tagcarwin/TagMonitorPane.shtml
  help/en/package/jmri/jmrix/rfid/swing/tagcarwin/images/MonitorTags.png
  help/en/package/jmri/jmrix/rfid/swing/tagcarwin/images/MonitorTagsDefault.png
  help/en/package/jmri/jmrix/rfid/swing/tagcarwin/images/MonitorTimeDuplicates.png
  help/en/package/jmri/jmrix/rfid/swing/tagcarwin/images/SetCarWindow.png
  help/en/package/jmri/jmrix/rfid/swing/tagcarwin/images/SettingLocation.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/JmrixBundle.properties
  java/src/jmri/jmrix/rfid/swing/RfidMenu.java
  java/src/jmri/jmrix/rfid/swing/tagcarwin/AssociateFrame.java
  java/src/jmri/jmrix/rfid/swing/tagcarwin/AssociateTag.java
  java/src/jmri/jmrix/rfid/swing/tagcarwin/Bundle.java
  java/src/jmri/jmrix/rfid/swing/tagcarwin/TableDataModel.java
  java/src/jmri/jmrix/rfid/swing/tagcarwin/TagCarItem.java
  java/src/jmri/jmrix/rfid/swing/tagcarwin/TagMonitorPane.java
  java/test/jmri/jmrix/rfid/swing/tagcarwin/TagMonitorPaneTest.java
Labels: Documentation, Needs L10N

#10663 Add DS74 as device IPL type, add UR93 and LNWI to duplex configuration.
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/DuplexGroup.properties
  java/src/jmri/jmrix/loconet/duplexgroup/swing/DuplexGroupInfoPanel.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/DuplexGroupTabbedPanel.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/LnDplxGrpInfoImpl.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/LnIPLImplementation.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/duplexgroup/swing/LnDplxGrpInfoImplTest.java
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Needs L10N

#10639 Prevent shared warrants from allocating blocks beyond stop conditions.
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/LearnSpeedPanel.java
  java/src/jmri/jmrit/logix/NXFrame.java
  java/src/jmri/jmrit/logix/OBlock.java
  java/src/jmri/jmrit/logix/RampData.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantFrame.java
  java/src/jmri/jmrit/logix/WarrantTableFrame.java
  java/src/jmri/jmrit/logix/WarrantTableModel.java
  java/test/jmri/jmrit/logix/EngineerTest.java
  java/test/jmri/jmrit/logix/LearnWarrantTest.java
  java/test/jmri/jmrit/logix/LinkedWarrantTest.java
  java/test/jmri/jmrit/logix/RampDataTest.java
Labels: Needs L10N

#10670 Throttles ctrl update
  help/en/html/tools/throttle/AdvancedThrottleControl.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/throttle/ThrottleFrame.java
  java/src/jmri/jmrit/throttle/ThrottleWindow.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesWindowKeyboardControls.java
Labels: Documentation, New PR

#10675 Update ScaleTrackDiagramDialog Test
  java/test/jmri/jmrit/display/layoutEditor/LayoutEditorDialogs/ScaleTrackDiagramDialogTest.java
Labels: New PR

#10674 Webserver display of Slip/Crossover Panel icons
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/SlipTurnoutIcon.java
  java/src/jmri/jmrit/display/configurexml/SlipTurnoutIconXml.java
  java/src/jmri/server/json/turnout/JsonTurnout.java
  java/src/jmri/web/servlet/panel/ControlPanelServlet.java
  web/js/panel.js
Labels: Enhancement

#10681 Delay getting dispatcher until later - AutoTrain tests now work.
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
Labels: New PR

#10684 Switchboard Display name option
  help/en/package/jmri/jmrit/display/SwitchboardEditor.shtml
  help/en/package/jmri/jmrit/display/images/SwitchboardMenu.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/DisplayBundle.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_de.properties
  java/src/jmri/jmrit/display/DisplayBundle_nl.properties
  java/src/jmri/jmrit/display/switchboardEditor/BeanSwitch.java
  java/src/jmri/jmrit/display/switchboardEditor/SwitchboardEditor.java
  java/src/jmri/jmrit/display/switchboardEditor/configurexml/SwitchboardEditorXml.java
  java/test/jmri/jmrit/display/switchboardEditor/SwitchboardEditorTest.java
  xml/schema/types/switchboardeditor.xsd
Labels: Enhancement, Needs L10N, New PR

#10682 Add some accessibility test info to JUnit doc page
  help/en/html/doc/Technical/JUnit.shtml
  java/test/jmri/util/AccessibilityChecksTest.java
Labels: Documentation, New PR

#10687 Update Accessibility tests
  java/test/jmri/jmrit/beantable/ListedTableFrameTest.java
  java/test/jmri/util/AccessibilityChecksTest.java
Labels: New PR

#10686 Fix one bug, add a Clear button, minor code cleanup in RFID tag Car Window
  java/src/jmri/jmrix/rfid/swing/tagcarwin/AssociateTag.java
  java/src/jmri/jmrix/rfid/swing/tagcarwin/TableDataModel.java
  java/src/jmri/jmrix/rfid/swing/tagcarwin/TagMonitorPane.java
Labels: New PR

#10679 Improve LogixNG actions and expressions LocalVariable and Memory
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/AbstractLogixNGTableAction.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionLocalVariable.java
  java/src/jmri/jmrit/logixng/actions/ActionMemory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionLocalVariableXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionMemoryXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionEntryExitSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionLightIntensitySwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionLightSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionLocalVariableSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionMemorySwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionScriptSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionSensorSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionSignalHeadSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionSignalMastSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionTurnoutLockSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionTurnoutSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionLocalVariable.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionMemory.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionLocalVariableXml.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionMemoryXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionLocalVariableSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionMemorySwing.java
  java/src/jmri/jmrit/logixng/swing/AbstractSwingConfigurator.java
  java/src/jmri/jmrit/logixng/swing/Bundle.java
  java/src/jmri/jmrit/logixng/swing/LogixNG_DataDialog.java
  java/src/jmri/jmrit/logixng/swing/SwingBundle.properties
  java/src/jmri/jmrit/logixng/swing/SwingConfiguratorInterface.java
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
  java/test/jmri/jmrit/logixng/ActionsAndExpressionsTest.java
  java/test/jmri/jmrit/logixng/FemaleSocketTestBase.java
  java/test/jmri/jmrit/logixng/configurexml/LogixNG_ActionMemory_ActionLocalVariable.csv
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG_ActionMemory_ActionLocalVariable - 4.99.2.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG_ActionMemory_ActionLocalVariable - 4.99.2.xml
  xml/schema/logixng/digital-actions/action-local-variable-4.23.1.xsd
  xml/schema/logixng/digital-actions/action-memory-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-local-variable-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-memory-4.23.1.xsd
Labels: Needs L10N

#10701 Add headless check to some tests
  java/test/jmri/jmrit/logixng/ActionsAndExpressionsTest.java
  java/test/jmri/jmrit/logixng/FemaleSocketTestBase.java
Labels: New PR

#10698 Update MQTT SignalMast and Reporter doc
  help/en/html/hardware/mqtt/index.shtml
Labels: Documentation

#10702 Update to CI documentation page to current structure
  help/en/html/doc/Technical/ContinuousIntegration.shtml
Labels: Documentation

#10706 Fix timeout reporter compare
  java/src/jmri/implementation/decorators/AbstractNamedBeanDecorator.java
  java/test/jmri/implementation/decorators/TimeoutReporterTest.java
  java/test/jmri/jmrit/operations/locations/LocationManagerTest.java
Labels: Bug

#10710 Update logixng help
  help/en/html/tools/logixng/reference/chapter11.shtml
  help/en/html/tools/logixng/reference/chapter2.shtml
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/images/chapter11/select_col.png
  help/en/html/tools/logixng/reference/images/chapter11/select_done.png
  help/en/html/tools/logixng/reference/images/chapter11/select_row.png
  help/en/html/tools/logixng/reference/images/chapter11/select_sample.png
  help/en/html/tools/logixng/reference/images/chapter11/select_table.png
  help/en/html/tools/logixng/reference/images/chapter11/table_cell_selection.png
  help/en/html/tools/logixng/reference/images/chapter5/execute_delay.png
  help/en/html/tools/logixng/reference/images/chapter5/throttle_action.png
  help/en/package/jmri/jmrit/beantable/LogixNGModuleTable.shtml
  help/en/package/jmri/jmrit/beantable/LogixNGTable.shtml
  help/en/package/jmri/jmrit/beantable/LogixNGTableTable.shtml
  help/en/package/jmri/jmrit/logixng/LogixImport.shtml
  help/en/package/jmri/jmrit/logixng/images/ExportConfirmation.png
  help/en/package/jmri/jmrit/logixng/images/ExportLogix.png
  help/en/package/jmri/jmrit/logixng/images/ImportConfirmation.png
  java/src/jmri/jmrit/logixng/actions/ActionLocalVariable.java
  java/src/jmri/jmrit/logixng/tools/swing/ImportLogixFrame.java
Labels: Documentation

#10713 Better handling of Intellibox functions
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/Ib1Throttle.java
  java/src/jmri/jmrix/loconet/Ib2Throttle.java
  java/src/jmri/jmrix/loconet/LocoNetThrottle.java
Labels: Documentation

#10714 Fix test errors
  java/test/jmri/jmrit/operations/rollingstock/cars/CarSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarsSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarsTableFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineSetFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderGuiTest.java
  java/test/jmri/jmrit/operations/trains/TrainConductorFrameTest.java
  java/test/jmri/jmrit/operations/trains/TrainsTableFrameTest.java
Labels: Add to Next Test Release

#10718 DP extraMenu update
  java/src/jmri/jmrit/roster/LocoFile.java
  java/src/jmri/jmrit/symbolicprog/ExtraMenuTableModel.java
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
  java/test/jmri/util/RosterTestUtil.java
  xml/decoders/zimo/LoadCalibrationExtraMenu.xml
  xml/decoders/zimo/PseudoIncrementalExtraMenu.xml
Labels: New PR

#10720 Copy LogixNG
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/AbstractLogixNGTableAction.java
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/LogixNGTableAction.java
Labels: Needs L10N

#10723 Add OperationsPro only to JUnit test suite
  default.lcf
  java/test/apps/tests/JUnitOperationsTests.java
Labels: Add to Next Test Release

#10705 210Plus
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/LnCommandStationType.java
  java/src/jmri/jmrix/loconet/LnConnectionTypeList.java
  java/src/jmri/jmrix/loconet/LnPortController.java
  java/src/jmri/jmrix/loconet/LocoNetBundle.properties
  java/src/jmri/jmrix/loconet/cmdstnconfig/CmdStnConfigPane.java
  java/src/jmri/jmrix/loconet/cmdstnconfig/DCS210Plusoptions.properties
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/Bundle.java
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/COPYING
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/ConnectionConfig.java
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/UsbDcs210PlusAdapter.java
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/UsbDcs210PlusBundle.properties
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/UsbDcs210PlusSystemConnectionMemo.java
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/configurexml/COPYING
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/configurexml/ConnectionConfigXml.java
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/swing/Bundle.java
  java/src/jmri/jmrix/loconet/usb_dcs210Plus/swing/Dcs210PlusUsbModeSelectPane.java
  java/test/jmri/jmrix/loconet/LnCommandStationTypeTest.java
  java/test/jmri/jmrix/loconet/usb_dcs210Plus/BundleTest.java
  java/test/jmri/jmrix/loconet/usb_dcs210Plus/ConnectionConfigTest.java
  java/test/jmri/jmrix/loconet/usb_dcs210Plus/UsbDcs210PlusAdapterTest.java
  java/test/jmri/jmrix/loconet/usb_dcs210Plus/UsbDcs210PlusSystemConnectionMemoTest.java
  java/test/jmri/jmrix/loconet/usb_dcs210Plus/configurexml/ConnectionConfigXmlTest.java
  java/test/jmri/jmrix/loconet/usb_dcs210Plus/swing/BundleTest.java
  java/test/jmri/jmrix/loconet/usb_dcs210Plus/swing/Dcs210PlusUsbModeSelectPaneTest.java
Labels: Needs L10N

#10726 Update LogixNG Copy references
  help/en/package/jmri/jmrit/beantable/LogixNGModuleTable.shtml
  help/en/package/jmri/jmrit/beantable/LogixNGTable.shtml
  help/en/package/jmri/jmrit/beantable/LogixNGTableTable.shtml
  help/en/package/jmri/jmrit/logixng/images/CopyLogixNG.png
  help/en/package/jmri/jmrit/logixng/images/SelectActions.png
  help/en/package/jmri/jmrit/logixng/images/SelectActionsNoCopy.png
Labels: Documentation

#10728 Export only modified CVs (Issue 10623)
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/symbolicprog/CsvExportAction.java
  java/src/jmri/jmrit/symbolicprog/CsvExportModifiedAction.java
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
Labels: Needs L10N

#10727 Minor Operations GUI change in Edit Car
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/trains/tools/TrainsScriptFrame.java
Labels: Add to Next Test Release, Documentation, Needs L10N

#10694 Refactor LogixNG
  java/src/jmri/jmrit/logixng/LogixNGBundle.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionLocalVariable.java
  java/src/jmri/jmrit/logixng/actions/ActionMemory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionLocalVariableXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionMemoryXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionLocalVariableSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionMemorySwing.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionLocalVariable.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionMemory.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionLocalVariableXml.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionMemoryXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionLocalVariableSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionMemorySwing.java
  java/src/jmri/jmrit/logixng/implementation/AbstractBase.java
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectTable.java
  java/src/jmri/jmrit/logixng/util/configurexml/LogixNG_SelectTableXml.java
  java/src/jmri/jmrit/logixng/util/swing/Bundle.java
  java/src/jmri/jmrit/logixng/util/swing/LogixNG_SelectTableSwing.java
  java/src/jmri/jmrit/logixng/util/swing/SwingBundle.properties
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
Labels: Needs L10N

#10731 Fix LogixNG bug
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectTable.java
Labels: Bug, New PR

#10703 cbus modules 3
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/node/CbusNodeNVManager.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeTableDataModel.java
  java/src/jmri/jmrix/can/cbus/swing/modules/CbusModulesCommon.java
  java/src/jmri/jmrix/can/cbus/swing/modules/CmdStaFlags.java
  java/src/jmri/jmrix/can/cbus/swing/modules/TitledSlider.java
  java/src/jmri/jmrix/can/cbus/swing/modules/TitledSpinner.java
  java/src/jmri/jmrix/can/cbus/swing/modules/UpdateNV.java
  java/src/jmri/jmrix/can/cbus/swing/modules/base/Servo8BaseEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/base/Sol8BaseEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/merg/CanCmdEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/merg/Canacc8EditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/Sprog3PlusEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/CbusNodeEditNVarPane.java
  java/test/jmri/jmrix/can/cbus/swing/modules/CmdStaFlagsTest.java
  java/test/jmri/jmrix/can/cbus/swing/modules/TitledSliderTest.java
  java/test/jmri/jmrix/can/cbus/swing/modules/TitledSpinnerTest.java
Labels: Needs L10N

#10733 Add note about updating dispatcher train info file
  help/en/package/jmri/jmrit/dispatcher/NewTrain.shtml
Labels: Documentation

#10736 DecoderPro media pane documentation update.
  help/en/html/tools/throttle/RostersMediaPane.shtml
  help/en/html/tools/throttle/images/DecProFunctionLabels.png
  help/en/html/tools/throttle/images/DecProRosterMediaPane.png
Labels: Documentation

#10738 WarrantLastBlockFixes
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/SCWarrant.java
  java/src/jmri/jmrit/logix/ThrottleSetting.java
  java/src/jmri/jmrit/logix/Tracker.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantTableModel.java
  java/test/jmri/jmrit/logix/EngineerTest.java
  java/test/jmri/jmrit/logix/valid/ShortBlocksTest.xml
Labels: Needs L10N
