Repository JMRI/JMRI, pull requests merged in 2022-06, with the labels that each got.

#11051 Test improvements for XML-comparison intermittent Windows CI fail
  .github/workflows/windows-test.yml
  java/test/jmri/jmrit/display/panelEditor/load/IconSample.xml
  java/test/jmri/jmrit/display/panelEditor/loadref/IconSample.xml
  java/test/jmri/jmrit/display/panelEditor/loadref/macos/IconSample.xml.1.png
  java/test/jmri/jmrit/display/panelEditor/loadref/windows/IconSample.xml.1.png
Labels: dev/test/publish infrastructure

#11064 Add two new operations automation actions, reset switch lists and print
  java/src/jmri/jmrit/operations/automation/AutomationItem.java
  java/src/jmri/jmrit/operations/automation/JmritOperationsAutomationBundle.properties
  java/src/jmri/jmrit/operations/automation/JmritOperationsAutomationBundle_fr.properties
  java/src/jmri/jmrit/operations/automation/actions/ActionCodes.java
  java/src/jmri/jmrit/operations/automation/actions/GenerateSwitchListChangesAction.java
  java/src/jmri/jmrit/operations/automation/actions/PrintSwitchListChangesAction.java
  java/src/jmri/jmrit/operations/automation/actions/PrintTrainBuildReportAction.java
  java/src/jmri/jmrit/operations/automation/actions/ResetSwitchListsAction.java
  java/src/jmri/jmrit/operations/automation/actions/RunSwitchListChangesAction.java
  java/src/jmri/jmrit/operations/locations/LocationManager.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchListEditFrame.java
  java/test/jmri/jmrit/operations/OperationsTestCase.java
  java/test/jmri/jmrit/operations/automation/AutomationItemTest.java
  java/test/jmri/jmrit/operations/automation/actions/PrintTrainBuildReportActionTest.java
  java/test/jmri/jmrit/operations/automation/actions/ResetSwitchListsActionTest.java
Labels: Add to Next Test Release, Needs L10N

#11067 Minor Spanish L10N corrections/additions
  java/src/apps/util/issuereporter/swing/Bundle_es.properties
  java/src/jmri/NamedBeanBundle_es.properties
Labels: Needs L10N

#11066 New Massoth decoder - Issue #11063
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/Massoth_pulsed_smoke_8415001.xml
Labels: Documentation

#11072 Add tests targets for spotbugs
  .gitignore
  build.xml
  help/en/Acknowledgements.shtml
Labels: dev/test/publish infrastructure

#11077 Implement PanelPro table and panel change detection and notification
  help/en/package/apps/TabbedPreferences.shtml
  help/en/package/apps/images/PrefsShutdown.png
  help/en/package/apps/images/StoreRequest.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/AppsMainMenu.java
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/configurexml/Bundle.properties
  java/src/jmri/configurexml/ShutdownPreferences.java
  java/src/jmri/configurexml/StoreAndCompare.java
  java/src/jmri/configurexml/StoreXmlUserAction.java
  java/src/jmri/configurexml/swing/Bundle.java
  java/src/jmri/configurexml/swing/Bundle.properties
  java/src/jmri/configurexml/swing/ShutdownPreferencesPanel.java
  java/src/jmri/configurexml/swing/StoreAndCompareDialog.java
  java/src/jmri/jmrit/display/EditorManager.java
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelEditorAction.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorAction.java
  java/src/jmri/jmrit/display/panelEditor/PanelEditorAction.java
  java/src/jmri/jmrit/display/switchboardEditor/SwitchboardEditorAction.java
  java/src/jmri/managers/DefaultShutDownManager.java
  java/test/jmri/configurexml/ShutdownPreferencesTest.java
  java/test/jmri/configurexml/StoreAndCompareTest.java
  java/test/jmri/configurexml/swing/BundleTest.java
  java/test/jmri/configurexml/swing/ShutdownPreferencesPanelTest.java
  java/test/jmri/configurexml/swing/StoreAndCompareDialogTest.java
  java/test/jmri/util/JUnitUtil.java
Labels: Needs L10N

#11078 Fix Spotbugs DCN_NULLPOINTER_EXCEPTION warnings
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/LocationManager.java
  java/src/jmri/jmrit/operations/rollingstock/engines/Engine.java
Labels: Documentation

#11075 Don't change parent for female sockets
  java/src/jmri/jmrit/logixng/actions/ActionListenOnBeans.java
  java/src/jmri/jmrit/logixng/implementation/AbstractBase.java
  java/src/jmri/jmrit/logixng/implementation/AbstractMaleSocket.java
Labels: New PR

#11076 merge profile
  java/src/jmri/jmrit/automat/AbstractAutomaton.java
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/NXFrame.java
  java/src/jmri/jmrit/logix/OBlock.java
  java/src/jmri/jmrit/logix/RampData.java
  java/src/jmri/jmrit/logix/SCWarrant.java
  java/src/jmri/jmrit/logix/SpeedUtil.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantFrame.java
  java/src/jmri/jmrit/logix/WarrantRoute.java
  java/src/jmri/jmrit/logix/WarrantTableModel.java
  java/test/jmri/jmrit/logix/RampDataTest.java
Labels: Needs L10N

#11092 Force store check enabled to false for tests
  java/test/jmri/util/JUnitUtil.java
Labels: New PR

#11086 Nexttrain, restarts, delays
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/dispatcher/ActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AllocatedSection.java
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoAllocate.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
  java/src/jmri/jmrit/dispatcher/TrainInfo.java
  java/src/jmri/jmrit/dispatcher/TrainInfoFile.java
  java/src/jmri/jmrit/display/BlockContentsIcon.java
  java/src/jmri/jmrit/display/MemoryIcon.java
  java/test/jmri/jmrit/dispatcher/AutoTrainsMultiBlockStopTest.java
  java/test/jmri/jmrit/dispatcher/DispatcherSMLLayout.xml
  java/test/jmri/jmrit/dispatcher/DispatcherTrainInfoFileTest.java
  java/test/jmri/jmrit/dispatcher/LoadAtStartUpTest.java
  java/test/jmri/jmrit/dispatcher/MultiBlockStop.xml
  java/test/jmri/jmrit/dispatcher/traininfo/FWDREV120.xml
  java/test/jmri/jmrit/dispatcher/traininfo/TestTrainCW.xml
  java/test/jmri/jmrit/dispatcher/traininfo/TestTrainCW_Return.xml
  java/test/jmri/jmrit/dispatcher/traininfo/TestTrainCW_V2.xml
  xml/DTD/dispatcher-traininfo.dtd
Labels: Needs L10N

#11095 Update LogixNG Help
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/chapter7.shtml
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_script.png
  help/en/html/tools/logixng/reference/images/chapter6/digital_expression_script.png
  help/en/html/tools/logixng/reference/images/chapter6/script_expression.png
Labels: Documentation

#11098 Improve test coverage
  java/src/jmri/jmrit/operations/automation/AutomationsTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/engines/Engine.java
  java/test/jmri/jmrit/operations/automation/AutomationsTableFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/EngineAttributeEditFrameTest.java
Labels: Add to Next Test Release

#11105 Minor operations help update
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Add to Next Test Release, Documentation

#11102 Add option to remove channel from MQTT topic
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/mqtt/logixng/Subscribe.java
  java/src/jmri/jmrix/mqtt/logixng/configurexml/SubscribeXml.java
  java/src/jmri/jmrix/mqtt/logixng/swing/Bundle.properties
  java/src/jmri/jmrix/mqtt/logixng/swing/SubscribeSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  xml/schema/logixng/digital-actions/mqtt-subscribe-4.99.7.xsd
Labels: Needs L10N

#11106 Some jmrit Tests Spotbugs
  java/test/jmri/DccLocoAddressTest.java
  java/test/jmri/implementation/DefaultCabSignalIT.java
  java/test/jmri/jmrit/entryexit/AddEntryExitPairPanelTest.java
  java/test/jmri/jmrit/entryexit/EntryExitTestTools.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineTest.java
  java/test/jmri/jmrit/operations/router/OperationsCarRouterTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/simpleclock/SimpleTimebaseTest.java
  java/test/jmri/jmrit/symbolicprog/CvValueTest.java
Labels: New PR

#11117 Enhance operations passenger car blocking feature
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/CommonConductorYardmasterPanel.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/trains/JsonManifest.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/jmrit/operations/trains/TrainCsvManifest.java
  java/src/jmri/jmrit/operations/trains/TrainCsvSwitchLists.java
  java/src/jmri/jmrit/operations/trains/tools/ShowCarsInTrainFrame.java
  java/src/jmri/web/servlet/operations/HtmlConductor.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarManagerTest.java
Labels: Add to Next Test Release, Documentation

#11122 Fix print preview bug
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsByCarTypesAction.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarLoadsAction.java
  java/src/jmri/jmrit/operations/trains/TrainPrintUtilities.java
  java/src/jmri/jmrit/roster/PrintListAction.java
  java/src/jmri/util/davidflanagan/HardcopyWriter.java
Labels: Add to Next Test Release

#11124 Add separator, required for Linux
  java/src/jmri/configurexml/StoreAndCompare.java
Labels: New PR

#11103 New logix Conditional Actions
  java/src/jmri/Conditional.java
  java/src/jmri/implementation/DefaultConditional.java
  java/src/jmri/implementation/DefaultConditionalAction.java
  java/src/jmri/implementation/DefaultConditionalExecute.java
  java/src/jmri/jmrit/conditional/ConditionalBundle.properties
  java/src/jmri/jmrit/conditional/ConditionalEditFrame.java
  java/src/jmri/jmrit/conditional/ConditionalTreeEdit.java
  java/src/jmri/jmrit/display/IndicatorTrackPaths.java
  java/src/jmri/jmrit/logix/NXFrame.java
  java/src/jmri/jmrit/logix/SpeedUtil.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantFrame.java
  java/src/jmri/jmrit/logix/WarrantTableAction.java
  java/src/jmri/jmrit/logix/WarrantTableFrame.java
  java/src/jmri/jmrit/logix/WarrantTableModel.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionWarrant.java
  java/src/jmri/jmrit/logixng/tools/ImportConditional.java
  java/test/jmri/ConditionalTest.java
  java/test/jmri/implementation/DefaultConditionalActionTest.java
  java/test/jmri/jmrit/logix/NXFrameTest.java
  java/test/jmri/jmrit/logix/WarrantTest.java
Labels: Needs L10N

#11125 Dispatcher - Fix traininfo problems
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
  java/src/jmri/jmrit/dispatcher/TrainInfo.java
  java/src/jmri/jmrit/dispatcher/TrainInfoFile.java
Labels: Needs L10N, New PR

#11126 Operations car loads can now be classified as hazardous
  java/src/jmri/jmrit/operations/rollingstock/cars/Car.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLoad.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLoads.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarLoadEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/ImportCars.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarLoadsAction.java
  java/src/jmri/server/json/operations/JsonOperationsHttpService.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarLoadsTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarsTest.java
Labels: New PR

#11127 SwingUtilities.isRightMouseButton() doesn't always work on Windows
  java/src/jmri/util/swing/JmriMouseEvent.java
Labels: Bug, New PR

#11128 Break failing operations GUI test into smaller tests.
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/EditCarLoads.png
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLoads.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarAttributeEditFrameTest.java
Labels: Documentation, New PR

#11131 Update MQTT documentation for clarity, new features
  help/en/html/hardware/mqtt/images/MQTTLogixNGPublish.jpg
  help/en/html/hardware/mqtt/images/MQTTLogixNGSubscribe.jpg
  help/en/html/hardware/mqtt/images/MQTTPrefs_example.jpg
  help/en/html/hardware/mqtt/images/MQTTPrefs_rel5_0.jpg
  help/en/html/hardware/mqtt/images/MQTTSchematic.JPG
  help/en/html/hardware/mqtt/images/MQTT_Preferences_rel4_21_2.png
  help/en/html/hardware/mqtt/index.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#11133 Update no file checks; move Store and Compare menu item from File to Debug
  java/src/apps/AppsMainMenu.java
  java/src/apps/jmrit/DebugMenu.java
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/NamedBeanBundle_es.properties
  java/src/jmri/configurexml/StoreAndCompare.java
  java/src/jmri/jmrit/Bundle.properties
Labels: Needs L10N
