Repository JMRI/JMRI, pull requests merged in 2023-05, with the labels that each got.

#11996 Update Acknowledgements.shtml
  help/en/Acknowledgements.shtml
Labels: New PR

#11999 Add CreateJmriApps.sh script for the Linux install
  help/en/releasenotes/current-draft-note.shtml
  scripts/Linux/CreateJmriApps.sh
Labels: New PR

#12005 Logixng WebRequestTest - assert Warnings
  java/test/jmri/jmrit/logixng/actions/WebRequestTest.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
Labels: New PR

#12006 Verify XBee nodes can load without the optional connection config
  java/src/jmri/jmrix/ieee802154/xbee/configurexml/ConnectionConfigXml.java
  java/test/jmri/jmrix/ieee802154/xbee/configurexml/ConnectionConfigXmlTest.java
Labels: New PR

#12014 Add help page mapping Logix features to LogixNG
  help/en/html/tools/logixng/reference/chapter1.shtml
  help/en/html/tools/logixng/reference/chapter1_1.shtml
  help/en/html/tools/logixng/reference/images/chapter1_1/else_if.png
  help/en/html/tools/logixng/reference/images/chapter1_1/listen.png
  help/en/html/tools/logixng/reference/images/chapter1_1/logix.png
  help/en/html/tools/logixng/reference/images/chapter1_1/nested_if.png
  help/en/html/tools/logixng/reference/images/chapter1_1/script_action.png
  help/en/html/tools/logixng/reference/images/chapter1_1/tabs.png
  help/en/html/tools/logixng/reference/index.shtml
Labels: Documentation

#12020 Update release notes for operations
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle.properties
  java/src/jmri/jmrit/operations/router/Router.java
Labels: Needs L10N

#12023 Add new Raspberry Pi install page to the install sidebar
  help/en/parts/SidebarInstall.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#12027 OperationsPro, minor improvements to build report
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
Labels: Needs L10N

#12038 OperationsPro Show car and loco previous locations
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_nl.properties
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/Xml.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/ImportCars.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_nl.properties
  jython/anyrail/AnyRailExportAdditions.py
  xml/DTD/operations-cars.dtd
  xml/DTD/operations-config.dtd
  xml/DTD/operations-engines.dtd
Labels: Needs L10N

#12039 Add git sharing link
  help/en/html/setup/Dropbox.shtml
  help/en/html/setup/git.shtml
Labels: Documentation

#12043 Lionel TMCC 2 update
  help/en/html/hardware/tmcc/index.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/tmcc/SerialMessage.java
  java/src/jmri/jmrix/tmcc/SerialThrottle.java
  java/src/jmri/jmrix/tmcc/SerialTrafficController.java
  java/src/jmri/jmrix/tmcc/serialmon/SerialMonFrame.java
  java/test/jmri/jmrix/tmcc/SerialMessageTest.java
  java/test/jmri/jmrix/tmcc/SerialThrottleTest.java
  xml/decoderIndex.xml
  xml/decoders/Lionel-TMCC-Steam.xml
  xml/nmra_mfg_list.xml
Labels: Documentation

#12045 Tiny MQTT doc update
  help/en/html/hardware/mqtt/index.shtml
Labels: Documentation

#12046 OperationsPro, Build report improvement, show number of locos and cars at each location
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
Labels: Needs L10N

#12047 Update LE Tools => Check bezier options
  help/en/package/jmri/jmrit/display/LayoutEditor.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorChecks.java
Labels: Documentation

#12052 Update for JOAL on Apple Silicon
  build.xml
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  lib/README.md
  lib/gluegen-rt.jar
  lib/gluegen.jar
  lib/joal-2.3.1-packagelist
  lib/joal.jar
  lib/macosx/libgluegen_rt.dylib
  lib/macosx/libjoal.dylib
  lib/macosx/libopenal.dylib
Labels: Documentation

#12054 Add Variable export
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/symbolicprog/CsvExportVariablesAction.java
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
Labels: Needs L10N

#12066 Update LogixNG WebRequest Test
  java/test/jmri/jmrit/logixng/actions/WebRequestTest.java
Labels: New PR

#12064 Medium semaphore icons from James Cunningham for BR-2003
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  resources/icons/BritishRailSignals/Medium/index.php
  resources/icons/BritishRailSignals/Medium/semaDistantCaution.gif
  resources/icons/BritishRailSignals/Medium/semaDistantProceed.gif
  resources/icons/BritishRailSignals/Medium/semaHomeCallOn(ws).gif
  resources/icons/BritishRailSignals/Medium/semaHomeClear(ws).gif
  resources/icons/BritishRailSignals/Medium/semaHomeDanger(ws).gif
  resources/icons/BritishRailSignals/Medium/semaHomeDanger.gif
  resources/icons/BritishRailSignals/Medium/semaHomeDistantCaution.gif
  resources/icons/BritishRailSignals/Medium/semaHomeDistantDanger.gif
  resources/icons/BritishRailSignals/Medium/semaHomeDistantProceed.gif
  resources/icons/BritishRailSignals/Medium/semaHomeProceed.gif
  xml/signals/BR-2003/appearance-2-d-sema.xml
  xml/signals/BR-2003/appearance-2-h-d-sema.xml
  xml/signals/BR-2003/appearance-2-h-sema-sub.xml
  xml/signals/BR-2003/appearance-2-h-sema.xml
  xml/signals/BR-2003/aspects.xml
  xml/signals/BR-2003/index.shtml
Labels: Documentation

#12068 Improve DP import option labels
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_ca.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_cs.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_da.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_de.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_es.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_fr.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_it.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_nl.properties
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
Labels: Needs L10N

#12074 OperationsPro, Export Locations, Add "Hold cars with custom loads"
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/tools/ExportLocations.java
  java/src/jmri/jmrit/operations/locations/tools/ImportLocations.java
  java/src/jmri/jmrit/operations/locations/tools/TrackLoadEditFrame.java
Labels: Needs L10N
