Repository JMRI/JMRI, pull requests merged in 2023-06, with the labels that each got.

#12078 html - button style / netBeans
  help/en/html/doc/Technical/Help.shtml
  help/en/html/doc/Technical/NetBeans.shtml
  help/en/html/doc/Technical/NewType.shtml
  help/en/html/hardware/loconet/LocoIO.shtml
  help/en/html/tools/EntryExit.shtml
Labels: Documentation

#12079 update some html inputs to spans
  help/en/manual/DecoderPro/Basic_BasicPane.shtml
  help/en/manual/DecoderPro/Comp_Speed_Talble.shtml
  help/en/manual/DecoderPro/Main_ConsistControl.shtml
  help/en/manual/DecoderPro/Main_Debug.shtml
  help/en/manual/DecoderPro/Main_LocoNet.shtml
  help/en/manual/DecoderPro/Main_Main.shtml
  help/en/manual/DecoderPro/Main_RosterGroup.shtml
Labels: Documentation

#12083 OperationsPro, New feature, pool staging tracks with departure control
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/tools/PoolTrackFrame.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
Labels: Documentation, Needs L10N

#12081 remove 2 html files from help
  help/en/manual/DecoderPro/Main_Throttle_controlPanel.html
  help/en/manual/DecoderPro/Main_Throttle_functionPanel.html
Labels: Documentation

#12080 Consist Tool : leverage roster icons
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/implementation/AbstractConsistManager.java
  java/src/jmri/implementation/DccConsistManager.java
  java/src/jmri/implementation/NmraConsistManager.java
  java/src/jmri/jmrit/Bundle.properties
  java/src/jmri/jmrit/Bundle_ca.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/Bundle_da.properties
  java/src/jmri/jmrit/Bundle_de.properties
  java/src/jmri/jmrit/Bundle_fr.properties
  java/src/jmri/jmrit/Bundle_it.properties
  java/src/jmri/jmrit/Bundle_ja_JP.properties
  java/src/jmri/jmrit/Bundle_nl.properties
  java/src/jmri/jmrit/consisttool/ConsistComboBox.java
  java/src/jmri/jmrit/consisttool/ConsistDataModel.java
  java/src/jmri/jmrit/consisttool/ConsistFile.java
  java/src/jmri/jmrit/consisttool/ConsistListCellRenderer.java
  java/src/jmri/jmrit/consisttool/ConsistTableRosterEntryColumnCellRenderer.java
  java/src/jmri/jmrit/consisttool/ConsistToolFrame.java
  java/src/jmri/jmrit/roster/RosterIconFactory.java
  java/src/jmri/jmrit/roster/RosterMediaPane.java
  java/src/jmri/jmrit/roster/swing/RosterEntrySelectorPanel.java
  java/src/jmri/jmrit/throttle/AddressListener.java
  java/src/jmri/jmrit/throttle/AddressPanel.java
  java/src/jmri/jmrit/throttle/BackgroundPanel.java
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/ControlPanelListener.java
  java/src/jmri/jmrit/throttle/FunctionButton.java
  java/src/jmri/jmrit/throttle/FunctionButtonPropertyEditor.java
  java/src/jmri/jmrit/throttle/FunctionPanel.java
  java/src/jmri/jmrit/throttle/SpeedPanel.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_ca.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_cs.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_da.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_de.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_it.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_ja_JP.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_nl.properties
  java/src/jmri/jmrit/throttle/ThrottleFrame.java
  java/src/jmri/jmrit/throttle/ThrottleWindow.java
  java/src/jmri/jmrit/throttle/ThrottleWindowActionsFactory.java
  java/src/jmri/jmrit/throttle/ThrottlesListPanel.java
  java/src/jmri/jmrit/throttle/ThrottlesTableCellRenderer.java
  java/src/jmri/jmrit/throttle/ThrottlesTableModel.java
  java/src/jmri/jmrit/withrottle/WiFiConsistManager.java
  java/src/jmri/jmrix/easydcc/EasyDccConsistManager.java
  java/src/jmri/jmrix/internal/InternalConsistManager.java
  java/src/jmri/jmrix/lenz/XNetConsistManager.java
  java/src/jmri/jmrix/loconet/LocoNetConsistManager.java
  java/src/jmri/jmrix/nce/NceConsistManager.java
  java/src/jmri/util/gui/GuiLafPreferencesManager.java
  java/src/jmri/util/swing/EditableResizableImagePanel.java
  java/src/jmri/util/swing/ResizableImagePanel.java
  java/test/jmri/jmrit/logix/LearnWarrantTest.java
Labels: Needs L10N

#12085 Add Entry/Exit to the For each bean list
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/CommonManager.java
  xml/schema/logixng/digital-actions/for-each-5.1.3.xsd
Labels: Needs L10N

#12090 Add a 'Set turntable position' statement to YAAT
  help/en/html/scripthelp/yaat/YAAT.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/YetAnotherAutoTrain.py
Labels: Documentation

#12087 move OpenLCBlibrary.html to shtml
  help/en/package/jmri/jmrix/openlcb/swing/downloader/.htaccess
  help/en/package/jmri/jmrix/openlcb/swing/downloader/OpenLCBlibrary.shtml
Labels: Documentation

#12097 DCC-EX: additional message types, new menu item, better time handling
  java/src/jmri/jmrix/dccpp/DCCppClockControl.java
  java/src/jmri/jmrix/dccpp/DCCppConstants.java
  java/src/jmri/jmrix/dccpp/DCCppMessage.java
  java/src/jmri/jmrix/dccpp/DCCppReply.java
  java/src/jmri/jmrix/dccpp/swing/ConfigBaseStationFrame.java
  java/src/jmri/jmrix/dccpp/swing/DCCppSwingBundle.properties
  java/test/jmri/jmrix/dccpp/DCCppMessageTest.java
  java/test/jmri/jmrix/dccpp/DCCppReplyTest.java
Labels: Needs L10N

#12098 support pages - update more inputs to spans
  help/en/manual/DecoderPro/Main_Throttle_controlPanel.shtml
  help/en/manual/DecoderPro/Main_Throttle_functionPanel.shtml
  help/en/manual/DecoderPro/Main_Throttle_menubar.shtml
  help/en/manual/DecoderPro/Main_XpressNet.shtml
  help/en/manual/DecoderPro/Programmer_Setup.shtml
  help/en/manual/DecoderPro/Programmer_Start.shtml
  help/en/manual/DecoderPro3/Adv_FunctionLabel.shtml
  help/en/manual/DecoderPro3/Basic_BasicPane.shtml
  help/en/manual/DecoderPro3/Basic_Start.shtml
Labels: Documentation

#12099 support pages - update even more inputs to spans
  help/en/manual/DecoderPro3/Comp_Speed_Talble.shtml
  help/en/manual/DecoderPro3/dp3_Main_ConsistControl.shtml
  help/en/manual/DecoderPro3/dp3_Main_Throttle_FrameProperties.shtml
  help/en/manual/DecoderPro3/dp3_Main_Throttle_addressPanel.shtml
  help/en/manual/DecoderPro3/dp3_Main_Throttle_controlPanel.shtml
  help/en/manual/DecoderPro3/dp3_Main_Throttle_functionPanel.shtml
  help/en/manual/DecoderPro3/dp3_Main_Throttle_menubar.shtml
  help/en/manual/DecoderPro3/dp3_Main_TurnoutControl.shtml
Labels: Documentation

#12100 support pages - update jmrix inputs to spans
  help/en/manual/DecoderPro3/Main_LocoNet.shtml
  help/en/manual/DecoderPro3/Main_OakTreeSystems.shtml
  help/en/manual/DecoderPro3/Main_PRICOM.shtml
  help/en/manual/DecoderPro3/Main_Powerline.shtml
  help/en/manual/DecoderPro3/Main_QSI.shtml
  help/en/manual/DecoderPro3/Main_XpressNet.shtml
  help/en/manual/DecoderPro3/RosterMedia.shtml
  help/en/manual/DecoderPro3/Start_DecoderPro_New.shtml
  help/en/manual/DecoderPro3/Start_Preferences.shtml
Labels: Documentation

#12102 support pages - input to span ops pt1
  help/en/manual/JMRI_OPS_UsersGuide/Ops_AddCars.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_AddEngine.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_AddInterchange.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_AddLocations.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_AddRoutes.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_AddSiding.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_AddStaging.shtml
Labels: Documentation

#12103 support pages - input to span ops pt2
  help/en/manual/JMRI_OPS_UsersGuide/Ops_AddTrain.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_AddYard.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_CarAttributes.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Cars.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Cars_Menu.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_EditEngines.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_EditTrain.shtml
Labels: Documentation

#12104 support pages - input to span ops pt3
  help/en/manual/JMRI_OPS_UsersGuide/Ops_EngineAttributes.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Engines.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_ImportCarsFile.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Locations.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Locations_Menu.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Locations_byCar.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Locations_setCars.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_PrintOptions.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Routes.shtml
Labels: Documentation

#12105 support pages - input to span ops pt4
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Routes_Menu.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_SetEngines.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Trains.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_TrainsBuild.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_TrainsModify.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Trains_BuildOptions.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_Trains_Menu.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_TripThruOperations.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Ops_schedule.shtml
  help/en/manual/JMRI_OPS_UsersGuide/Start_Preferences.shtml
Labels: Documentation

#12106 Implement YAAT 3
  help/en/html/scripthelp/yaat/YAAT.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/YetAnotherAutoTrain3.py
Labels: Documentation

#12111 replace double quotes when exporting
  jython/DCC-EX/RosterExportToDCC-EX.py
Labels: New PR

#12112 support pages - tweak some links
  help/en/Acknowledgements.shtml
  help/en/html/apps/DecoderPro/XML.shtml
  help/en/html/apps/PanelPro/AdvIcons.shtml
  help/en/html/apps/PanelPro/index.shtml
  help/en/html/doc/Technical/AppPreferences.shtml
  help/en/html/doc/Technical/Javadoc.shtml
  help/en/html/doc/Technical/NetBeans.shtml
  help/en/html/doc/Technical/XmlSchema.shtml
  help/en/html/doc/Technical/index.shtml
  help/en/html/setup/git.shtml
  help/en/index.shtml
Labels: Documentation, New PR

#12116 TCS roster import/export
  help/en/html/hardware/openlcb/TCS.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/symbolicprog/TcsDownloadAction.java
  java/src/jmri/jmrit/symbolicprog/TcsExportAction.java
  java/src/jmri/jmrit/symbolicprog/TcsUploadAction.java
Labels: Add to Next Test Release, Documentation

#12117 Use consistent naming in LogixNG
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
Labels: Add to Next Test Release, Needs L10N

#12122 Improve responsiveness of Memory and Block displays on Layout Editor panels
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/layoutEditor/BlockContentsIcon.java
  java/src/jmri/jmrit/display/layoutEditor/MemoryIcon.java
Labels: Add to Next Test Release

#12124 german translations for MX, MS and MN-Decoder
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/zimo/CV1-CV99_MS_series.xml
  xml/decoders/zimo/CV100-CV199_MS_series.xml
  xml/decoders/zimo/CV260-CV355sound_v40.xml
  xml/decoders/zimo/CV260-CV399_MS_series.xml
  xml/decoders/zimo/CV356.xml
  xml/decoders/zimo/CV500-CV603.xml
  xml/decoders/zimo/CV500-CV603_MS_series.xml
  xml/decoders/zimo/CV700-CV899_MS_series.xml
  xml/decoders/zimo/PaneABC.xml
  xml/decoders/zimo/PaneAccelDecel.xml
  xml/decoders/zimo/PaneAccelDecel_MS_series.xml
  xml/decoders/zimo/PaneInputMapping.xml
  xml/programmers/parts/LightsPane.xml
Labels: Add to Next Test Release, New PR

#12123 Fix openlcb memory config tool "put" not initializing the dst variable.
  java/src/jmri/jmrix/openlcb/swing/memtool/MemoryToolPane.java
Labels: Add to Next Test Release, New PR

#12118 Augment consumer name in Event Table
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/eventtable/EventTablePane.java
Labels: Add to Next Test Release

#12115 Add JMRI version to bottom of generated Javadoc
  build.xml
  help/en/releasenotes/current-draft-note.shtml
Labels: After Next Production Release

#12120 update xml / JavaDoc Copyright weblinks
  build.xml
  jython/HEADER.html
  pom.xml
  xml/README.md
  xml/XSLT/CVsummary.xsl
  xml/XSLT/DecoderID.xsl
  xml/XSLT/DecoderMfgIndex.xsl
  xml/XSLT/DecoderModelIndex.xsl
  xml/XSLT/DecoderModelList.xsl
  xml/XSLT/LogixToCode.xsl
  xml/XSLT/SelectionGuide.xsl
  xml/XSLT/appearancetable.xsl
  xml/XSLT/aspecttable.xsl
  xml/XSLT/consistRoster.xsl
  xml/XSLT/decoder-with-form.xsl
  xml/XSLT/decoder.xsl
  xml/XSLT/idtags.xsl
  xml/XSLT/locomotive.xsl
  xml/XSLT/mfgID.xsl
  xml/XSLT/panelfile-2-9-6.xsl
  xml/XSLT/panelfile-4-19-2.xsl
  xml/XSLT/panelfile.xsl
  xml/XSLT/roster.xsl
  xml/XSLT/roster2array.xsl
  xml/XSLT/roster2text.xsl
  xml/XSLT/rpsfile.xsl
  xml/XSLT/speedometer.xsl
  xml/XSLT/throttle-config.xsl
  xml/XSLT/throttle-layout-config.xsl
  xml/XSLT/timetable.xsl
  xml/XSLT/vsdecoder-config.xsl
Labels: After Next Production Release

#12125 Update index correctly (prevents crashes)
  jython/DispatcherSystem/CreateGraph.py
Labels: After Next Production Release

#12131 Add demo file for YAAT3
  help/en/html/scripthelp/yaat/YAAT.shtml
  help/en/html/scripthelp/yaat/YAAT3.jmri.zip
Labels: Documentation

#12139 minor update some weblinks
  help/en/html/apps/DecoderPro/CreateDecoderAdvanced.shtml
  help/en/html/apps/SaveWhatHowWhereWhen.shtml
  help/en/html/hardware/loconet/SE74.shtml
  help/en/html/hardware/marklin/index.shtml
  help/en/html/tools/logixng/reference/chapter5.shtml
Labels: Documentation

#12140 Turnout Table UI update
  help/en/package/jmri/jmrit/beantable/TurnoutTable.shtml
  help/en/package/jmri/jmrit/beantable/images/TurnoutRetryOperationEditor_574x188.jpg
  help/en/package/jmri/jmrit/beantable/images/TurnoutTableColumnList.jpg
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/CommonTurnoutOperation.java
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/NoFeedbackTurnoutOperation.java
  java/src/jmri/RawTurnoutOperation.java
  java/src/jmri/SensorTurnoutOperation.java
  java/src/jmri/TurnoutOperation.java
  java/src/jmri/TurnoutOperationManager.java
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BeanTableDataModel.java
  java/src/jmri/jmrit/beantable/TurnoutTableAction.java
  java/src/jmri/jmrit/beantable/turnout/TurnoutTableDataModel.java
  java/src/jmri/jmrit/beantable/turnout/TurnoutTableJTable.java
  java/src/jmri/jmrit/turnoutoperations/Bundle.properties
  java/src/jmri/jmrit/turnoutoperations/CommonTurnoutOperationConfig.java
  java/src/jmri/jmrit/turnoutoperations/TurnoutOperationFrame.java
  java/src/jmri/managers/ProxyTurnoutManager.java
  java/test/jmri/TurnoutOperationManagerTest.java
  java/test/jmri/jmrit/beantable/turnout/TurnoutTableDataModelTest.java
  java/test/jmri/jmrit/turnoutoperations/TurnoutOperationFrameTest.java
Labels: Documentation, Needs L10N, New PR

#12138 json car, engine: remove location, set unknown flag, remove from train
  java/src/jmri/server/json/operations/Bundle.properties
  java/src/jmri/server/json/operations/JsonOperations.java
  java/src/jmri/server/json/operations/JsonOperationsHttpService.java
  java/src/jmri/server/json/operations/JsonUtil.java
  java/src/jmri/server/json/operations/car-client.json
  java/src/jmri/server/json/operations/car-server.json
  java/src/jmri/server/json/operations/engine-client.json
  java/src/jmri/server/json/operations/engine-server.json
  java/test/jmri/server/json/operations/JsonOperationsHttpServiceTest.java
Labels: Needs L10N
