Repository JMRI/JMRI, pull requests merged in 2023-02, with the labels that each got.

#11754 Powerline dmx serial
  java/src/jmri/jmrix/powerline/DmxSequence.java
  java/src/jmri/jmrix/powerline/PowerlineBundle.properties
  java/src/jmri/jmrix/powerline/SerialAddress.java
  java/src/jmri/jmrix/powerline/SerialConnectionTypeList.java
  java/src/jmri/jmrix/powerline/SerialLight.java
  java/src/jmri/jmrix/powerline/SerialLightManager.java
  java/src/jmri/jmrix/powerline/SerialSystemConnectionMemo.java
  java/src/jmri/jmrix/powerline/SerialTrafficController.java
  java/src/jmri/jmrix/powerline/SerialTurnout.java
  java/src/jmri/jmrix/powerline/cm11/SpecificSensorManager.java
  java/src/jmri/jmrix/powerline/configurexml/SerialLightManagerXml.java
  java/src/jmri/jmrix/powerline/configurexml/SerialSensorManagerXml.java
  java/src/jmri/jmrix/powerline/configurexml/SerialTurnoutManagerXml.java
  java/src/jmri/jmrix/powerline/dmx512/Bundle.java
  java/src/jmri/jmrix/powerline/dmx512/COPYING
  java/src/jmri/jmrix/powerline/dmx512/ConnectionConfig.java
  java/src/jmri/jmrix/powerline/dmx512/PowerlineActionListBundle.properties
  java/src/jmri/jmrix/powerline/dmx512/SpecificDmxLight.java
  java/src/jmri/jmrix/powerline/dmx512/SpecificDriverAdapter.java
  java/src/jmri/jmrix/powerline/dmx512/SpecificLight.java
  java/src/jmri/jmrix/powerline/dmx512/SpecificLightManager.java
  java/src/jmri/jmrix/powerline/dmx512/SpecificMessage.java
  java/src/jmri/jmrix/powerline/dmx512/SpecificReply.java
  java/src/jmri/jmrix/powerline/dmx512/SpecificSystemConnectionMemo.java
  java/src/jmri/jmrix/powerline/dmx512/SpecificTrafficController.java
  java/src/jmri/jmrix/powerline/dmx512/configurexml/ConnectionConfigXml.java
  java/src/jmri/jmrix/powerline/dmx512/configurexml/SpecificLightManagerXml.java
  java/src/jmri/jmrix/powerline/dmx512/package.html
  java/src/jmri/jmrix/powerline/insteon2412s/SpecificSensorManager.java
  java/src/jmri/jmrix/powerline/simulator/SpecificSensorManager.java
  java/src/jmri/jmrix/powerline/swing/PowerlineMenu.java
  java/src/jmri/managers/AbstractLightManager.java
  java/test/jmri/jmrix/powerline/SerialAddressTest.java
  java/test/jmri/jmrix/powerline/dmx512/BundleTest.java
  java/test/jmri/jmrix/powerline/dmx512/COPYING
  java/test/jmri/jmrix/powerline/dmx512/ConnectionConfigTest.java
  java/test/jmri/jmrix/powerline/dmx512/SpecificDriverAdapterTest.java
  java/test/jmri/jmrix/powerline/dmx512/SpecificLightManagerTest.java
  java/test/jmri/jmrix/powerline/dmx512/SpecificLightTest.java
  java/test/jmri/jmrix/powerline/dmx512/SpecificMessageTest.java
  java/test/jmri/jmrix/powerline/dmx512/SpecificReplyTest.java
  java/test/jmri/jmrix/powerline/dmx512/SpecificSystemConnectionMemoTest.java
  java/test/jmri/jmrix/powerline/dmx512/SpecificTrafficControllerTest.java
  java/test/jmri/jmrix/powerline/dmx512/configurexml/ConnectionConfigXmlTest.java
  java/test/jmri/jmrix/powerline/dmx512/configurexml/SpecificLightManagerXmlTest.java
Labels: Needs L10N

#11777 Dmx cleanup
  help/en/html/hardware/anyma/index.shtml
  help/en/html/hardware/powerline/Compatibility.shtml
  help/en/html/hardware/powerline/Names.shtml
  help/en/html/hardware/powerline/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/powerline/images/DMX512-usb.jpg
  help/en/html/hardware/powerline/index.shtml
  help/en/parts/SidebarSupportedHardware.shtml
  java/src/jmri/jmrix/powerline/dmx512/SpecificTrafficController.java
  java/src/jmri/managers/AbstractLightManager.java
Labels: Documentation

#11776 CBUS CANISB Update
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/swing/modules/AbstractEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/CanisbEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/CanisbPaneProvider.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/Sprog3PlusEditNVPane.java
Labels: Needs L10N

#11737 20230110 special slots
  java/src/jmri/jmrix/loconet/LnCommandStationType.java
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/LnOpsModeProgrammer.java
  java/src/jmri/jmrix/loconet/SlotManager.java
  java/src/jmri/jmrix/loconet/duplexgroup/swing/LnIPLImplementation.java
  java/src/jmri/jmrix/loconet/loconetovertcp/LnOverTcpPacketizer.java
  java/src/jmri/jmrix/loconet/loconetovertcp/LnTcpPreferencesPanel.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/src/jmri/jmrix/loconet/slotmon/SlotMonPane.java
  java/test/jmri/jmrix/loconet/CsOpSwAccessTest.java
  java/test/jmri/jmrix/loconet/LnCommandStationTypeTest.java
  java/test/jmri/jmrix/loconet/LnOpsModeProgrammerTest.java
  java/test/jmri/jmrix/loconet/LnThrottleManagerTest.java
  java/test/jmri/jmrix/loconet/SlotManagerAndPowerMan.java
  java/test/jmri/jmrix/loconet/SlotManagerTest.java
Labels: Needs L10N

#11786 Fix missing write to upper CVs in SplitEnumVariableValue
  help/en/html/apps/DecoderPro/CreateDecoderAdvanced.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/symbolicprog/CvValue.java
  java/src/jmri/jmrit/symbolicprog/SplitEnumVariableValue.java
  xml/decoders/TCS_BachmannFT.xml
  xml/decoders/TCS_BachmannGP35.xml
  xml/decoders/TCS_BachmannRS3.xml
  xml/decoders/TCS_WOWDieselV5-121.xml
Labels: Documentation

#11784 Press F8 to disable Logixs and LogixNGs. Press F9 to prevent LogixNGs to be started
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/Apps.java
  java/src/apps/AppsBase.java
  java/src/apps/AppsBundle.properties
  java/src/apps/gui3/Apps3.java
  java/src/jmri/configurexml/LoadXmlConfigAction.java
  java/src/jmri/jmrit/logixng/LogixNG_Manager.java
  java/src/jmri/jmrit/logixng/implementation/DefaultLogixNGManager.java
Labels: Needs L10N

#11789 Update Logix/LogixNG help for F8/F9 change
  help/en/html/setup/images/StartDialog.png
  help/en/html/setup/index.shtml
  help/en/html/tools/Logix.shtml
  help/en/html/tools/logixng/LogixNG.shtml
Labels: Documentation

#11792 OperationsPro, Fix NPE
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/router/Router.java
Labels: Documentation

#11796 OperationsPro, improve build report by showing track type
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Needs L10N

#11799 OperationsPro, improve help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#11795 Help info for Digitrax SE74
  help/en/html/doc/Technical/Help.shtml
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/SE74.shtml
  help/en/html/hardware/loconet/images/Se74.png
  help/en/html/hardware/loconet/images/Se74AspectModeSignalAHead.png
  help/en/html/hardware/loconet/images/Se74AspectModeSignalBHead.png
  help/en/html/hardware/loconet/images/Se74AspectModeSignalHeads.png
  help/en/html/hardware/loconet/images/Se74CompatabilityModeSignalAHead.png
  help/en/html/hardware/loconet/images/Se74CompatabilityModeSignalBHead.png
  help/en/html/hardware/loconet/images/Se74CompatabilityModeSignalCHead.png
  help/en/html/hardware/loconet/images/Se74CompatibiltyModeSignalHeads.png
  help/en/html/hardware/loconet/images/Se74MastOnPanel.png
  help/en/html/hardware/loconet/images/SignalMastExample.png
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#11803 Update Acknowledgements.shtml
  help/en/Acknowledgements.shtml
Labels: Documentation

#11806 Remove bad http link
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#11814 AAR-1946 signal system updates
  help/en/releasenotes/current-draft-note.shtml
  java/test/jmri/implementation/configurexml/load/TenMastOutputs.xml
  java/test/jmri/implementation/configurexml/loadref/SignalHeadTestExamples.xml
  java/test/jmri/jmrix/openlcb/configurexml/loadref/TestFile.xml
  xml/signals/AAR-1946/appearance-CPL.xml
  xml/signals/AAR-1946/appearance-PL-1-high-abs.xml
  xml/signals/AAR-1946/appearance-PL-1-high-pbs.xml
  xml/signals/AAR-1946/appearance-PL-1-low.xml
  xml/signals/AAR-1946/appearance-PL-2-high.xml
  xml/signals/AAR-1946/appearance-SL-1-high-abs.xml
  xml/signals/AAR-1946/appearance-SL-1-high-pbs.xml
  xml/signals/AAR-1946/appearance-SL-1-low.xml
  xml/signals/AAR-1946/appearance-SL-2-high-abs.xml
  xml/signals/AAR-1946/appearance-SL-2-high-pbs.xml
  xml/signals/AAR-1946/appearance-SL-2-low.xml
  xml/signals/AAR-1946/appearance-SL-3-high.xml
Labels: Bug, Enhancement, Cleanup, New PR

#11812 Test Spotbug Reports - use unique filenames
  .gitignore
  build.xml
Labels: New PR

#11816 OperationsPro, always add route and location comments to CSV files
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/TrainCsvCommon.java
  java/test/jmri/jmrit/operations/trains/TrainCsvSwitchListsTest.java
Labels: Documentation

#11815 update some html inputs to text
  help/en/manual/DecoderPro/Adv_FunctionLabel.shtml
  help/en/manual/DecoderPro/Adv_RosterMedia.shtml
  help/en/manual/DecoderPro/Basic_BasicPane.shtml
  help/en/manual/DecoderPro/Comp_PrintData.shtml
  help/en/manual/DecoderPro/Comp_Speed_Talble.shtml
  help/en/manual/DecoderPro/Dcode_Testing.shtml
  help/en/manual/DecoderPro/Main_ConsistControl.shtml
  help/en/manual/DecoderPro/Main_Debug.shtml
  help/en/manual/DecoderPro/Main_LocoNet.shtml
  help/en/manual/DecoderPro/Main_Main.shtml
  help/en/manual/DecoderPro/Main_OakTreeSystems.shtml
  help/en/manual/DecoderPro/Main_PRICOM.shtml
  help/en/manual/DecoderPro/Main_Powerline.shtml
  help/en/manual/DecoderPro/Main_QSI.shtml
  help/en/manual/DecoderPro/Main_RosterGroup.shtml
  help/en/manual/DecoderPro/Main_Throttle_FrameProperties.shtml
  help/en/manual/DecoderPro/Main_Throttle_addressPanel.shtml
  help/en/manual/DecoderPro/Main_TurnoutControl.shtml
  help/en/manual/DecoderPro/Main_XpressNet.shtml
Labels: Documentation, New PR
