Repository JMRI/JMRI, pull requests merged in 2023-10, with the labels that each got.

#12464 OperationsPro add reset color to Trains window
  java/src/jmri/jmrit/operations/JmritOperationsBundle.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_fr.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_da.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_fr.properties
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/Xml.java
  java/src/jmri/jmrit/operations/trains/tools/TrainsTableSetColorFrame.java
  java/test/jmri/jmrit/operations/trains/TrainsTableFrameTest.java
  java/test/jmri/jmrit/operations/trains/XmlTest.java
  xml/DTD/operations-trains.dtd
Labels: Needs L10N

#12467 OperationsPro Update Help
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/EditTrainTools.png
  help/en/package/jmri/jmrit/operations/images/ModifyTrainsByCarType.png
  help/en/package/jmri/jmrit/operations/images/ShowCarTypesServicedTrain.png
  help/en/package/jmri/jmrit/operations/images/TrainsPaneMenu.png
  java/src/jmri/jmrit/operations/trains/TrainEditFrame.java
  java/src/jmri/jmrit/operations/trains/TrainsTableFrame.java
Labels: Documentation

#12449 Rename startup action "Open file" to "Load table content and panels"
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/util/startup/Bundle.properties
  java/src/jmri/util/startup/Bundle_ca.properties
  java/src/jmri/util/startup/Bundle_cs.properties
  java/src/jmri/util/startup/Bundle_da.properties
  java/src/jmri/util/startup/Bundle_de.properties
  java/src/jmri/util/startup/Bundle_es.properties
  java/src/jmri/util/startup/Bundle_nl.properties
Labels: Needs L10N

#12470 OperationsPro Code cleanup
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/CommonConductorYardmasterPanel.java
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/LocationManager.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/YardmasterPanel.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStockManager.java
  java/src/jmri/jmrit/operations/rollingstock/cars/Car.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineManager.java
  java/src/jmri/jmrit/operations/routes/Route.java
  java/src/jmri/jmrit/operations/routes/RouteLocation.java
  java/src/jmri/jmrit/operations/trains/JsonManifest.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/jmrit/operations/trains/TrainConductorPanel.java
  java/src/jmri/jmrit/operations/trains/TrainCsvManifest.java
  java/src/jmri/jmrit/operations/trains/TrainCsvSwitchLists.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/TrainManifest.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchListEditFrame.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchLists.java
  java/src/jmri/jmrit/operations/trains/schedules/TrainScheduleManager.java
  java/src/jmri/jmrit/operations/trains/tools/ExportTrainLineups.java
  java/src/jmri/jmrit/operations/trains/tools/ShowCarsInTrainFrame.java
  java/src/jmri/web/servlet/operations/HtmlConductor.java
  java/src/jmri/web/servlet/operations/HtmlManifest.java
  java/src/jmri/web/servlet/operations/HtmlTrainCommon.java
Labels: Documentation

#12474 Update help references for PR #12449
  help/en/html/apps/PanelPro/index.shtml
  help/en/package/apps/TabbedPreferences.shtml
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#12472 add option(s) for restoring block values, issue #12459
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BlockTableAction.java
  java/src/jmri/jmrit/display/layoutEditor/BlockValueFile.java
Labels: Needs L10N

#12473 LogixNG Where Used help
  help/en/html/tools/logixng/SidebarToolLocalPart.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGWhereUsed.shtml
  help/en/package/jmri/jmrit/logixng/images/logixng_where_used.png
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
Labels: Documentation, Needs L10N

#12475 Update audio expression help
  help/en/html/tools/logixng/reference/chapter6.shtml
Labels: Documentation

#12481 Eclipse formatting, disable comment line wrapping
  .settings/org.eclipse.jdt.core.prefs
Labels: New PR

#12482 Update current-draft-warnings.shtml for PR #12478
  help/en/releasenotes/current-draft-warnings.shtml
Labels: New PR

#12483 OperationsPro, Fix Manifest line length when colored text
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineManager.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
Labels: New PR

#12484 OpenLCB updates
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/send/OpenLcbCanSendPane.java
  lib/README.md
  lib/openlcb.jar
Labels: New PR

#12485 Update Soundtraxx decoder ID
  java/src/jmri/jmrit/decoderdefn/IdentifyDecoder.java
  java/test/jmri/jmrit/decoderdefn/IdentifyDecoderTest.java
Labels: After Next Test Release, New PR

#12489 Revert "Update Soundtraxx decoder ID"
  java/src/jmri/jmrit/decoderdefn/IdentifyDecoder.java
  java/test/jmri/jmrit/decoderdefn/IdentifyDecoderTest.java
Labels: New PR

#12487 Add xml test file for #12478
  java/test/jmri/jmrit/logixng/configurexml/load/LogixWhenTriggered_5.5.4_to_5.5.5.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixWhenTriggered_5.5.4_to_5.5.5.xml
Labels: New PR

#12488 Create panelfile-5-5-5.xsl
  xml/XSLT/panelfile-5-5-5.xsl
Labels: New PR

#12493 OperationsPro Improve car and locomotive roster printing
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/JmritOperationsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterAction.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterAction.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterFrame.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterActionTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterActionTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterFrameTest.java
Labels: Documentation, Needs L10N

#12492 Update help for LogixNG changes
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter5/digital_boolean_action_common.png
  help/en/html/tools/logixng/reference/images/chapter5/logix_action.png
  help/en/html/tools/logixng/reference/images/chapter5/logix_example.png
  help/en/html/tools/logixng/reference/images/chapter5/other_logix_action.png
  help/en/package/jmri/jmrit/display/PanelEditor.shtml
  help/en/package/jmri/jmrit/logixng/InlineLogixNG.shtml
  help/en/package/jmri/jmrit/logixng/LogixNGTableEditor.shtml
  help/en/package/jmri/jmrit/logixng/images/InlineLogixNGIcon.png
  help/en/package/jmri/jmrit/logixng/images/LogixNGEditor.png
Labels: Documentation

#12499 Add LogixNG Icon to Layout Editor
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorFloatingToolBarPanel.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorHorizontalToolBarPanel.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorToolBarPanel.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorVerticalToolBarPanel.java
  xml/schema/types/layouteditor.xsd
Labels: Needs L10N

#12502 Further additions/updates to Getting Started with RFID
  help/en/html/hardware/rfid/GettingStartedWithRFID.shtml
  help/en/html/hardware/rfid/Sidebar.shtml
  help/en/html/hardware/rfid/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/rfid/images/Cars2Rel554.jpg
  help/en/html/hardware/rfid/images/CarsRel554.jpg
  help/en/html/hardware/rfid/images/IDTagTable2Rel554.jpg
  help/en/html/hardware/rfid/images/LocationsRel554.jpg
  help/en/html/hardware/rfid/images/OpsProCarTablesLinkedRel554.jpg
  help/en/html/hardware/rfid/images/OpsProCarTablesRel554.jpg
Labels: Documentation

#12507 Fix Warrant Expression
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionWarrant.java
Labels: Needs L10N

#12511 Require @Override and removal of unused imports
  help/en/releasenotes/current-draft-note.shtml
  java/ecj.warning.options-ci
  java/ecj.warning.options-test-ci
Labels: dev/test/publish infrastructure, Developer

#12512 OperationsPro Improve Trains preview and printing
  java/src/jmri/jmrit/operations/JmritOperationsBundle.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_da.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_de.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_fr.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_it.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_nl.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_it.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_da.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_de.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_fr.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_it.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_nl.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/TrainsTableFrame.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrainAction.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrains.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrainsAction.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrainsFrame.java
  java/test/jmri/jmrit/operations/trains/tools/PrintTrainTest.java
  java/test/jmri/jmrit/operations/trains/tools/PrintTrainsActionTest.java
Labels: Needs L10N

#12513 Digitrax SFX Series7 decoder update
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/Digitrax_0SFX_Series7.xml
  xml/decoders/digitrax/PaneDigitraxFunctionmapSeries7.xml
  xml/decoders/digitrax/PaneDigitraxSoundFeaturesSeries7.xml
  xml/decoders/digitrax/featureSettings7.xml
  xml/decoders/digitrax/functionMapSettings7.xml
  xml/decoders/digitrax/soundOptions7.xml
  xml/decoders/digitrax/soundSettings7.xml
Labels: Documentation

#12510 Documentation updates and links to RFID
  help/en/html/FAQ.shtml
  help/en/html/hardware/rfid/GettingStartedWithRFID.shtml
  help/en/html/hardware/rfid/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/rfid/images/ReporterTableRel554.jpg
  help/en/html/hardware/rfid/index.shtml
  help/en/html/tools/IdTags.shtml
  help/en/html/tools/Reporters.shtml
  help/en/html/tools/scripting/Examples.shtml
  help/en/package/jmri/jmrit/beantable/BlockTable.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/AssignIdTagToRollingStock.py
Labels: Documentation

#12518 OperationsPro Internationalize info messages
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/automation/AutomationTableFrame.java
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/LocationManager.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/divisions/DivisionManager.java
  java/src/jmri/jmrit/operations/locations/schedules/ScheduleEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarColors.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLoads.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarRoads.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarTypes.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineManager.java
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle.properties
  java/src/jmri/jmrit/operations/routes/RouteEditFrame.java
  java/src/jmri/jmrit/operations/setup/AutoSave.java
  java/src/jmri/jmrit/operations/setup/BackupBase.java
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrainsFrame.java
Labels: Documentation, Needs L10N

#12519 Add LEB decoders (issue 12514)
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/Leb_ACC_4S.xml
  xml/decoders/Leb_DECSIGBF1_OP1.xml
  xml/decoders/Leb_DECSIGBF1_V1.xml
  xml/decoders/Leb_DECSIGBF1_V2.xml
  xml/decoders/Leb_DECSIGBF1_V3.xml
  xml/decoders/Leb_DECSIGBF1_V4.xml
  xml/decoders/leb/TableAllumage.xml
  xml/decoders/leb/TableAllumageOptions.xml
  xml/decoders/leb/TableAllumageOptionsPane.xml
  xml/decoders/leb/TableAllumagePane.xml
  xml/decoders/leb/choix-BinLin.xml
  xml/decoders/leb/choix-Remap_led.xml
  xml/decoders/leb/choix-Signal_Cible.xml
  xml/decoders/leb/choix-Signal_Indication.xml
  xml/decoders/leb/choix-Signal_Options.xml
  xml/decoders/leb/enum-Commande_BinLin.xml
  xml/decoders/leb/enum-Signal_Cible.xml
  xml/decoders/leb/enum-Signal_Indication.xml
  xml/decoders/leb/enum-Signal_Options.xml
  xml/decoders/leb/enum-Signal_REMAP_ID1.xml
  xml/decoders/leb/enum-Signal_REMAP_ID2.xml
  xml/decoders/leb/enum-Signal_REMAP_ID3.xml
  xml/decoders/leb/enum-Signal_REMAP_OPTION.xml
Labels: Documentation

#12520 Fix broken links in some documentation
  help/en/html/hardware/rfid/index.shtml
  help/en/html/tools/IdTags.shtml
  help/en/html/tools/Reporters.shtml
Labels: Documentation

#12530 Add Window and Help menus to OpenLCB CDI window
  help/en/package/jmri/jmrix/openlcb/swing/networktree/NetworkTreePane.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/ClientActions.java
Labels: Documentation

#12534 OperationsPro Update help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#12533 Add the GET_BLOCK_WARRANT and GET_BLOCK_TRAIN_NAME OBlock actions to the OBlock Logix import
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/tools/ImportConditional.java
  java/src/jmri/jmrit/logixng/tools/ToolsBundle.properties
Labels: Needs L10N

#12537 JFrame Servlet html4 lint
  java/src/jmri/web/servlet/frameimage/JmriJFrameServlet.properties
  java/src/jmri/web/servlet/frameimage/JmriJFrameServlet_ca.properties
  java/src/jmri/web/servlet/frameimage/JmriJFrameServlet_cs.properties
  java/src/jmri/web/servlet/frameimage/JmriJFrameServlet_da.properties
  java/src/jmri/web/servlet/frameimage/JmriJFrameServlet_de.properties
  java/src/jmri/web/servlet/frameimage/JmriJFrameServlet_fr.properties
  java/src/jmri/web/servlet/frameimage/JmriJFrameServlet_it.properties
  java/src/jmri/web/servlet/frameimage/JmriJFrameServlet_nl.properties
  web/servlet/Footer.html
Labels: Needs L10N

#12540 OperationsPro minor improvement to router messages
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarRoutingReportAction.java
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle.properties
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle_da.properties
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle_en_GB.properties
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle_fr.properties
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle_it.properties
  java/src/jmri/jmrit/operations/router/Router.java
Labels: Needs L10N

#12541 Power control - view multiple connections
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/jmrit/powerpanel/PowerPane.java
  java/src/jmri/jmrit/powerpanel/README
  java/src/jmri/jmrit/powerpanel/package-info.java
  java/src/jmri/swing/Bundle.properties
  java/src/jmri/swing/PowerManagerMenu.java
  java/test/jmri/jmrit/powerpanel/PowerPaneTest.java
Labels: Needs L10N

#12546 OperationsPro Fix routing with interchanges when trains have same route
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/test/jmri/jmrit/operations/router/OperationsCarRouterTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
Labels: Needs L10N

#12549 Add LogixNG expression Timer
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/ConditionalNG.java
  java/src/jmri/jmrit/logixng/MaleSocket.java
  java/src/jmri/jmrit/logixng/actions/Sequence.java
  java/src/jmri/jmrit/logixng/expressions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/Timer.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/TimerXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/TimerSwing.java
  java/src/jmri/jmrit/logixng/implementation/DefaultConditionalNG.java
  java/src/jmri/jmrit/logixng/tools/swing/ModuleEditorMaleSocket.java
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/LogixNGTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalExpressionSocketTest.java
  xml/schema/logixng/digital-expressions/digital-expressions-4.23.1.xsd
  xml/schema/logixng/digital-expressions/timer-5.5.6.xsd
Labels: Needs L10N, New PR

#12554 OpenLCB Signal Mast Add/Edit Pane enhancements
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/OlcbSignalMast.java
  java/src/jmri/jmrix/openlcb/swing/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/OlcbSignalMastAddPane.java
  java/test/jmri/jmrix/openlcb/OlcbSystemConnectionMemoScaffold.java
  java/test/jmri/jmrix/openlcb/swing/OlcbSignalMastAddPaneTest.java
Labels: Needs L10N

#12557 Enable/disable startup actions
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/configurexml/CreateButtonModelXml.java
  java/src/apps/startup/Bundle.properties
  java/src/apps/startup/StartupActionsPreferencesPanel.java
  java/src/apps/startup/configurexml/ScriptButtonModelXml.java
  java/src/apps/startup/configurexml/StartupPauseModelXml.java
  java/src/apps/startup/configurexml/TriggerRouteModelXml.java
  java/src/jmri/util/startup/AbstractActionModel.java
  java/src/jmri/util/startup/AbstractStartupModel.java
  java/src/jmri/util/startup/StartupActionsManager.java
  java/src/jmri/util/startup/StartupModel.java
  java/src/jmri/util/startup/configurexml/PerformActionModelXml.java
  java/src/jmri/util/startup/configurexml/PerformFileModelXml.java
  java/src/jmri/util/startup/configurexml/PerformScriptModelXml.java
Labels: Needs L10N

#12552 LogixNG action timer can be used in a LogixNG module
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionTimer.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionTimerXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionTimerSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.5.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.4.xml
  xml/schema/logixng/digital-actions/action-timer-4.23.1.xsd
Labels: Needs L10N

#12562 Add LogixNG action Throttle function
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionThrottleFunction.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionThrottleFunctionXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionThrottleFunctionSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectBoolean.java
  java/src/jmri/jmrit/logixng/util/UtilBundle.properties
  java/src/jmri/jmrit/logixng/util/configurexml/LogixNG_SelectBooleanXml.java
  java/src/jmri/jmrit/logixng/util/swing/LogixNG_SelectBooleanSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/common-types-4.23.1.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/throttle-function-5.5.6.xsd
Labels: Needs L10N

#12559 Select an icon below another icon on Panel Editor
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/AnalogClock2Display.java
  java/src/jmri/jmrit/display/AudioIcon.java
  java/src/jmri/jmrit/display/BlockContentsIcon.java
  java/src/jmri/jmrit/display/DisplayBundle.properties
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/GlobalVariableComboIcon.java
  java/src/jmri/jmrit/display/GlobalVariableIcon.java
  java/src/jmri/jmrit/display/GlobalVariableInputIcon.java
  java/src/jmri/jmrit/display/GlobalVariableSpinnerIcon.java
  java/src/jmri/jmrit/display/IndicatorTrackIcon.java
  java/src/jmri/jmrit/display/IndicatorTurnoutIcon.java
  java/src/jmri/jmrit/display/LightIcon.java
  java/src/jmri/jmrit/display/LogixNGIcon.java
  java/src/jmri/jmrit/display/MemoryComboIcon.java
  java/src/jmri/jmrit/display/MemoryIcon.java
  java/src/jmri/jmrit/display/MemoryInputIcon.java
  java/src/jmri/jmrit/display/MemorySpinnerIcon.java
  java/src/jmri/jmrit/display/MultiSensorIcon.java
  java/src/jmri/jmrit/display/Positionable.java
  java/src/jmri/jmrit/display/PositionableJComponent.java
  java/src/jmri/jmrit/display/PositionableJPanel.java
  java/src/jmri/jmrit/display/PositionableLabel.java
  java/src/jmri/jmrit/display/ReporterIcon.java
  java/src/jmri/jmrit/display/RpsPositionIcon.java
  java/src/jmri/jmrit/display/SensorIcon.java
  java/src/jmri/jmrit/display/SignalHeadIcon.java
  java/src/jmri/jmrit/display/SignalMastIcon.java
  java/src/jmri/jmrit/display/SlipTurnoutIcon.java
  java/src/jmri/jmrit/display/TurnoutIcon.java
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelEditor.java
  java/src/jmri/jmrit/display/controlPanelEditor/PortalIcon.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutTrackView.java
  java/src/jmri/jmrit/display/panelEditor/PanelEditor.java
  java/src/jmri/jmrit/display/switchboardEditor/BeanSwitch.java
  java/src/jmri/jmrit/display/switchboardEditor/SwitchboardEditor.java
  java/test/jmri/jmrit/display/EditorScaffold.java
Labels: Needs L10N

#12568 OperationsPro update help and release notes
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation
