Repository JMRI/JMRI, pull requests merged in 2023-11, with the labels that each got.

#12570 Update preferences help for start up enable/disable
  help/en/package/apps/TabbedPreferences.shtml
  help/en/package/apps/images/PrefsStartUp.png
  help/en/package/apps/images/PrefsStartup4_15.png
Labels: Documentation

#12571 Add Audio icon to Layout Editor
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/AudioSourceManager.java
  java/src/jmri/jmrit/audio/DefaultAudioSourceManager.java
  java/src/jmri/jmrit/display/AudioIcon.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditor.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorFloatingToolBarPanel.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorHorizontalToolBarPanel.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorToolBarPanel.java
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorVerticalToolBarPanel.java
  java/src/jmri/jmrit/logixng/LogixNGBundle.properties
  java/src/jmri/managers/DefaultInstanceInitializer.java
  web/js/panel.js
  xml/schema/types/layouteditor.xsd
Labels: Needs L10N, New PR

#12576 Switch "stale" processing to stale action
  .github/stale.yml
  .github/workflows/stale-action.yml
Labels: dev/test/publish infrastructure

#12579 OperationsPro minor GUI improvement to spur auto select
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/SpurEditFrame.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
Labels: Documentation

#12580 New DCC-EX Virtual LCD display
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/dccpp/DCCppActionListBundle.properties
  java/src/jmri/jmrix/dccpp/DCCppConstants.java
  java/src/jmri/jmrix/dccpp/DCCppMessage.java
  java/src/jmri/jmrix/dccpp/DCCppReply.java
  java/src/jmri/jmrix/dccpp/simulator/DCCppSimulatorAdapter.java
  java/src/jmri/jmrix/dccpp/swing/DCCppMenu.java
  java/src/jmri/jmrix/dccpp/swing/DCCppSwingBundle.properties
  java/src/jmri/jmrix/dccpp/swing/virtuallcd/Bundle.java
  java/src/jmri/jmrix/dccpp/swing/virtuallcd/VirtualLCDAction.java
  java/src/jmri/jmrix/dccpp/swing/virtuallcd/VirtualLCDFrame.java
  java/src/jmri/jmrix/dccpp/swing/virtuallcd/package-info.java
  java/test/jmri/jmrix/dccpp/DCCppReplyTest.java
Labels: Needs L10N

#12581 Update Transit Actions.
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/TransitSectionAction.java
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle.properties
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/dispatcher/AutoTrainAction.java
  java/src/jmri/managers/configurexml/DefaultTransitManagerXml.java
  java/test/jmri/jmrit/beantable/ListedTableFrameTest.java
  java/test/jmri/jmrit/beantable/TransitTableActionTest.java
  java/test/jmri/jmrit/beantable/usermessagepreferences/UserMessagePreferencesPaneTest.java
  xml/schema/types/transits-2-9-6.xsd
Labels: Needs L10N

#12582 Update LnMessageInterp for signal aspect message
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  jython/LnSendTool.py
Labels: Needs L10N

#12585 Add the help content for the Audio Icon
  help/en/html/tools/Audio.shtml
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter5/audio_action.png
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_display.png
  help/en/html/tools/logixng/reference/images/chapter5/layout_audio_icon.png
  help/en/package/jmri/jmrit/display/AudioIcon.shtml
  help/en/package/jmri/jmrit/display/LayoutEditor.shtml
  help/en/package/jmri/jmrit/display/PanelEditor.shtml
  help/en/package/jmri/jmrit/display/images/audio_icon_web_panels_menu.png
Labels: Documentation

#12590 Update sidebar link on BiDib help pages
  help/en/html/hardware/bidib/BiDiB-SignalMast.shtml
  help/en/html/hardware/bidib/BiDiB-SignalMast_de.shtml
  help/en/html/hardware/bidib/index.shtml
  help/en/html/hardware/bidib/index_de.shtml
Labels: Documentation

#12592 OperationsPro add location name to edit track title
  java/src/jmri/jmrit/operations/locations/InterchangeEditFrame.java
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/SpurEditFrame.java
  java/src/jmri/jmrit/operations/locations/StagingEditFrame.java
  java/src/jmri/jmrit/operations/locations/YardEditFrame.java
  java/test/jmri/jmrit/operations/locations/LocationEditFrameTest.java
Labels: Needs L10N

#12593 Czech translation 2023-11-08
  java/src/apps/ActionListBundle_cs.properties
  java/src/apps/AppsConfigBundle_cs.properties
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/configurexml/swing/Bundle_cs.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/audio/swing/AudioTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/decoderdefn/DecoderFile_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_cs.properties
  java/src/jmri/jmrit/display/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/display/logixng/swing/SwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/UtilBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/swing/SwingBundle_cs.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrit/roster/JmritRosterBundle_cs.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_cs.properties
  java/src/jmri/jmrit/turnoutoperations/Bundle_cs.properties
  java/src/jmri/jmrix/JmrixBundle_cs.properties
  java/src/jmri/jmrix/dccpp/swing/DCCppSwingBundle_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/openlcb/Bundle_cs.properties
  java/src/jmri/server/json/logixngicon/Bundle_cs.properties
  java/src/jmri/server/json/operations/Bundle_cs.properties
  java/src/jmri/util/swing/UtilBundle_cs.properties
Labels: Needs L10N

#12598 support leading/trailing spaces in DCC-EX LCD message text
  java/src/jmri/jmrix/dccpp/DCCppConstants.java
  java/src/jmri/jmrix/dccpp/DCCppReply.java
  java/src/jmri/jmrix/dccpp/simulator/DCCppSimulatorAdapter.java
  java/src/jmri/jmrix/dccpp/swing/virtuallcd/VirtualLCDFrame.java
  java/test/jmri/jmrix/dccpp/DCCppReplyTest.java
Labels: New PR

#12600 OperationsPro update images in help files
  help/en/package/jmri/jmrit/operations/images/Locations.png
  help/en/package/jmri/jmrit/operations/images/ModifyLocationsByCarType.png
  help/en/package/jmri/jmrit/operations/images/Settings.png
  help/en/package/jmri/jmrit/operations/images/TrainSchedules.png
  java/src/jmri/jmrit/operations/locations/SpurTableModel.java
Labels: Documentation

#12601 OperationsPro Clean up and format help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#12602 Improve LogixNG expression Entry/Exit
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/entryexit/DestinationPoints.java
  java/src/jmri/jmrit/logixng/Base.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionEntryExit.java
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionEntryExitSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  xml/schema/logixng/digital-expressions/expression-entryexit-4.23.1.xsd
Labels: Needs L10N

#12608 Update and re-org MQTT documents and images
  help/en/html/hardware/mqtt/images/MQTTPrefs_default_rel5_5_6.jpg
  help/en/html/hardware/mqtt/images/MQTTPrefs_example.jpg
  help/en/html/hardware/mqtt/images/MQTTPrefs_example_rel5_5_6.jpg
  help/en/html/hardware/mqtt/images/MQTTPrefs_rel5_0.jpg
  help/en/html/hardware/mqtt/index.shtml
Labels: Documentation

#12609 update the project's copyright in a field
  project.properties
Labels: Cleanup, Add to Next Test Release

#12613 Update Entry/Exit expression help
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/images/chapter6/entryexit_expression.png
Labels: Documentation

#12615 Bidib tests to JUnit5
  java/test/jmri/TestArchitectureTest.java
  java/test/jmri/jmrix/bidib/BiDiBAddressTest.java
  java/test/jmri/jmrix/bidib/BiDiBConnectionTypeListTest.java
  java/test/jmri/jmrix/bidib/BiDiBConstantsTest.java
  java/test/jmri/jmrix/bidib/BiDiBNodeInitializerTest.java
  java/test/jmri/jmrix/bidib/BiDiBOutputMessageHandlerTest.java
  java/test/jmri/jmrix/bidib/BiDiBPowerManagerTest.java
  java/test/jmri/jmrix/bidib/BiDiBSignalMastTest.java
  java/test/jmri/jmrix/bidib/BiDiBTrafficControllerTest.java
  java/test/jmri/jmrix/bidib/BundleTest.java
  java/test/jmri/jmrix/bidib/PackageTest.java
  java/test/jmri/jmrix/bidib/bidibovertcp/BiDiBOverTcpAdapterTest.java
  java/test/jmri/jmrix/bidib/bidibovertcp/BundleTest.java
  java/test/jmri/jmrix/bidib/bidibovertcp/PackageTest.java
  java/test/jmri/jmrix/bidib/bidibovertcp/configurexml/PackageTest.java
  java/test/jmri/jmrix/bidib/configurexml/BiDiBLightManagerXmlTest.java
  java/test/jmri/jmrix/bidib/configurexml/BiDiBReporterManagerXmlTest.java
  java/test/jmri/jmrix/bidib/configurexml/BiDiBSensorManagerXmlTest.java
  java/test/jmri/jmrix/bidib/configurexml/BiDiBSignalMastXmlTest.java
  java/test/jmri/jmrix/bidib/configurexml/BiDiBTurnoutManagerXmlTest.java
  java/test/jmri/jmrix/bidib/configurexml/PackageTest.java
  java/test/jmri/jmrix/bidib/serialdriver/BundleTest.java
  java/test/jmri/jmrix/bidib/serialdriver/PackageTest.java
  java/test/jmri/jmrix/bidib/serialdriver/SerialDriverAdapterTest.java
  java/test/jmri/jmrix/bidib/serialdriver/configurexml/PackageTest.java
  java/test/jmri/jmrix/bidib/simulator/BiDiBSimulatorAdapterTest.java
  java/test/jmri/jmrix/bidib/simulator/BundleTest.java
  java/test/jmri/jmrix/bidib/simulator/PackageTest.java
  java/test/jmri/jmrix/bidib/simulator/configurexml/PackageTest.java
  java/test/jmri/jmrix/bidib/swing/BiDiBMenuTest.java
  java/test/jmri/jmrix/bidib/swing/BiDiBNamedPaneActionTest.java
  java/test/jmri/jmrix/bidib/swing/BiDiBSignalMastAddPaneTest.java
  java/test/jmri/jmrix/bidib/swing/BiDiBTableModelTest.java
  java/test/jmri/jmrix/bidib/swing/BundleTest.java
  java/test/jmri/jmrix/bidib/swing/PackageTest.java
  java/test/jmri/jmrix/bidib/swing/mon/BundleTest.java
  java/test/jmri/jmrix/bidib/swing/mon/PackageTest.java
  java/test/jmri/jmrix/bidib/tcpserver/BiDiBMessageReceiverTest.java
  java/test/jmri/jmrix/bidib/tcpserver/BundleTest.java
  java/test/jmri/jmrix/bidib/tcpserver/NetPlainTcpBidibTest.java
  java/test/jmri/jmrix/bidib/tcpserver/PackageTest.java
  java/test/jmri/jmrix/bidib/tcpserver/ServerBidibMessageProcessorTest.java
  java/test/jmri/jmrix/bidib/tcpserver/ServerMessageReceiverTest.java
  java/test/jmri/jmrix/bidib/tcpserver/TcpServerActionTest.java
  java/test/jmri/jmrix/bidib/tcpserver/TcpServerNetMessageHandlerTest.java
  java/test/jmri/jmrix/bidib/tcpserver/TcpServerStartupActionFactoryTest.java
  java/test/jmri/jmrix/bidib/tcpserver/TcpServerTest.java
Labels: dev/test/publish infrastructure

#12620 Enhance the Entry/Exit action
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter5/entryexit_action.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/entryexit/EntryExitPairs.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionEntryExit.java
Labels: Needs L10N

#12617 Test Arch setUp / tearDown annotation
  java/test/jmri/InstanceManagerTest.java
  java/test/jmri/TestArchitectureTest.java
  java/test/jmri/jmrit/beantable/SignalHeadAddEditFrameTest.java
  java/test/jmri/jmrit/display/layoutEditor/LayoutTrackViewTest.java
  java/test/jmri/jmrit/symbolicprog/AbstractVariableValueTestBase.java
  java/test/jmri/server/json/JsonServiceFactoryTestBase.java
Labels: dev/test/publish infrastructure

#12624 Update Acknowledgement
  help/en/Acknowledgements.shtml
Labels: Documentation

#12625 Help cleanup and additions for DCC-EX
  help/en/html/hardware/dcc-ex/images/DCCppMenu.png
  help/en/html/hardware/dcc-ex/images/DCCppMenu416.png
  help/en/html/hardware/dcc-ex/index.shtml
  help/en/html/hardware/dccpp/index.shtml
  help/en/local/index.html
  help/en/parts/SidebarSupportedHardware.shtml
  java/src/jmri/jmrix/dccpp/swing/DCCppMenu.java
Labels: Documentation

#12627 Move ESU decoder add message from "Hardware" to "Decoders"
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#12629 Improve LogixNG Entry/Exit action
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionEntryExit.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionEntryExitSwing.java
Labels: Needs L10N

#12633 Minor doc updates
  help/en/Acknowledgements.shtml
  help/en/html/apps/DecoderPro/FileUpdate.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#12637 OperationsPro C/I and spur tracks now control locomotive movement
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderEngines.java
Labels: Documentation, Needs L10N

#12639 Add missing diagram to MQTT doc
  help/en/html/hardware/mqtt/images/mqttschematic2.jpg
Labels: Documentation

#12642 Support for Train-O-Rama FD Micro family of function decoders
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/TrainOMatic_FD.xml
  xml/decoders/tOm/enum-OutputEffect.xml
Labels: Documentation

#12647 Add help for new TSA whens and whats.
  help/en/package/jmri/jmrit/beantable/ViewSpecialActions.shtml
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/dispatcher/AutoTrainAction.java
Labels: Documentation

#12659 Validate NX Add Pair; check for LogixNG references
  help/en/html/tools/EntryExit.shtml
  help/en/html/tools/images/EntryExitLogixNGList.png
  help/en/html/tools/images/EntryExitValidateDialog.png
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/package/jmri/jmrit/entryexit/EntryExitFrame.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/entryexit/AddEntryExitPairPanel.java
  java/src/jmri/jmrit/entryexit/EntryExitBundle.properties
  java/src/jmri/jmrit/entryexit/EntryExitPairs.java
Labels: Documentation, Needs L10N

#12666 LocoNet ALM additions for recent-ish accessories
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/alm/Alm.java
  java/src/jmri/jmrix/loconet/alm/AlmMsgTypes.java
  java/src/jmri/jmrix/loconet/alm/almi/Almi.properties
  java/src/jmri/jmrix/loconet/alm/almi/Almir.java
  java/test/jmri/jmrix/loconet/alm/almi/AlmirTest.java
Labels: Needs L10N

#12669 Change format of CSV file written by Event Table
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/eventtable/EventTablePane.java
Labels: New PR

#12670 Update current-draft-note.shtml for web server ssi
  help/en/releasenotes/current-draft-note.shtml
Labels: New PR

#12671 Rename mqttschematic2.jpg to MQTTSchematic2.jpg so it will be found
  help/en/html/hardware/mqtt/images/MQTTSchematic2.jpg
Labels: Documentation, New PR
