Repository JMRI/JMRI, pull requests merged in 2023-09, with the labels that each got.

#12338 Yes, the SE74 can be programmed by DecoderPro
  help/en/html/hardware/loconet/SE74.shtml
Labels: Documentation

#12340 Documenting new CSS per Panel feature
  help/en/html/web/index.shtml
  web/css/user.css
Labels: Documentation

#12341 Update Acknowledgements for PR 12340
  help/en/Acknowledgements.shtml
Labels: Documentation

#12353 JOptionPane to JmriJOptionPane - CTC / decoderdefn
  java/src/jmri/jmrit/ctc/CTCMain.java
  java/src/jmri/jmrit/ctc/editor/code/CommonSubs.java
  java/src/jmri/jmrit/ctc/editor/gui/FrmAddModifyCTCColumn.java
  java/src/jmri/jmrit/ctc/editor/gui/FrmCO.java
  java/src/jmri/jmrit/ctc/editor/gui/FrmMainForm.java
  java/src/jmri/jmrit/ctc/editor/gui/FrmTRL_Rules.java
  java/src/jmri/jmrit/decoderdefn/DecoderFile.properties
  java/src/jmri/jmrit/decoderdefn/DecoderIndexFile.java
  java/src/jmri/jmrit/decoderdefn/InstallDecoderURLAction.java
  java/src/jmri/jmrit/decoderdefn/NameCheckAction.java
Labels: Needs L10N

#12382 OperationsPro New Tool
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_de.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/schedules/ScheduleEditFrame.java
  java/src/jmri/jmrit/operations/locations/schedules/SchedulesTableFrame.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/Bundle.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/ExportSchedules.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/ExportSchedulesAction.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/ScheduleCopyAction.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/ScheduleCopyFrame.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/ScheduleOptionsAction.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/ScheduleOptionsFrame.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/ScheduleResetHitsAction.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/SchedulesAndStagingAction.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/SchedulesAndStagingFrame.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/SchedulesByLoadAction.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/SchedulesByLoadFrame.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/SchedulesResetHitsAction.java
  java/src/jmri/jmrit/operations/locations/tools/TrackLoadEditFrame.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/Bundle.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/ExportSchedulesActionTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/ExportSchedulesTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/ScheduleCopyActionTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/ScheduleCopyFrameTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/ScheduleOptionsActionTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/ScheduleOptionsFrameTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/ScheduleResetHitsActionTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/SchedulesAndStagingActionTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/SchedulesAndStagingFrameTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/SchedulesByLoadActionTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/SchedulesByLoadFrameTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/SchedulesResetHitsActionTest.java
Labels: Needs L10N

#12385 Update load/store/work
  help/en/html/apps/LoadStoreWork.shtml
Labels: Documentation

#12388 Fix an edge case for the terminate train dispatcher action
  java/src/jmri/jmrit/logixng/util/DispatcherActiveTrainManager.java
Labels: New PR

#12390 update ThrottlesTableModel to prevent NPE
  java/src/jmri/jmrit/throttle/AddressPanel.java
  java/src/jmri/jmrit/throttle/ThrottlesTableModel.java
Labels: New PR

#12391 Fix bad test
  help/en/html/doc/Technical/Eclipse.shtml
  java/src/jmri/jmrit/operations/locations/schedules/tools/ExportSchedules.java
  java/src/jmri/jmrit/operations/locations/tools/ExportLocations.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/Bundle.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/BundleTest.java
Labels: New PR

#12393 Improve how tabs are rendered in OpenLCB/LCC CDI
  help/en/releasenotes/current-draft-note.shtml
  lib/README.md
  lib/openlcb.jar
Labels: New PR

#12395 Win Launcher log path
  jython/InitAllTurnoutsSensors.py
  scripts/WinInstallFiles/LaunchJMRI.exe
  scripts/WinInstallFiles/LaunchJMRI.nsi
Labels: New PR

#12396 Fix problem with Py3 constant definition
  jython/jmri_bindings.py3
Labels: New PR

#12398 Win Launcher NSIS Long Strings reminder
  help/en/html/doc/Technical/NetBeans.shtml
Labels: Documentation

#12400 OperationsPro Improve edit car load window
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/tools/ShowTrainsServingLocationFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ja_JP.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarLoadEditFrame.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarSetFrameTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarLoadAttributeActionTest.java
Labels: Documentation, Needs L10N

#12402 update uncaughtExceptionHandler / ExceptionDisplayFrame
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/setup/BackupDialog.java
  java/src/jmri/jmrit/operations/setup/LoadDemoAction.java
  java/src/jmri/jmrit/operations/setup/OperationsSettingsPanel.java
  java/src/jmri/jmrit/operations/setup/ResetAction.java
  java/src/jmri/jmrit/operations/setup/RestoreDialog.java
  java/src/jmri/jmrit/operations/setup/RestoreFilesAction.java
  java/src/jmri/util/StringUtil.java
  java/src/jmri/util/exceptionhandler/Bundle.properties
  java/src/jmri/util/exceptionhandler/Bundle_ca.properties
  java/src/jmri/util/exceptionhandler/Bundle_cs.properties
  java/src/jmri/util/exceptionhandler/UncaughtExceptionHandler.java
  java/src/jmri/util/swing/ExceptionContext.java
  java/src/jmri/util/swing/ExceptionDisplayFrame.java
  java/src/jmri/util/swing/UnexpectedExceptionContext.java
  java/src/jmri/util/swing/UtilBundle.properties
  java/test/jmri/util/StringUtilTest.java
  java/test/jmri/util/exceptionhandler/UncaughtExceptionHandlerTest.java
  java/test/jmri/util/swing/ExceptionContextTest.java
  java/test/jmri/util/swing/ExceptionDisplayFrameTest.java
  java/test/jmri/util/swing/UnexpectedExceptionContextTest.java
Labels: Needs L10N

#12406 Ignore two special cases which cause unexpected store requests during PanelPro shutdown
  help/en/package/apps/TabbedPreferences.shtml
  help/en/package/apps/images/PrefsShutdown.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/configurexml/ShutdownPreferences.java
  java/src/jmri/configurexml/StoreAndCompare.java
  java/src/jmri/configurexml/swing/Bundle.properties
  java/src/jmri/configurexml/swing/ShutdownPreferencesPanel.java
Labels: Documentation, Needs L10N

#12413 update PaletteBundle_en_GB
  java/src/jmri/jmrit/display/palette/PaletteBundle.properties
  java/src/jmri/jmrit/display/palette/PaletteBundle_en_GB.properties
  java/test/jmri/jmrit/display/palette/TableItemPanelTest.java
Labels: Needs L10N

#12419 OperationsPro Update help
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/ShowStagingAndSchedulesByCarTypeAndLoad.png
  java/src/jmri/jmrit/operations/locations/schedules/tools/SchedulesAndStagingFrame.java
Labels: Documentation

#12424 Log4JTreePane Dialog improvements.
  help/en/package/apps/jmrit/log/Log4JTreePane.png
  help/en/package/apps/jmrit/log/Log4JTreePane.shtml
  help/en/package/apps/jmrit/log/Log4JTreePane_543x360.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/jmrit/log/Log4JTreePane.java
  java/src/jmri/jmrit/Bundle.properties
Labels: Documentation, Needs L10N

#12427 OperationsPro, New tool preview or print car routing report
  java/src/jmri/jmrit/operations/rollingstock/RollingStockSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManagerXml.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarRoutingReportAction.java
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle.properties
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
  java/src/jmri/jmrit/operations/trains/TrainPrintUtilities.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrainBuildReportAction.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarRoutingReportActionTest.java
Labels: Needs L10N

#12436 Minor update to acknowledgements page
  help/en/Acknowledgements.shtml
Labels: Documentation

#12439 Change placeholders in MQTT topics to be consistent with all objects
  help/en/html/hardware/mqtt/index.shtml
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/jmri/jmrix/mqtt/Bundle.properties
  java/src/jmri/jmrix/mqtt/Bundle_cs.properties
  java/src/jmri/jmrix/mqtt/MqttConsist.java
  java/src/jmri/jmrix/mqtt/MqttConsistManager.java
  java/src/jmri/jmrix/mqtt/MqttThrottle.java
  java/src/jmri/jmrix/mqtt/MqttThrottleManager.java
  java/test/jmri/jmrix/mqtt/MqttConsistTest.java
  java/test/jmri/jmrix/mqtt/MqttThrottleTest.java
Labels: Documentation, Needs L10N

#12444 LocoNet Monitor for some Extended Accessory "long CV" accesses
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Enhancement, Add to Next Test Release

#12443 Add LogixNG tool WhereUsed
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGMenu.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/WhereUsedAction.java
  java/src/jmri/jmrit/logixng/tools/swing/WhereUsedFrame.java
  java/src/jmri/jmrit/logixng/util/UtilBundle.properties
  java/src/jmri/jmrit/logixng/util/WhereUsed.java
  java/test/jmri/jmrit/logixng/util/WhereUsedTest.java
Labels: Needs L10N, New PR

#12447 OperationsPro New feature, planned pickups for staging
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/locations/InterchangeEditFrame.java
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/SpurEditFrame.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/YardEditFrame.java
  java/src/jmri/jmrit/operations/locations/tools/AlternateTrackFrame.java
  java/src/jmri/jmrit/operations/locations/tools/IgnoreUsedTrackFrame.java
  java/src/jmri/jmrit/operations/locations/tools/TrackCopyAction.java
  java/src/jmri/jmrit/operations/locations/tools/TrackCopyFrame.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/TrainsTableModel.java
  java/test/jmri/jmrit/operations/locations/tools/TrackCopyFrameTest.java
Labels: Needs L10N

#12452 OperationsPro Routing Improvement
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/Location.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/schedules/Schedule.java
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
Labels: Needs L10N

#12451 web panels: improve font matching plus anyrail script fixes
  java/src/jmri/configurexml/StoreAndCompare.java
  java/src/jmri/jmrit/display/configurexml/PositionableLabelXml.java
  java/test/jmri/configurexml/LoadAndStoreTestBase.java
  jython/CreateSectionsFromBlocks.py
  jython/anyrail/AnyRailExportAdditions.py
  web/js/panel.js
  xml/schema/types/editors.xsd
Labels: New PR

#12454 YAAT: Add random wait times to the Wait for n seconds command
  help/en/html/scripthelp/yaat/YAAT.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/YetAnotherAutoTrain3.py
Labels: Documentation

#12456 Add Getting Started with RFID to web site/help
  help/en/html/hardware/rfid/GettingStartedWithRFID.shtml
  help/en/html/hardware/rfid/images/IDTagTableRel554.jpg
  help/en/html/hardware/rfid/images/Locomotives2Rel554.jpg
  help/en/html/hardware/rfid/images/LocomotivesRel554.jpg
  help/en/html/hardware/rfid/images/OpsProTablesLinkedRel554.jpg
  help/en/html/hardware/rfid/images/OpsProTablesRel554.jpg
  help/en/html/hardware/rfid/images/PanelProMainRel554.jpg
  help/en/html/hardware/rfid/images/PanelProTablesLinkedRel554.jpg
  help/en/html/hardware/rfid/images/PanelProTablesRel554.jpg
  help/en/html/hardware/rfid/images/PanelsTablesLinkedRel554.jpg
Labels: Documentation

#12460 OperationsPro Improve train manifest
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_de.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/LocationsTableFrame.java
  java/src/jmri/jmrit/operations/locations/StagingEditFrame.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/TrackEditFrame.java
  java/src/jmri/jmrit/operations/locations/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/tools/LocationCopyAction.java
  java/src/jmri/jmrit/operations/locations/tools/LocationCopyFrame.java
  java/src/jmri/jmrit/operations/locations/tools/ModifyLocationsAction.java
  java/src/jmri/jmrit/operations/locations/tools/ModifyLocationsCarLoadsAction.java
  java/src/jmri/jmrit/operations/locations/tools/TrackCopyAction.java
  java/src/jmri/jmrit/operations/locations/tools/TrackCopyFrame.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/routes/Route.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/test/jmri/jmrit/operations/locations/InterchangeEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/LocationEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/StagingEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/LocationCopyActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/LocationCopyFrameTest.java
  java/test/jmri/jmrit/operations/locations/tools/TrackCopyActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/TrackCopyFrameTest.java
Labels: Documentation, Needs L10N

#12462 New VSD option "chuff fade out"
  help/en/html/tools/vsd/VSDFileAndConfig.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/vsdecoder/Steam1Sound.java
Labels: Documentation
