Repository JMRI/JMRI, pull requests merged in 2023-04, with the labels that each got.

#11895 improve documentation of OpenLCB Sensor and Turnout options
  help/en/html/hardware/openlcb/index.shtml
Labels: Documentation

#11896 OperationsPro improve build report, no functional changes
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
Labels: Needs L10N

#11870 New CBUS NV Programming Method
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusDccProgrammer.java
  java/src/jmri/jmrix/can/cbus/node/CbusBasicNodeTable.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/CbusNodeNVEditGuiPane.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/CbusNodeTablePane.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/NodeConfigToolPane.java
  java/test/jmri/jmrix/can/cbus/CbusConfigurationManagerTest.java
  java/test/jmri/jmrix/can/cbus/CbusPredefinedMetersTest.java
  java/test/jmri/jmrix/can/cbus/node/CbusAllocateNodeNumberTest.java
  java/test/jmri/jmrix/can/cbus/node/CbusNodeTableDataModelTest.java
  xml/decoders/MERG_CBUS_canacc8.xml
  xml/decoders/MERG_CBUS_canmio_out.xml
  xml/decoders/MERG_CBUS_canmio_svo.xml
  xml/decoders/MERG_CBUS_cansol.xml
  xml/decoders/SPROG_DCC_CBUS_canisb.xml
  xml/decoders/SPROG_DCC_CBUS_canservoio.xml
  xml/decoders/SPROG_DCC_CBUS_cansolnoid.xml
  xml/decoders/SPROG_DCC_CBUS_cansprog3p.xml
  xml/decoders/cbus/EnumAccStartup.xml
  xml/decoders/cbus/EnumServoSpeed-0-7.xml
  xml/decoders/cbus/EnumServoStartup.xml
  xml/decoders/cbus/PaneCbusSetup.xml
  xml/decoders/cbus/PaneCbusSetupSimple.xml
  xml/decoders/cbus/PaneOut8.xml
  xml/decoders/cbus/PaneServo8.xml
  xml/decoders/cbus/PaneSol8.xml
  xml/decoders/cbus/PaneSolSetup.xml
  xml/decoders/cbus/VarOut8.xml
  xml/decoders/cbus/VarServo8.xml
  xml/decoders/cbus/VarServoCutoff.xml
  xml/decoders/cbus/VarServoWait.xml
  xml/decoders/cbus/VarSol8.xml
  xml/decoders/cbus/VarSolSetup.xml
  xml/programmers/Cbus.xml
Labels: Needs L10N

#11902 OpenLCB Hub - display LinkLocal addresses
  java/src/jmri/jmrix/openlcb/swing/hub/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/hub/HubPane.java
Labels: Needs L10N

#11903 Add php script to test and demonstrate the LogixNG action WebRequest
  help/en/html/tools/logixng/reference/WebRequestExample/LogixNG_WebRequest_Test.php
Labels: Documentation, New PR

#11906 Improve OLCB Event Table doc
  help/en/package/jmri/jmrix/openlcb/swing/eventtable/EventTablePane.shtml
Labels: Documentation

#11907 Update Preferences help and release note
  help/en/package/apps/TabbedPreferences.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#11911 Memory Table - value Class ToolTip
  help/en/package/jmri/jmrit/beantable/MemoryTable.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/MemoryTableDataModel.java
  java/test/jmri/jmrit/beantable/MemoryTableDataModelTest.java
Labels: Documentation

#11904 CBUS - update Import FCU xml file
  java/src/jmri/SystemConnectionMemo.java
  java/src/jmri/jmrix/DefaultSystemConnectionMemo.java
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusEvent.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeBackupManager.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeEvent.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeEventManager.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeFromBackup.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeFromFcuTableDataModel.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeNVManager.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/CbusNodeEventTablePane.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/CbusNodeInfoPane.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/CbusNodeRestoreFcuFrame.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/NodeConfigToolPane.java
  java/test/jmri/jmrix/can/cbus/node/CbusNodeBackupManagerTest.java
  java/test/jmri/jmrix/can/cbus/node/CbusNodeFromFcuTableDataModelTest.java
  java/test/jmri/jmrix/can/cbus/swing/nodeconfig/CbusNodeRestoreFcuFrameTest.java
  java/test/jmri/jmrix/can/cbus/swing/nodeconfig/fcu-n256-canpan.xml
Labels: Needs L10N, New PR

#11912 OperationsPro add counter action to automation
  java/src/jmri/jmrit/operations/automation/AutomationItem.java
  java/src/jmri/jmrit/operations/automation/JmritOperationsAutomationBundle.properties
  java/src/jmri/jmrit/operations/automation/actions/ActionCodes.java
  java/src/jmri/jmrit/operations/automation/actions/CounterAction.java
  java/test/jmri/jmrit/operations/automation/AutomationItemTest.java
  java/test/jmri/jmrit/operations/automation/actions/CounterActionTest.java
Labels: Needs L10N

#11915 Improve labelling of DecoderPro modes
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/progsupport/ProgServiceModeComboBox.java
  java/src/jmri/jmrit/progsupport/ProgSupportBundle.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneOpsProgFrame.java
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneServiceProgFrame.java
Labels: Needs L10N

#11916 LogixNG help for Web Request action
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_other.png
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_web_browser.png
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_web_request.png
  help/en/html/tools/logixng/reference/images/chapter5/web_request_charset.png
  help/en/html/tools/logixng/reference/images/chapter5/web_request_execute.png
  help/en/html/tools/logixng/reference/images/chapter5/web_request_method.png
Labels: Documentation, New PR

#11917 Update LogixNG action WebRequest
  help/en/html/tools/logixng/reference/WebRequestExample/WebRequest.xml
  java/src/jmri/jmrit/logixng/actions/WebRequest.java
  java/src/jmri/jmrit/logixng/actions/configurexml/WebRequestXml.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/WebRequestSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  xml/schema/logixng/digital-actions/web-request-5.3.5.xsd
Labels: Documentation, Needs L10N, New PR

#11919 Update LogixNG_WebRequest_Test.php
  help/en/html/tools/logixng/reference/WebRequestExample/LogixNG_WebRequest_Test.php
Labels: Documentation

#11923 Remove reference to post local variable
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_web_request.png
Labels: Documentation

#11930 Update WebRequest.xml
  help/en/html/tools/logixng/reference/WebRequestExample/WebRequest.xml
  java/test/jmri/jmrit/logixng/actions/WebRequestTest.java
  xml/schema/logixng/digital-actions/web-request-5.3.5.xsd
Labels: Documentation

#11931 Update LogixNG help
  help/en/html/tools/logixng/reference/chapter5.shtml
Labels: Documentation

#11933 Create TOC for Panel XML display/print function
  help/en/html/apps/PanelPro/ShowPanel.shtml
  help/en/releasenotes/current-draft-note.shtml
  web/js/PanelFileTOCinline.js
  xml/XSLT/panelfile-4-19-2.xsl
Labels: Documentation

#11938 OperationsPro car division improvements to "Show Car Types Serviced"
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/tools/TrainByCarTypeFrame.java
Labels: Needs L10N

#11945 Update help tooltip content
  help/en/package/jmri/jmrit/display/LayoutEditor.shtml
  help/en/package/jmri/jmrit/display/Tooltips.shtml
Labels: Documentation

#11947 Further improvement to XSLT Panel File Display/Print for Logix/LogixNG
  help/en/html/apps/PanelPro/ShowPanel.shtml
  xml/XSLT/panelfile-4-19-2.xsl
Labels: Documentation

#11958 Add "where used" tooltips to CV pane
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/symbolicprog/CvTableModel.java
  java/src/jmri/jmrit/symbolicprog/CvValueRenderer.java
  java/src/jmri/jmrit/symbolicprog/VariableTableModel.java
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgPane.java
Labels: Documentation

#11955 OperationsPro divisions, improve build report, update help
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
Labels: Documentation, Needs L10N

#11964 Digitrax Series7 SDXH167 decoder definition
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/decoderIndex.xml
  xml/decoders/Digitrax_0SFX_Series7.xml
Labels: Documentation

#11966 New AnyRailBuildBlockSensorList.py script and meta info
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/anyrail/AnyRailBuildBlockSensorList.py
  jython/anyrail/README.md
Labels: Documentation

#11970 Added progress dialogs to roster and decoder index recreation
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/Apps.java
  java/src/apps/gui3/dp3/DecoderPro3.java
  java/src/jmri/jmrit/decoderdefn/DecoderFile.properties
  java/src/jmri/jmrit/decoderdefn/DecoderIndexFile.java
  java/src/jmri/jmrit/roster/JmritRosterBundle.properties
  java/src/jmri/jmrit/roster/Roster.java
Labels: Needs L10N

#11974 Issue 11973 Improve Kuehn ZTC217 decoder definition
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/Kuehn_ZTC217.xml
Labels: Documentation

#11978 OperatiosPro improve help, printer paper size
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#11980 Add variable Lights to MQTT
  help/en/html/hardware/mqtt/index.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/implementation/AbstractVariableLight.java
  java/src/jmri/jmrix/mqtt/MqttLight.java
Labels: Documentation

#11984 Add native-DCC Turnout addressing to OpenLCB/LCC connections
  help/en/html/hardware/openlcb/index.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/OlcbAddress.java
Labels: Documentation
