Repository JMRI/JMRI, pull requests merged in 2023-03, with the labels that each got.

#11822 add CBUS Hub Control
  help/en/package/jmri/jmrix/can/cbus/swing/hubpane/CbusHubPane.shtml
  help/en/package/jmri/jmrix/can/cbus/swing/hubpane/cbus-hub-control-445x228.png
  help/en/package/jmri/jmrix/can/cbus/swing/hubpane/fcu-network-setup-467x566.png
  java/src/jmri/jmrix/can/CanActionListBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/swing/CbusMenu.java
  java/src/jmri/jmrix/can/cbus/swing/SprogCbusMenu.java
  java/src/jmri/jmrix/can/cbus/swing/hubpane/CbusHubAction.java
  java/src/jmri/jmrix/can/cbus/swing/hubpane/CbusHubPane.java
  java/src/jmri/jmrix/can/cbus/swing/hubpane/package-info.java
  java/test/jmri/jmrix/can/cbus/swing/hubpane/CbusHubActionTest.java
  java/test/jmri/jmrix/can/cbus/swing/hubpane/CbusHubPaneTest.java
Labels: Documentation, Needs L10N

#11823 Fix SE74 Help typo
  help/en/html/hardware/loconet/SE74.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Cleanup, Documentation

#11825 Add "duplicate" actions to the Timetable tool
  help/en/html/tools/TimeTable.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/timetable/Layout.java
  java/src/jmri/jmrit/timetable/Schedule.java
  java/src/jmri/jmrit/timetable/Segment.java
  java/src/jmri/jmrit/timetable/Station.java
  java/src/jmri/jmrit/timetable/Stop.java
  java/src/jmri/jmrit/timetable/TimeTableBundle.properties
  java/src/jmri/jmrit/timetable/TimeTableDataManager.java
  java/src/jmri/jmrit/timetable/Train.java
  java/src/jmri/jmrit/timetable/TrainType.java
  java/src/jmri/jmrit/timetable/swing/TimeTableFrame.java
  java/test/jmri/jmrit/timetable/swing/TimeTableFrameTest.java
Labels: Documentation, Needs L10N

#11828 Add an Event Table to the OpenLCB/LCC menu
  help/en/package/jmri/jmrix/openlcb/swing/eventtable/EventTablePane.shtml
  help/en/package/jmri/jmrix/openlcb/swing/eventtable/Event_Table.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/JmrixSystemsBundle.properties
  java/src/jmri/jmrix/openlcb/OlcbActionListBundle.properties
  java/src/jmri/jmrix/openlcb/OpenLcbMenu.java
  java/src/jmri/jmrix/openlcb/swing/eventtable/Bundle.java
  java/src/jmri/jmrix/openlcb/swing/eventtable/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/eventtable/EventTableAction.java
  java/src/jmri/jmrix/openlcb/swing/eventtable/EventTablePane.java
  java/src/jmri/jmrix/openlcb/swing/eventtable/package-info.java
  java/src/jmri/util/swing/MultiLineCellRenderer.java
  lib/README.md
  lib/openlcb.jar
Labels: Documentation, Needs L10N

#11831 Minor update to JVM summary doc
  help/en/html/doc/Technical/JVMCapabilities.shtml
  help/en/html/doc/Technical/JVMCapabilitiesOlder.shtml
Labels: Documentation, New PR

#11830 DecoderPro <-> TCS CS-105
  help/en/Acknowledgements.shtml
  help/en/html/hardware/openlcb/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/openlcb/TCS.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/TcsExportAction.java
  java/src/jmri/jmrit/symbolicprog/TcsImportAction.java
  java/src/jmri/jmrit/symbolicprog/TcsImporter.java
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
  java/test/jmri/jmrit/symbolicprog/TcsImporterTest.java
Labels: Documentation, Needs L10N

#11829 Digitrax Series7 programming support
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/symbolicprog/ExtraMenuTableModel.java
  java/src/jmri/jmrix/loconet/LnOpsModeProgrammer.java
  java/src/jmri/jmrix/loconet/LnProgrammerManager.java
  java/src/jmri/jmrix/loconet/LocoNetBundle.properties
  java/src/jmri/jmrix/loconet/alm/Alm.java
  java/src/jmri/jmrix/loconet/alm/almi/Almir.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_nl.properties
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
  xml/decoderIndex.xml
  xml/decoders/Digitrax_DS74.xml
  xml/decoders/Digitrax_SE74.xml
  xml/schema/decoder-4-15-2.xsd
Labels: Needs L10N

#11834 support page tweaks - CBUS Hub / networking
  help/en/html/doc/Technical/Networking.shtml
  help/en/html/hardware/can/cbus/images/swing/merg-cbus-menu-205x259.png
  help/en/html/hardware/can/cbus/images/swing/merg-menu-206x145.png
  help/en/html/hardware/can/cbus/index.shtml
  help/en/html/hardware/merg/Details.shtml
  help/en/package/jmri/jmrix/can/cbus/swing/hubpane/CbusHubPane.shtml
  help/en/package/jmri/jmrix/openlcb/swing/hub/HubPane.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/hub/Bundle.properties
Labels: Documentation, Needs L10N

#11837 OperationsPro, minor help update
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#11839 Add DecoderPro <-> TCS command station transfer
  help/en/html/hardware/openlcb/TCS.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/roster/FunctionLabelPane.java
  java/src/jmri/jmrit/roster/RosterEntryPane.java
  java/src/jmri/jmrit/symbolicprog/CvTableModel.java
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/TcsDownloadAction.java
  java/src/jmri/jmrit/symbolicprog/TcsExportAction.java
  java/src/jmri/jmrit/symbolicprog/TcsImportAction.java
  java/src/jmri/jmrit/symbolicprog/TcsImporter.java
  java/src/jmri/jmrit/symbolicprog/TcsUploadAction.java
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.java
Labels: Documentation, Needs L10N

#11848 Update openlcb.jar to 0.7.32
  help/en/releasenotes/current-draft-note.shtml
  lib/README.md
  lib/openlcb.jar
  pom.xml
Labels: New PR

#11849 Simplify LocoNet monitor sensor messages
  help/en/html/hardware/loconet/Addressing.shtml
  help/en/html/tools/signaling/SimpleSignalExample.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_nl.properties
  java/test/jmri/jmrix/loconet/LocoNetMessageTest.java
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Documentation, Needs L10N

#11850 Update help for Web Operations options
  help/en/html/web/Operations.shtml
  help/en/html/web/images/WebServerOperationsTrainsConductorExample.jpg
  help/en/html/web/images/WebServerOperationsTrainsExample.jpg
  help/en/html/web/images/WebServerOperationsTrainsManifestExample.jpg
Labels: Documentation

#11855 OperationsPro, minor help update
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#11867 Czech translation 2023-03-19
  java/src/apps/AppsBundle_cs.properties
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_cs.properties
  java/src/jmri/jmrit/display/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/display/logixng/swing/SwingBundle_cs.properties
  java/src/jmri/jmrit/display/palette/PaletteBundle_cs.properties
  java/src/jmri/jmrit/logix/WarrantBundle_cs.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_cs.properties
  java/src/jmri/jmrit/timetable/TimeTableBundle_cs.properties
  java/src/jmri/jmrit/withrottle/WiThrottleBundle_cs.properties
  java/src/jmri/jmrix/JmrixBundle_cs.properties
  java/src/jmri/jmrix/JmrixSystemsBundle_cs.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_cs.properties
  java/src/jmri/jmrix/loconet/usb_dcs52/UsbDcs52Bundle_cs.properties
  java/src/jmri/jmrix/openlcb/OlcbActionListBundle_cs.properties
  java/src/jmri/jmrix/openlcb/swing/eventtable/Bundle_cs.properties
  java/src/jmri/jmrix/openlcb/swing/hub/Bundle_cs.properties
  java/src/jmri/jmrix/openlcb/swing/memtool/Bundle_cs.properties
  java/src/jmri/jmrix/openlcb/swing/monitor/Bundle_cs.properties
  xml/decoders/TrainOMatic_NMJ_224.xml
Labels: Needs L10N

#11868 Create a LogixNG Transit Expression
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/images/chapter6/digital_expression_item.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/expressions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionTransit.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/ExpressionTransitXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle.properties
  java/src/jmri/jmrit/logixng/expressions/swing/ExpressionTransitSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/expressions/ExpressionTransitTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalExpressionSocketTest.java
  xml/schema/logixng/digital-expressions/digital-expressions-4.23.1.xsd
  xml/schema/logixng/digital-expressions/expression-transit-5.3.5.xsd
Labels: Documentation, Needs L10N

#11874 Fix missing SplitEnumVal for fragment files
  xml/schema/decoder-4-15-2.xsd
Labels: New PR

#11873 Update EventTablePane.shtml
  help/en/package/jmri/jmrix/openlcb/swing/eventtable/EventTablePane.shtml
Labels: Documentation

#11866 Adds OlcbReporter
  java/src/jmri/jmrix/openlcb/Bundle.properties
  java/src/jmri/jmrix/openlcb/OlcbAddress.java
  java/src/jmri/jmrix/openlcb/OlcbConfigurationManager.java
  java/src/jmri/jmrix/openlcb/OlcbReporter.java
  java/src/jmri/jmrix/openlcb/OlcbReporterManager.java
  java/src/jmri/jmrix/openlcb/configurexml/OlcbReporterManagerXml.java
  java/test/jmri/jmrix/openlcb/OlcbReporterManagerTest.java
  java/test/jmri/jmrix/openlcb/OlcbReporterTest.java
  java/test/jmri/jmrix/openlcb/configurexml/OlcbReporterManagerXmlTest.java
Labels: Needs L10N

#11876 OpenLCB updates
  help/en/Acknowledgements.shtml
  help/en/package/jmri/jmrix/openlcb/swing/eventtable/EventTablePane.shtml
  help/en/package/jmri/jmrix/openlcb/swing/eventtable/Event_Table.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/eventtable/EventTablePane.java
  lib/openlcb.jar
Labels: Documentation

#11882 OperationsPro improve build report, show spurs without schedules
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
Labels: Needs L10N

#11883 Throttle, labels on speed slider
  help/en/html/tools/throttle/RostersMediaPane.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/ControlPanelCustomSliderUI.java
  java/src/jmri/jmrit/throttle/StoreXmlThrottlesLayoutAction.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
  java/src/jmri/jmrit/throttle/ThrottleFramePropertyEditor.java
  java/src/jmri/jmrit/throttle/ThrottleWindow.java
  jython/Jynstruments/ThrottleFrame/Bell.jyn/Bell.py
  jython/Jynstruments/ThrottleFrame/Horn.jyn/Horn.py
  jython/Jynstruments/ThrottleFrame/Light.jyn/Light.py
  jython/Jynstruments/ThrottleFrame/SoundOn2xF0.jyn/SoundOn2xF0.py
  jython/Jynstruments/ThrottleFrame/SoundOnF8.jyn/SoundOnF8.py
  jython/Jynstruments/ThrottleWindowToolBar/DCCThrottle.jyn/DCCThrottle.py
  jython/Jynstruments/ThrottleWindowToolBar/WiimoteThrottle.jyn/WiimoteThrottle.py
  jython/Jynstruments/ThrottleWindowToolBar/WiimoteThrottle2.jyn/WiimoteThrottle2.py
  resources/icons/throttles/labelArrowHorizontal.png
  resources/icons/throttles/labelArrowVertical.png
Labels: Documentation, Needs L10N
