Repository JMRI/JMRI, pull requests merged in 2023-01, with the labels that each got.

#11697 Correct line ends on some decoder files
  xml/decoders/Piko_SmartDecoder_4.1_Sound.xml
  xml/decoders/Piko_SmartDecoder_XP5.1_Sound.xml
  xml/decoders/piko/Dateiliste_piko_4.1.txt
  xml/decoders/piko/Dateiliste_piko_XP5.1.txt
  xml/decoders/piko/cv897-1024_v5.1.xml
Labels: New PR

#11706 update Hardware Weblinks p-r
  help/en/html/hardware/pi/index.shtml
  help/en/html/hardware/powerline/Compatibility.shtml
  help/en/html/hardware/powerline/Names.shtml
  help/en/html/hardware/qsi/index.shtml
  help/en/html/hardware/raildriver/details.shtml
  help/en/html/hardware/raildriver/index.shtml
  help/en/html/hardware/roco/z21/index.shtml
  help/en/html/hardware/rps/index.shtml
  help/en/html/hardware/rps/sensors.shtml
Labels: Documentation

#11705 update Hardware Weblinks m-o
  help/en/html/hardware/maple/index.shtml
  help/en/html/hardware/marklin/index.shtml
  help/en/html/hardware/merg/index.shtml
  help/en/html/hardware/misc/DccSpecialties.shtml
  help/en/html/hardware/modbus/index.shtml
  help/en/html/hardware/mqtt/index.shtml
  help/en/html/hardware/mrc/index.shtml
  help/en/html/hardware/nce/NCE.shtml
  help/en/html/hardware/nce/Wangrow.shtml
  help/en/html/hardware/oaktree/OakTree.shtml
Labels: Documentation

#11704 update Hardware Weblinks c-i
  help/en/html/hardware/can/cbus/Names.shtml
  help/en/html/hardware/can/cbus/index.shtml
  help/en/html/hardware/can/index.shtml
  help/en/html/hardware/cmri/CMRI.shtml
  help/en/html/hardware/dccpp/index.shtml
  help/en/html/hardware/digirails/index.shtml
  help/en/html/hardware/ecos/index.shtml
  help/en/html/hardware/grapevine/Names.shtml
  help/en/html/hardware/grapevine/index.shtml
  help/en/html/hardware/ieee801254/index.shtml
Labels: Documentation

#11703 update Hardware Loconet Weblinks
  help/en/html/hardware/loconet/Addressing.shtml
  help/en/html/hardware/loconet/CommandStationConfig.shtml
  help/en/html/hardware/loconet/DCS240.shtml
  help/en/html/hardware/loconet/DCS52.shtml
  help/en/html/hardware/loconet/DS54.shtml
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/DigitraxMeters.shtml
  help/en/html/hardware/loconet/DigitraxPower.shtml
  help/en/html/hardware/loconet/KeyspanUSB.shtml
  help/en/html/hardware/loconet/LbServer.shtml
  help/en/html/hardware/loconet/LocoBuffer.shtml
  help/en/html/hardware/loconet/LocoBufferII.shtml
  help/en/html/hardware/loconet/LocoBufferUSB.shtml
  help/en/html/hardware/loconet/LocoIO.shtml
  help/en/html/hardware/loconet/LocoNetClasses.shtml
  help/en/html/hardware/loconet/LocoNetServer.shtml
  help/en/html/hardware/loconet/LocoNetSim.shtml
  help/en/html/hardware/loconet/LocoNetTools.shtml
  help/en/html/hardware/loconet/LocoNetworking.shtml
  help/en/html/hardware/loconet/MS100.shtml
  help/en/html/hardware/loconet/PR2.shtml
  help/en/html/hardware/loconet/PR3.shtml
  help/en/html/hardware/loconet/PR4.shtml
  help/en/html/hardware/loconet/StandaloneLocoNet.shtml
  help/en/html/hardware/loconet/Uhlenbrock.shtml
Labels: Documentation

#11702 update Hardware Weblinks index a-b
  help/en/html/hardware/MacintoshSerialPorts.shtml
  help/en/html/hardware/acela/Names.shtml
  help/en/html/hardware/acela/index.shtml
  help/en/html/hardware/anyma/index.shtml
  help/en/html/hardware/arduino/ArduinoCMRIByteComm.shtml
  help/en/html/hardware/arduino/index.shtml
  help/en/html/hardware/bachrus/index.shtml
  help/en/html/hardware/hardware-template.shtml
  help/en/html/hardware/index.shtml
Labels: Documentation

#11707 update Hardware Weblinks s-x
  help/en/html/hardware/SRCP/index.shtml
  help/en/html/hardware/TerminalServer.shtml
  help/en/html/hardware/USBtoSerial.shtml
  help/en/html/hardware/XBee/index.shtml
  help/en/html/hardware/XPressNet/index.shtml
  help/en/html/hardware/secsi/index.shtml
  help/en/html/hardware/sprog/SPROG.shtml
  help/en/html/hardware/sproggen5/Sidebar.shtml
  help/en/html/hardware/tams/index.shtml
  help/en/html/hardware/xap/index.shtml
Labels: Documentation

#11711 Switch AbstractValue states from ints to enum
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/gui3/dp3/PaneProgDp3Action.java
  java/src/jmri/jmrit/roster/LocoFile.java
  java/src/jmri/jmrit/symbolicprog/AbstractValue.java
  java/src/jmri/jmrit/symbolicprog/CompositeVariableValue.java
  java/src/jmri/jmrit/symbolicprog/ConstantValue.java
  java/src/jmri/jmrit/symbolicprog/CsvExportModifiedAction.java
  java/src/jmri/jmrit/symbolicprog/CvTableModel.java
  java/src/jmri/jmrit/symbolicprog/CvValue.java
  java/src/jmri/jmrit/symbolicprog/DecVarSlider.java
  java/src/jmri/jmrit/symbolicprog/DecVariableValue.java
  java/src/jmri/jmrit/symbolicprog/EnumVariableValue.java
  java/src/jmri/jmrit/symbolicprog/ExtraMenuTableModel.java
  java/src/jmri/jmrit/symbolicprog/FnMapPanelESU.java
  java/src/jmri/jmrit/symbolicprog/LongAddrVariableValue.java
  java/src/jmri/jmrit/symbolicprog/ShortAddrVariableValue.java
  java/src/jmri/jmrit/symbolicprog/SpeedTableVarValue.java
  java/src/jmri/jmrit/symbolicprog/SplitEnumVariableValue.java
  java/src/jmri/jmrit/symbolicprog/SplitVariableValue.java
  java/src/jmri/jmrit/symbolicprog/VariableTableModel.java
  java/src/jmri/jmrit/symbolicprog/VariableValue.java
  java/src/jmri/jmrit/symbolicprog/tabbedframe/PaneProgPane.java
  java/test/jmri/jmrit/symbolicprog/AbstractVariableValueTestBase.java
  java/test/jmri/jmrit/symbolicprog/CompositeVariableValueTest.java
  java/test/jmri/jmrit/symbolicprog/CvValueTest.java
  java/test/jmri/jmrit/symbolicprog/LongAddrVariableValueTest.java
  java/test/jmri/jmrit/symbolicprog/SplitVariableValueTest.java
Labels: Cleanup

#11716 Add Reporter support to MQTT connections
  help/en/Acknowledgements.shtml
  help/en/html/hardware/mqtt/index.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/implementation/AbstractNamedBean.java
  java/src/jmri/jmrix/mqtt/MqttReporter.java
  java/src/jmri/jmrix/mqtt/MqttReporterManager.java
  java/src/jmri/jmrix/mqtt/MqttSystemConnectionMemo.java
  java/src/jmri/jmrix/mqtt/configurexml/MqttReporterManagerXml.java
  java/src/jmri/managers/configurexml/DefaultIdTagManagerXml.java
  java/test/jmri/jmrix/mqtt/MqttReporterManagerTest.java
  java/test/jmri/jmrix/mqtt/MqttReporterTest.java
Labels: Documentation

#11720 Only notify throttle avaiable after the write of the throttle ID has …
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/images/LoconetAdditionalSettings.png
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/LnThrottleManager.java
  java/src/jmri/jmrix/loconet/LocoNetSlot.java
  java/src/jmri/jmrix/loconet/LocoNetThrottle.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/slotmon/SlotMonDataModel.java
  java/test/jmri/jmrix/loconet/LnThrottleManagerTest.java
Labels: Documentation, New PR

#11723 Minor updates to display of jython/ dir; MQTT help
  help/en/html/hardware/mqtt/images/MQTTPrefs_example.jpg
  jython/MQTT/README.md
  jython/README
  jython/README.md
  jython/index.php
Labels: Documentation

#11728 OperationsPro, GUI improvements
  java/src/jmri/jmrit/operations/rollingstock/RollingStockEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle.properties
  java/src/jmri/jmrit/operations/router/Router.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineEditFrameTest.java
Labels: Needs L10N

#11731 Fix bug that didn't restarted LogixNG Timer action
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionTimer.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionTimerXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionTimerSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/DeepCopyTest.java
  java/test/jmri/jmrit/logixng/SocketOperationTest.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.4.99.5.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.4.xml
  xml/schema/logixng/digital-actions/action-timer-4.23.1.xsd
Labels: Bug

#11727 Decoder UNI16ARD-NAV-TC
  xml/decoders/Public_Domain_dccdoma_UNI16ARD_NAV_TC.xml
  xml/decoders/public_domain/sidlo_enum_aspect.xml
  xml/decoders/public_domain/sidlo_enum_aspect_set.xml
  xml/decoders/public_domain/sidlo_enum_mast_preset.xml
  xml/decoders/public_domain/sidlo_enum_output.xml
Labels: New PR

#11735 Update LogixNG help for 5.3.2
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter5/timer_dialog.png
Labels: Documentation

#11738 OperationsPro, fix schedule bug
  java/src/jmri/jmrit/operations/rollingstock/cars/Car.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
Labels: New PR

#11744 Match directory names to output of Help->File Locations
  help/en/html/doc/Technical/Logging.shtml
Labels: Documentation

#11749 Add TurnoutsMasterSlave script
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/TurnoutsMasterSlave.py
Labels: Documentation

#11751 Put page breaks into Panel XML print using XSLT
  help/en/html/apps/PanelPro/ShowPanel.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/XSLT/panelfile-4-19-2.xsl
Labels: Documentation

#11755 ProtectRampFlag
  java/src/jmri/jmrit/logix/Engineer.java
  java/src/jmri/jmrit/logix/Warrant.java
  java/src/jmri/jmrit/logix/WarrantBundle.properties
  java/src/jmri/jmrit/logix/WarrantTableModel.java
Labels: Needs L10N

#11760 Fix cut&paste error in SetUnknownTurnoutsToClosed script
  jython/SetUnknownTurnoutsClosed.py
Labels: Bug, New PR

#11600 Support for SPROG DCC CAN ISB Module
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/node/CbusNodeCanListener.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeConstants.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeNVManager.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeNVTableDataModel.java
  java/src/jmri/jmrix/can/cbus/swing/modules/AbstractEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/base/Servo8BaseEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/base/Sol8BaseEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/merg/CanCmdEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/merg/CanCmdPaneProvider.java
  java/src/jmri/jmrix/can/cbus/swing/modules/merg/Canacc8EditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/CanisbEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/CanisbPaneProvider.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/PiSprog3EditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/PiSprog3PaneProvider.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/Sprog3PlusEditNVPane.java
  java/src/jmri/jmrix/can/cbus/swing/modules/sprogdcc/Sprog3PlusPaneProvider.java
  java/test/jmri/jmrix/can/cbus/swing/modules/sprogdcc/CanisbEditNVPaneTest.java
  java/test/jmri/jmrix/can/cbus/swing/modules/sprogdcc/CanisbPaneProviderTest.java
Labels: Needs L10N

#11772 Optionally Also request steal when address is in JMRI internal use
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/withrottle/MultiThrottleController.java
  java/src/jmri/jmrit/withrottle/WiThrottleBundle.properties
  java/src/jmri/jmrit/withrottle/WiThrottleBundle_de.properties
  java/src/jmri/jmrit/withrottle/WiThrottlePreferences.java
  java/src/jmri/jmrit/withrottle/WiThrottlePrefsPanel.java
Labels: Needs L10N

#11771 On Loconet, handle LACK 0x7 f properly
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/jmri/jmrix/loconet/SlotManager.java
  java/test/jmri/jmrix/loconet/LnOpsModeProgrammerTest.java
  java/test/jmri/jmrix/loconet/SlotManagerTest.java
Labels: Documentation

#11767 Small Typo
  java/src/jmri/jmrit/withrottle/WiThrottleBundle_de.properties
Labels: Needs L10N

#11773 Update DELAYED feedback description
  help/en/package/jmri/jmrit/beantable/TurnoutTable.shtml
Labels: Documentation
