Repository JMRI/JMRI, pull requests merged in 2024-01, with the labels that each got.

#12798 Update copyright notices to 2024
  build.xml
  help/en/indexheader
  help/en/tocheader
  project.properties
  scripts/HOWTO-distribution.md
  scripts/WinInstallFiles/LaunchJMRI.nsi
  xml/XSLT/CSVsummary.xsl
  xml/XSLT/CVsummary.xsl
  xml/XSLT/DecoderID.xsl
  xml/XSLT/DecoderMfgIndex.xsl
  xml/XSLT/DecoderModelIndex.xsl
  xml/XSLT/DecoderModelList.xsl
  xml/XSLT/LogixToCode.xsl
  xml/XSLT/SelectionGuide.xsl
  xml/XSLT/appearancetable.xsl
  xml/XSLT/aspecttable.xsl
  xml/XSLT/build.xml
  xml/XSLT/consistRoster.xsl
  xml/XSLT/decoder-with-form.xsl
  xml/XSLT/decoder.xsl
  xml/XSLT/idtags.xsl
  xml/XSLT/locomotive.xsl
  xml/XSLT/mfgID.xsl
  xml/XSLT/panelfile-2-9-6.xsl
  xml/XSLT/panelfile-4-19-2.xsl
  xml/XSLT/panelfile-5-5-5.xsl
  xml/XSLT/panelfile.xsl
  xml/XSLT/roster.xsl
  xml/XSLT/roster2text.xsl
  xml/XSLT/roster4web-simple.xsl
  xml/XSLT/roster4web.xsl
  xml/XSLT/rpsfile.xsl
  xml/XSLT/speedometer.xsl
  xml/XSLT/throttle-config.xsl
  xml/XSLT/throttle-layout-config.xsl
  xml/XSLT/timetable.xsl
  xml/XSLT/vsdecoder-config.xsl
Labels: dev/test/publish infrastructure

#12800 remove obsolete SF image
  help/en/parts/SidebarTail.shtml
Labels: Documentation

#12801 Fix extraneous offset in feedback reply display
  java/src/jmri/jmrix/lenz/XNetReply.java
  java/test/jmri/jmrix/lenz/XNetReplyTest.java
Labels: Documentation

#12802 restore github link in help footers
  help/en/parts/Footer.shtml
Labels: Documentation

#12805 Use block values when starting a VSDecoder
  help/en/html/tools/vsd/VSDLocationsMgr.shtml
  help/en/html/tools/vsd/VSDMain.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/vsdecoder/VSDecoderManager.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDManagerFrame.java
Labels: Documentation

#12812 CBUS Node Delete Event - prevent NPE
  java/src/jmri/jmrix/can/cbus/node/CbusBasicNode.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeEventManager.java
  java/test/jmri/jmrix/can/cbus/swing/nodeconfig/CbusNodeEditEventFrameTest.java
Labels: New PR

#12809 Add LogixNG action ProgramOnMain
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/ProgramOnMain.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ProgramOnMainXml.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/ProgramOnMainSwing.java
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectComboBox.java
  java/src/jmri/jmrit/logixng/util/configurexml/LogixNG_SelectComboBoxXml.java
  java/src/jmri/jmrit/logixng/util/swing/LogixNG_SelectComboBoxSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/actions/ActionScriptTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.5.1.3.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.5.1.4.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.5.5.5.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.3.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.1.4.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.5.5.xml
  java/test/jmri/jmrit/logixng/expressions/ExpressionScriptTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/common-types-4.23.1.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/program-on-main-5.7.3.xsd
Labels: Needs L10N

#12819 Lcc time messages
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/monitor/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/monitor/MonitorPane.java
Labels: Needs L10N

#12826 Issue 12825 - 31 functions in Trix decoders
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/decoders/trix/mLD3_mSD3_enum_triggers.xml
Labels: Documentation, New PR

#12832 New LogixNG actions
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionRequestUpdateOfSensor.java
  java/src/jmri/jmrit/logixng/actions/ActionTable.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionRequestUpdateOfSensorXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionTableXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionRequestUpdateOfSensorSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionTableSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectTable.java
  java/src/jmri/jmrit/logixng/util/swing/LogixNG_SelectTableSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/action-request-update-of-sensor-5.7.4.xsd
  xml/schema/logixng/digital-actions/action-table-5.7.4.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
Labels: Needs L10N

#12839 Routes can select feedback mode
  help/en/html/tools/Routes.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/Route.java
  java/src/jmri/implementation/DefaultRoute.java
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/routetable/AbstractRouteAddEditFrame.java
  java/src/jmri/managers/configurexml/DefaultRouteManagerXml.java
  xml/schema/types/routes-2-9-6.xsd
  xml/schema/types/routes.xsd
Labels: Documentation

#12840 LogixNG improvements
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/LogixNGPreferences.java
  java/src/jmri/jmrit/logixng/Stack.java
  java/src/jmri/jmrit/logixng/SymbolTable.java
  java/src/jmri/jmrit/logixng/actions/WebRequest.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionRequestUpdateAllSensorsSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/IfThenElseSwing.java
  java/src/jmri/jmrit/logixng/implementation/DefaultGlobalVariable.java
  java/src/jmri/jmrit/logixng/implementation/DefaultLogixNGManager.java
  java/src/jmri/jmrit/logixng/implementation/DefaultLogixNGPreferences.java
  java/src/jmri/jmrit/logixng/implementation/DefaultStack.java
  java/src/jmri/jmrit/logixng/implementation/DefaultSymbolTable.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGPreferencesPanel.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/util/TypeConversionUtil.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/SymbolTableTest.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/implementation/LogixNGPreferencesTest.java
Labels: Needs L10N

#12842 Fix bug in LogixNG
  java/src/jmri/jmrit/logixng/actions/swing/AbstractDigitalActionSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/AbstractAnalogExpressionSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/AbstractDigitalExpressionSwing.java
  java/src/jmri/jmrit/logixng/expressions/swing/AbstractStringExpressionSwing.java
Labels: Bug

#12845 Czech translation 2024-01-19
  java/src/apps/startup/Bundle_cs.properties
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle.properties
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/beanedit/BeanEditBundle_cs.properties
  java/src/jmri/jmrit/blockboss/BlockBossBundle_cs.properties
  java/src/jmri/jmrit/conditional/ConditionalBundle_cs.properties
  java/src/jmri/jmrit/decoderdefn/DecoderFile_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelBundle_cs.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_cs.properties
  java/src/jmri/jmrit/display/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/display/logixng/swing/SwingBundle_cs.properties
  java/src/jmri/jmrit/display/palette/PaletteBundle_cs.properties
  java/src/jmri/jmrit/entryexit/EntryExitBundle_cs.properties
  java/src/jmri/jmrit/logix/WarrantBundle_cs.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/swing/DigitalExpressionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/ToolsBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/UtilBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_cs.properties
  java/src/jmri/jmrit/whereused/Bundle_cs.properties
  java/src/jmri/jmrit/z21server/z21serverBundle_cs.properties
  java/src/jmri/jmrix/JmrixBundle_cs.properties
  java/src/jmri/jmrix/bidib/BiDiBBundle_cs.properties
  java/src/jmri/jmrix/bidib/swing/BiDiBSwingBundle_cs.properties
  java/src/jmri/jmrix/dccpp/DCCppActionListBundle_cs.properties
  java/src/jmri/jmrix/dccpp/swing/DCCppSwingBundle_cs.properties
  java/src/jmri/jmrix/lenz/XNetBundle_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/loconet/streamport/LnStreamBundle_cs.properties
  java/src/jmri/jmrix/mqtt/Bundle_cs.properties
  java/src/jmri/jmrix/nce/NceBundle_cs.properties
  java/src/jmri/jmrix/openlcb/Bundle_cs.properties
  java/src/jmri/jmrix/openlcb/swing/Bundle_cs.properties
  java/src/jmri/jmrix/openlcb/swing/monitor/Bundle_cs.properties
  java/src/jmri/jmrix/roco/RocoBundle_cs.properties
  java/src/jmri/server/json/Bundle_cs.properties
  java/src/jmri/server/json/audioicon/Bundle_cs.properties
  java/src/jmri/swing/Bundle_cs.properties
Labels: Needs L10N

#12847 Improve error messages of LogixNG actions
  java/src/jmri/jmrit/display/Editor.java
  java/src/jmri/jmrit/display/logixng/ActionPositionable.java
  java/src/jmri/jmrit/display/logixng/ActionPositionableByClass.java
  java/src/jmri/jmrit/display/logixng/LogixNGBundle.properties
  java/src/jmri/jmrit/logixng/implementation/swing/ErrorHandlingDialog_MultiLine.java
Labels: Needs L10N

#12848 Improve LCC/OpenLCB docs
  help/en/html/hardware/openlcb/index.shtml
Labels: Documentation

#12846 LogixNG action "Table: For each" can now loop thru the headers
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/TableForEach.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/LogLocalVariablesSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/TableForEachSwing.java
  java/test/jmri/jmrit/logixng/actions/ForTest.java
  java/test/jmri/jmrit/logixng/actions/TableForEachTest.java
Labels: Needs L10N

#12854 OperationsPro Fix "Show Cars in Train" window
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/jmrit/operations/trains/tools/ShowCarsInTrainFrame.java
Labels: Documentation, Needs L10N

#12860 Add LogixNG action WindowToFront
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/logixng/ActionFactory.java
  java/src/jmri/jmrit/display/logixng/ActionLayoutTurnout.java
  java/src/jmri/jmrit/display/logixng/ActionPositionable.java
  java/src/jmri/jmrit/display/logixng/ActionPositionableByClass.java
  java/src/jmri/jmrit/display/logixng/LogixNGBundle.properties
  java/src/jmri/jmrit/display/logixng/WindowToFront.java
  java/src/jmri/jmrit/display/logixng/configurexml/WindowToFrontXml.java
  java/src/jmri/jmrit/display/logixng/swing/WindowToFrontSwing.java
  java/src/jmri/util/JmriJFrame.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/display-action-window-to-front-5.7.4.xsd
Labels: Needs L10N

#12862 Additional documentation on MQTT features in JMRI
  help/en/html/hardware/mqtt/images/MQTT_Power_Control_rel554.png
  help/en/html/hardware/mqtt/index.shtml
Labels: Documentation

#12867 Fix NPE and missing bundles
  java/src/jmri/jmrit/logixng/LogixNGBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/TableForEachSwing.java
Labels: Needs L10N
