Repository JMRI/JMRI, pull requests merged in 2024-05, with the labels that each got.

#13069 OperationsPro Fix car import when RWE or RWL load name isn't specified
  java/src/jmri/jmrit/operations/rollingstock/ImportRollingStock.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/ImportCars.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/ImportCarsTest.java
Labels: New PR

#13070 Update Connections.shtml
  help/en/html/hardware/openlcb/Connections.shtml
Labels: Documentation

#13071 Let LogixNG log what it's doing
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/LogixNGPreferences.java
  java/src/jmri/jmrit/logixng/implementation/DefaultLogixNGPreferences.java
  java/src/jmri/jmrit/logixng/tools/debugger/AbstractDebuggerMaleSocket.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGPreferencesPanel.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
Labels: Needs L10N

#13078 OperationsPro improve help
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/Xml.java
  java/src/jmri/jmrit/operations/rollingstock/engines/Xml.java
Labels: Documentation

#13084 Update for Digitrax Series 7 decoders
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/LnOpsModeProgrammer.java
  java/src/jmri/jmrix/loconet/SlotManager.java
  java/src/jmri/jmrix/loconet/usb_dcs240Plus/UsbDcs240PlusAdapter.java
  java/test/jmri/jmrix/loconet/SlotManagerTest.java
  xml/decoders/Digitrax_0SFX_Series7.xml
  xml/decoders/Digitrax_0SFX_Series7.xsl
  xml/decoders/digitrax/PaneDigitraxFunctionmapSeries7.xml
  xml/decoders/digitrax/PaneDigitraxSoundFeaturesSeries7.xml
  xml/decoders/digitrax/featureSettings7.xml
  xml/decoders/digitrax/functionMapSettings7.xml
  xml/decoders/digitrax/soundOptions7.xml
  xml/decoders/digitrax/soundSettings7.xml
Labels: New PR

#13091 remove CVS $Revision$ tags
  java/src/apps/gui3/dp3/Bundle_fr.properties
  java/src/jmri/jmrit/DccLocoAddressSelectorBundle_cs.properties
  java/src/jmri/jmrit/DccLocoAddressSelectorBundle_fr.properties
  java/src/jmri/jmrit/automat/monitor/AutomatTableBundle_fr.properties
  java/src/jmri/jmrit/beantable/beanedit/BeanEditBundle_fr.properties
  java/src/jmri/jmrit/operations/automation/JmritOperationsAutomationBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_fr.properties
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle_fr.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_fr.properties
  java/src/jmri/jmrit/progsupport/ProgSupportBundle_fr.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_fr.properties
  java/src/jmri/jmrit/vsdecoder/swing/VSDSwingBundle_fr.properties
  java/src/jmri/jmrix/cmri/serial/nodeiolist/NodeIOListBundle.properties
  java/src/jmri/jmrix/cmri/serial/nodeiolist/NodeIOListBundle_de.properties
  java/src/jmri/jmrix/cmri/serial/nodeiolist/NodeIOListBundle_es.properties
  java/src/jmri/jmrix/cmri/serial/nodeiolist/NodeIOListBundle_it.properties
  java/src/jmri/jmrix/cmri/serial/nodeiolist/NodeIOListBundle_ja_JP.properties
  java/src/jmri/jmrix/lenz/swing/XNetSwingBundle_fr.properties
  java/src/jmri/jmrix/lenz/swing/lv102/LV102Bundle_fr.properties
  java/src/jmri/jmrix/lenz/swing/lzv100/LZ100Bundle_fr.properties
  java/src/jmri/jmrix/lenz/swing/stackmon/StackMonBundle_fr.properties
Labels: Needs L10N

#13086 Clarify to the reader what CTC even is.
  help/en/package/jmri/jmrit/ctc/CTC.shtml
Labels: New PR

#13096 Update CTC.shtml
  help/en/package/jmri/jmrit/ctc/CTC.shtml
Labels: Documentation

#13097 Add the hidden attribute to the Layout Editor Shape item
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutShape.java
  java/src/jmri/jmrit/display/layoutEditor/configurexml/LayoutShapeXml.java
  xml/schema/types/editors.xsd
Labels: Needs L10N

#13098 Usability improvments
  help/en/html/tools/throttle/RostersMediaPane.shtml
  help/en/html/tools/throttle/ThrottleWindowMenus.shtml
  help/en/html/tools/throttle/ThrottlesPreferencesPane.shtml
  help/en/html/tools/throttle/images/DecProFunctionLabels.png
  help/en/html/tools/throttle/images/ThrottlesPreferencesPane.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/roster/FunctionLabelPane.java
  java/src/jmri/jmrit/roster/JmritRosterBundle.properties
  java/src/jmri/jmrit/roster/RosterEntry.java
  java/src/jmri/jmrit/roster/swing/RosterFrame.java
  java/src/jmri/jmrit/roster/swing/RosterTable.java
  java/src/jmri/jmrit/throttle/ControlPanel.java
  java/src/jmri/jmrit/throttle/FunctionButton.java
  java/src/jmri/jmrit/throttle/FunctionPanel.java
  java/src/jmri/jmrit/throttle/ThrottleBundle.properties
  java/src/jmri/jmrit/throttle/ThrottleBundle_fr.properties
  java/src/jmri/jmrit/throttle/ThrottleFrame.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferences.java
  java/src/jmri/jmrit/throttle/ThrottlesPreferencesUISettingsPane.java
  resources/icons/functionicons/svg/cab_light_back_diesel_off_europe.svg
  resources/icons/functionicons/svg/cab_light_back_diesel_on_europe.svg
  resources/icons/functionicons/svg/cab_light_diesel_off_europe.svg
  resources/icons/functionicons/svg/cab_light_diesel_on_europe.svg
Labels: Documentation, Needs L10N

#13105 OperationsPro Improvements to Web Manifest and Conductor
  java/src/jmri/jmrit/operations/routes/RouteLocation.java
  java/src/jmri/jmrit/operations/trains/JsonManifest.java
  java/src/jmri/jmrit/operations/trains/TrainManifest.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchLists.java
  java/src/jmri/server/json/JSON.java
  java/src/jmri/server/json/operations/JsonOperationsHttpService.java
  java/src/jmri/server/json/operations/JsonUtil.java
  java/src/jmri/web/servlet/operations/HtmlConductor.java
  java/src/jmri/web/servlet/operations/HtmlManifest.java
  java/src/jmri/web/servlet/operations/HtmlTrainCommon.java
  java/src/jmri/web/servlet/operations/OperationsServlet.java
  web/servlet/operations/ManifestStrings.properties
  web/servlet/operations/ManifestStrings_cs.properties
  web/servlet/operations/ManifestStrings_de.properties
  web/servlet/operations/ManifestStrings_nl.properties
Labels: Needs L10N

#13108 Run separate-tests CI on macOS 14
  .github/workflows/run-separate.yml
Labels: dev/test/publish infrastructure

#13109 OperationsPro catch type or road name exception
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/ImportCars.java
Labels: Needs L10N

#13119 Add an Examples section to the LogixNG Reference
  help/en/html/tools/logixng/reference/YardLadderExample/index.shtml
  help/en/html/tools/logixng/reference/YardLadderExample/yard-ladder-example.zip
  help/en/html/tools/logixng/reference/YardLadderExample/yard-ladder-logixng.png
  help/en/html/tools/logixng/reference/YardLadderExample/yard-ladder-panel.png
  help/en/html/tools/logixng/reference/YardLadderExample/yard-ladder-table.png
  help/en/html/tools/logixng/reference/chapter11.shtml
  help/en/html/tools/logixng/reference/chapter8.shtml
  help/en/html/tools/logixng/reference/index.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#13126 OperationsPro allow user to use departure times on switch lists
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_da.properties
  java/src/jmri/jmrit/operations/setup/PrintOptionPanel.java
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainManifest.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchLists.java
  java/test/jmri/jmrit/operations/setup/PrintOptionPanelTest.java
  java/test/jmri/jmrit/operations/trains/TrainManifestTest.java
  xml/DTD/operations-config.dtd
Labels: Needs L10N

#13125 Improve LogixNG action ProgramOnMain
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ProgramOnMain.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ProgramOnMainXml.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/ProgramOnMainSwing.java
  java/src/jmri/jmrit/logixng/util/swing/LogixNG_SelectEnumSwing.java
  java/src/jmri/jmrit/logixng/util/swing/LogixNG_SelectEnumSwing_EnumDialog.java
  java/src/jmri/jmrit/logixng/util/swing/SwingBundle.properties
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.7.5.xml
  xml/schema/logixng/digital-actions/program-on-main-5.7.3.xsd
Labels: New PR

#13134 OperationsPro Make frame titles more web server friendly
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/YardmasterFrame.java
  java/src/jmri/jmrit/operations/trains/TrainsTableFrame.java
  java/test/jmri/jmrit/operations/locations/LocationsTableFrameTest.java
Labels: Needs L10N

#13136 20240524 edit train name
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
  java/src/jmri/jmrit/dispatcher/TrainInfo.java
  java/src/jmri/jmrit/dispatcher/TrainInfoFile.java
  java/test/jmri/jmrit/dispatcher/traininfo/TestTrainCW.xml
  java/test/jmri/jmrit/dispatcher/traininfo/TestTrainCW_Return.xml
Labels: Needs L10N

#13132 Can't paste if male socket isn't compatible with female socket
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
Labels: Bug, New PR

#13139 Add TSA to try and bypass next safe section.
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/TransitSectionAction.java
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle.properties
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/dispatcher/ActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoAllocate.java
  java/src/jmri/jmrit/dispatcher/AutoTrainAction.java
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
Labels: Needs L10N

#13138 Update NCE.shtml
  help/en/html/hardware/nce/NCE.shtml
Labels: Documentation

#13145 LogixNG: Only unregister listeners when needed
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
Labels: New PR
