Repository JMRI/JMRI, pull requests merged in 2024-03, with the labels that each got.

#12934 Update LogixNG help for 5.7.5 changes
  help/en/html/tools/logixng/LogixNG.shtml
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter8.shtml
  help/en/html/tools/logixng/reference/chapter9.shtml
  help/en/html/tools/logixng/reference/images/chapter5/action_item_enable_disable_logixng.png
  help/en/html/tools/logixng/reference/images/chapter5/action_item_set_reporter.png
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_item.png
  help/en/html/tools/logixng/reference/images/chapter8/local_variable_types.png
  help/en/html/tools/logixng/reference/images/chapter8/log_variables.png
  help/en/html/tools/logixng/reference/images/chapter9/functions_convert.png
Labels: Documentation

#12942 Improve LogixNG
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ForEach.java
  java/src/jmri/jmrit/logixng/util/parser/ExpressionNodeMethod.java
  java/src/jmri/jmrit/logixng/util/parser/FunctionManager.java
  java/src/jmri/jmrit/logixng/util/parser/functions/CommonFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/StringFunctions.java
  java/test/jmri/jmrit/logixng/actions/ForEachTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/CommonFunctionsTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/StringFunctionsTest.java
Labels: Documentation, Needs L10N

#12940 Improve the STL Editor store process
  help/en/html/hardware/openlcb/index.shtml
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.shtml
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/compile_error.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/compile_good.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/compile_required.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/lcc_menu.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/store_done.png
  java/src/jmri/jmrix/openlcb/swing/stleditor/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.java
Labels: Documentation, Needs L10N

#12943 Help update for PR 12942
  help/en/html/tools/logixng/reference/chapter9.shtml
  help/en/html/tools/logixng/reference/images/chapter9/functions_common.png
  help/en/html/tools/logixng/reference/images/chapter9/functions_string.png
Labels: Documentation

#12945 Test a jython created function in LogixNG formula
  java/test/jmri/jmrit/logixng/util/parser/functions/JythonDefinedFunctionsTest.java
Labels: New PR

#12946 Fix two bugs in LogixNG functions. Improve testing of LogixNG functions.
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/util/parser/functions/AbstractFunction.java
  java/src/jmri/jmrit/logixng/util/parser/functions/NamedBeanFunctions.java
  java/src/jmri/util/TypeConversionUtil.java
  java/test/jmri/jmrit/logixng/util/parser/functions/ClockFunctionsTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/CommonFunctionsTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/ConvertFunctionsTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/ExpressionNodeConstantScaffold.java
  java/test/jmri/jmrit/logixng/util/parser/functions/JavaFunctionsTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/LayoutFunctionsTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/MathFunctionsTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/NamedBeanFunctionsTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/StringFunctionsTest.java
Labels: Bug, New PR

#12944 Dispatcher. Add ramping using the speed profile. It will adjust the s…
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
Labels: Needs L10N

#12947 Refactor LogixNG functions - No functional changes
  java/src/jmri/jmrit/logixng/util/parser/functions/ClockFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/CommonFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/ConvertFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/JavaFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/LayoutFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/MathFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/NamedBeanFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/StringFunctions.java
  java/test/jmri/jmrit/logixng/util/parser/functions/ConvertFunctionsTest.java
Labels: New PR

#12948 Add new LogixNG functions
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/MathFunctions.java
  java/test/jmri/jmrit/logixng/util/parser/functions/MathFunctionsTest.java
Labels: Needs L10N

#12951 Update LogixNG chapter 9
  help/en/html/tools/logixng/reference/chapter9.shtml
  help/en/html/tools/logixng/reference/images/chapter9/functions_math.png
Labels: Documentation, New PR

#12952 Sort by Tools => Servers menu items by name
  java/src/jmri/jmrit/ToolsMenu.java
Labels: New PR

#12953 OperationsPro Add warning to system console if Operations.xml corrupted
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/LocationManagerXml.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManagerXml.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineManagerXml.java
  java/src/jmri/jmrit/operations/routes/RouteManagerXml.java
  java/src/jmri/jmrit/operations/setup/OperationsSetupXml.java
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/trains/TrainManagerXml.java
Labels: Documentation, New PR

#12954 Czech translation 2024-03-09
  java/src/jmri/jmrit/etcs/Bundle_cs.properties
  java/src/jmri/jmrix/cmri/serial/assignment/ListBundle_cs.properties
  java/src/jmri/jmrix/cmri/serial/cmrinetmanager/CMRInetManagerBundle_cs.properties
  java/src/jmri/jmrix/cmri/serial/diagnostic/DiagnosticBundle_cs.properties
  java/src/jmri/jmrix/cmri/serial/nodeconfig/NodeConfigBundle_cs.properties
  java/src/jmri/jmrix/cmri/serial/nodeconfigmanager/NodeConfigManagerBundle_cs.properties
  java/src/jmri/jmrix/cmri/serial/nodeiolist/NodeIOListBundle_cs.properties
  java/src/jmri/jmrix/cmri/serial/serialmon/SerialFilterBundle_cs.properties
Labels: Needs L10N, New PR

#12966 Replace boolean resistancewheelset with multi state traindetection,
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/dispatcher/ActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_ca.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_cs.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_da.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_fr.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_it.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_nl.properties
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
  java/src/jmri/jmrit/dispatcher/TrainInfo.java
  java/src/jmri/jmrit/dispatcher/TrainInfoFile.java
  java/test/jmri/jmrit/dispatcher/DispatcherTrainInfoFileTest.java
  java/test/jmri/jmrit/dispatcher/DispatcherTrainInfoTest.java
  java/test/jmri/jmrit/dispatcher/traininfo/TestInfoV5-WholeTrain.xml
Labels: Needs L10N

#12968 fix remote command arguments in example
  help/en/html/doc/Technical/GitFAQ.shtml
Labels: Documentation

#12976 Czech translation 2024-03-23
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/display/logixng/swing/SwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
Labels: Needs L10N

#12978 Italian language update
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/AppsBundle_it.properties
  java/src/jmri/NamedBeanBundle_it.properties
  java/src/jmri/jmrit/conditional/ConditionalBundle_it.properties
  java/src/jmri/jmrix/can/cbus/CbusBundle_it.properties
  java/src/jmri/jmrix/lenz/XNetBundle_it.properties
  xml/signals/FS-1987/appearance-ACEIIcat.1vela.xml
  xml/signals/FS-1987/appearance-ACEIIcat.2vele.xml
  xml/signals/FS-1987/appearance-ACEIacc.2vele.xml
  xml/signals/FS-1987/appearance-ACEIacc.3vele.xml
  xml/signals/FS-1987/appearance-ACEIavv.1vela.xml
  xml/signals/FS-1987/appearance-ACEIavv.2vele.xml
Labels: Needs L10N

#12983 json: restore examples, add car.whereLastSeen, car.whenLastSeen; don't hide /json and /simple links on home page
  help/en/html/web/JsonServlet.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/server/json/JSON.java
  java/src/jmri/server/json/operations/JsonUtil.java
  java/src/jmri/server/json/operations/car-client.json
  java/src/jmri/server/json/operations/car-server.json
  java/src/jmri/server/json/operations/engine-client.json
  java/src/jmri/server/json/operations/engine-server.json
  java/test/jmri/server/json/operations/JsonOperationsHttpServiceTest.java
  web/servlet/home/Home.html
  web/servlet/home/Home_cs.html
  web/servlet/home/Home_de.html
  web/servlet/home/Home_nl.html
Labels: Documentation

#12986 Update help for script access to LogixNG local variables
  help/en/html/tools/logixng/reference/chapter13.shtml
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/chapter8.shtml
  help/en/html/tools/logixng/reference/chapter9.shtml
  help/en/html/tools/logixng/reference/images/chapter13/greeting-conditional.png
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation
