Repository JMRI/JMRI, pull requests merged in 2024-11, with the labels that each got.

#13562 Roster Speed Profile lint
  java/src/jmri/SpeedStepMode.java
  java/src/jmri/jmrit/roster/RosterSpeedProfile.java
  java/test/jmri/jmrit/roster/RosterSpeedProfileTest.java
Labels: New PR

#13571 OperationsPro New feature, Set Locomotives
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/rollingstock/RollingStockSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarsSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EngineSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/JmritOperationsEnginesBundle_nl.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/EnginesSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/EnginesSetFrameAction.java
  java/src/jmri/jmrit/operations/trains/TrainsTableModel.java
  java/test/jmri/jmrit/operations/XmlLoadTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EngineSetFrameTest.java
Labels: Needs L10N

#13570 Improve creation of default Node ID
  java/src/jmri/jmrix/openlcb/OlcbConfigurationManager.java
Labels: New PR

#13577 Lenz XpressNet ThrottleManager- releaseThrottle
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/lenz/XNetThrottleManager.java
  java/test/jmri/managers/AbstractThrottleManagerTestBase.java
Labels: New PR

#13580 OperationsPro improve build report
  java/src/jmri/jmrit/operations/router/Router.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/Train.java
Labels: Needs L10N

#13581 Add a preview STL logic option to the view menu
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.shtml
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/stl_preview.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/view_menu.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/stleditor/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.java
Labels: Documentation, Needs L10N

#13583 Update acknowledgments
  help/en/Acknowledgements.shtml
Labels: Documentation

#13584 OperationsPro More build report improvements
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/Train.java
Labels: Needs L10N, New PR

#13588 Stop autoallocate thread when dispatcher exits.
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
Labels: New PR

#13589 STL Editor: Implement a shift-click copy process
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.java
Labels: Documentation, New PR

#13591 OperationsPro add car's "Route Path" to car export
  java/src/jmri/jmrit/operations/JmritOperationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/ExportCars.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
Labels: Needs L10N, New PR

#13595 update CBUS Command Station Monitor
  help/en/html/hardware/can/cbus/images/swing/command-station/cbus-command-station-sessions-774x213.png
  help/en/html/hardware/can/cbus/images/swing/command-station/cs-session-626x179.png
  help/en/package/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorPane.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusThrottleManager.java
  java/src/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorDataModel.java
  java/src/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorPane.java
  java/test/jmri/jmrix/can/cbus/CbusThrottleManagerTest.java
  java/test/jmri/jmrix/can/cbus/swing/cbusslotmonitor/CbusSlotMonitorDataModelTest.java
Labels: Documentation, Needs L10N

#13599 Add SNIP request to OpenLCB/LCC Send pane
  help/en/package/jmri/jmrix/openlcb/swing/send/OpenLcbCanSendFrame.shtml
  help/en/package/jmri/jmrix/openlcb/swing/send/SendFrame.jpg
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/send/OpenLcbCanSendPane.java
Labels: Documentation, New PR

#13601 Czech translation 2024-11-13
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrix/nce/NceBundle_cs.properties
  java/src/jmri/util/swing/UtilBundle_cs.properties
  xml/decoders/Kuehn_N45.xml
Labels: Needs L10N

#13600 STL Editor: Add multiple store modes to the View menu.
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.shtml
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/compact_preview.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/compressed_preview.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/editor_tab.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/input_tab.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/output_tab.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/readable_preview.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/receivers_tab.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/stl_preview.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/transmitters_tab.png
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/images/view_menu.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/stleditor/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.java
Labels: Documentation, Needs L10N

#13602 add John Purcell to acknowledgements
  help/en/Acknowledgements.shtml
Labels: Documentation

#13605 Roster Table - Improve Operating Duration column
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/roster/swing/Bundle.properties
  java/src/jmri/jmrit/roster/swing/RosterTable.java
  java/src/jmri/jmrit/roster/swing/RosterTableModel.java
  java/src/jmri/util/DateUtil.java
  java/test/jmri/jmrit/roster/swing/RosterTableTest.java
  java/test/jmri/util/DateUtilTest.java
Labels: Needs L10N

#13609 allow 8 VSDecoders instead of 4
  help/en/html/tools/vsd/VSDHeadless.shtml
  help/en/html/tools/vsd/VSDLocationsMgr.shtml
  help/en/html/tools/vsd/VSDMain.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/vsdecoder/VSDecoder.java
  java/src/jmri/jmrit/vsdecoder/VSDecoderManager.java
  java/src/jmri/jmrit/vsdecoder/swing/VSDControl.java
Labels: Documentation

#13610 Operations Tests - Wait for Threads
  java/test/jmri/jmrit/operations/XmlLoadTest.java
  java/test/jmri/jmrit/operations/automation/AutomationManagerTest.java
  java/test/jmri/jmrit/operations/automation/actions/BuildTrainActionTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/ExportSchedulesActionTest.java
  java/test/jmri/jmrit/operations/locations/schedules/tools/ExportSchedulesTest.java
  java/test/jmri/jmrit/operations/locations/tools/ExportLocationsRosterActionTest.java
  java/test/jmri/jmrit/operations/locations/tools/ExportLocationsTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/ExportCarsTest.java
  java/test/jmri/jmrit/operations/rollingstock/engines/tools/ExportEnginesTest.java
  java/test/jmri/jmrit/operations/routes/RouteEditFrameTest.java
  java/test/jmri/jmrit/operations/routes/tools/ExportRoutesTest.java
  java/test/jmri/jmrit/operations/trains/TrainEditFrameTest.java
  java/test/jmri/jmrit/operations/trains/XmlTest.java
  java/test/jmri/jmrit/operations/trains/tools/ExportTimetableActionTest.java
  java/test/jmri/jmrit/operations/trains/tools/ExportTimetableTest.java
  java/test/jmri/jmrit/operations/trains/tools/ExportTrainLineupsActionTest.java
  java/test/jmri/jmrit/operations/trains/tools/ExportTrainLineupsTest.java
  java/test/jmri/jmrit/operations/trains/tools/ExportTrainRosterActionTest.java
  java/test/jmri/jmrit/operations/trains/tools/ExportTrainsTest.java
  java/test/jmri/jmrit/operations/trains/tools/PrintSavedTrainManifestActionTest.java
Labels: New PR

#13612 OperationsPro Fix bug in Show Staging and Schedules by Car Type and Load
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/schedules/tools/SchedulesAndStagingFrame.java
  java/src/jmri/jmrit/operations/locations/tools/TrackDestinationEditFrame.java
Labels: Documentation

#13615 OpenLCB update to current library version
  help/en/package/jmri/jmrix/openlcb/swing/networktree/NetworkTreePane.shtml
  help/en/releasenotes/current-draft-note.shtml
  lib/README.md
  lib/openlcb.jar
Labels: Documentation

#13618 Update Comp_Speed_Talble.shtml
  help/en/manual/DecoderPro3/Comp_Speed_Talble.shtml
  help/en/manual/DecoderPro3/images/Speed_Table_Speedsteps.png
Labels: Documentation

#13617 Update Comp_Speed_Talble.shtml
  help/en/manual/DecoderPro3/Comp_Speed_Talble.shtml
Labels: Documentation

#13622 SymbolicProg NL
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle.properties
  java/src/jmri/jmrit/symbolicprog/SymbolicProgBundle_nl.properties
Labels: Needs L10N

#13624 NBB properties nl
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/NamedBeanBundle_nl.properties
  java/src/jmri/configurexml/swing/Bundle_nl.properties
  java/src/jmri/jmrit/sensorgroup/Bundle_nl.properties
Labels: Needs L10N

#13630 LogixNG nl translations
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_nl.properties
  java/src/jmri/jmrit/beantable/LogixNGModuleTableAction.java
  java/src/jmri/jmrit/beantable/LogixNGTableTableAction.java
  java/src/jmri/jmrit/beantable/LogixTableAction.java
  java/src/jmri/jmrit/beantable/beanedit/BeanEditBundle_nl.properties
  java/src/jmri/jmrit/display/DisplayBundle_nl.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_nl.properties
  java/src/jmri/jmrit/logixng/implementation/ImplementationBundle.properties
  java/src/jmri/jmrit/logixng/implementation/ImplementationBundle_nl.properties
  java/src/jmri/jmrit/logixng/implementation/swing/ErrorHandlingDialog.java
  java/src/jmri/jmrit/logixng/implementation/swing/ErrorHandlingDialog_MultiLine.java
  java/src/jmri/jmrit/logixng/tools/ToolsBundle.properties
  java/src/jmri/jmrit/logixng/tools/ToolsBundle_nl.properties
  java/src/jmri/jmrit/logixng/tools/debugger/DebuggerBundle_nl.properties
  java/src/jmri/jmrit/logixng/tools/swing/EditCommentDialog.java
  java/src/jmri/jmrit/logixng/tools/swing/EditThreadsDialog.java
  java/src/jmri/jmrit/logixng/tools/swing/ImportLogixFrame.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGBrowseWindow.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_nl.properties
  java/src/jmri/jmrit/logixng/tools/swing/TableEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
  java/src/jmri/jmrit/logixng/util/parser/swing/FunctionsHelpDialog.java
  java/src/jmri/jmrit/permission/swing/AddUserDialog.java
  java/src/jmri/jmrit/permission/swing/Bundle.properties
  java/src/jmri/jmrit/permission/swing/Bundle_cs.properties
  java/src/jmri/jmrit/permission/swing/Bundle_de.properties
  java/src/jmri/jmrit/permission/swing/Bundle_nl.properties
  java/src/jmri/jmrit/permission/swing/ChangePasswordAction.java
  java/src/jmri/jmrit/permission/swing/ChangePasswordDialog.java
  java/src/jmri/jmrit/permission/swing/ChangeUserPasswordDialog.java
  java/src/jmri/jmrit/permission/swing/LoginAction.java
  java/src/jmri/jmrit/permission/swing/LoginDialog.java
  java/src/jmri/swing/Bundle_cs.properties
  java/src/jmri/swing/Bundle_nl.properties
Labels: Needs L10N, New PR

#13633 Update OpenLCB_Java openlcb.jar to 0.8.2 from Maven Central
  lib/README.md
  lib/openlcb.jar
  pom.xml
Labels: Cleanup

#13613 LocoNet monitor Ops CV
  java/src/jmri/jmrix/lenz/LenzCommandStation.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
Labels: New PR
