Repository JMRI/JMRI, pull requests merged in 2024-07, with the labels that each got.

#13239 OperationsPro minor build report car routing formatting change
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/router/JmritOperationsRouterBundle.properties
Labels: Documentation, Needs L10N

#13240 Linking to /extras/sounds
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  resources/sounds/README.md
Labels: Contribution, Documentation

#13245 Improve LogixNG system name handling
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/AbstractLogixNGTableAction.java
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGEditor.java
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle.properties
  java/src/jmri/jmrit/logixng/tools/swing/TreeEditor.java
Labels: Needs L10N

#13249 Dispatcher System: corrections to scheduling
  jython/DispatcherSystem/Scheduler.py
Labels: New PR

#13251 TMCC 200 speed steps
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/SpeedStepMode.java
  java/src/jmri/jmrix/tmcc/SerialThrottle.java
  java/src/jmri/jmrix/tmcc/SerialThrottleManager.java
Labels: Needs L10N

#13252 240711 prevent accidental delete
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/profile/Bundle.properties
  java/src/jmri/profile/ProfileManagerDialog.java
  java/src/jmri/profile/ProfilePreferencesPanel.java
Labels: Needs L10N

#13255 OperationsPro Add trains file saved to train logger
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainLogger.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
Labels: Needs L10N

#13260 OpenLCB memory tool: parse space input when doing a put
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/memtool/MemoryToolPane.java
Labels: New PR

#13263 Refactored Bachrus Speed Matcher with Speed Step Scale Speed Matching
  java/src/jmri/jmrix/bachrus/BachrusBundle.properties
  java/src/jmri/jmrix/bachrus/DccSpeedProfile.java
  java/src/jmri/jmrix/bachrus/GraphPane.java
  java/src/jmri/jmrix/bachrus/Speed.java
  java/src/jmri/jmrix/bachrus/SpeedoConsoleAction.java
  java/src/jmri/jmrix/bachrus/SpeedoConsoleFrame.java
  java/src/jmri/jmrix/bachrus/SpeedoDial.java
  java/src/jmri/jmrix/bachrus/SpeedoStartupActionFactory.java
  java/src/jmri/jmrix/bachrus/speedmatcher/Bundle.java
  java/src/jmri/jmrix/bachrus/speedmatcher/SpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/SpeedMatcherBundle.properties
  java/src/jmri/jmrix/bachrus/speedmatcher/SpeedMatcherConfig.java
  java/src/jmri/jmrix/bachrus/speedmatcher/basic/BasicESUTableSpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/basic/BasicSimpleCVSpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/basic/BasicSpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/basic/BasicSpeedMatcherBundle.properties
  java/src/jmri/jmrix/bachrus/speedmatcher/basic/BasicSpeedMatcherConfig.java
  java/src/jmri/jmrix/bachrus/speedmatcher/basic/BasicSpeedMatcherFactory.java
  java/src/jmri/jmrix/bachrus/speedmatcher/basic/BasicSpeedTableSpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/basic/Bundle.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/Bundle.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleESUTableSpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleSpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleSpeedMatcherBundle.properties
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleSpeedMatcherConfig.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleSpeedMatcherFactory.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleSpeedTableSpeedMatcher.java
Labels: Needs L10N

#13274 Add LogixNG help content for Call Module
  help/en/html/tools/logixng/LogixNG.shtml
  help/en/html/tools/logixng/reference/chapter13.shtml
Labels: Documentation

#13277 OperationsPro improve load name checking
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/CarsTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarLoadEditFrame.java
Labels: Documentation, Needs L10N

#13282 OperationsPro update help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#13283 Some additions to Acknowledgements
  help/en/Acknowledgements.shtml
Labels: Documentation

#13284 A Few Bachrus Speedmatcher Tweaks
  help/en/html/hardware/bachrus/images/BasicSpeedMatcher.PNG
  help/en/html/hardware/bachrus/images/MomentumSection.PNG
  help/en/html/hardware/bachrus/images/SpeedMatchSection.png
  help/en/html/hardware/bachrus/images/SpeedStepScaleSpeedMatcher.PNG
  help/en/package/jmri/jmrix/bachrus/SpeedoConsoleFrame.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/bachrus/BachrusBundle.properties
  java/src/jmri/jmrix/bachrus/SpeedoConsoleFrame.java
  java/src/jmri/jmrix/bachrus/speedmatcher/SpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleESUTableSpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleSpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleSpeedMatcherConfig.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedStepScaleSpeedTableSpeedMatcher.java
  java/src/jmri/jmrix/bachrus/speedmatcher/speedStepScale/SpeedTableStepSpeed.java
Labels: Needs L10N
