Repository JMRI/JMRI, pull requests merged in 2024-02, with the labels that each got.

#12872 Fix NPE
  java/src/jmri/jmrit/logixng/tools/swing/CallModuleParameterTableModel.java
  java/src/jmri/jmrit/logixng/tools/swing/LocalVariableTableModel.java
Labels: New PR

#12869 Add LogixNG action JsonDecode
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/JsonDecode.java
  java/src/jmri/jmrit/logixng/actions/configurexml/JsonDecodeXml.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/JsonDecodeSwing.java
  java/src/jmri/jmrit/logixng/util/parser/ExpressionNodeArray.java
  java/src/jmri/jmrit/logixng/util/parser/ExpressionNodeMap.java
  java/src/jmri/util/TypeConversionUtil.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/actions/JsonDecodeTest.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/json-decode-5.7.4.xsd
Labels: Needs L10N

#12871 add ETCS Driver Machine Interface Panel
  help/en/package/jmri/jmrit/etcs/etcs_did_2_640x480.png
  help/en/package/jmri/jmrit/etcs/etcs_did_640x478.png
  help/en/package/jmri/jmrit/etcs/etcs_resource_folder_761x250.png
  help/en/package/jmri/jmrit/etcs/index.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/etcs/Bundle.java
  java/src/jmri/jmrit/etcs/Bundle.properties
  java/src/jmri/jmrit/etcs/CabMessage.java
  java/src/jmri/jmrit/etcs/MovementAuthority.java
  java/src/jmri/jmrit/etcs/ResourceUtil.java
  java/src/jmri/jmrit/etcs/StationTrackCondition.java
  java/src/jmri/jmrit/etcs/TrackCondition.java
  java/src/jmri/jmrit/etcs/TrackSection.java
  java/src/jmri/jmrit/etcs/dmi/swing/Bundle.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiCabMessage.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiCircularSpeedGuideSection.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiDemo.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiFlashTimer.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiFrame.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanel.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelA.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelB.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelC.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelD.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelE.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelF.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelG.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiSpeedoDialPanel.java
  java/src/jmri/jmrit/etcs/dmi/swing/package-info.java
  java/src/jmri/jmrit/etcs/package-info.java
  java/test/jmri/jmrit/etcs/BundleTest.java
  java/test/jmri/jmrit/etcs/MovementAuthorityTest.java
  java/test/jmri/jmrit/etcs/dmi/swing/BundleTest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiDemoTest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiFrameTest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiPanelATest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiPanelBTest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiPanelCTest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiPanelDTest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiPanelETest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiPanelGTest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiPanelTest.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiSpeedoDialPanelTest.java
  java/test/jmri/util/swing/JemmyUtil.java
Labels: Documentation, Needs L10N, New PR

#12880 OperationsPro Coding improvement, fix field conflicts
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLengths.java
  java/src/jmri/jmrit/operations/routes/tools/SetTrainIconRouteFrame.java
Labels: Documentation

#12884 Improve LocoNet Monitor's "Query Mode" messages display
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Needs L10N

#12891 Emey bidib fixes202402
  help/en/html/hardware/bidib/index.shtml
  help/en/html/hardware/bidib/index_de.shtml
  java/src/jmri/jmrix/bidib/BiDiBSignalMast.java
  java/src/jmri/jmrix/bidib/tcpserver/TcpServer.java
  java/src/jmri/jmrix/bidib/tcpserver/TcpServerAction.java
  java/test/jmri/jmrix/bidib/tcpserver/TcpServerActionTest.java
Labels: Documentation

#12890 Catch up on LogixNG Help content
  help/en/html/tools/logixng/LogixNG.shtml
  help/en/html/tools/logixng/images/Preferences.png
  help/en/html/tools/logixng/reference/chapter11.shtml
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter11/table_for_each.png
  help/en/html/tools/logixng/reference/images/chapter5/decode_json.png
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_display.png
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_item.png
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_other.png
  help/en/html/tools/logixng/reference/images/chapter5/prog_on_main.png
  help/en/html/tools/logixng/reference/images/chapter5/request_sensor_state.png
  help/en/html/tools/logixng/reference/images/chapter5/table_action.png
  help/en/html/tools/logixng/reference/images/chapter5/window_to_front.png
  help/en/html/tools/logixng/reference/images/chapter6/expression_sensor_edge.png
  help/en/package/jmri/jmrit/beantable/LogixNGTable.shtml
  help/en/package/jmri/jmrit/logixng/InlineLogixNG.shtml
Labels: Documentation

#12897 LogixNG improvements
  help/en/html/tools/logixng/reference/WebRequestExample/WebRequest.xml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/LogixNGBundle.properties
  java/src/jmri/jmrit/logixng/SymbolTable.java
  java/src/jmri/jmrit/logixng/actions/DigitalFormula.java
  java/src/jmri/jmrit/logixng/actions/LogLocalVariables.java
  java/src/jmri/jmrit/logixng/actions/ProgramOnMain.java
  java/src/jmri/jmrit/logixng/actions/configurexml/LogLocalVariablesXml.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/LogLocalVariablesSwing.java
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectInteger.java
  java/src/jmri/jmrit/logixng/util/parser/functions/ConvertFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle.properties
  java/src/jmri/util/TypeConversionUtil.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/SymbolTableTest.java
  java/test/jmri/jmrit/logixng/configurexml/StoreAndLoadTest.java
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/implementation/DefaultGlobalVariableTest.java
  java/test/jmri/jmrit/logixng/util/parser/RecursiveDescentParserTest.java
  java/test/jmri/jmrit/logixng/util/parser/functions/ConvertFunctionsTest.java
  java/test/jmri/util/TypeConversionUtilTest.java
  xml/schema/logixng/common-types-4.23.1.xsd
  xml/schema/logixng/digital-actions/log-local-variables-4.23.1.xsd
Labels: Documentation, Needs L10N

#12900 LogixNG new actions
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/LogixNG.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/ActionSetReporter.java
  java/src/jmri/jmrit/logixng/actions/DigitalFactory.java
  java/src/jmri/jmrit/logixng/actions/EnableLogixNG.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionReporterXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/ActionSetReporterXml.java
  java/src/jmri/jmrit/logixng/actions/configurexml/EnableLogixNGXml.java
  java/src/jmri/jmrit/logixng/actions/swing/ActionSetReporterSwing.java
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle.properties
  java/src/jmri/jmrit/logixng/actions/swing/EnableLogixNGSwing.java
  java/src/jmri/jmrit/logixng/implementation/DefaultLogixNG.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/action-set-reporter-5.7.5.xsd
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/enable-logixng-5.7.5.xsd
Labels: Needs L10N

#12902 OperationsPro Ability to quickly create a custom load for all car types.
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/EditCarLoads.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/CarSetFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarLoadEditFrame.java
  java/test/jmri/jmrit/operations/rollingstock/cars/tools/CarLoadEditFrameTest.java
Labels: Documentation, Needs L10N

#12909 OperationsPro Improve how switch lists are generated when using MR SLAM
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/excel/TrainCustomCommon.java
Labels: Documentation

#12912 ETCS DMI Tweak Sound
  java/src/jmri/jmrit/etcs/Bundle.properties
  java/src/jmri/jmrit/etcs/ResourceUtil.java
  java/src/jmri/jmrit/etcs/TrackCondition.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiDemo.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanel.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelA.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelB.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelC.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelD.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelE.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelF.java
  java/src/jmri/jmrit/etcs/dmi/swing/DmiPanelG.java
  java/test/jmri/jmrit/etcs/dmi/swing/DmiPanelTest.java
Labels: Needs L10N

#12875 STL Editor for the RR-Cirkits Tower LCC+Q
  help/en/package/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.shtml
  java/src/jmri/jmrix/JmrixSystemsBundle.properties
  java/src/jmri/jmrix/openlcb/OpenLcbMenu.java
  java/src/jmri/jmrix/openlcb/swing/stleditor/Bundle.java
  java/src/jmri/jmrix/openlcb/swing/stleditor/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/stleditor/StlEditorAction.java
  java/src/jmri/jmrix/openlcb/swing/stleditor/StlEditorPane.java
  java/src/jmri/jmrix/openlcb/swing/stleditor/package-info.java
Labels: Needs L10N

#12923 Czech translation 2024-02-24
  java/src/apps/AppsBundle_cs.properties
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle_cs.properties
  java/src/jmri/jmrit/display/controlPanelEditor/ControlPanelBundle_cs.properties
  java/src/jmri/jmrit/display/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/display/palette/PaletteBundle_cs.properties
  java/src/jmri/jmrit/etcs/Bundle_cs.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/ActionBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/tools/swing/LogixNGSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
  java/src/jmri/jmrix/JmrixSystemsBundle_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/openlcb/swing/idtool/Bundle_cs.properties
Labels: Needs L10N

#12921 further SensorManager updateAll tweaks
  help/en/html/tools/logixng/reference/chapter5.shtml
  java/src/jmri/SensorManager.java
  java/src/jmri/jmrix/loconet/LnSensor.java
  java/src/jmri/jmrix/openlcb/OlcbSensorManager.java
  java/src/jmri/jmrix/pi/RaspberryPiSensor.java
Labels: Documentation, New PR

#12927 OperationsPro Improve GUI destination checking
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/tools/TrackDestinationEditFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/CarRoads.java
  java/src/jmri/server/json/operations/JsonUtil.java
  java/test/jmri/server/json/operations/JsonOperationsHttpServiceTest.java
Labels: Documentation, Needs L10N, New PR
