Repository JMRI/JMRI, pull requests merged in 2024-08, with the labels that each got.

#13289 OperationsPro code cleanup, no functional changes
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/schedules/Schedule.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
  java/test/jmri/jmrit/operations/locations/TrackTest.java
Labels: Documentation, Needs L10N

#13291 web panel: new parameter ("protect=yes") to treat web panel as read-only
  help/en/html/web/PanelServlet.shtml
  help/en/releasenotes/current-draft-note.shtml
  web/js/panel.js
Labels: Documentation

#13298 Print summary to find failing Headless CI test
  .github/workflows/headless-test.yml
Labels: New PR

#13296 OperationsPro New feature, group car moves on Manifests and switch lists
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_en_GB.properties
  java/src/jmri/jmrit/operations/setup/PrintOptionPanel.java
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/setup/Xml.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/test/jmri/jmrit/operations/setup/PrintOptionPanelTest.java
  xml/DTD/operations-cars.dtd
  xml/DTD/operations-config.dtd
Labels: Documentation, Needs L10N, New PR

#13305 Prevent NPE, documentation updates
  help/en/index.shtml
  help/en/package/jmri/jmrit/dispatcher/NewTrain.shtml
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
Labels: Documentation

#13301 Implement the LogixNG Export tool
  help/en/html/tools/logixng/ExportLogixNG.shtml
  help/en/html/tools/logixng/LogixNG.shtml
  help/en/html/tools/logixng/SidebarToolLocalPart.shtml
  jython/LogixNG/ExportLogixNG.py
Labels: Documentation

#13302 Update CreateDecoder.shtml
  help/en/html/apps/DecoderPro/CreateDecoder.shtml
Labels: Documentation

#13310 New Trix decoder definition
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  xml/decoderIndex.xml
  xml/decoders/Trix_Snd_BR23.xml
Labels: Documentation

#13314 jmrit.logix MergePrompt tweaks
  java/src/jmri/jmrit/logix/MergePrompt.java
  java/src/jmri/jmrit/logix/WarrantShutdownTask.java
  java/test/jmri/jmrit/logix/MergePromptTest.java
Labels: New PR

#13322 Clarify Layout Editor default track/block colors
  help/en/package/jmri/jmrit/display/LayoutEditor.shtml
Labels: Documentation

#13323 Add links to function label and roster media help pages
  help/en/package/jmri/jmrit/symbolicprog/tabbedframe/PaneProgFrame.shtml
Labels: Documentation

#13324 OperationsPro Give user option for staging turn to have cars stay
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
Labels: Documentation, Needs L10N

#13328 OperationsPro Allow caboose to use staging with routing restriction on
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
Labels: Documentation, Needs L10N

#13317 Permission manager
  help/en/package/jmri/jmrit/permission/PermissionManager.shtml
  help/en/parts/SidebarTools.shtml
  java/src/apps/Apps.java
  java/src/apps/AppsBase.java
  java/src/apps/AppsConfigurationManager.java
  java/src/apps/AppsMainMenu.java
  java/src/apps/gui3/tabbedpreferences/EditConnectionPreferencesDialog.java
  java/src/apps/gui3/tabbedpreferences/TabbedPreferences.java
  java/src/apps/gui3/tabbedpreferences/TabbedPreferencesAction.java
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/Permission.java
  java/src/jmri/PermissionFactory.java
  java/src/jmri/PermissionManager.java
  java/src/jmri/PermissionOwner.java
  java/src/jmri/PermissionsSystemAdmin.java
  java/src/jmri/ReferenceNotNull.java
  java/src/jmri/Role.java
  java/src/jmri/User.java
  java/src/jmri/configurexml/Bundle.properties
  java/src/jmri/configurexml/LoadAndStorePermissionOwner.java
  java/src/jmri/configurexml/LoadXmlConfigAction.java
  java/src/jmri/configurexml/LoadXmlUserAction.java
  java/src/jmri/configurexml/StoreXmlUserAction.java
  java/src/jmri/jmrit/permission/Bundle.java
  java/src/jmri/jmrit/permission/Bundle.properties
  java/src/jmri/jmrit/permission/DefaultPermissionManager.java
  java/src/jmri/jmrit/permission/DefaultRole.java
  java/src/jmri/jmrit/permission/DefaultUser.java
  java/src/jmri/jmrit/permission/PermissionInstanceInitializer.java
  java/src/jmri/jmrit/permission/swing/AddUserDialog.java
  java/src/jmri/jmrit/permission/swing/Bundle.java
  java/src/jmri/jmrit/permission/swing/Bundle.properties
  java/src/jmri/jmrit/permission/swing/ChangePasswordAction.java
  java/src/jmri/jmrit/permission/swing/ChangePasswordDialog.java
  java/src/jmri/jmrit/permission/swing/ChangeUserPasswordDialog.java
  java/src/jmri/jmrit/permission/swing/LoginAction.java
  java/src/jmri/jmrit/permission/swing/LoginDialog.java
  java/src/jmri/jmrit/permission/swing/LogoutAction.java
  java/src/jmri/jmrit/permission/swing/PermissionPreferencesPanel.java
  java/src/jmri/swing/PreferencesPanel.java
  java/src/jmri/util/swing/JMenuUtil.java
  xml/config/parts/jmri/jmrit/roster/swing/RosterFrameMenu.xml
  xml/schema/guinode.xsd
Labels: Needs L10N

#13330 Update the HOWTO-distribution for GitHub Desktop
  scripts/HOWTO-distribution.md
Labels: New PR

#13332 Check for UTF8 BOM and TABs
  .github/workflows/static-analysis.yml
  scripts/test_BOM_and_tab.sh
Labels: dev/test/publish infrastructure

#13334 User lower case in standard user name "admin"
  help/en/package/jmri/jmrit/permission/PermissionManager.shtml
  java/src/jmri/jmrit/permission/Bundle.properties
Labels: Documentation, Needs L10N

#13335 Add release note for permission manager. Include sidebar on web page
  help/en/package/jmri/jmrit/permission/PermissionManager.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#13344 New version of Openlcb_java PR #267 code
  help/en/releasenotes/current-draft-note.shtml
  lib/openlcb.jar
Labels: New PR

#13340 Update HOWTO-distribution.md
  scripts/HOWTO-distribution.md
Labels: New PR

#13339 Check that the default_lcf.xml and scripts/default.xml files are in synch
  .github/workflows/static-analysis.yml
  scripts/test_default_lcf.sh
Labels: New PR

#13338 Change XSL encoding to UTF-8
  xml/XSLT/CSVsummary.xsl
  xml/XSLT/CVsummary.xsl
  xml/XSLT/DecoderID.xsl
  xml/XSLT/DecoderMfgIndex.xsl
  xml/XSLT/DecoderModelIndex.xsl
  xml/XSLT/DecoderModelList.xsl
  xml/XSLT/LogixToCode.xsl
  xml/XSLT/PowerAsCSV.xsl
  xml/XSLT/PropertiesFiles.xsl
  xml/XSLT/SelectionGuide.xsl
  xml/XSLT/SizeAsCSV.xsl
  xml/XSLT/appearancetable.xsl
  xml/XSLT/aspecttable.xsl
  xml/XSLT/consistRoster.xsl
  xml/XSLT/decoder-with-form.xsl
  xml/XSLT/decoder.xsl
  xml/XSLT/idtags.xsl
  xml/XSLT/interestingCVs.xml
  xml/XSLT/locomotive.xsl
  xml/XSLT/mfgID.xsl
  xml/XSLT/panelfile-2-9-6.xsl
  xml/XSLT/panelfile-4-19-2.xsl
  xml/XSLT/panelfile-5-5-5.xsl
  xml/XSLT/panelfile.xsl
  xml/XSLT/reservedCSV.xsl
  xml/XSLT/roster.xsl
  xml/XSLT/roster2array.xsl
  xml/XSLT/roster2text.xsl
  xml/XSLT/rpsfile.xsl
  xml/XSLT/speedometer.xsl
  xml/XSLT/timetable.xsl
  xml/XSLT/vsdecoder-config.xsl
Labels: New PR

#13350 A bit of clean-up in new Permissions help page
  help/en/package/jmri/jmrit/permission/PermissionManager.shtml
Labels: Documentation

#13359 fix json examples
  help/en/html/web/JsonServlet.shtml
Labels: Documentation

#13363 Remove Thread.stop() and ThreadDeath
  .github/workflows/static-analysis-21.yml
  .spotbugs-check.xml
  build.xml
  java/src/jmri/jmrix/ieee802154/xbee/XBeeTrafficController.java
  java/src/jmri/jmrix/nce/NceConsist.java
  java/src/jmri/jmrix/pricom/downloader/LoaderPane.java
  java/src/jmri/jmrix/pricom/pockettester/DataSource.java
  java/src/jmri/jmrix/roco/z21/Z21LocoNetTunnel.java
  java/src/jmri/jmrix/roco/z21/Z21TrafficController.java
  java/src/jmri/jmrix/roco/z21/Z21XPressNetTunnel.java
  lib/README.md
  lib/spotbugs-annotations-4.7.3.jar
  lib/spotbugs-annotations-4.8.6.jar
  pom.xml
Labels: dev/test/publish infrastructure

#13355 Let Static Analysis CI test XSLT transformations
  .github/workflows/static-analysis.yml
  scripts/test_decoder_XSLT_transforms.sh
Labels: dev/test/publish infrastructure, New PR

#13374 Beantables bottom bar
  java/src/jmri/jmrit/beantable/AbstractTableAction.java
  java/src/jmri/jmrit/beantable/AbstractTableTabAction.java
  java/src/jmri/jmrit/beantable/AudioTableFrame.java
  java/src/jmri/jmrit/beantable/AudioTablePanel.java
  java/src/jmri/jmrit/beantable/BeanTableFrame.java
  java/src/jmri/jmrit/beantable/BeanTablePane.java
  java/src/jmri/jmrit/beantable/IdTagTableTabAction.java
  java/src/jmri/jmrit/beantable/ListedTableFrame.java
  java/src/jmri/jmrit/beantable/OBlockTableFrame.java
  java/src/jmri/jmrit/beantable/OBlockTablePanel.java
  java/src/jmri/jmrix/ecos/swing/locodatabase/EcosLocoTableTabAction.java
  java/test/jmri/jmrit/beantable/AbstractTableTabActionBase.java
Labels: New PR

#13378 OperationsPro Add Print/Preview for trains servicing a location
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/tools/PrintTrainsServingLocation.java
  java/src/jmri/jmrit/operations/locations/tools/PrintTrainsServingLocationAction.java
  java/src/jmri/jmrit/operations/locations/tools/ShowTrainsServingLocationFrame.java
Labels: Documentation

#13383 OperationsPro Log which backup set is being restored
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/SetCars.png
  java/src/jmri/jmrit/operations/setup/BackupBase.java
  java/src/jmri/jmrit/operations/setup/BackupSet.java
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/RestoreDialog.java
Labels: Documentation, Needs L10N

#13385 DCC-EX: documentation correction
  help/en/html/hardware/dcc-ex/index.shtml
Labels: Documentation

#13395 OperationsPro Fix loco set out to track with restrictions
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
Labels: Needs L10N
