Repository JMRI/JMRI, pull requests merged in 2025-09, with the labels that each got.

#14394 OperationsPro Minor improvement to train turns
  java/src/jmri/jmrit/operations/locations/gui/YardmasterPanel.java
  java/src/jmri/jmrit/operations/routes/Route.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/TrainLogger.java
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/gui/TrainsTableModel.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderCars.java
  java/test/jmri/jmrit/operations/trains/XmlTest.java
  java/test/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderTest.java
Labels: Needs L10N

#14397 Set stopping distances for sections in the transit.
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/TransitSection.java
  java/src/jmri/jmrit/beantable/SectionTransitTableBundle.properties
  java/src/jmri/jmrit/beantable/TransitTableAction.java
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
  java/src/jmri/managers/configurexml/DefaultTransitManagerXml.java
  java/test/jmri/configurexml/loadref/SectionManagerXmlTest-4.7.4.xml
  java/test/jmri/configurexml/loadref/SectionManagerXmlTest.xml
  java/test/jmri/configurexml/loadref/SectionTransitsLoadAndStore.xml
  java/test/jmri/jmrit/display/layoutEditor/load/GeoPanelsAnon.xml
  java/test/jmri/jmrit/display/layoutEditor/loadref/PU-MonP-Signal-Panel-4-19-6.xml
  java/test/jmri/jmrit/logixng/configurexml/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.5.5.xml
  java/test/jmri/jmrit/logixng/configurexml/loadref/LogixNG.5.7.5.xml
  java/test/jmri/jmrit/logixng/configurexml2/load/LogixNG.xml
  java/test/jmri/jmrit/logixng/configurexml2/loadref/LogixNG.5.5.5.xml
  java/test/jmri/jmrit/logixng/configurexml2/loadref/LogixNG.5.7.5.xml
  xml/schema/types/transits-2-9-6.xsd
Labels: Needs L10N

#14415 OperationsPro GUI improvement to "Show Schedules by Car Type and Load"
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_ca.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_da.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_fr.properties
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle_it.properties
  java/src/jmri/jmrit/operations/locations/schedules/tools/SchedulesByLoadFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/Car.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderCars.java
Labels: Needs L10N

#14413 update asserts to JUnit5 util prefs iharder
  java/test/jmri/util/iharder/dnd/DnDListTest.java
  java/test/jmri/util/iharder/dnd/FileDropEventTest.java
  java/test/jmri/util/iharder/dnd/FileDropTest.java
  java/test/jmri/util/iharder/dnd/TransferableObjectTest.java
  java/test/jmri/util/jdom/LocaleSelectorTest.java
  java/test/jmri/util/junit/AssertTest.java
  java/test/jmri/util/node/NodeIdentityTest.java
  java/test/jmri/util/prefs/HasConnectionButUnableToConnectExceptionTest.java
  java/test/jmri/util/prefs/InitializationExceptionTest.java
  java/test/jmri/util/prefs/JmriConfigurationProviderTest.java
  java/test/jmri/util/prefs/JmriPreferencesProviderTest.java
  java/test/jmri/util/prefs/JmriUserInterfaceConfigurationProviderTest.java
Labels: New PR

#14418 Update Eclipse help
  help/en/html/doc/Technical/Eclipse.shtml
  help/en/html/doc/Technical/images/EclipsePackageExplorer.png
Labels: Documentation

#14421 OperationsPro Some minor GUI improvements
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/gui/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/tools/AlternateTrackAction.java
  java/src/jmri/jmrit/operations/locations/tools/ChangeTrackTypeAction.java
  java/src/jmri/jmrit/operations/locations/tools/ChangeTracksTypeAction.java
  java/src/jmri/jmrit/operations/locations/tools/LocationsByCarTypeFrame.java
  java/src/jmri/jmrit/operations/locations/tools/TrackEditCommentsAction.java
  java/src/jmri/jmrit/operations/rollingstock/cars/gui/CarRosterMenu.java
  java/src/jmri/jmrit/operations/rollingstock/engines/gui/EngineRosterMenu.java
  java/src/jmri/jmrit/operations/routes/gui/RoutesTableFrame.java
  java/src/jmri/jmrit/operations/setup/gui/OperationsSettingsFrame.java
  java/src/jmri/jmrit/operations/trains/tools/TrainsByCarTypeFrame.java
Labels: Documentation

#14425 Add 'No Group' to the roster groups, and handle appropriately
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/roster/DeleteRosterItemAction.java
  java/src/jmri/jmrit/roster/JmritRosterBundle.properties
  java/src/jmri/jmrit/roster/Roster.java
  java/src/jmri/jmrit/roster/swing/CopyRosterGroupAction.java
  java/src/jmri/jmrit/roster/swing/CreateRosterGroupAction.java
  java/src/jmri/jmrit/roster/swing/DeleteRosterGroupAction.java
  java/src/jmri/jmrit/roster/swing/RenameRosterGroupAction.java
  java/src/jmri/jmrit/roster/swing/RosterFrame.java
  java/src/jmri/jmrit/roster/swing/RosterGroupsPanel.java
  java/src/jmri/jmrit/roster/swing/RosterTable.java
  java/test/jmri/server/json/roster/JsonRosterSocketServiceTest.java
Labels: Needs L10N

#14432 OperationsPro update help
  help/en/package/jmri/jmrit/operations/Operations.shtml
Labels: Documentation

#14441 OperationsPro improvements to Cars print and preview
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterFrame.java
Labels: Documentation, Needs L10N
