Repository JMRI/JMRI, pull requests merged in 2025-01, with the labels that each got.

#13733 Welcome 2025!
  build.xml
  project.properties
  scripts/WinInstallFiles/LaunchJMRI.nsi
  xml/XSLT/CSVsummary.xsl
  xml/XSLT/CVsummary.xsl
  xml/XSLT/DecoderID.xsl
  xml/XSLT/DecoderMfgIndex.xsl
  xml/XSLT/DecoderModelIndex.xsl
  xml/XSLT/DecoderModelList.xsl
  xml/XSLT/LogixToCode.xsl
  xml/XSLT/SelectionGuide.xsl
  xml/XSLT/appearancetable.xsl
  xml/XSLT/aspecttable.xsl
  xml/XSLT/build.xml
  xml/XSLT/consistRoster.xsl
  xml/XSLT/decoder.xsl
  xml/XSLT/idtags.xsl
  xml/XSLT/locomotive.xsl
  xml/XSLT/mfgID.xsl
  xml/XSLT/panelfile-2-9-6.xsl
  xml/XSLT/panelfile-4-19-2.xsl
  xml/XSLT/panelfile-5-5-5.xsl
  xml/XSLT/panelfile.xsl
  xml/XSLT/roster.xsl
  xml/XSLT/roster2text.xsl
  xml/XSLT/roster4web-simple.xsl
  xml/XSLT/roster4web.xsl
  xml/XSLT/rpsfile.xsl
  xml/XSLT/speedometer.xsl
  xml/XSLT/throttle-config.xsl
  xml/XSLT/throttle-layout-config.xsl
  xml/XSLT/timetable.xsl
  xml/XSLT/vsdecoder-config.xsl
Labels: Needs L10N

#13725 Add LogixNG expression StringIO
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle.properties
  java/src/jmri/jmrit/logixng/expressions/StringExpressionStringIO.java
  java/src/jmri/jmrit/logixng/expressions/StringFactory.java
  java/src/jmri/jmrit/logixng/expressions/configurexml/StringExpressionStringIOXml.java
  java/src/jmri/jmrit/logixng/expressions/swing/StringExpressionStringIOSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleStringExpressionSocketTest.java
  xml/schema/logixng/string-expressions/expression-stringio-5.11.2.xsd
  xml/schema/logixng/string-expressions/string-expressions-4.23.1.xsd
Labels: Needs L10N, New PR

#13735 OperationsPro Add print Manifest and switch list duplex option
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarRoutingReportAction.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterFrame.java
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/PrintOptionPanel.java
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/setup/Xml.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainPrintUtilities.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchLists.java
  java/src/jmri/jmrit/operations/trains/tools/PrintSavedBuildReportAction.java
  java/src/jmri/jmrit/operations/trains/tools/PrintSavedTrainManifestAction.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrainsFrame.java
  java/src/jmri/util/davidflanagan/HardcopyWriter.java
  xml/DTD/operations-config.dtd
Labels: Needs L10N

#13736 Interpet IPL Identity message for BDL716
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Enhancement, Needs L10N

#13737 update Block Table
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_ca.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_da.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_de.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_es.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_fr.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_it.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_nl.properties
  java/src/jmri/jmrit/beantable/block/BlockTableDataModel.java
  java/src/jmri/jmrit/beantable/block/BlockTableJTable.java
  java/test/jmri/jmrit/beantable/BlockTableActionTest.java
Labels: Needs L10N

#13740 Block action linting
  java/src/jmri/jmrit/beantable/BlockTableAction.java
  java/src/jmri/jmrit/beantable/beanedit/BlockEditAction.java
Labels: New PR

#13743 OperationsPro Option to select short or long side when printing duplex
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/PrintOptions.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/CarRoutingReportAction.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterFrame.java
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/PrintOptionPanel.java
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainPrintUtilities.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchLists.java
  java/src/jmri/jmrit/operations/trains/tools/PrintSavedBuildReportAction.java
  java/src/jmri/jmrit/operations/trains/tools/PrintSavedTrainManifestAction.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrainsFrame.java
  java/src/jmri/util/davidflanagan/HardcopyWriter.java
  xml/DTD/operations-config.dtd
Labels: Needs L10N

#13752 Update LogixNG help for StringIO changes
  help/en/html/tools/StringIO.shtml
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/chapter6.shtml
  help/en/html/tools/logixng/reference/images/chapter5/read_set_string.png
  help/en/html/tools/logixng/reference/images/chapter6/if_stringio_value.png
  help/en/html/tools/logixng/reference/images/chapter6/string_expression_item.png
Labels: Documentation

#13763 OperationsPro New feature, locomotive pick up and set out text colors
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/PrintOptions.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/CommonConductorYardmasterPanel.java
  java/src/jmri/jmrit/operations/locations/YardmasterByTrackPanel.java
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/PrintOptionPanel.java
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/setup/Xml.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/web/servlet/operations/HtmlManifest.java
  java/src/jmri/web/servlet/operations/HtmlTrainCommon.java
  xml/DTD/operations-config.dtd
Labels: Needs L10N

#13770 OperationsPro Add track move counts to export locations
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/tools/ExportLocations.java
Labels: Documentation

#13777 update SpotBugs Help : SuppressFBWarnings
  help/en/html/doc/Technical/SpotBugs.shtml
Labels: Documentation

#13789 OperationsPro Add import routes tool
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/routes/JmritOperationsRoutesBundle.properties
  java/src/jmri/jmrit/operations/routes/RoutesTableFrame.java
  java/src/jmri/jmrit/operations/routes/tools/ExportRoutes.java
  java/src/jmri/jmrit/operations/routes/tools/ImportRoutes.java
  java/src/jmri/jmrit/operations/routes/tools/ImportRoutesAction.java
  java/test/jmri/jmrit/operations/routes/tools/ImportRoutesActionTest.java
  java/test/jmri/jmrit/operations/routes/tools/ImportRoutesTest.java
Labels: Documentation, Needs L10N

#13794 Fix DCC-ex url
  help/en/html/hardware/dcc-ex/index.shtml
Labels: Documentation

#13801 Densha De GO USB device driver for USBThrottle Jynstrument
  help/en/html/tools/throttle/AdvancedThrottleControl.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/Jynstruments/ThrottleFrame/Bell.jyn/Bell.py
  jython/Jynstruments/ThrottleFrame/Direction.jyn/Direction.py
  jython/Jynstruments/ThrottleFrame/EStop.jyn/EStop.py
  jython/Jynstruments/ThrottleFrame/Horn.jyn/Horn.py
  jython/Jynstruments/ThrottleFrame/Light.jyn/Light.py
  jython/Jynstruments/ThrottleFrame/RosterImage.jyn/RosterImage.py
  jython/Jynstruments/ThrottleFrame/SoundOn2xF0.jyn/SoundOn2xF0.py
  jython/Jynstruments/ThrottleFrame/SoundOnF8.jyn/SoundOnF8.py
  jython/Jynstruments/ThrottleWindowToolBar/DCCThrottle.jyn/DCCThrottle.py
  jython/Jynstruments/ThrottleWindowToolBar/USBThrottle.jyn/USBThrottle.py
  jython/Jynstruments/ThrottleWindowToolBar/WiimoteThrottle.jyn/WiimoteThrottle.py
  jython/Jynstruments/ThrottleWindowToolBar/WiimoteThrottle2.jyn/WiimoteThrottle2.py
Labels: Documentation

#13796 Improve Z21 server and add support for Roco WlanMaus
  help/en/Acknowledgements.shtml
  help/en/JmriHelp_enIndex.xml
  help/en/JmriHelp_enTOC.xml
  help/en/local/jmri_map.xml
  help/en/package/jmri/jmrit/z21server/z21server.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/z21server/AppClient.java
  java/src/jmri/jmrit/z21server/ClientManager.java
  java/src/jmri/jmrit/z21server/FacelessServer.java
  java/src/jmri/jmrit/z21server/MainServer.java
  java/src/jmri/jmrit/z21server/NumberMapAction.java
  java/src/jmri/jmrit/z21server/NumberMapFrame.java
  java/src/jmri/jmrit/z21server/Service40.java
  java/src/jmri/jmrit/z21server/TurnoutNumberMapHandler.java
  java/src/jmri/jmrit/z21server/UserInterface.java
  java/src/jmri/jmrit/z21server/Z21ClientsListModel.java
  java/src/jmri/jmrit/z21server/Z21serverCreationAction.java
  java/src/jmri/jmrit/z21server/Z21serverStartupActionFactory.java
  java/src/jmri/jmrit/z21server/z21serverBundle.properties
  java/src/jmri/jmrit/z21server/z21serverBundle_cs.properties
  java/src/jmri/jmrit/z21server/z21serverBundle_de.properties
  java/src/jmri/jmrit/z21server/z21serverBundle_fr.properties
  java/test/jmri/jmrit/z21server/AppClientTest.java
  java/test/jmri/jmrit/z21server/BundleTest.java
  java/test/jmri/jmrit/z21server/ClientManagerTest.java
  java/test/jmri/jmrit/z21server/FacelessServerTest.java
  java/test/jmri/jmrit/z21server/MainServerTest.java
  java/test/jmri/jmrit/z21server/NumberMapActionTest.java
  java/test/jmri/jmrit/z21server/NumberMapFrameTest.java
  java/test/jmri/jmrit/z21server/Service40Test.java
  java/test/jmri/jmrit/z21server/TurnoutNumberMapHandlerTest.java
  java/test/jmri/jmrit/z21server/UserInterfaceTest.java
  java/test/jmri/jmrit/z21server/Z21ClientsListModelTest.java
  java/test/jmri/jmrit/z21server/Z21serverCreationActionTest.java
Labels: Documentation, Needs L10N, New PR

#13810 OperationsPro fix header when using tabular and leading spaces.
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/tools/ImportLocations.java
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
Labels: Documentation

#13804 OpenLCB/LCC updates
  help/en/package/jmri/jmrix/openlcb/swing/downloader/OpenLCBlibrary.shtml
  help/en/package/jmri/jmrix/openlcb/swing/send/OpenLcbCanSendFrame.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/DropCdiCache.java
  java/src/jmri/jmrix/openlcb/swing/NamedEventIdTextField.java
  java/src/jmri/jmrix/openlcb/swing/downloader/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/downloader/LoaderPane.java
  java/src/jmri/jmrix/openlcb/swing/lccpro/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/lccpro/LccProFrame.java
  java/src/jmri/jmrix/openlcb/swing/send/Bundle.java
  java/src/jmri/jmrix/openlcb/swing/send/Bundle.properties
  java/src/jmri/jmrix/openlcb/swing/send/OpenLcbCanSendPane.java
  java/src/jmri/util/swing/OvertypeTextArea.java
  lib/README.md
  lib/openlcb.jar
  pom.xml
Labels: Documentation, Needs L10N

#13812 OperationsPro Allow user to print or preview cars in train
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainConductorFrame.java
  java/src/jmri/jmrit/operations/trains/tools/PrintShowCarsInTrain.java
  java/src/jmri/jmrit/operations/trains/tools/PrintShowCarsInTrainAction.java
  java/src/jmri/jmrit/operations/trains/tools/ShowCarsInTrainFrame.java
  java/test/jmri/jmrit/operations/trains/tools/PrintShowCarsInTrainActionTest.java
  java/test/jmri/jmrit/operations/trains/tools/PrintShowCarsInTrainTest.java
  java/test/jmri/jmrit/operations/trains/tools/ShowCarsInTrainActionTest.java
Labels: Needs L10N

#13821 Czech translation 2025-01-27
  java/src/apps/ActionListBundle_cs.properties
  java/src/jmri/NamedBeanBundle_cs.properties
  java/src/jmri/jmrit/Bundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/beanedit/BeanEditBundle_cs.properties
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_cs.properties
  java/src/jmri/jmrit/display/layoutEditor/LayoutEditorBundle_cs.properties
  java/src/jmri/jmrit/logixng/expressions/ExpressionBundle_cs.properties
  java/src/jmri/jmrit/z21server/z21serverBundle_cs.properties
  java/src/jmri/jmrix/bidib/BiDiBBundle_cs.properties
  java/src/jmri/jmrix/bidib/swing/BiDiBSwingBundle_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/openlcb/Bundle_cs.properties
  java/src/jmri/jmrix/openlcb/swing/Bundle_cs.properties
  java/src/jmri/script/Bundle_cs.properties
Labels: Needs L10N

#13827 OperationsPro, allow user to print loco set outs at end of Manifest
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/PrintOptionPanel.java
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/setup/Xml.java
  java/src/jmri/jmrit/operations/trains/TrainManifest.java
  java/src/jmri/jmrit/operations/trains/tools/PrintShowCarsInTrain.java
  java/test/jmri/jmrit/operations/setup/PrintOptionPanelTest.java
  xml/DTD/operations-config.dtd
Labels: Needs L10N

#13825 feat/socketservice change railroad name example
  .gitignore
  java/src/jmri/server/json/util/JsonUtilHttpService.java
  java/src/jmri/server/json/util/JsonUtilSocketService.java
  java/src/jmri/server/json/util/railroad-client.json
  java/src/jmri/web/server/RailroadNamePreferencesPanel.java
  web/js/jquery.jmri.js
  web/railroad.html
Labels: Needs L10N
