Repository JMRI/JMRI, pull requests merged in 2025-04, with the labels that each got.

#13997 Help tweaks
  help/en/JmriHelp_enIndex.xml
  help/en/html/apps/DecoderPro/Roster.shtml
  help/en/html/hardware/loconet/BTLocoBridge.shtml
  help/en/html/hardware/loconet/LocoBufferUSB.shtml
  help/en/html/hardware/loconet/SidebarHardwareLocalPart.shtml
  help/en/html/hardware/loconet/images/Bt_lnbridge_rensad2.png
Labels: Documentation

#14001 OperationsPro Fix train departure times when crossing days
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/Train.java
Labels: Documentation

#14005 Hide Reporter tab
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_ca.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_cs.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_da.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_de.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_es.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_it.properties
  java/src/jmri/jmrit/beantable/BeanTableBundle_nl.properties
  java/src/jmri/jmrit/beantable/OBlockTableBundle.properties
  java/src/jmri/jmrit/beantable/beanedit/BeanEditBundle.properties
  java/src/jmri/jmrit/beantable/beanedit/BeanEditBundle_de.properties
  java/src/jmri/jmrit/beantable/beanedit/BeanEditBundle_nl.properties
  java/src/jmri/jmrit/beantable/beanedit/OBlockEditAction.java
Labels: Needs L10N

#14004 update ConditionalFrame / ConditionalCopyFrame
  java/src/jmri/jmrit/conditional/ConditionalCopyFrame.java
  java/src/jmri/jmrit/conditional/ConditionalFrame.java
Labels: New PR

#14007 OperationsPro make car pick up time sortable
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/CarManager.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainCommon.java
  java/test/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderTest.java
Labels: Documentation

#14009 Fix problem with locale in Java 21
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectDouble.java
Labels: Bug

#14017 Help index fix
  help/en/JmriHelp_enTOC.xml
Labels: Documentation

#14022 add Digitrax BDL716
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/LnOpsModeProgrammer.java
  java/src/jmri/jmrix/loconet/alm/almi/Almir.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/LnOpsModeProgrammerTest.java
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
  xml/decoders/Digitrax_BDL716.xml
Labels: Enhancement, Needs L10N, New PR

#14023 OperationsPro Release warning
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/current-draft-warnings.shtml
Labels: New PR

#14032 OperationsPro enhancement to Manifest add passenger blocking order
  java/src/jmri/jmrit/operations/JmritOperationsBundle.properties
  java/src/jmri/jmrit/operations/setup/Setup.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainCommon.java
  java/src/jmri/server/json/operations/JsonOperations.java
  java/src/jmri/server/json/operations/JsonUtil.java
  java/src/jmri/server/json/operations/car-client.json
  java/src/jmri/server/json/operations/car-server.json
  java/src/jmri/web/servlet/operations/HtmlTrainCommon.java
  java/test/jmri/jmrit/operations/setup/SetupTest.java
  java/test/jmri/jmrit/operations/setup/backup/OperationsBackupTest.java
  java/test/jmri/server/json/operations/JsonOperationsHttpServiceTest.java
Labels: Needs L10N

#14033 Intl Utilities - add intValue, strip whitespace.
  help/en/html/doc/Technical/I8N.shtml
  java/src/jmri/util/IntlUtilities.java
  java/test/jmri/util/IntlUtilitiesTest.java
Labels: Documentation

#14046 OperationsPro changes to route edit window
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/EditManifestText.png
  help/en/package/jmri/jmrit/operations/images/EditRoute.png
  help/en/package/jmri/jmrit/operations/images/RouteTurn.png
  java/src/jmri/jmrit/operations/routes/gui/RouteEditFrame.java
  java/src/jmri/jmrit/operations/routes/gui/RouteEditTableModel.java
  java/test/jmri/jmrit/operations/routes/gui/RouteEditFrameTest.java
Labels: Documentation

#14065 Updated standalone loconet to include more-recent products
  help/en/html/hardware/loconet/DCS240.shtml
  help/en/html/hardware/loconet/DCS52.shtml
  help/en/html/hardware/loconet/Digitrax.shtml
  help/en/html/hardware/loconet/LocoNetTools.shtml
  help/en/html/hardware/loconet/SE74.shtml
  help/en/html/hardware/loconet/StandaloneLocoNet.shtml
  help/en/releasenotes/current-draft-note.shtml
Labels: Documentation

#14064 Minor updates
  help/en/Acknowledgements.shtml
  java/src/jmri/jmrit/automat/AbstractAutomaton.java
Labels: Documentation

#14068 OperationsPro Fix NPE when changing loads for all cars
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/rollingstock/cars/CarLoads.java
Labels: Documentation
