Repository JMRI/JMRI, pull requests merged in 2025-06, with the labels that each got.

#14146 Upgrade YetAnotherAutoTrain.py (YAAT) to version 3.3
  help/en/html/scripthelp/yaat/YAAT.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/YetAnotherAutoTrain3.py
Labels: Documentation

#14131 CBUS Node Manager - Check for duplicate CAN IDs
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/node/CbusBasicNodeTableOperations.java
  java/src/jmri/jmrix/can/cbus/node/CbusNodeTableDataModel.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/CbusNodeTablePane.java
  java/test/jmri/jmrix/can/cbus/swing/nodeconfig/NodeConfigToolPaneTest.java
Labels: Needs L10N, New PR

#14165 OperationsPro Improve car timing when using quick service
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderCars.java
Labels: Needs L10N

#14163 Add ability to write XML files without dynamic contents
  help/en/html/setup/git.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/configurexml/ConfigXmlManager.java
  java/src/jmri/configurexml/LoadAndStorePreferences.java
  java/src/jmri/configurexml/swing/Bundle.properties
  java/src/jmri/configurexml/swing/LoadAndStorePreferencesPanel.java
  java/src/jmri/jmrit/XmlFile.java
  java/src/jmri/jmrit/revhistory/configurexml/FileHistoryXml.java
  java/src/jmri/managers/configurexml/AbstractMemoryManagerConfigXML.java
  java/test/jmri/jmrit/logixng/actions/WebRequestTest.java
Labels: Documentation, Needs L10N

#14171 drM SPC200R - basic Speedo support
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/bachrus/BachrusBundle.properties
  java/src/jmri/jmrix/bachrus/DRMConnectionTypeList.java
  java/src/jmri/jmrix/bachrus/SpeedoConsoleFrame.java
  java/src/jmri/jmrix/bachrus/SpeedoReply.java
  java/src/jmri/jmrix/bachrus/SpeedoTrafficController.java
  java/src/jmri/jmrix/bachrus/drmserialdriver/Bundle.java
  java/src/jmri/jmrix/bachrus/drmserialdriver/COPYING
  java/src/jmri/jmrix/bachrus/drmserialdriver/ConnectionConfig.java
  java/src/jmri/jmrix/bachrus/drmserialdriver/SerialDriverAdapter.java
  java/src/jmri/jmrix/bachrus/drmserialdriver/configurexml/COPYING
  java/src/jmri/jmrix/bachrus/drmserialdriver/configurexml/ConnectionConfigXml.java
  java/src/jmri/jmrix/bachrus/drmserialdriver/package-info.java
  java/test/jmri/jmrix/bachrus/SpeedoReplyTest.java
Labels: Needs L10N

#14173 OperationsPro minor spelling fixes
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/.settings/JMRI PanelPro.launch
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsByCarTypesAction.java
  java/src/jmri/jmrit/operations/locations/tools/PrintLocationsFrame.java
  java/src/jmri/jmrit/operations/locations/tools/PrintTrainsServingLocation.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarLoadsAction.java
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarRosterFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterFrame.java
  java/src/jmri/jmrit/operations/routes/tools/PrintRoutes.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_fr.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_it.properties
  java/src/jmri/jmrit/operations/trains/TrainPrintUtilities.java
  java/src/jmri/jmrit/operations/trains/tools/PrintShowCarsInTrain.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrainsByCarTypesAction.java
  java/src/jmri/jmrit/operations/trains/tools/PrintTrainsFrame.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderCars.java
Labels: Documentation, Needs L10N

#14202 Reduce dynamic content in stored XML files: Timebase time and system-specific font extensions
  java/src/jmri/configurexml/LoadAndStorePreferences.java
  java/src/jmri/configurexml/swing/Bundle.properties
  java/src/jmri/configurexml/swing/LoadAndStorePreferencesPanel.java
  java/src/jmri/jmrit/display/configurexml/PositionableLabelXml.java
  java/src/jmri/jmrit/simpleclock/configurexml/SimpleTimebaseXml.java
  java/test/jmri/jmrit/display/configurexml/PositionableLabelXmlTest.java
Labels: Needs L10N

#14118 MERG CBUS Filter to use JCheckBoxTree
  help/en/html/hardware/can/cbus/images/swing/filter/events-426x413.png
  help/en/html/hardware/can/cbus/images/swing/filter/filter-426x254.png
  help/en/html/hardware/can/cbus/images/swing/filter/filter-539x304.png
  help/en/html/hardware/can/cbus/images/swing/filter/filter-events-539x717.png
  help/en/html/hardware/can/cbus/images/swing/filter/filter-nodes-539x553.png
  help/en/html/hardware/can/cbus/images/swing/filter/nodes-426x247.png
  help/en/package/jmri/jmrix/can/cbus/swing/console/CbusConsoleFrame.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/can/cbus/CbusBundle.properties
  java/src/jmri/jmrix/can/cbus/CbusFilter.java
  java/src/jmri/jmrix/can/cbus/CbusFilterType.java
  java/src/jmri/jmrix/can/cbus/swing/CbusFilterFrame.java
  java/src/jmri/jmrix/can/cbus/swing/CbusFilterPanel.java
  java/src/jmri/jmrix/can/cbus/swing/CbusFilterTreePane.java
  java/src/jmri/util/swing/JCheckBoxTree.java
  java/src/jmri/util/swing/JCheckBoxTreeCellRenderer.java
  java/test/jmri/ArchitectureTest.java
  java/test/jmri/jmrix/can/cbus/CbusFilterTest.java
  java/test/jmri/jmrix/can/cbus/CbusFilterTypeTest.java
  java/test/jmri/jmrix/can/cbus/swing/CbusFilterFrameTest.java
  java/test/jmri/jmrix/can/cbus/swing/CbusFilterPanelTest.java
  java/test/jmri/jmrix/can/cbus/swing/CbusFilterTreePaneTest.java
  java/test/jmri/jmrix/can/cbus/swing/console/CbusConsoleDisplayOptionsPaneTest.java
  java/test/jmri/util/swing/JCheckBoxTreeCellRendererTest.java
  java/test/jmri/util/swing/JCheckBoxTreeTest.java
Labels: Needs L10N

#14204 Fix improper LocoNet message length interpretation
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/LocoNetSlot.java
  java/src/jmri/jmrix/loconet/SlotManager.java
  java/test/jmri/jmrix/loconet/SlotManagerTest.java
Labels: Bug, Add to Next Test Release

#14205 Upgrade YAAT to 3.4; add the '@include filename' statement
  help/en/html/scripthelp/yaat/YAAT.shtml
  help/en/releasenotes/current-draft-note.shtml
  jython/YetAnotherAutoTrain3.py
Labels: Documentation

#14207 Extend the WiThrottle section of preferences help
  help/en/package/apps/TabbedPreferences.shtml
  help/en/package/apps/images/PrefsWiThrottle.png
Labels: Documentation

#14214 OperationsPro add quick service to classification/interchange tracks
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/package/jmri/jmrit/operations/images/Turn.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/gui/InterchangeEditFrame.java
  java/src/jmri/jmrit/operations/locations/gui/LocationEditFrame.java
  java/src/jmri/jmrit/operations/locations/gui/TrackTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/cars/Car.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderCars.java
  java/test/jmri/jmrit/operations/locations/gui/InterchangeEditFrameTest.java
  java/test/jmri/jmrit/operations/locations/gui/LocationEditFrameTest.java
Labels: Documentation, Needs L10N

#14216 Update index.shtml
  help/en/html/hardware/tmcc/index.shtml
Labels: Documentation

#14221 Czech translation 2025-06-27
  java/src/jmri/configurexml/swing/Bundle_cs.properties
  java/src/jmri/jmrit/display/DisplayBundle_cs.properties
  java/src/jmri/jmrit/logixng/LogixNGBundle_cs.properties
  java/src/jmri/jmrit/logixng/actions/swing/DigitalActionSwingBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/LogixNGParserBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
  java/src/jmri/jmrit/operations/JmritOperationsBundle_cs.properties
  java/src/jmri/jmrit/roster/JmritRosterBundle_cs.properties
  java/src/jmri/jmrit/withrottle/WiThrottleBundle_cs.properties
  java/src/jmri/jmrix/loconet/LocoNetBundle_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
Labels: Needs L10N
