Repository JMRI/JMRI, pull requests merged in 2025-02, with the labels that each got.

#13830 OperationsPro, also change loco order for switch lists
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle.properties
  java/src/jmri/jmrit/operations/setup/JmritOperationsSetupBundle_en_GB.properties
  java/src/jmri/jmrit/operations/setup/PrintOptionPanel.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchLists.java
Labels: Needs L10N

#13832 When setting up a new train use detection Entire Train, unless overri…
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/dispatcher/AutoActiveTrain.java
  java/src/jmri/jmrit/dispatcher/AutoTurnouts.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
  java/src/jmri/jmrit/dispatcher/DispatcherFrame.java
  java/src/jmri/jmrit/dispatcher/TrainInfo.java
Labels: Needs L10N

#13842 Improve the LogixnG "Execute delayed" help
  help/en/html/tools/logixng/reference/chapter5.shtml
Labels: Documentation

#13845 Lissy RFID reports
  help/en/html/hardware/loconet/LocoIO.shtml
  help/en/html/hardware/loconet/Uhlenbrock.shtml
  help/en/html/hardware/rfid/GettingStartedWithRFID.shtml
  help/en/package/jmri/jmrix/loconet/locomon/LocoMonFrame.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle_nl.properties
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/LnReporter.java
  java/src/jmri/jmrix/loconet/LnReporterManager.java
  java/src/jmri/jmrix/loconet/LocoNetMessage.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_nl.properties
  java/test/jmri/jmrix/loconet/LnReporterTest.java
  xml/decoders/Public_Domain_HDL_LocoIO.xml
Labels: Enhancement, Documentation

#13848 Add some loconet interps.
  java/src/jmri/jmrix/loconet/LnConstants.java
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Needs L10N

#13852 Add LogixNG function currentTimeMillis()
  help/en/html/tools/logixng/reference/images/chapter9/functions_clock.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/util/parser/functions/ClockFunctions.java
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle.properties
  java/test/jmri/jmrit/logixng/util/parser/functions/ClockFunctionsTest.java
Labels: Needs L10N, New PR

#13853 OperationsPro fix test, and update help
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/setup/AutoSave.java
  java/test/jmri/jmrit/operations/XmlLoadTest.java
Labels: Documentation, New PR

#13855 Fix OpenLCB well-known turnout addressing
  java/src/jmri/jmrix/openlcb/OlcbAddress.java
  java/test/jmri/jmrix/openlcb/OlcbAddressTest.java
Labels: New PR

#13854 Add Iain White to Acknowledgements
  help/en/Acknowledgements.shtml
Labels: Documentation

#13857 Entry/Exit Enhancements
  help/en/html/tools/EntryExit.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/entryexit/DestinationPoints.java
  java/src/jmri/jmrit/entryexit/EntryExitBundle.properties
  java/src/jmri/jmrit/entryexit/EntryExitPairs.java
  java/src/jmri/jmrit/entryexit/PointDetails.java
Labels: Needs L10N

#13861 OperationsPro Code cleanup, no functional changes
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/trains/TrainCommon.java
  java/src/jmri/jmrit/operations/trains/TrainPrintUtilities.java
Labels: Documentation

#13863 Signal Masts on hold check, addhoc transits
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/dispatcher/ActivateTrainFrame.java
  java/src/jmri/jmrit/dispatcher/AutoAllocate.java
  java/src/jmri/jmrit/dispatcher/DispatcherBundle.properties
Labels: Needs L10N

#13865 Add "Copy System Name" to bean tables' popup menu
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/BeanTableDataModel.java
Labels: Needs L10N

#13866 LocoNet Monitor updates
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpret.java
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation.properties
  java/test/jmri/jmrix/loconet/messageinterp/LocoNetMessageInterpretTest.java
Labels: Enhancement, Needs L10N

#13867 OperationsPro Add checkboxes to Locomotives window
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/JmritOperationsRollingStockBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_ca.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_da.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_de.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_fr.properties
  java/src/jmri/jmrit/operations/rollingstock/cars/JmritOperationsCarsBundle_it.properties
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/EnginesTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/PrintEngineRosterFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/ResetCheckboxesEnginesTableAction.java
  java/src/jmri/jmrit/operations/rollingstock/engines/tools/ShowCheckboxesEnginesTableAction.java
  java/test/jmri/jmrit/operations/rollingstock/engines/EnginesTableFrameTest.java
Labels: Documentation, Needs L10N

#13869 Czech translation 2025-02-15
  java/src/jmri/jmrit/dispatcher/DispatcherBundle_cs.properties
  java/src/jmri/jmrit/entryexit/EntryExitBundle_cs.properties
  java/src/jmri/jmrit/logixng/util/parser/functions/FunctionsBundle_cs.properties
  java/src/jmri/jmrix/lenz/messageformatters/XNetMessageFormattersBundle_cs.properties
  java/src/jmri/jmrix/loconet/messageinterp/MessageInterpretation_cs.properties
  java/src/jmri/jmrix/roco/z21/swing/configtool/Z21ConfigBundle_cs.properties
  java/src/jmri/jmrix/roco/z21/z21Bundle_cs.properties
Labels: Needs L10N

#13788 MERG CBUS Default connection CAN ID
  help/en/html/hardware/merg/Details.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/AbstractPortController.java
  java/src/jmri/jmrix/can/TrafficController.java
  java/src/jmri/jmrix/can/adapters/gridconnect/canrs/serialdriver/SerialDriverAdapter.java
  java/src/jmri/jmrix/can/adapters/gridconnect/net/MergNetworkDriverAdapter.java
  java/src/jmri/jmrix/can/adapters/gridconnect/net/NetworkDriverAdapter.java
  java/src/jmri/jmrix/can/cbus/CbusConstants.java
Labels: Documentation

#13884 Improve LogixNG
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/logixng/NamedBeanType.java
  java/src/jmri/jmrit/logixng/actions/ActionBundle.properties
  java/src/jmri/jmrit/logixng/actions/CommonManager.java
  xml/schema/logixng/common-types-4.23.1.xsd
  xml/schema/logixng/digital-actions/for-each-5.1.3.xsd
Labels: Needs L10N

#13880 Adding and changing German label texts
  xml/decoders/esu/v5lpOutputLabels.xml
  xml/decoders/esu/v5lsOutputLabels.xml
  xml/decoders/esu/v5standardCVs.xml
Labels: New PR

#13887 OperationsPro code cleanup, no functional changes
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/automation/AutomationItem.java
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/locations/tools/PrintTrainsServingLocation.java
  java/src/jmri/jmrit/operations/locations/tools/ShowTrainsServingLocationFrame.java
  java/src/jmri/jmrit/operations/rollingstock/RollingStock.java
  java/src/jmri/jmrit/operations/routes/Route.java
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainBuilder.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderBase.java
  java/src/jmri/jmrit/operations/trains/TrainBuilderCars.java
  java/src/jmri/jmrit/operations/trains/TrainEditFrame.java
  java/src/jmri/jmrit/operations/trains/tools/TrainByCarTypeFrame.java
  java/src/jmri/web/servlet/operations/HtmlManifest.java
  java/test/jmri/jmrit/operations/locations/SpurEditFrameTest.java
  java/test/jmri/jmrit/operations/router/RouterTest.java
  java/test/jmri/jmrit/operations/trains/TrainBuilderTest.java
  java/test/jmri/jmrit/operations/trains/TrainTest.java
  java/test/jmri/jmrit/operations/trains/XmlTest.java
Labels: Documentation

#13886 Properly decode LCC MTIs for events with payload
  help/en/Acknowledgements.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/openlcb/swing/monitor/MonitorPane.java
  lib/README.md
  lib/openlcb.jar
Labels: Documentation

#13890 Debug.shtml - expand custom defaultlcf.xml info
  help/en/html/apps/Debug.shtml
Labels: Documentation
