Repository JMRI/JMRI, pull requests merged in 2025-07, with the labels that each got.

#14225 Fix OBlock Resource 'BlockUnknown' not found exception
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/oblock/OBlockTableModel.java
Labels: Needs L10N

#14234 OperationsPro allow cars on quick service to be pulled on next build
  java/src/jmri/jmrit/operations/rollingstock/cars/tools/PrintCarLoadsAction.java
  java/src/jmri/jmrit/operations/routes/RouteLocation.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainBuilderCars.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainCommon.java
Labels: Needs L10N

#14229 Update NamedBeanBundle.properties
  java/src/jmri/NamedBeanBundle.properties
Labels: Needs L10N

#14244 Update index.shtml
  help/en/html/hardware/tmcc/index.shtml
Labels: Documentation, New PR

#14250 Update PermissionManager.shtml
  help/en/package/jmri/jmrit/permission/PermissionManager.shtml
Labels: Documentation

#14252 OperationsPro allow user to use the enter key to begin car search
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/OperationsTableModel.java
  java/src/jmri/jmrit/operations/locations/gui/TrackTableModel.java
  java/src/jmri/jmrit/operations/locations/schedules/ScheduleTableModel.java
  java/src/jmri/jmrit/operations/locations/schedules/SchedulesTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/cars/gui/CarsTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/cars/gui/CarsTableModel.java
  java/src/jmri/jmrit/operations/rollingstock/engines/gui/EnginesTableFrame.java
  java/src/jmri/jmrit/operations/rollingstock/engines/gui/EnginesTableModel.java
Labels: Documentation

#14255 Rename new Lionel decoders
  xml/decoders/Lionel-TMCC-1.xml
  xml/decoders/Lionel-TMCC2-Legacy.xml
Labels: New PR

#14256 OperationsPro load operations files when AutomationManager is called
  java/src/jmri/jmrit/operations/automation/AutomationManager.java
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_da.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_de.properties
  java/src/jmri/jmrit/operations/trains/JmritOperationsTrainsBundle_en_GB.properties
  java/src/jmri/jmrit/operations/trains/TrainManager.java
  java/src/jmri/jmrit/operations/trains/gui/TrainsTableFrame.java
  jython/operations/OperationsAssignUnitsToFlatcars.py
  jython/operations/OperationsAutomationManager.py
  jython/operations/OperationsTrainWindow.py
Labels: Needs L10N

#14262 Add LogixNG action OperationsProStartAutomation
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/Category.java
  java/src/jmri/jmrit/logixng/actions/ProgramOnMain.java
  java/src/jmri/jmrit/logixng/util/LogixNG_SelectComboBox.java
  java/src/jmri/jmrit/logixng/util/configurexml/LogixNG_SelectComboBoxXml.java
  java/src/jmri/jmrit/logixng/util/swing/LogixNG_SelectComboBoxSwing.java
  java/src/jmri/jmrit/operations/logixng/ActionFactory.java
  java/src/jmri/jmrit/operations/logixng/Bundle.java
  java/src/jmri/jmrit/operations/logixng/CategoryOperations.java
  java/src/jmri/jmrit/operations/logixng/JmritOperationsLogixNGBundle.properties
  java/src/jmri/jmrit/operations/logixng/OperationsProStartAutomation.java
  java/src/jmri/jmrit/operations/logixng/configurexml/OperationsProStartAutomationXml.java
  java/src/jmri/jmrit/operations/logixng/swing/Bundle.java
  java/src/jmri/jmrit/operations/logixng/swing/JmritOperationsLogixNGSwingBundle.properties
  java/src/jmri/jmrit/operations/logixng/swing/OperationsProStartAutomationSwing.java
  java/test/jmri/jmrit/logixng/CreateLogixNGTreeScaffold.java
  java/test/jmri/jmrit/logixng/implementation/DefaultFemaleDigitalActionSocketTest.java
  xml/schema/logixng/digital-actions/digital-actions-4.23.1.xsd
  xml/schema/logixng/digital-actions/operationspro-start-automation-5.13.2.xsd
Labels: Needs L10N

#14241 Add permissions for programmers
  help/en/releasenotes/current-draft-note.shtml
  help/en/releasenotes/current-draft-warnings.shtml
  java/src/jmri/NamedBeanBundle.properties
  java/src/jmri/PermissionsProgrammer.java
  java/src/jmri/Programmer.java
  java/src/jmri/implementation/PermissionAddressedProgrammer.java
  java/src/jmri/implementation/PermissionProgrammer.java
  java/src/jmri/jmrix/bidib/BiDiBProgrammerManager.java
  java/src/jmri/jmrix/can/cbus/CbusDccProgrammer.java
  java/src/jmri/jmrix/can/cbus/swing/nodeconfig/NodeConfigToolPane.java
  java/src/jmri/jmrix/lenz/XNetOpsModeProgrammer.java
  java/src/jmri/jmrix/lenz/XNetProgrammer.java
  java/src/jmri/managers/DefaultProgrammerManager.java
  java/src/jmri/progdebugger/ProgDebugger.java
  java/src/jmri/swing/PermissionsProgrammerSwing.java
  java/test/jmri/InstanceManagerTest.java
  java/test/jmri/jmrit/roster/swing/RosterFrameTest.java
  java/test/jmri/jmrix/lenz/XNetInitializationManagerTest.java
  java/test/jmri/jmrix/lenz/hornbyelite/XNetInitializationManagerTest.java
  java/test/jmri/jmrix/lenz/li100/XNetInitializationManagerTest.java
  java/test/jmri/jmrix/roco/z21/XNetInitializationManagerTest.java
  java/test/jmri/jmrix/ztc/ztc611/XNetInitializationManagerTest.java
  java/test/jmri/progdebugger/DebugProgrammerManagerTest.java
Labels: Needs L10N

#14265 Update TMCC/SerialThrottle.java
  java/src/jmri/jmrix/tmcc/SerialThrottle.java
Labels: New PR

#14271 Fix a bug in XpressNet when programming locos
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrix/lenz/XNetHeartBeat.java
  java/src/jmri/jmrix/lenz/XNetProgrammer.java
  java/src/jmri/jmrix/lenz/XNetTrafficController.java
Labels: Bug

#14274 OperationsPro allow non-lead cars in a kernel to have unique load names
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/locations/Track.java
  java/src/jmri/jmrit/operations/rollingstock/cars/Car.java
  java/test/jmri/jmrit/operations/locations/LocationManagerTest.java
  java/test/jmri/jmrit/operations/rollingstock/cars/CarsTest.java
Labels: Documentation

#14273 Update LogixNG Help: OperationsPro Automation action
  help/en/html/tools/logixng/reference/chapter5.shtml
  help/en/html/tools/logixng/reference/images/chapter5/digital_action_opsrunauto.png
  help/en/html/tools/logixng/reference/images/chapter5/opspro-run-automation.png
Labels: Documentation

#14292 Add decoder manufacturer and family columns to DP main display
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/roster/JmritRosterBundle.properties
  java/src/jmri/jmrit/roster/swing/RosterTable.java
  java/src/jmri/jmrit/roster/swing/RosterTableModel.java
  java/test/jmri/jmrit/roster/swing/RosterTableModelTest.java
Labels: Needs L10N

#14291 Add JMRIusers link to help menu
  help/en/releasenotes/current-draft-note.shtml
  java/src/apps/JmriUsersAction.java
  java/src/apps/swing/HelpMenuProvider.java
  java/src/jmri/NamedBeanBundle.properties
  java/test/jmri/jmrit/display/AbstractEditorTestBase.java
Labels: Needs L10N

#14294 OperationsPro add hyphen feature to train name
  help/en/package/jmri/jmrit/operations/Operations.shtml
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/operations/CommonConductorYardmasterPanel.java
  java/src/jmri/jmrit/operations/JmritOperationsBundle.properties
  java/src/jmri/jmrit/operations/trains/Train.java
  java/src/jmri/jmrit/operations/trains/TrainManifest.java
  java/src/jmri/jmrit/operations/trains/TrainSwitchLists.java
  java/src/jmri/jmrit/operations/trains/trainbuilder/TrainCommon.java
Labels: Documentation

#14302 Add option to copy DCC signal head appearance numbers
  help/en/package/jmri/jmrit/beantable/SignalAddEdit.shtml
  help/en/package/jmri/jmrit/beantable/images/SignalHeadAddDCC.png
  help/en/releasenotes/current-draft-note.shtml
  java/src/jmri/jmrit/beantable/BeanTableBundle.properties
  java/src/jmri/jmrit/beantable/SignalHeadAddEditFrame.java
Labels: Needs L10N

#14307 Improvements to WiThrottle protocol web page.
  help/en/package/jmri/jmrit/withrottle/Protocol.shtml
Labels: Documentation

#14311 Update Protocol.shtml
  help/en/package/jmri/jmrit/withrottle/Protocol.shtml
Labels: Documentation

#14323 Update Digirails
  help/en/html/hardware/digirails/index.shtml
  help/en/parts/SidebarSupportedHardware.shtml
Labels: Documentation

#14326 OperationsPro some minor enhancements to code and help
  help/en/package/jmri/jmrit/operations/Operations.shtml
  java/src/jmri/jmrit/operations/locations/JmritOperationsLocationsBundle.properties
  java/src/jmri/jmrit/operations/locations/gui/StagingEditFrame.java
  java/src/jmri/jmrit/operations/locations/schedules/tools/SchedulesAndStagingFrame.java
  java/test/jmri/jmrit/operations/setup/gui/OperationsSettingsFrameTest.java
Labels: Documentation, Needs L10N
